### ISSUE TITLE
No reference about comment tags

### ISSUE THREAD

**Issue by rusluck** [mdn/content#31268] opened 2023-12-24 14:34 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element

### What information was incorrect, unhelpful, or incomplete?

Couldn't find any information about comment tags in HTML throughout the whole website

### What did you expect to see?

Information describing comment tags, especially on this page

### Do you have any supporting links, references, or citations?

Information about comment tags: https://www.w3schools.com/html/html_comments.asp

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/index.md
* Last commit: https://github.com/mdn/content/commit/627e21dbbdfccf91017ed816708bc0a8d1e8bb83
* Document last modified: 2023-07-11T12:06:46.000Z

</details>

**Comment by Josh-Cena** [comment] 2023-12-25 04:58
Duplicate of https://github.com/mdn/content/issues/21761

**Closed by Josh-Cena** 2023-12-25 04:58 UTC
Labels: Content:HTML, needs triage
