### ISSUE TITLE
Intl.NumberFormat.prototype.formatToParts(): compact type is not listed

### ISSUE THREAD

**Issue by KuSh** [mdn/content#21529] opened 2022-10-13 14:53 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/formatToParts

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/formatToParts#description

### What information was incorrect, unhelpful, or incomplete?

compact is not listed

```js
Intl.NumberFormat('fr', { style: 'unit', notation: 'compact', unit: 'gram', unitDisplay: 'narrow', maximumFractionDigits: 1 }).formatToParts(1500000)
Array(6) [ {…}, {…}, {…}, {…}, {…}, {…} ]
​0: Object { type: "integer", value: "1" }
​1: Object { type: "decimal", value: "," }
​2: Object { type: "fraction", value: "5" }
3: Object { type: "literal", value: " " }
​4: Object { type: "compact", value: "M" }
​5: Object { type: "unit", value: "g" }
​length: 6
​```

### What did you expect to see?

Description of the compact type

### Do you have any supporting links, references, or citations?

https://tc39.es/ecma402/#sec-partitionnotationsubpattern 4.c.iv
+ firefox current implementation

### Do you have anything more you want to share?

Thanks for your incredible work !

### MDN metadata

<!-- Do not make changes below this line -->
<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/intl/numberformat/formattoparts`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/formatToParts
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/intl/numberformat/formattoparts/index.md
* Last commit: https://github.com/mdn/content/commit/d6ce8fcbbc4a71ec9209f379e5ea9774bbf1f5ac
* Document last modified: 2022-09-13T07:06:03.000Z

</details>

**Comment by Josh-Cena** [comment] 2022-10-13 15:43
Duplicate of https://github.com/mdn/content/issues/516

**Closed by Josh-Cena** 2022-10-13 15:43 UTC
Labels: Content:JS, needs-triage

**Comment by KuSh** [comment] 2022-10-13 15:50
Sorry for that ... the mdn link is directing directly on the bug creation

**Comment by Josh-Cena** [comment] 2022-10-13 15:52
Don't worry, everyone does it sometimes ;). Next time, you may want to search the issue tracker first even when you land directly on the issue creation page.
