### ISSUE TITLE
Issue with "transform": LaTeX is not rendered

### ISSUE THREAD

**Issue by helviett** [mdn/content#5626] opened 2021-06-03 13:21 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/transform

#### Specific section or headline?
Matrix section

#### What did you expect to see?
Rendered latex

#### Did you test this? If so, how?
Opened in latest Google Chrome.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/svg/attribute/transform`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/transform
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/attribute/transform/index.html
* Last commit: https://github.com/mdn/content/commit/735b0c6054fe25ee303afec6c14ae8281b134c53
* Document last modified: 2021-03-19T22:31:21.000Z

</details>

**Comment by teoli2003** [comment] 2021-06-03 15:11
Hi!

This is not LaTeX, but MathML. MathML is natively supported by Safari and Firefox. MDN had a polyfill for the other browser but was lost when we migrated to yari end of 2020. There is currently a discussion to get the polyfill back: it happens in #3435.

Thanks for the report.

**Comment by sideshowbarker** [comment] 2021-06-04 08:22
Closing since this is a duplicate of https://github.com/mdn/content/issues/3435

**Closed by sideshowbarker** 2021-06-04 08:22 UTC
