### ISSUE TITLE
Issue with "<iframe>: The Inline Frame element": …

### ISSUE THREAD

**Issue by metasean** [mdn/content#779] opened 2020-12-30 20:37 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe

#### What information was incorrect, unhelpful, or incomplete?

The "[A simple `<iframe>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#A_simple_iframe)" example does not work in FF Nightly 86.0a1 (2020-12-30) _or_ FF 84.0.1 (64-bit) on macOS Catalina v. 10.15.7

<img width="1343" alt="Screen Shot 2020-12-30 at 1 18 03 PM" src="https://user-images.githubusercontent.com/7552754/103379919-861be880-4aa4-11eb-9950-87fba53ed200.png">

#### Specific section or headline?
"[A simple `<iframe>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#A_simple_iframe)"

#### What did you expect to see?
A working example of an iFrame

#### Did you test this? If so, how?
- Tested it in 2 different versions of FF and, in both versions, with my privacy plug-ins all enabled and again with my privacy plug-ins all disabled.
- Verified that the initial example (i.e. "[HTML Demo: <iframe>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#content) is working exactly as expected."
- Verified that the [`src`](https://mdn-samples.mozilla.org/snippets/html/iframe-simple-contents.html) page is a valid webpage.  
  
(Given the error message, the problem isn't on the [https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe](`<iframe>`) documentation page itself, rather it's the permissions for https://mdn-samples.mozilla.org/snippets/html/iframe-simple-contents.html page.)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/iframe`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/html/element/iframe/index.html
* Report started: 2020-12-30T20:18:27.277Z

</details>

**Comment by sideshowbarker** [comment] 2021-01-01 19:31
I guess this is a duplicate of https://github.com/mdn/content/issues/635. As I mentioned there, I’ve raised https://github.com/mdn/yari/issues/2281 for it.

**Comment by sideshowbarker** [comment] 2021-02-27 02:57
Closing as duplicate of #635 (and now fixed, I believe)

**Closed by sideshowbarker** 2021-02-27 02:57 UTC
Labels: 30 minute task, Content:HTML, duplicate
