### ISSUE TITLE
overscroll-behavior example doesn't work in safari

### ISSUE THREAD

**Issue by dy** [mdn/content#15824] opened 2022-05-09 15:51 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior

### What specific section or headline is this issue about?

Try it

### What information was incorrect, unhelpful, or incomplete?

Example doesn't work in Safari

### What did you expect to see?

Example works

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/overscroll-behavior`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/overscroll-behavior/index.md
* Last commit: https://github.com/mdn/content/commit/cfc412af4381cdf29a9ecfa11f41ea877a6cc030
* Document last modified: 2022-04-08T05:42:32.000Z

</details>

**Comment by wbamberg** [comment] 2022-05-09 18:26
According to the compat table: https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior#browser_compatibility this property is not supported in Safari, so this example can't be made to work.

When I visit this page in Safari I see the expected version where the editor is not loaded:

<img width="817" alt="Screen Shot 2022-05-09 at 11 24 45 AM" src="https://user-images.githubusercontent.com/432915/167473261-a02d2a34-ec0e-4b2d-84ab-6c0cdbe547d7.png">

I agree that this is a bit confusing and making it less so is the subject of some ongoing work (https://github.com/mdn/bob/pull/763) but it seems to be working as intended.

**Comment by janbrasna** [comment] 2022-05-10 21:59
@wbamberg While I think it's completely fine this example can't work in Safari, I'm just curious: 

> "When I visit this page in Safari I see the expected version where the editor is not loaded"

I'd expect the example previews all to load, just not honor the actual property value (to demonstrate the difference… as there's no difference in Safari, or, more exactly, it represents how setting all three values would behave in Safari IRL) — but not loading the preview renders at all looks somewhat suspicious to me… Am I missing something?

**Comment by NiedziolkaMichal** [comment] 2022-05-11 22:01
This is fixed by PR [#759](https://github.com/mdn/bob/pull/759), however new version of BOB needs to be released, in order for it to be published. @schalkneethling Could you do it please?

**Comment by sideshowbarker** [comment] 2022-05-12 01:57
Fixed by https://github.com/mdn/bob/pull/759

**Closed by sideshowbarker** 2022-05-12 01:57 UTC
Labels: Content:CSS
