### ISSUE TITLE
Content bug: AppCache page appears for a split second and then disappears

### ISSUE THREAD

**Issue by captainbrosset** [mdn/content#6858] opened 2021-07-13 14:00 UTC
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache

## What is the problem?

I tried loading this page on several browsers (firefox and edge) and I am seeing a weird issue where the page content does appear for, maybe, half a second, and then disappears right after. The page is then blank, and devtools shows errors in the console.

## What did you expect to see?

AppCache was deprecated and removed from browsers, but the page still contains interesting information that should likely remain available.
If MDN wants to remove it altogether, that's fine, but it should end up in a 404 instead of this weird flashing bug.

Note that the page works fine on IE where, perhaps, the code that makes it disappear just doesn't run.

I stumbled upon this archival PR but I'm still raising this issue so that a better user experience (i.e. redirect to a 404) can be put in place: https://github.com/mdn/content/pull/4016

**Comment by sideshowbarker** [comment] 2021-07-14 05:38
Thanks for raising this. The source for this files no longer even exists in the https://github.com/mdn/content repo, nor in the https://github.com/mdn/archived-content. So there’s actually no source anywhere any longer where a fix could be applied.

So I’m not sure what needs to happen here at this point. I think we need some attention from @mdn/core at least.

Cc @SphinxKnight

**Comment by Elchi3** [comment] 2021-07-14 08:40
Dupe of https://github.com/mdn/yari/issues/4011

**Comment by captainbrosset** [comment] 2021-07-14 08:55
Thank you both. Good to know the problem will go away soon.

**Comment by sideshowbarker** [comment] 2021-07-14 11:28
Cheers — going ahead and closing this one now

**Closed by sideshowbarker** 2021-07-14 11:28 UTC
Labels: Content:HTML
