### ISSUE TITLE
Quotation attribution must be placed outside the blockquote element

### ISSUE THREAD

**Issue by miatangvik** [mdn/content#28644] opened 2023-08-18 07:51 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/blockquote

### What specific section or headline is this issue about?

Try it

### What information was incorrect, unhelpful, or incomplete?

In the HTML Demo for `blockquote` the attribution for the quotation is placed inside the `blockquote` element, while in the [spec](https://html.spec.whatwg.org/multipage/grouping-content.html#the-blockquote-element) it says that

> Attribution for the quotation, if any, must be placed outside the [blockquote](https://html.spec.whatwg.org/multipage/grouping-content.html#the-blockquote-element) element.

### What did you expect to see?

Attribution for the quotation outside the `blockquote` element.

### Do you have any supporting links, references, or citations?

https://html.spec.whatwg.org/multipage/grouping-content.html#the-blockquote-element

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/blockquote`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/blockquote
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/blockquote/index.md
* Last commit: https://github.com/mdn/content/commit/e04d8d2766c468f149445c0bf438d09f9b2d188c
* Document last modified: 2023-06-13T08:10:47.000Z

</details>

**Comment by wbamberg** [comment] 2023-08-18 14:23
Thanks for filing! This looks like a duplicate of https://github.com/mdn/content/issues/28401.

As Josh says [here](https://github.com/mdn/content/issues/28401#issuecomment-1666073569), we do need to clarify this in the page, as the current state is very confusing for people.

**Closed** 2023-08-18 15:14 UTC
Labels: Content:HTML, needs triage
