### ISSUE TITLE
Issue with "Allowing cross-origin use of images and canvas": (Glitch links are not working https://glitch.com/edit/#!/remix/cors-image-example)

### ISSUE THREAD

**Issue by echarish** [mdn/content#3476] opened 2021-03-25 00:15 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image

#### What information was incorrect, unhelpful, or incomplete?
The try out option doesn't work, on click of link https://glitch.com/edit/#!/remix/cors-image-example an error is shown on the glitch screen saying "An error occurred when trying to create this project, please try again later."

#### Specific section or headline?
You can try out or remix this example on Glitch.

#### What did you expect to see?
Able to see the code and see it in action

#### Did you test this? If so, how?
click on the link

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/cors_enabled_image`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/cors_enabled_image/index.html
* Last commit: https://github.com/mdn/content/commit/2a14c0eac061493b1160076a3e72ec8e346d2223
* Document last modified: 2021-02-19T18:56:36.000Z

</details>

**Comment by himanshugarg** [comment] 2021-09-07 02:37
Possible duplicate of the newer issue #5389

**Comment by sideshowbarker** [comment] 2021-09-07 04:17
> Possible duplicate of the newer issue #5389

Thanks @himanshugarg — closing this as a duplicate of that

**Closed by sideshowbarker** 2021-09-07 04:17 UTC
Labels: duplicate, Content:HTTP
