### ISSUE TITLE
Missing “Formal syntax” for CSS minmax

### ISSUE THREAD

**Issue by zhangenming** [mdn/content#21439] opened 2022-10-10 06:49 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/minmax

### What information was incorrect, unhelpful, or incomplete?

![image](https://user-images.githubusercontent.com/21235555/194811033-9eb4d780-c82d-4b9d-bac5-494f8dd9729a.png)

### What did you expect to see?

fix or delete?

**Comment by Josh-Cena** [comment] 2022-10-10 17:34
Duplicate of https://github.com/mdn/content/issues/18780

**Closed by Josh-Cena** 2022-10-10 17:34 UTC
Labels: Content:CSS
