### ISSUE TITLE
Final "translate" example is incorrect

### ISSUE THREAD

**Issue by Chamelespoon** [mdn/content#27102] opened 2023-06-01 17:19 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/XPath/Functions/translate

### What information was incorrect, unhelpful, or incomplete?

The output of the final example is specified as:

```plain
The quick red fox.
```

### What did you expect to see?

The translate function should be replacing all `o` characters with `d`, so the output should be:

```plain
The quick red fdx.
```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/xpath/functions/translate`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/XPath/Functions/translate
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/xpath/functions/translate/index.md
* Last commit: https://github.com/mdn/content/commit/fa2391c795745f025132dc470bd9e6cae73b1fd5
* Document last modified: 2023-02-23T10:09:26.000Z

</details>

**Comment by Josh-Cena** [comment] 2023-06-02 03:15
It's an overfix from https://github.com/mdn/content/pull/20851

**Comment by wbamberg** [comment] 2023-06-02 03:57
Also a duplicate of https://github.com/mdn/content/issues/22616. Note the suggestion there to use a different example: this might help prevent the example from getting overfixed again in future (i.e., if the translated text is a real word).

**Comment by Josh-Cena** [comment] 2023-06-02 04:06
Thanks, closing as duplicate. FWIW, I think this example calls out how naïvely using it as `replace` leads to subtle bugs.

**Closed by Josh-Cena** 2023-06-02 04:06 UTC
Labels: good first issue, Content:Other
