### ISSUE TITLE
Issue with "Clipboard.read()": …

### ISSUE THREAD

**Issue by tomOgn** [mdn/content#1882] opened 2021-01-29 11:50 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/read

#### What information was incorrect, unhelpful, or incomplete?
The code sample shows the `read` promise returning an object with `items` as field. At least on Chrome and Safari (I didn't check the other browsers) the output I get is directly the array `items`.

#### Specific section or headline?
Example paragraph

#### What did you expect to see?
```
navigator.clipboard.read().then(items => {
      for (const item of items) {
[...]
```

#### Did you test this? If so, how?
Tested it on Chrome and Safari.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/clipboard/read`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/read
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/clipboard/read/index.html
* Last commit: https://github.com/mdn/content/commit/2d423bd1a98b85b8584f08990792ebf39fcea56b
* Document last modified: 2021-01-09T13:41:23.000Z

</details>

**Comment by myakura** [comment] 2021-02-02 04:48
good catch. it looks like the documentation hasn't been updated to take account of the current spec (and implementation). `read()` returns a Promise object which resolves to an array of `ClipboardItem` objects. 

https://web.dev/async-clipboard/
https://webkit.org/blog/10855/

**Comment by myakura** [comment] 2021-02-02 04:56
looks like a dupe of #1036

**Comment by chrisdavidmills** [comment] 2021-02-02 16:30
Yup, this is a dupe, so closing; thanks for taking the time to submit this one @tomOgn

**Closed by chrisdavidmills** 2021-02-02 16:30 UTC
