### ISSUE TITLE
Responsive design issue 

### ISSUE THREAD

**Issue by ijasz** [mdn/content#26340] opened 2023-04-21 10:21 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/MDN/Community/Issues

### What specific section or headline is this issue about?

Responsive design issue 

### What information was incorrect, unhelpful, or incomplete?

z-index design issue to be corrected

### What did you expect to see?

 z-index to be corrected

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mdn/community/issues`
* MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Community/Issues
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mdn/community/issues/index.md
* Last commit: https://github.com/mdn/content/commit/ac5dfaa2f71a7381cd8fdd4cb554507f375ac19c
* Document last modified: 2023-02-26T18:54:50.000Z

</details>

**Comment by Josh-Cena** [comment] 2023-04-21 15:20
Assuming duplicate of https://github.com/mdn/yari/issues/8646

**Closed by Josh-Cena** 2023-04-21 15:20 UTC
Labels: Content:JS, needs triage
