### ISSUE TITLE
Not working in Opera 93 on Windows 10.

### ISSUE THREAD

**Issue by schoenid** [mdn/content#22404] opened 2022-11-18 23:16 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/accent-color

### What specific section or headline is this issue about?

Browser Compatibility

### What information was incorrect, unhelpful, or incomplete?

Opera from version 79 is noted as working.

### What did you expect to see?

Not working in Opera 93.

### Do you have any supporting links, references, or citations?

Opera Version: 93.0.4585.11 (Newest at the time of this note).
The colors do not change in the demo.

### Do you have anything more you want to share?

It's fully working in Firefox, Chrome and Edge in the actual version.

Maybe there are some hidden experimental settings, to make it working in Opera, but I could't find it. So with regular settings it's not working.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/accent-color`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/accent-color
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/accent-color/index.md
* Last commit: https://github.com/mdn/content/commit/abcebf471d56ef12239e2565f26d952e8a8cab2e
* Document last modified: 2022-05-17T13:23:31.000Z

</details>

**Comment by bsmth** [comment] 2022-11-21 11:06
Hi @schoenid, thanks for raising the issue. I cannot reproduce the problem you reported. It's working for me when testing the following Opera versions (with default configuration) using BrowserStack:


- ✅ 91
- ✅ 92
- ✅ 93

It might be worth checking if you have any non-default configuration / preferences set for rendering or extensions that might block the example from running.

**Comment by schoenid** [comment] 2022-11-21 14:46
### Opera:
![image](https://user-images.githubusercontent.com/15383666/203080393-af42221f-50f8-46a5-9e4b-b78aaf9fb4c7.png)
Version:
![image](https://user-images.githubusercontent.com/15383666/203080626-0f330820-a2f1-43bf-a22e-21835e211a69.png)
I could not find any setting in the preferences to make it working.

### Firefox:
![image](https://user-images.githubusercontent.com/15383666/203080926-021a7a7f-59bf-439e-97ba-69936e783633.png)

Version:
![image](https://user-images.githubusercontent.com/15383666/203081084-8f34111c-c14c-4549-ac12-7e827a67ffee.png)

### Chrome:
![image](https://user-images.githubusercontent.com/15383666/203081396-b05a5e9d-5d17-4790-99c1-74e0dbe38e39.png)

Version:
![image](https://user-images.githubusercontent.com/15383666/203081543-0e083def-79b0-484e-aa6f-4b9d50d48253.png)

### Edge:
![image](https://user-images.githubusercontent.com/15383666/203081822-a1df124c-a72d-4d62-990d-75f7136b4817.png)

Version:
![image](https://user-images.githubusercontent.com/15383666/203081963-2fa158e7-15b2-4a44-9146-cf3372ab2998.png)

### Summary:
Opera does not support CSS accent-color.
All Browser were freshly installed.

Opera special settings:

- Default language: German
- VPN: off
- Startpage Search field: off
- Default search machine: duckduckgo

**Comment by bsmth** [comment] 2022-11-21 15:06
Hi @schoenid, thanks for the follow-up. This is working for me:

![image](https://user-images.githubusercontent.com/43580235/203087708-e0e7382b-469b-447a-a729-d48e0a0d116b.png)

OS: macOS 13.0.1 (22A400)
Opera: ✅ Version:91.0.4516.77 (arm64)
Opera: ✅ Version:93.0.4585.11 (arm64)

It might be worth getting [in touch with Opera support](https://help.opera.com/en/touch/report-a-problem/) for this one.

**Comment by schoenid** [comment] 2022-11-21 16:21
I wouldn't believe, if I didn't see ...

Great. So it's working on some systems, but not on others ... so I've tried it on different systems in my house. 

- It's not working on any Windows 10 System. One of them is freshly installed on a notebook computer (intel64).

- It's working on Ubuntu !!!
- It's working on Windows 7 too. What surprise ...

- It's not available for Raspberry Pi, so I can't test it on an Arm64 system. Your BrowserStack version is not available for free, so I can't get it ...
- My computers are not fit for Windows 11, so I can't test it there.

**So it seems to be a Windows 10 issue.**

Best thanks for help!

**Comment by hamishwillee** [comment] 2022-11-21 23:11
Yes, confirm that this is Windows 10 Opera for me too. Interestingly the element does show that the colour is applied.
```
input.custom {
    accent-color: rebeccapurple;
}
```
Closing this issue - it's not an MDN bug. Cheers for posting.

**Closed by hamishwillee** 2022-11-21 23:11 UTC
Labels: to move
