### ISSUE TITLE
Content bug: an formula broken

### ISSUE THREAD

**Issue by logic-finder** [mdn/content#7008] opened 2021-07-18 10:57 UTC
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/createPeriodicWave

## Specific page section or heading?

Example

## What is the problem?

\left(a+bi\right)e^{i} , \left(c+di\right)e^{2i} , \left(f+gi\right)e^{3i}

## What did you expect to see?

The above seems to try to show a formula but I think something is broken.

## Did you test this? If so, how?

I found this broken formula while I translated this article to Korean. I looked other translated articles but the situation was same. Please let me know if there are any way to fix it. Thank you.

**Comment by alattalatta** [comment] 2021-07-18 11:11
https://github.com/mdn/yari/issues/4197

**Comment by sideshowbarker** [comment] 2021-07-18 11:21
Thanks @alattalatta — yeah, this is a duplicate of https://github.com/mdn/yari/issues/4197

**Closed by sideshowbarker** 2021-07-18 11:21 UTC
Labels: duplicate, needs-triage
