### ISSUE TITLE
Specifications and Browser compatibility missing for docs/Web/API/HTMLElement/load_event

### ISSUE THREAD

**Issue by def00111** [mdn/content#36521] opened 2024-10-27 20:02 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/load_event

### What information was incorrect, unhelpful, or incomplete?

Specifications and Browser compatibility missing.

### What did you expect to see?

Specifications and Browser compatibility are available.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/htmlelement/load_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/load_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlelement/load_event/index.md
* Last commit: https://github.com/mdn/content/commit/e9e2ec643ac69c132f31427a0b586ab2cf83ed58
* Document last modified: 2024-07-26T02:56:30.000Z

</details>

**Comment by Josh-Cena** [comment] 2024-10-27 23:03
Duplicate of https://github.com/mdn/browser-compat-data/issues/21585, which will be fixed by the linked PR

**Closed by Josh-Cena** 2024-10-27 23:03 UTC
Labels: Content:WebAPI, needs triage
