### ISSUE TITLE
Issue with "Author detail page": (author detail page keeps loading without displaying data)

### ISSUE THREAD

**Issue by ghost** [mdn/content#7656] opened 2021-08-06 11:42 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/Author_detail_page

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/displaying_data/author_detail_page`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/Author_detail_page
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/displaying_data/author_detail_page/index.html
* Last commit: https://github.com/mdn/content/commit/adc309da4235ec6c01f40e3212168ea5b98358c9
* Document last modified: 2021-01-29T01:56:44.000Z

</details>

**Comment by hamishwillee** [comment] 2021-08-06 12:05
Can you reproduced using the version in https://github.com/mdn/express-locallibrary-tutorial ?

If not, there is probably a problem with your code. If you can can, please confirm your OS, and upload a version I can test on to github.

**Comment by wbamberg** [comment] 2021-11-23 05:07
Closing due to non-response.

**Closed by wbamberg** 2021-11-23 05:07 UTC
