### ISSUE TITLE
Crafty not defined error

### ISSUE THREAD

**Issue by JXSnack** [mdn/content#29177] opened 2023-09-18 08:08 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Games/Techniques/2D_collision_detection

### What specific section or headline is this issue about?

The play function

### What information was incorrect, unhelpful, or incomplete?

In the code it says `Crafty.init(200, 200)`, but there is no crafty on the website.

### What did you expect to see?

No error

### Do you have any supporting links, references, or citations?

![Bildschirmfoto 2023-09-18 um 10 08 06](https://github.com/mdn/content/assets/72796341/b42844d7-26af-4468-92d0-4d368c27c377)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/games/techniques/2d_collision_detection`
* MDN URL: https://developer.mozilla.org/en-US/docs/Games/Techniques/2D_collision_detection
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/games/techniques/2d_collision_detection/index.md
* Last commit: https://github.com/mdn/content/commit/acfe8c9f1f4145f77653a2bc64a9744b001358dc
* Document last modified: 2023-07-07T07:19:19.000Z

</details>

**Comment by hamishwillee** [comment] 2023-09-18 08:19
Thank you. You're absolutely right. Closing as this is a duplicate of https://github.com/mdn/yari/issues/9346

**Closed by hamishwillee** 2023-09-18 08:19 UTC
Labels: needs triage, Content:Games
