### ISSUE TITLE
Geolocation demo doesn't appear to work.

### ISSUE THREAD

**Issue by shannonwoolis** [mdn/content#1254] opened 2021-01-13 11:33 UTC
Hello,

This doesn't seem to work on Chrome (Version 87.0.4280.88 (Official Build) (x86_64))

I'm on macOS Big Sur.

It seems to work fine on Firefox and Safari.

I have tried a couple of different sites, including your own test box.

Please could you look into this?

Thanks!

**Comment by chrisdavidmills** [comment] 2021-01-13 11:43
Hi @shannonwoolis !

What doesn't work? You've not provided any details of what it is.

**Comment by shannonwoolis** [comment] 2021-01-13 11:47
Apologies @chrisdavidmills 

The 'Result' part of this page: https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API#result

I have spoken to the API developers and they said this:
_I looked into the availability of the API and Chrome does expose the API (e.g., navigator.geolocation is a Geolocation object). That said, you're right that the live sample on MDN does not work properly (it works standalone but not in the iframe on MDN).
Since this appears to be more of a content issue than a compatibility issue, I suggest that your report this as an issue on mdn/content instead. Thank you!_

**Comment by ddbeck** [comment] 2021-01-13 11:49
I think this is a follow-up to https://github.com/mdn/browser-compat-data/issues/8737

**Comment by chrisdavidmills** [comment] 2021-01-13 11:59
@shannonwoolis no worries at all, and thanks for the info. This demo does need some work; it looks like a samesite issue, and we probably need to host it somewhere else (like on GitHub, inside https://github.com/mdn/dom-examples/ maybe) and link to it instead.

Triaging now.

**Comment by shannonwoolis** [comment] 2021-01-13 13:21
@chrisdavidmills I'm not sure it's to do with where it is being hosted as I have used this method on a couple of websites and they don't work on Chrome anymore either

**Comment by chrisdavidmills** [comment] 2021-01-13 13:33
@shannonwoolis OK, useful to know. We'll have to get someone to investigate this a bit more deeply.

**Comment by sideshowbarker** [comment] 2021-01-13 15:49
https://github.com/mdn/content/pull/1267 fixes this, I think.

The patch in that PR has the effect of adding an `allow="geolocation` attribute to the Results iframe in the
Web/API/Geolocation_API article. Otherwise, without that, the default in Chrome — and in current Firefox too, in my
testing at least — is to (silently) disallow geolocation for any cross-origin iframe. (I think Safari allows it, though).

**Comment by shannonwoolis** [comment] 2021-01-13 16:30
@sideshowbarker I'm not using an iframe though

**Comment by sideshowbarker** [comment] 2021-01-13 16:36
> @sideshowbarker I'm not using an iframe though

You’re not using and iframe where? The published/production https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API#result page section mentioned in https://github.com/mdn/content/issues/1254#issuecomment-759397055 is using an iframe, right?

**Comment by shannonwoolis** [comment] 2021-01-14 09:02
@sideshowbarker Yeah I think the result on that page is using an iframe but, for example, I am not using an iframe on this website: https://www.domex-uk.co.uk/coverage-area/ - geolocation is used for the "Use my current location" button

**Comment by sideshowbarker** [comment] 2021-01-14 09:59
> @sideshowbarker Yeah I think the result on that page is using an iframe but, for example, I am not using an iframe on this website: [domex-uk.co.uk/coverage-area](https://www.domex-uk.co.uk/coverage-area/) - geolocation is used for the "Use my current location" button

OK, yeah I can see there’s some bug in the JavaScript code for that site. But helping you with debugging it is out of scope for this particular issue tracker. Here we just deal with the content of the MDN docs. And there’s nothing in this issue report which indicates any problem with the MDN docs — other than the problem I fixed in https://github.com/mdn/content/pull/1267.

So for help with debugging the https://www.domex-uk.co.uk/coverage-area/ problem, you probably want to consider posting at a site like https://stackoverflow.com/.

But if you post there, please read all of https://stackoverflow.com/help/minimal-reproducible-example before posting — and if/when you post there, make sure to include:

* a code snippet for the relevant part of the frontend JavaScript code — not just a link to https://www.domex-uk.co.uk/coverage-area/
* the exact error messages that the browser is logging in the devtools console

When I look at the devtools console, what I see getting logged there in Firefox is this:
```
Uncaught TypeError: can't access property 0, t.result is null
    success https://www.domex-uk.co.uk/wp-content/themes/domex/_js/production.min.js?ver=5.5.3:1
    jQuery 6
    t https://www.domex-uk.co.uk/wp-content/themes/domex/_js/production.min.js?ver=5.5.3:1
    PositionCallback* https://www.domex-uk.co.uk/wp-content/themes/domex/_js/production.min.js?ver=5.5.3:1
    jQuery 9
    <anonymous> https://www.domex-uk.co.uk/wp-content/themes/domex/_js/areas-page.min.js?ver=5.5.3:1
    jQuery 8
production.min.js:1:38390
    success https://www.domex-uk.co.uk/wp-content/themes/domex/_js/production.min.js?ver=5.5.3:1
    jQuery 6
    t https://www.domex-uk.co.uk/wp-content/themes/domex/_js/production.min.js?ver=5.5.3:1
    (Async: PositionCallback)
    <anonymous> https://www.domex-uk.co.uk/wp-content/themes/domex/_js/production.min.js?ver=5.5.3:1
    jQuery 9
    <anonymous> https://www.domex-uk.co.uk/wp-content/themes/domex/_js/areas-page.min.js?ver=5.5.3:1
    jQuery 8
```
…and in Chrome, this:
```
Uncaught TypeError: Cannot read property '0' of null
    at Object.success (production.min.js?ver=5.5.3:1)
    at i (jquery.js?ver=1.12.4-wp:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4-wp:2)
    at x (jquery.js?ver=1.12.4-wp:4)
    at XMLHttpRequest.c (jquery.js?ver=1.12.4-wp:4)
```

**Closed** 2021-01-14 10:21 UTC
Labels: 1 hour task, Content:WebAPI
