### ISSUE TITLE
Issue with "Examine and edit the box model": Some demo videos are private

### ISSUE THREAD

**Issue by Lippiece** [mdn/content#13832] opened 2022-03-13 18:28 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_and_edit_the_box_model

#### What information was incorrect, unhelpful, or incomplete?
Some demo videos are private.

#### Specific section or headline?
"If you hover over part of the box model in the Box Model view, the corresponding part of the page is highlighted:"
and
"Editing the box model"

#### What did you expect to see?
An available video.

#### Did you test this? If so, how?
Open the URL, scroll to the stated positions and see "this video is private".

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/page_inspector/how_to/examine_and_edit_the_box_model`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_and_edit_the_box_model
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/page_inspector/how_to/examine_and_edit_the_box_model/index.html
* Last commit: https://github.com/mdn/content/commit/05b71a290b2ab444b23e0f35f619d93203c7e2d8
* Document last modified: 2021-02-02T16:31:29.000Z

</details>

**Comment by wbamberg** [comment] 2022-03-13 19:14
Duplicate of https://github.com/mdn/content/issues/7457 .

**Closed by wbamberg** 2022-03-13 19:14 UTC
Labels: needs-triage
