### ISSUE TITLE
Conflicting information on initializing autonomous custom element classes (onconnectedcallback vs constrcutor)

### ISSUE THREAD

**Issue by davidhoferzeni** [mdn/content#27457] opened 2023-06-21 11:40 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_custom_elements

### What specific section or headline is this issue about?

autonomous_custom_elements

### What information was incorrect, unhelpful, or incomplete?

There is a full paragraph on the usage of the "connectedCallback" to populate and style the custom component instead of directly initializing the element in the constructor.

### What did you expect to see?

However, the linked (and working) [example ](https://github.com/mdn/web-components-examples/tree/main/popup-info-box-web-component) does exactly that so the information provided in that paragraph might be outdated (esp. the final sentence).

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/web_components/using_custom_elements`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_custom_elements
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/web_components/using_custom_elements/index.md
* Last commit: https://github.com/mdn/content/commit/270351317fdaa57ba9123a19aa281e9e40bb0baa
* Document last modified: 2023-06-20T19:01:21.000Z

</details>

**Comment by Josh-Cena** [comment] 2023-06-21 11:43
Duplicate of https://github.com/mdn/content/issues/22887

**Closed by Josh-Cena** 2023-06-21 11:43 UTC
Labels: Content:WebAPI, needs triage
