### ISSUE TITLE
No more vars in JavaScript docs

### ISSUE THREAD

**Issue by wbamberg** [mdn/content#16614] opened 2022-05-23 23:41 UTC
After the Write the Docs sprint, these are all the pages in the JavaScript documentation that use `var`, according to my very basic script:

- [x] https://developer.mozilla.org/en-US/docs/web/javascript/guide/grammar_and_types
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/guide/control_flow_and_error_handling
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/guide/functions
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/the_performance_hazards_of_prototype_mutation
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/memory_management
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/enumerability_and_ownership_of_properties
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/closures
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/operators/delete
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/operators/await
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/operators/new
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/operators/this
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/operators/comma_operator
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/operators/typeof
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/classes/extends
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/classes/class_static_initialization_blocks
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/deprecated_and_obsolete_features/the_legacy_iterator_protocol
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/var
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/throw
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/const
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/let
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/for
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/function_star_
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/break
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/block
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/array/from
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/array/@@iterator
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/typedarray/findindex
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/typedarray/values
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/math/cosh
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/math/clz32
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/math/asinh
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/math/imul
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/math/tanh
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/math/sinh
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/math/hypot
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/webassembly/memory
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/webassembly/memory/memory
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/webassembly/memory/buffer
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/webassembly/module/exports
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/webassembly/table/get
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/webassembly/instantiate
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/object/entries
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/object/defineproperties
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/object/keys
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/object/setprototypeof
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/string/repeat
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/string/trimstart
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/string/codepointat
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/string/fromcodepoint
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/string/startswith
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/strict_mode
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/strict_mode/transitioning_to_strict_mode
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/functions
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/functions/default_parameters
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/functions/arrow_functions
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/functions/arguments
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/functions/arguments/callee
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/errors/deprecated_string_generics
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/errors/not_defined
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/errors/stmt_after_return
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/errors/undeclared_var
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/errors/cant_access_lexical_declaration_before_init
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/errors/getter_only
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/errors/not_a_function
- [x] https://developer.mozilla.org/en-US/docs/web/javascript/reference/errors/is_not_iterable

There are likely to be some false positives in there. Note that we should **not** change any code inside polyfills.

**Comment by gullapalli9482** [comment] 2022-05-25 14:40
I want to take up this issue.
Just for confirmation, the issue is about changing the var variable to the alternative one for the necessary context.

**Comment by wbamberg** [comment] 2022-05-25 15:00
> I want to take up this issue. Just for confirmation, the issue is about changing the var variable to the alternative one for the necessary context.

Thank you @gullapalli9482 ! Yes (sorry I should have provided more context) exactly, this is about replacing usages of `var` with `let` or `const` as appropriate.

Note that our policy here is "use `const` where we can, `let` where we have to", and that we are not updating usages inside polyfills.

I don't personally mind much how many files you include in each PR, but I do recommend if possible that you include at least a few in each PR, rather than one PR per page.

**Comment by gullapalli9482** [comment] 2022-05-25 15:41
Definitely 👍🏼 .

**Comment by wbamberg** [comment] 2022-06-22 21:09
Thanks @Phosra . I'm sure there are more, yes, but any progress here is good!

**Comment by Josh-Cena** [comment] 2022-07-03 15:39
I've done a basic run-through and removed the false-positives from polyfills (which will be removed anyway) and intended usages. Only about 35 pages left.

**Comment by Josh-Cena** [comment] 2022-07-11 12:50
As far as I can tell this seems to be done—can we do a run-down to confirm all the remaining usages are intended?

**Comment by teoli2003** [comment] 2022-07-11 13:00
These are the only ones with a `var ` entry:
- [ ] reference/functions/index.md
- [ ] reference/errors/deprecated_expression_closures/index.md
- [ ] reference/errors/delete_in_strict_mode/index.md
- [ ] reference/functions/default_parameters/index.md
- [ ] reference/strict_mode/index.md
- [ ] reference/global_objects/error/index.md
- [ ] reference/global_objects/eval/index.md
- [ ] reference/statements/block/index.md
- [ ] reference/global_objects/function/call/index.md
- [ ] reference/statements/for/index.md
- [ ] reference/statements/let/index.md
- [ ] reference/statements/for...in/index.md
- [ ] reference/statements/const/index.md
- [ ] reference/global_objects/array/@@unscopables/index.md
- [ ] reference/statements/function/index.md
- [ ] reference/statements/var/index.md
- [ ] closures/index.md
- [ ] a_re-introduction_to_javascript/index.md
- [ ] reference/classes/class_static_initialization_blocks/index.md
- [ ] reference/operators/delete/index.md
- [ ] reference/operators/this/index.md
- [ ] reference/operators/function/index.md
- [ ] guide/control_flow_and_error_handling/index.md
- [ ] guide/grammar_and_types/index.md
- [ ] guide/modules/index.md
- [ ] guide/details_of_the_object_model/index.md

I'll check them and ask questions if I have any doubt. (We'll do this when I'm back later today)

**Comment by Josh-Cena** [comment] 2022-07-11 13:03
The `details_of_the_object_model` needs a total revamp so I've kept it out for now (tracked in #10301). Otherwise it's quite weird to have `const`/`let` but all other syntax totally outdated.

**Comment by teoli2003** [comment] 2022-07-11 21:08
> There are other examples still, for example, I caught another in #18196

Yes, this issue is about the Web/JavaScript/ directory; we still have plenty vars to fix in Web/API, Games/, …
This is a first milestone (Yes, maintaining 10000+ pages is sometimes cumbersome).

**Comment by Josh-Cena** [comment] 2022-08-02 18:36
@teoli2003 did you get to do the last run-down? Judging from the recent unsuccessful attempts to change more vars to consts, I'm pretty confident it's all done.

**Comment by teoli2003** [comment] 2022-08-03 06:35
LGTM, let's close this one. \o/

**Closed by teoli2003** 2022-08-03 06:35 UTC
Labels: Content:JS
