### ISSUE TITLE
Missing importmap

### ISSUE THREAD

**Issue by Dreamsorcerer** [mdn/content#22980] opened 2022-12-15 15:33 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attr-type

### What specific section or headline is this issue about?

type

### What information was incorrect, unhelpful, or incomplete?

Firefox v108 release notes mentions supporting import maps, but this is not listed as a valid type on this page or mentioned anywhere on MDN currently.

### What did you expect to see?

Information about import maps.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/script`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/script/index.md
* Last commit: https://github.com/mdn/content/commit/ae3aa164f47537842934ffc0b58a41c841a6036b
* Document last modified: 2022-11-30T15:12:40.000Z

</details>

**Comment by Josh-Cena** [comment] 2022-12-15 17:17
Duplicate of #16150

**Comment by Josh-Cena** [comment] 2022-12-15 17:18
Will be fixed by the linked PRs in that issue

**Closed** 2022-12-15 17:18 UTC
Labels: duplicate, Content:HTML
