### ISSUE TITLE
Updating `sessionStorage` is not firing storage event. Only updating `localStorage` fires the storage event.

### ISSUE THREAD

**Issue by mayank1513** [mdn/content#34162] opened 2024-06-14 13:15 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window/storage_event

### What specific section or headline is this issue about?

Window: storage event

### What information was incorrect, unhelpful, or incomplete?

Updating `sessionStorage` is not firing storage event. Only updating `localStorage` fires the storage event.

### What did you expect to see?

When I update sessionStorage on one tab, the storage event (similar to the one that is fired when I update the localStorage) should be fire in the other tab with the same url.

### Do you have any supporting links, references, or citations?

I tested on local machine

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/window/storage_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/storage_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/storage_event/index.md
* Last commit: https://github.com/mdn/content/commit/14b411eb48e12a0157690930711868ddb94f860a
* Document last modified: 2024-03-13T14:27:11.000Z

</details>

**Comment by Josh-Cena** [comment] 2024-06-14 15:13
Actually duplicate of https://github.com/mdn/content/issues/30598

**Closed by Josh-Cena** 2024-06-14 15:13 UTC
Labels: help wanted, Content:WebAPI
