### ISSUE TITLE
Uncaught DOMException: IDBDatabase.transaction: 'notes_os' is not a known object store name

### ISSUE THREAD

**Issue by JuanPastenCastillo** [mdn/content#10659] opened 2021-11-20 17:09 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Client-side_storage

#### What information was incorrect, unhelpful, or incomplete?
The dont work, in the line 97 the browser says: "Uncaught DOMException: IDBDatabase.transaction: 'notes_os' is not a known object store name"

#### Specific section or headline?
Line 97

#### What did you expect to see?
The code work

#### Did you test this? If so, how?
I don't test it because i'm learning about this.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/client-side_web_apis/client-side_storage`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Client-side_storage
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/client-side_web_apis/client-side_storage/index.md
* Last commit: https://github.com/mdn/content/commit/07453ac2b659a397b0fee921fa71db5488e9ca62
* Document last modified: 2021-10-08T14:43:33.000Z

</details>

**Comment by Rumyra** [comment] 2021-11-22 16:06
Hi @JuanPastenCastillo - can you explain what you mean by 'line 97' please - is it the example?

**Comment by JuanPastenCastillo** [comment] 2021-11-22 16:26
Hi @Rumyra. Yes, i don't link what i mean with "line 97" to the problem. My bad.

In the javascript code of that article have the message of error that sais: "Uncaught DOMException: IDBDatabase.transaction: 'notes_os' is not a known object store name" in the line 97.

The javascript code (the problem in the line 97) is in the follow link: https://github.com/mdn/learning-area/blob/master/javascript/apis/client-side-storage/indexeddb/notes/index.js

Now i see the code running in my computer with vs code and liver server and i see that have two more errors: when you try to add some new note the line 61 will throw error (in the same javascript code shared above).

@Rumyra It is understood? Did i make myself explain?

**Comment by Rumyra** [comment] 2021-11-25 17:04
Yes thank you @JuanPastenCastillo that's really helpful. From a quick glance it seems 'notes_os' is either not being created or referenced properly. We'll need to dig a bit deeper to figure out whether it's a problem with the example code 👍 

Thanks so much for reporting :)

**Comment by himanshugarg** [comment] 2021-11-28 00:54
Possible duplicate of #2414

**Comment by sideshowbarker** [comment] 2022-02-17 03:11
Closing as duplicate per https://github.com/mdn/content/issues/10659#issuecomment-980815206

**Closed by sideshowbarker** 2022-02-17 03:11 UTC
Labels: needs-triage
