### ISSUE TITLE
Blob example not working

### ISSUE THREAD

**Issue by tonyschwebach** [mdn/content#35473] opened 2024-08-15 01:30 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Blob

### What specific section or headline is this issue about?

Examples

### What information was incorrect, unhelpful, or incomplete?

The example does not work. 

### What did you expect to see?

I expect clicking the button in the example would display the <p> element on the page, but nothing happens. An error is thrown.

InvalidAccessError: A parameter or an operation is not supported by the underlying object

### Do you have anything more you want to share?

To reproduce, go to https://developer.mozilla.org/en-US/docs/Web/API/Blob#examples "Result" section and and click the button.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/blob`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Blob
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/blob/index.md
* Last commit: https://github.com/mdn/content/commit/de2ef1e9950eebbacdd55f072dfe03014d113bbd
* Document last modified: 2024-07-13T01:34:51.000Z

</details>

**Comment by Josh-Cena** [comment] 2024-08-15 01:42
Duplicate of https://github.com/mdn/content/issues/34350

**Closed by Josh-Cena** 2024-08-15 01:42 UTC
Labels: Content:WebAPI, needs triage
