### ISSUE TITLE
Content bug: Link to resize on HTMLVideoElement is broken

### ISSUE THREAD

**Issue by amyrlam** [mdn/content#4230] opened 2021-04-19 03:40 UTC
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/API/HTMLVideoElement/videoHeight

## Specific page section or heading?

The link to `resize` under https://developer.mozilla.org/en-US/docs/Web/API/HTMLVideoElement/videoHeight#about_intrinsic_width_and_height and https://developer.mozilla.org/en-US/docs/Web/API/HTMLVideoElement/videoHeight#example is broken. It may not exist.

## What is the problem?

Link to `resize` is broken. It may not exist. See conversation on this PR: https://github.com/mdn/content/pull/4059#issuecomment-821420706

## What did you expect to see?

(1) Working resize link or (2) remove resize link if does not exist.

## Did you test this? If so, how?

Link to `resize` is red as it's broken. 

![image](https://user-images.githubusercontent.com/1372946/115178508-45ad9e00-a086-11eb-8d78-625dafab7eb6.png)

**Comment by bsmth** [comment] 2022-11-02 16:45
Hi @amyrlam it's common on MDN Web Docs to link to pages that do not yet exist as a means of adding a placeholder / reminder that this linked page should be created at some point.

As per the [comment you linked](https://github.com/mdn/content/pull/4059#issuecomment-821420706) it looks like we're supposed to be linking to a [resize event](https://html.spec.whatwg.org/multipage/media.html#event-media-resize).

**Comment by Josh-Cena** [comment] 2022-12-27 02:56
Duplicate of #11608. I'm going to keep that one as it's more specific about where to add the page.

**Closed** 2022-12-27 02:57 UTC
Labels: duplicate, Content:WebAPI
