### ISSUE TITLE
Mention how getPropertyValue serializes values (color representation, etc.)

### ISSUE THREAD

**Issue by kingma-sbw** [mdn/content#32826] opened 2024-03-25 16:39 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration/getPropertyValue

### What specific section or headline is this issue about?

Whole page

### What information was incorrect, unhelpful, or incomplete?

Everything ok here but I wonder if stating how color values are returned might help developers. It seems depending on browser it might return the color as `rgba(r, g, b, a)` or as how the color was specified in the first place. 

### What did you expect to see?

Mention how background-color and color are specified

### Do you have any supporting links, references, or citations?

https://stackoverflow.com/questions/9421208/how-to-compare-colors-in-javascript

**Comment by Josh-Cena** [comment] 2024-06-05 09:51
CSSOM cannot convert between color models because it's not going to be safe. We should probably slightly document https://drafts.csswg.org/cssom/#serialize-a-css-value on this page.

**Comment by kingma-sbw** [comment] 2024-06-06 06:08
It probably should not, but it does. 

Irrespective on how the color was defined getPropertyValue will return a `rgb(r, g, b, a)` value as far es I have seen in the wild

**Comment by Josh-Cena** [comment] 2024-06-06 06:21
Wow, I stand corrected then!

**Comment by Josh-Cena** [comment] 2024-06-06 06:22
Related to https://github.com/mdn/content/issues/32734. After we create a glossary, this page should link to it.

**Comment by kingma-sbw** [comment] 2024-06-06 06:39
I edited my bold statement which was plainly wrong. Where it _does_ convert is when using `getComputedStyle()` This will happily transform `#8CBF35` to  `rgb(140, 191, 53)` .

**Comment by Josh-Cena** [comment] 2024-06-06 07:44
@kingma-sbw that's not what I see though.

```html
<style>
  .foo {
    color: #8CBF35;
  }
</style>
<script>
  const declaration = document.styleSheets[0].cssRules[0].style;
  console.log(declaration.getPropertyValue("color"));
</script>
```

Output: `rgb(140, 191, 53)`

I'm using Chrome, latest. Safari and Firefox give the same output.

**Comment by Josh-Cena** [comment] 2024-07-12 22:55
After triaging, I noticed that https://github.com/mdn/content/issues/32734 is exactly asking for the same thing, so I'm closing this as a duplicate of that. Pages such as https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/hwb already have the following note:

> Absolute `hwb()` colors are serialized to [`rgb()`](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/rgb) values. The values of the red, green, and blue components may be rounded in serialization.

**Closed by Josh-Cena** 2024-07-12 22:55 UTC
Labels: help wanted, Content:WebAPI, area: DOM/CSSOM
