### ISSUE TITLE
Print execution is blocked in sandbox (Chrome 130+)

### ISSUE THREAD

**Issue by ivanStraltsou** [mdn/content#36565] opened 2024-10-29 21:58 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/@page

### What specific section or headline is this issue about?

Examples

### What information was incorrect, unhelpful, or incomplete?

"Print website" button is not working with (Ignored call to 'print()'. The document is sandboxed, and the 'allow-modals' keyword is not set.)

### What did you expect to see?

Print modal window preview

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/@page`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/@page
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/@page/index.md
* Last commit: https://github.com/mdn/content/commit/ed9ebd794add41de1f2e759502b73e8650afe56b
* Document last modified: 2024-10-02T13:58:44.000Z

</details>

**Comment by Josh-Cena** [comment] 2024-10-29 23:11
Duplicate of #36132

**Closed by Josh-Cena** 2024-10-29 23:11 UTC
Labels: Content:CSS, needs triage
