### ISSUE TITLE
LaTeX not working in Math.hypot() page

### ISSUE THREAD

**Issue by its4zahoor** [mdn/content#253] opened 2020-12-15 17:54 UTC
The Formula for Hypotenuse in [Math.hypot()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/hypot) is not rendering in LaTeX, Screenshot attached below 

![image](https://user-images.githubusercontent.com/24554084/102252824-632bf900-3f28-11eb-9e81-20c7aac00f27.png)

**Comment by sideshowbarker** [comment] 2020-12-15 18:49
Can’t reproduce. In what browser?

The markup source of that formula in that article isn’t LaTeX — instead the source is MathML markup, right?

**Comment by doersino** [comment] 2020-12-15 23:12
Broken in Chrome, the TeX-style `<annotation>` is shown there instead. Works fine in browsers that support MathML.

**Comment by sideshowbarker** [comment] 2020-12-15 23:51
> Broken in Chrome, the TeX-style `<annotation>` is shown there instead. Works fine in browsers that support MathML.

Ah, I see. It works fine for me in my Chrome — but I suppose that might be because I’m running Chrome Canary, v89, and that has some MathML support that’s not in the current stable version of Chrome?

**Comment by sideshowbarker** [comment] 2020-12-16 01:59
OK I realize now it works for me because I have chrome://flags/#enable-experimental-web-platform-features enabled.

So the workaround for now is to open chrome://flags/#enable-experimental-web-platform-features in Chrome and select **Enabled** to turn it on.

**Comment by its4zahoor** [comment] 2020-12-16 18:17
@sideshowbarker yeah It's broken for current stable builds of 
-  ```Microsoft Edge Version 87.0.664.60 (Official build) (64-bit)``` and
-  ```Google Chrome Version 87.0.4280.88 (Official Build) (64-bit)```

**Comment by sideshowbarker** [comment] 2021-06-06 07:05
We’re now using https://github.com/mdn/content/issues/3435 to track the general issue here, so I’m going to close this as superseded by that issue.

**Closed by sideshowbarker** 2021-06-06 07:05 UTC

**Comment by its4zahoor** [comment] 2021-11-18 21:38
The [Math.log10](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/log10 ) is still showing raw math syntax.

![MathLog10_LaTeX](https://user-images.githubusercontent.com/24554084/142500705-8784c206-38fb-4dee-be09-de1d8fbef8e3.png)
