### ISSUE TITLE
Issue with "JSON viewer": This video is private

### ISSUE THREAD

**Issue by ivki** [mdn/content#13890] opened 2022-03-15 10:11 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/JSON_viewer

#### What information was incorrect, unhelpful, or incomplete?

Youtube video on JSON viewer is set to "private", so not available to viewers.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/json_viewer`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/JSON_viewer
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/json_viewer/index.html
* Last commit: https://github.com/mdn/content/commit/cbe151a06d6e5b4d1fbb46081bd16e69ef4c1630
* Document last modified: 2020-09-15T15:48:51.000Z

</details>

**Comment by teoli2003** [comment] 2022-03-15 10:12
This is indeed annoying. I'm closing this issue as it is a duplicate of #7457.

**Closed by teoli2003** 2022-03-15 10:12 UTC
Labels: needs-triage
