### ISSUE TITLE
Issue with "Math.sqrt()": …

### ISSUE THREAD

**Issue by jasontwuk** [mdn/content#458] opened 2020-12-19 10:59 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/sqrt

#### What information was incorrect, unhelpful, or incomplete?
Hi, I am not a math expert, but the highlighted code does not make sense to me. Maybe it is an error?
![screenshot](https://user-images.githubusercontent.com/13745974/102687614-34dc4100-41e8-11eb-86f4-a6274e28368e.png)

#### Specific section or headline?
At the top of the web page.

#### What did you expect to see?
Maybe it should be `√number`?

#### Did you test this? If so, how?
I did not test it.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/math/sqrt`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/sqrt
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/global_objects/math/sqrt/index.html
* Report started: 2020-12-19T09:32:53.939Z

</details>

**Comment by sideshowbarker** [comment] 2020-12-19 16:37
Thanks — I think this is a duplicate of https://github.com/mdn/content/issues/253

**Comment by jasontwuk** [comment] 2020-12-19 17:01
You are welcome. 
`Math.PI` has the same issue too.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/PI
![screenshot](https://user-images.githubusercontent.com/13745974/102694857-97026980-421b-11eb-8ea0-a7b41716f3e7.png)

**Comment by sideshowbarker** [comment] 2020-12-19 17:03
> `Math.PI` has the same issue too.

Yeah I think most all the pages with embedded MathML have this problem

**Comment by sideshowbarker** [comment] 2021-02-27 02:53
Closing as duplicate of #253

**Closed by sideshowbarker** 2021-02-27 02:53 UTC
