### ISSUE TITLE
Array Method Not Scrollable

### ISSUE THREAD

**Issue by cuthbertpress** [mdn/content#25675] opened 2023-03-27 13:56 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice

### What specific section or headline is this issue about?

Methods

### What information was incorrect, unhelpful, or incomplete?

Array Methods not scrollable and thus most of them are hidden.

### What did you expect to see?

I need the array methods to be scrollable

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/slice`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/slice/index.md
* Last commit: https://github.com/mdn/content/commit/194d3e00cb93a6e5ea44812548f4131cb17f0381
* Document last modified: 2023-02-21T00:33:25.000Z

</details>

**Comment by Josh-Cena** [comment] 2023-03-27 14:00
Duplicate of https://github.com/mdn/yari/issues/8494

**Closed as not planned by Josh-Cena** 2023-03-27 14:00 UTC
