### ISSUE TITLE
Issue with "String.prototype.slice()": …

### ISSUE THREAD

**Issue by manngo** [mdn/content#941] opened 2021-01-05 01:07 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice

#### What information was incorrect, unhelpful, or incomplete?

> If `endIndex` is omitted or undefined, or greater than `str.length`, `slice()` extracts to the end of the string. If negative, it is treated as `str.length + endIndex`. (For example, if `endIndex` is `-3`, it is treated as `str.length - 3`.) If it is not undefined and not a number after `Number(endIndex)`, an empty string is returned.

#### Specific section or headline?

endIndex

#### What’s the problem?

The phrase

> not a number after `Number(endIndex)`

is very hard to understand. What does it mean exactly. Does it just mean not a number? There is a similar phrase for `beginEndex`.

BTW what has happened to the Edit button? I want to make a few layout changes.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/string/slice`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/global_objects/string/slice/index.html
* Report started: 2021-01-05T01:02:10.874Z

</details>

**Comment by sideshowbarker** [comment] 2021-01-05 04:34
> BTW what has happened to the Edit button? I want to make a few layout changes.

See https://github.com/mdn/content/blob/main/README.md#making-contributions. The mechanism for making edits is now to use GitHub to create patches and pull requests.

* https://github.com/mdn/content/blob/main/README.md#simple-changes explains how you can use the GitHub web UI to make small changes directly.

* https://github.com/mdn/content/blob/main/README.md#more-substantial-changes explains how to make more substantial changes (using the `git` CLI or GitHub Desktop client).

**Comment by Ryuno-Ki** [comment] 2021-02-12 08:52
@manngo If you want to pick this up, please edit

https://github.com/mdn/content/blob/6d93334d29b5771389f39c19b0b2e8ce7df01931/files/en-us/web/javascript/reference/global_objects/string/slice/index.html#L40-L56

(While at it, the `<var>` elements can be dropped at the very least).

@theonlypwner already made some changes in https://github.com/mdn/content/commit/d4ee7cef94566b023c633e5332e1173d524427c7

**Comment by theonlypwner** [comment] 2021-02-12 18:21
#1868 fixed #1838 by updating the `endIndex` description to

> The zero-based index _before_ which to end extraction. The character at this index will not be included.
>
> If `endIndex` is omitted or undefined, or greater than `str.length`, `slice()` extracts to the end of the string. If negative, it is treated as `str.length + endIndex`. (For example, if `endIndex` is `-3`, it is treated as `str.length - 3`.) If it is not undefined, and `Number(endIndex)` is not positive, an empty string is returned.
>
> If `endIndex` is specified, `endIndex` should be greater than `beginIndex`, otherwise an empty string is returned. (For example, `slice(-3, 0)`, `slice(-1, -3)`, or `slice(3, 1)` returns `""`.)

I also fixed the original issue, by simply saying

> `Number(endIndex)` is not positive

because if `endIndex` (after adding `str.length` if needed) is 0 or negative or NaN or -Infinity, the result will be an empty string.

---

However, I did not edit `startIndex`. The current text is
> The zero-based index at which to begin extraction. If negative, it is treated as `str.length + beginIndex`. (For example, if `beginIndex` is `-3`, it is treated as `str.length - 3`.) If `beginIndex` is not a number after `Number(beginIndex)`, it is treated as `0`.

I would edit it to
> The zero-based index at which to begin extraction. If negative, it is treated as `str.length + beginIndex`. (For example, if `beginIndex` is `-3`, it is treated as `str.length - 3`.) If `Number(beginIndex)` is not positive, `beginIndex` is treated as `0`.

because if `beginIndex` (after adding `str.length` if needed) is 0 or negative or NaN or -Infinity, it will have the same effect as if it had been 0.

---

Also, do we really want to drop `<var>` elements? They italicize the variable names.

**Comment by teoli2003** [comment] 2021-06-07 12:58
I think this was a duplicate of # #5371 and fixed by #5372.

If so, can someone close this issue here too? Thanks.

**Comment by theonlypwner** [comment] 2021-06-07 15:40
This issue is regarding "not a number after `Number(beginIndex)`" and "not a number after `Number(endIndex)`".

The description for `beginIndex` has not been touched yet, but the description for `endIndex` was updated in #1868 and later #5372.

The next step seems to be to clarify the behavior of `endIndex` for `NaN` and update "not a number after `Number(beginIndex)`" to match the style of the description for `endIndex`.

**Closed** 2021-09-10 14:50 UTC
Labels: help wanted, Content:JS
