### ISSUE TITLE
HTML-only example not closing dialog

### ISSUE THREAD

**Issue by mrec** [mdn/content#37132] opened 2024-12-07 07:50 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog

### What specific section or headline is this issue about?

Examples > HTML-only dialog

### What information was incorrect, unhelpful, or incomplete?

Clicking the OK button in this example does not close the dialog as promised

### What did you expect to see?

Dialog closes when clicking OK

### Do you have any supporting links, references, or citations?

Firefox 133.0 (64-bit), WIn10 Pro

### Do you have anything more you want to share?

The same example works fine when opened in the Playground

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/dialog`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/dialog/index.md
* Last commit: https://github.com/mdn/content/commit/d2421d25d1676cc11b01cc4981061e4d0aa78e95
* Document last modified: 2024-10-29T20:01:28.000Z

</details>

**Comment by Josh-Cena** [comment] 2024-12-07 19:23
Duplicate of https://github.com/mdn/yari/issues/11460

**Closed by Josh-Cena** 2024-12-07 19:23 UTC
Labels: Content:HTML, needs triage
