### ISSUE TITLE
Guide: Using Custom Elements; Autonomous Custom Elements. Code example incorrect. 

### ISSUE THREAD

**Issue by simonfox** [mdn/content#27605] opened 2023-06-27 20:59 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_custom_elements

### What specific section or headline is this issue about?

Autonomous Custom Elements

### What information was incorrect, unhelpful, or incomplete?

The paragraph below is inconsistent with the linked example at https://github.com/mdn/web-components-examples/blob/main/popup-info-box-web-component/main.js

> Inside the method connectedCallback, we define all the functionality the element will have when the element is connected to the DOM. In this case we attach a shadow root to the custom element, use some DOM manipulation to create the element's internal shadow DOM structure — which is then attached to the shadow root — and finally attach some CSS to the shadow root to style it. We don't use constructor() because an element's attributes are unavailable until connected to the DOM.

### What did you expect to see?

The content describes work to be done in the `connectedCallback` and specifically says not to use the constructor. In the linked example however, the work is done in the constructor.

I'm assuming that the example is incorrect?

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/web_components/using_custom_elements`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_custom_elements
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/web_components/using_custom_elements/index.md
* Last commit: https://github.com/mdn/content/commit/270351317fdaa57ba9123a19aa281e9e40bb0baa
* Document last modified: 2023-06-20T19:01:21.000Z

</details>

**Comment by Josh-Cena** [comment] 2023-06-28 03:08
Duplicate of https://github.com/mdn/content/issues/22887

**Closed** 2023-06-28 03:08 UTC
Labels: closed: duplicate, Content:WebAPI, area: Web Components
