### ISSUE TITLE
Issue with "Browser compatibility and Scroll Snap": Macbook Pro 2019 (Intel) / MacOs Monterey

### ISSUE THREAD

**Issue by Yaidier** [mdn/content#10562] opened 2021-11-16 11:22 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scroll_Snap/Browser_compat

Im developing an app that uses this property... suddenly stopped working as expected... the I realized that the problem wasn't related only to my app but to the css property itself... it does works fine in all other browsers but firefox...

Finally I landed on this page (https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scroll_Snap/Browser_compat) and even there the expample doesn' t work..

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/css_scroll_snap/browser_compat`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scroll_Snap/Browser_compat
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_scroll_snap/browser_compat/index.md
* Last commit: https://github.com/mdn/content/commit/26f50bdaeb1228f458d21dbdf7dc110387b20daa
* Document last modified: 2021-08-12T23:59:09.000Z

</details>

**Comment by wbamberg** [comment] 2021-11-18 00:46
I think this page: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scroll_Snap/Browser_compat is only relevant for old versions of Firefox (up to version 68, released more than 2 years ago now: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/68).

And scroll snap is supported in Firefox: for me at least, the interactive example at https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-snap-type works as expected.

Can you create a codepen that shows the problem as simply as possible? Otherwise it's hard to know what the issue is here.

**Comment by ankurpiparsania** [comment] 2021-11-18 06:15
@wbamberg  I too am seeing this same issue. even the example listed in https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-snap-type doesnt seem to work. See video below to get idea of erratic behaviour. It seems that if you do a slow long scroll using touchpad, then it works but a quick inertia scroll using touchpad doesn't snap

https://user-images.githubusercontent.com/49896447/142362009-c0554e68-2481-4ab7-83af-7d4a6f309184.mov

**Comment by Yaidier** [comment] 2021-11-18 06:35
@wbamberg Thanks for your response... as @ankurpiparsania show in his video that is exactly what happen to me... it doesn't work neither on https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-snap-type, the scroll gets stuck most of the time. Here the codepen: https://codepen.io/yaidier/pen/oNemzpq

I updated to MacOs Monterey recently so maybe it is related??? @ankurpiparsania What hardware/software do you use?

**Comment by wbamberg** [comment] 2021-11-18 17:40
Thanks a lot for the extra information, it's really helpful. I can't reproduce this on Big Sur, but it does look like there is a problem on Monterey: https://bugzilla.mozilla.org/show_bug.cgi?id=1737820 - does that look like the same thing to you?

Not sure if we should document this though, if it's likely to get fixed - I don't think it's practical for us to document every bug in every browser.

**Comment by Yaidier** [comment] 2021-11-18 17:56
That is exactly what is going on...

**Comment by wbamberg** [comment] 2021-11-20 00:49
I've filed https://github.com/mdn/browser-compat-data/pull/13654 to note this as a browser compatibility issue.

**Comment by wbamberg** [comment] 2021-11-20 00:50
I'm also wondering whether we should delete https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scroll_Snap/Browser_compat - it seems more likely to confuse people than anything else, at this point.

**Comment by wbamberg** [comment] 2021-11-26 20:26
Fixed by https://github.com/mdn/browser-compat-data/pull/13654 and https://github.com/mdn/content/pull/10794.

**Closed by wbamberg** 2021-11-26 20:26 UTC
Labels: needs-triage
