### ISSUE TITLE
mongoose.prototype.save() does not accept callbacks anymore

### ISSUE THREAD

**Issue by Mineycrates** [mdn/content#25195] opened 2023-03-09 06:30 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose

### What specific section or headline is this issue about?

populatedb.js

### What information was incorrect, unhelpful, or incomplete?

populatedb.js returned errors --
When I tried running the script, an error was returned, indicating that mongoose.prototype.save() does not accept callback functions anymore. I checked the documentation in mongoose and found out that it is now promise-based. I modified the code (using .then and .catch) accordingly and the script executed properly.

### What did you expect to see?

for populatedb.js to execute without errors

### Do you have anything more you want to share?

snippet of the erroneous code from populatedb.js:

`author.save(function (err) {
    if (err) {
      cb(err, null)
      return
    }
    console.log('New Author: ' + author);
    authors.push(author)
    cb(null, author)
  }  );`
  
  modified local code to run the script without errors:
  `author.save().then(() => {
    console.log('New Author: ' + author);
    authors.push(author)
    cb(null, author)
  }).catch(err => {
    if (err) {
      cb(err, null)
      return
    }
  });`

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/mongoose`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/mongoose/index.md
* Last commit: https://github.com/mdn/content/commit/3de92d2ceb72d561b0979db3675320405fa04952
* Document last modified: 2023-03-06T06:22:07.000Z

</details>

**Comment by teoli2003** [comment] 2023-03-09 06:35
Duplicate of #24972

**Closed by teoli2003** 2023-03-09 06:35 UTC
Labels: needs triage
