### ISSUE TITLE
Doesn't Scroll to subheading in chrome

### ISSUE THREAD

**Issue by fawazahmed0** [mdn/content#24552] opened 2023-02-19 01:11 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#simplifying_scope_management

### What information was incorrect, unhelpful, or incomplete?

This [link](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#simplifying_scope_management), doesn't scroll to subheading in chrome, but seems to scroll fine in firefox.

### What did you expect to see?

Scroll to subheading should work in chrome

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/strict_mode`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/strict_mode/index.md
* Last commit: https://github.com/mdn/content/commit/4d5e54779c2a9bede3bfd8858f062ad9b366f9dd
* Document last modified: 2023-02-12T05:44:52.000Z

</details>

**Comment by teoli2003** [comment] 2023-02-19 01:25
I can confirm the behavior. 

@schalkneethling Can you move this to mdn/yari (not sure if it is a yari issue or a Chrome issue, but there is nothing that content can do, the fragment looks ok)

**Comment by Josh-Cena** [comment] 2023-02-19 02:30
Duplicate of https://github.com/mdn/yari/issues/7168

**Closed by Josh-Cena** 2023-02-19 02:30 UTC
Labels: Content:JS, needs triage
