### ISSUE TITLE
Issue with "brightness()": (short summary here please)

### ISSUE THREAD

**Issue by naman77s** [mdn/content#7091] opened 2021-07-20 15:28 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function/brightness()

#### Did you test this? If so, how?

<!-- Do not make changes below this line --
![Screenshot_2021-07-20-20-56-57-739_com android chrome](https://user-images.githubusercontent.com/70265763/126351693-16089ebf-7f5a-47a3-87c6-dec7f77f20ed.jpg)
>
<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/filter-function/brightness()`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function/brightness()
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/filter-function/brightness()/index.html
* Last commit: https://github.com/mdn/content/commit/16c9986e59c1601d10d04568d95223b40dc7f249
* Document last modified: 2021-07-04T00:13:30.000Z

</details>

**Comment by reddymahendra52** [comment] 2021-07-20 15:48
Can you please elaborate on what the issue is??

**Comment by naman77s** [comment] 2021-07-20 15:51
I actually attached a photo, maybe it wasnt attached.. See the image below,
The text line with white background going outside it's parent box

**Comment by bariscanyilmaz** [comment] 2021-07-20 16:30
@naman77s image isn't attached. There is no image.

**Comment by naman77s** [comment] 2021-07-20 16:32
Sorry about that, here it is.

**Comment by bariscanyilmaz** [comment] 2021-07-20 17:46
@naman77s  I think your images not uploaded to github. I can't see your images. I attached your latest reply's screenshot. Do you see it.
![issue](https://user-images.githubusercontent.com/30300440/126370722-460973ce-7542-4ca4-b22c-eb63d083cf37.png)

**Comment by naman77s** [comment] 2021-07-20 18:10
Yes i can see

**Comment by Ryuno-Ki** [comment] 2021-07-20 18:50
Attachment won't be processed by GitHub. Please use the web UI to upload the image.

**Comment by teoli2003** [comment] 2021-08-14 11:41
As there is no information provided for 25 days, I'm closing this.

@naman77s, please, reopen this if you are able to provide some information on the issue (or open a new issue if you prefer).

**Closed by teoli2003** 2021-08-14 11:41 UTC
