### ISSUE TITLE
Google Chrome does not scroll down to page section indicated by URL fragment

### ISSUE THREAD

**Issue by maksverver** [mdn/content#34686] opened 2024-07-07 18:51 UTC
This happens with literally all URLs on the MDN site, but consider an example: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#loading

If I enter this URL in the location bar in Firefox, the page loads, and the browser view scrolls down to the section on the `loading` attribute. This is the expected behavior.

If I enter the same URL in the location bar in Chrome, the page loads, but does not scroll down! This is unexpected.

I noticed that clicking on a heading inside the page does cause the page to scroll (and the URL in the location bar to change accordingly), so it's not completely broken, but clicking on any link to a *different page* causes the page to load *without* scrolling down to the appropriate section (indicated by the URL fragment), which makes it quite difficult to navigate the site.

I tested this with a fresh user profile (default settings, no account, no extensions, etc.). Version info:

```
Google Chrome	126.0.6478.126 (Official Build) (64-bit) 
Revision	d36ace6122e0a59570e258d82441395206d60e1c-refs/branch-heads/6478@{#1591}
OS	Linux
JavaScript	V8 12.6.228.21
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

```

**Comment by Josh-Cena** [comment] 2024-07-07 18:53
Duplicate of https://github.com/mdn/yari/issues/8049. This repo is for content issues, not issues with the website.

**Closed by Josh-Cena** 2024-07-07 18:53 UTC
Labels: Content:HTML, needs triage
