### ISSUE TITLE
Issue with "Document.elementFromPoint()": Add info about nodes dragged and their position in the DOM tree

### ISSUE THREAD

**Issue by surfmuggle** [mdn/content#3520] opened 2021-03-26 07:48 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/elementFromPoint

#### What information was incorrect, unhelpful, or incomplete?

We were using `elementFromPoint ` for a node that can be dragged for the dragend event to find out which node is below the dragged node. In the recent Edge this works but in Firefox it does not. I assume that the cause is that a dragged node is

- above the "node" document / window in firefox
- above the current node below the dragged node in edge

~~We found a "fix" - instead of using the `onDragEndEvent` we can use `onDropEvent`. For the drop event `document.elementFromPoint` returns the expected node.~~

```
draggableNode.addEventListener("dragend", onDragEndEvent, false);


function onDragEndEvent(event)
{
     // returns html in firefox  but the node below in edge / 
     let elemBelow = document.elementFromPoint(event.clientX, event.clientY);
}

function onDropEvent(event)
{
    // i was wrong here 
}
```

#### Specific section or headline?

None. I suggest to add an additional information or a link to explain why `document.elementFromPoint` returns the html root for a  dragged node

#### What did you expect to see?

For the `dragend` event i expected that firefox behaves like edge. That `document.elementFromPoint` return the node under the draggedElement at the moment the event dragEnd fires. 
~~None the less i now understand that the drop event might be better suited.~~

#### Did you test this? If so, how?

I created a codepen https://codepen.io/codemuggle/pen/NWbQqOW

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/document/elementfrompoint`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/elementFromPoint
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/document/elementfrompoint/index.html
* Last commit: https://github.com/mdn/content/commit/8c415e413672154158329afc9812d320c1ca97c8
* Document last modified: 2021-03-15T11:09:29.000Z

</details>

**Comment by OnkarRuikar** [comment] 2024-06-09 06:12
I am not able to reproduce this on Firefox 128.0a1 (2024-05-30) (64-bit). I used the same codepen.

**Comment by Josh-Cena** [comment] 2024-06-13 18:38
I think this is fixed now.

**Closed by Josh-Cena** 2024-06-13 18:38 UTC
Labels: help wanted, Content:WebAPI, area: DOM/CSSOM
