### ISSUE TITLE
Web Push userVisibleOnly Details

### ISSUE THREAD

**Issue by aluhrs13** [mdn/content#30077] opened 2023-11-06 21:13 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/PushSubscriptionOptions/userVisibleOnly

### What information was incorrect, unhelpful, or incomplete?

The [Push API spec](https://w3c.github.io/push-api/#dom-pushsubscription-options) includes a [`userVisibleOnly`](https://w3c.github.io/push-api/#dom-pushsubscriptionoptions-uservisibleonly) option, that MDN implies is fully functional for WebKit or Chromium browsers but isn't actually the case. Both will reject the promise requiring it to be true.

Normally an API predictably rejecting a promise isn't a huge deal, but if a developer goes through the overhead of understanding `applicationServerKey`, VAPID, push services, etc. only to see "Promise Rejected", that could be extremely frustrating.

At a minimum it seems like the page PushSubscription options should include details on this, but the following pages could probably use more aggressive dissuading developers from trying to use push for non-visible cases:
1. https://developer.mozilla.org/en-US/docs/Web/API/PushManager/subscribe#syntax
2. https://developer.mozilla.org/en-US/docs/Web/API/Push_API
3. https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Tutorials/js13kGames/Re-engageable_Notifications_Push

For completeness, I could I only find one page online calling out this behavior - https://web.dev/articles/push-notifications-subscribing-a-user#uservisibleonly_options

### What did you expect to see?

That browsers might reject a subscription if `userVisibleOnly` is set to false. Happy to open an issue and/or PR on the browser-compat-data side if that's the best place to approach this too.

### Do you have any supporting links, references, or citations?

- Chromium source: https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/push_messaging/push_messaging_service_impl.cc;l=561
- WebKit source: https://github.com/WebKit/WebKit/blob/main/Source/WebCore/Modules/push-api/PushManager.cpp#L80

**Comment by caugner** [comment] 2023-11-08 11:22
The **read-only** `userVisibleOnly` property on the `PushSubscriptionOptions` object seems to be supported in Chrome 54+, Edge 17+, Opera 41+ and partially supported in Safari 16+, according to BCD.

You're saying that browsers reject a subscription if `userVisibleOnly` is set to false, but [this page](https://developer.mozilla.org/en-US/docs/Web/API/PushSubscriptionOptions/userVisibleOnly) seems to be about being able to **read** this property.

It looks like the `userVisibleOnly` property can only be set on the `PushSubscriptionOptionsInit` dictionary, which isn't explicitly documented on MDN, but covered by the [PushManager.subscribe() ](https://developer.mozilla.org/en-US/docs/Web/API/PushManager/subscribe#uservisibleonly) article.

I agree that the definition of `userVisibleOnly` on that page could mention that the value must be set to `true` in practice, even though the specification doesn't mention this requirement.

**Comment by Sriparno08** [comment] 2023-11-11 09:05
Hey @caugner, can I work on this?

**Comment by Ryuno-Ki** [comment] 2023-11-17 15:05
I learned about this issue [on Mastodon](https://mas.to/@patrickbrosset/111425231278280655) because @captainbrosset tooted about it.

When trying the demo at https://attractive-tranquil-nephew.glitch.me/ I cannot reproduce the behaviour in Firefox 115.0.2 on Debian/Linux. Nevertheless I would be willing to submit a PR that addresses this:

> It looks like the userVisibleOnly property can only be set on the PushSubscriptionOptionsInit dictionary, which isn't explicitly documented on MDN, but covered by the [PushManager.subscribe() ](https://developer.mozilla.org/en-US/docs/Web/API/PushManager/subscribe#uservisibleonly)article.
> 
> I agree that the definition of userVisibleOnly on that page could mention that the value must be set to true in practice, even though the specification doesn't mention this requirement.

**Comment by captainbrosset** [comment] 2023-11-17 16:38
The error message seems to be displayed on Chromium-based browsers (in the Console panel of DevTools). Nothing seems to happen in Firefox.

**Comment by Ryuno-Ki** [comment] 2023-11-18 20:59
Confirmed (as in: Promise rejected logged to the console) with Chromium Version 119.0.6045.159 (Official Build) built on Debian 12.2, running on Debian (64-bit).

**Comment by Ryuno-Ki** [comment] 2023-11-18 21:12
I've submitted https://github.com/mdn/content/pull/30369 and checked the other MDN pages. As far as I can tell, the property is always set to `true` there.

**Comment by Josh-Cena** [comment] 2024-06-14 15:24
I think this is sufficiently fixed by https://github.com/mdn/content/pull/30369

**Closed by Josh-Cena** 2024-06-14 15:24 UTC
Labels: Content:WebAPI, effort: small, Content:PWA, goal: clarity, goal: accuracy
