### ISSUE TITLE
Response.json(): missing static method documentation

### ISSUE THREAD

**Issue by mfulton26** [mdn/content#25180] opened 2023-03-08 15:46 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Response/json

### What information was incorrect, unhelpful, or incomplete?

[`Response.prototype.json()`](https://fetch.spec.whatwg.org/#dom-body-json) and [`Response.json()`](https://fetch.spec.whatwg.org/#dom-response-json) are both defined in [Fetch Standard](https://fetch.spec.whatwg.org/) but MDN only documents the instance method and not the static method.

### What did you expect to see?

`json()` listed in the side navigation box along with the other static methods ([error()](https://developer.mozilla.org/en-US/docs/Web/API/Response/error) and [redirect()](https://developer.mozilla.org/en-US/docs/Web/API/Response/redirect)).

### Do you have any supporting links, references, or citations?

- https://fetch.spec.whatwg.org/#dom-body-json
- https://fetch.spec.whatwg.org/#dom-response-json

### Do you have anything more you want to share?

Should content for both go on the same page? Is there a way to differentiate in the MDN URL between static and instance methods? They both appear to currently map to https://developer.mozilla.org/en-US/docs/Web/API/Response/json.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/response/json`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Response/json
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/response/json/index.md
* Last commit: https://github.com/mdn/content/commit/3b22c657f659c249cbe6e4fc6794370a5cb67a72
* Document last modified: 2023-03-01T11:11:40.000Z

</details>

**Comment by teoli2003** [comment] 2023-03-08 16:01
Duplicate of #21550

**Closed by teoli2003** 2023-03-08 16:01 UTC
Labels: Content:WebAPI, needs triage
