### ISSUE TITLE
Clarify license for sample code

### ISSUE THREAD

**Issue by mdedetrich** [mdn/content#27920] opened 2023-07-13 11:53 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie

### What specific section or headline is this issue about?

Sample code

### What information was incorrect, unhelpful, or incomplete?

At https://github.com/mdn/content/blob/main/LICENSE.md#licenses-for-code-examples-and-snippets it states what the licenses for code snippets are in Mozilla's MDN code samples, that is after Auguest 2010 code samples are licensed with CC0 and before that they are licensed as MIT.

The problem is that when looking at the history of the sample code, i.e. https://github.com/mdn/content/blob/main/files/en-us/web/api/document/cookie/index.md its unclear when exactly it was created and hence which license it has (the git history of that file appears to start at some kind of code dump and its unclear where that originating code came from).

The context behind this issue is that the Apache Pekko project references some of this code and because of this we need to know which license it has (see https://lists.apache.org/thread/0tdcpcnzlfpm7zt0fvgx95t7h2cr4j75 and https://www.apache.org/legal/resolved.html#handling-public-domain-licensed-works).

### What did you expect to see?

Initially an answer as to when this specific code sample (i.e. https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie) was created so I can clarify the license (CC0 or MIT).

Ideally it would be nice if each doc page either stated the license of that page at the bottom and/or a date when the doc was originally created (this can be considered a nice to have).

### Do you have any supporting links, references, or citations?

Mentioned before but repeating again for reference

- https://lists.apache.org/thread/0tdcpcnzlfpm7zt0fvgx95t7h2cr4j75
- https://www.apache.org/legal/resolved.html#handling-public-domain-licensed-works

**Comment by Josh-Cena** [comment] 2023-07-13 12:33
Duplicate of https://github.com/mdn/content/issues/17396

Assuming CC0 if the code was present in the initial checkin is a safer bet.

**Closed by Josh-Cena** 2023-07-13 12:33 UTC
Labels: Content:WebAPI, needs triage
