### ISSUE TITLE
Conflicting documentation about `pushState` and the `popState` event

### ISSUE THREAD

**Issue by Mossop** [mdn/content#30168] opened 2023-11-09 22:06 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/History/pushState

### What specific section or headline is this issue about?

History: pushState() method

### What information was incorrect, unhelpful, or incomplete?

The page says:
```
This method is asynchronous. Add a listener for the popstate event in order to determine when the navigation has completed. The state parameter will be available in it
```

But over on the docs for [popstate](https://developer.mozilla.org/en-US/docs/Web/API/Window/popstate_event) it says:
```
Note that just calling history.pushState() or history.replaceState() won't trigger a popstate event.
```

### What did you expect to see?

The two pages should agree on whether calling `pushState` triggers a `popstate` event or not (I don't think it does).

**Comment by wbamberg** [comment] 2023-11-09 22:29
This is a duplicate of https://github.com/mdn/content/issues/30014 - as I commented there, yes, I also think `pushState` does not trigger a `popstate` event.

Oh and also https://github.com/mdn/content/issues/25785.

I'll file a PR to fix it.

**Closed** 2023-11-10 07:49 UTC
Labels: Content:WebAPI, needs triage
