### ISSUE TITLE
Issue with "Select an element": YouTube videos are dead links

### ISSUE THREAD

**Issue by nok-ko** [mdn/content#10194] opened 2021-11-01 00:28 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Select_an_element

#### What information was incorrect, unhelpful, or incomplete?
All of the embedded YouTube videos show “This video is unavailable”
<img width="776" alt="image" src="https://user-images.githubusercontent.com/13428215/139606708-c6127dad-6ba6-478c-a0dc-1b652dc159a2.png">

#### What did you expect to see?
The YouTube videos.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/page_inspector/how_to/select_an_element`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Select_an_element
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/page_inspector/how_to/select_an_element/index.html
* Last commit: https://github.com/mdn/content/commit/05b71a290b2ab444b23e0f35f619d93203c7e2d8
* Document last modified: 2021-02-02T16:31:29.000Z

</details>

**Comment by hamishwillee** [comment] 2021-11-01 00:56
Thanks very much for reporting. Closing as a duplicate of https://github.com/mdn/content/issues/7457 . This is planned to be fixed in the very near future.

**Comment by hamishwillee** [comment] 2021-11-01 00:56
Actually, reopening. This is in a different area. @rebloor FYI

**Comment by wbamberg** [comment] 2022-01-12 04:22
This is tracked in https://github.com/mdn/content/issues/7457 (specifically, at https://github.com/mdn/content/issues/7457#issuecomment-982736416).

**Closed by wbamberg** 2022-01-12 04:22 UTC
Labels: Content:DevTools, needs-triage
