### ISSUE TITLE
IDs can actually start with a digit

### ISSUE THREAD

**Issue by WebReflection** [mdn/content#25769] opened 2023-03-30 09:56 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id

### What specific section or headline is this issue about?

The warning in the middle of the page

### What information was incorrect, unhelpful, or incomplete?

the value for an id attribute should start with a letter

### What did you expect to see?

Accordingly to the linked standard:

> There are no other restrictions on what form an ID can take; in particular, IDs can consist of just digits, start with a digit, start with an underscore, consist of just punctuation, etc.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/global_attributes/id`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/global_attributes/id/index.md
* Last commit: https://github.com/mdn/content/commit/d3cdafcdb4d22e5c55771501e7c80451a96aa032
* Document last modified: 2023-03-12T06:37:36.000Z

</details>

**Comment by teoli2003** [comment] 2023-03-30 09:59
Duplicate of #25200 

(I need to revisit the PR that will fix it, hope to have the time to go back to it this week)

**Closed by teoli2003** 2023-03-30 09:59 UTC
Labels: Content:HTML, needs triage
