### ISSUE TITLE
Editable Code windows are nonfunctional

### ISSUE THREAD

**Issue by CrimsonCoder637** [mdn/content#34254] opened 2024-06-18 20:13 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/conditionals

### What specific section or headline is this issue about?

All of them

### What information was incorrect, unhelpful, or incomplete?

The Editable Code windows are not compiling, so there is no way to run your own code input, check the solution, or reset the windows. Selecting options in the dropdown (selector) examples also do not do anything. Issue is consistent across devices and Chrome/Edge.

### What did you expect to see?

The code should have compiled and clicking the Rest and Show Solution buttons should reveal new content.

### Do you have anything more you want to share?

https://go.screenpal.com/watch/cZ1FYlVNNGp

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/building_blocks/conditionals`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/conditionals
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/building_blocks/conditionals/index.md
* Last commit: https://github.com/mdn/content/commit/af1e384356e21dbcc573d1c1cc015ec79c644de1
* Document last modified: 2024-06-14T05:38:35.000Z

</details>

**Comment by wbamberg** [comment] 2024-06-19 05:25
Thanks for filing!

We can't reproduce this. Can you please let us know:
- which browser versions you see it with
- whether you get any errors in the browser console
- which extensions you have running, and whether you still see this problem without them

**Comment by Josh-Cena** [comment] 2024-06-29 21:42
Closing because none of us can reproduce

**Closed by Josh-Cena** 2024-06-29 21:42 UTC
Labels: needs info, Content:Learn:JavaScript
