### ISSUE TITLE
Web/API/Media_Capture_and_Streams_API/Taking_still_photos page runner doesn't work

### ISSUE THREAD

**Issue by jrmoreno1** [mdn/content#31159] opened 2023-12-19 17:07 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Media_Capture_and_Streams_API/Taking_still_photos

### What specific section or headline is this issue about?

DEMO

### What information was incorrect, unhelpful, or incomplete?

The "play" button takes you to https://developer.mozilla.org/en-US/play with the contents filled out, but the running it on that page doesn't work in either chrome or firefox.  In firefox running the code and clicking on the view live results gives an error message in the console "InvalidAccessError: A parameter or an operation is not supported by the underlying object"

### What did you expect to see?

A working demo of taking a picture from a laptops web cam

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/media_capture_and_streams_api/taking_still_photos`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Media_Capture_and_Streams_API/Taking_still_photos
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/media_capture_and_streams_api/taking_still_photos/index.md
* Last commit: https://github.com/mdn/content/commit/cbd8527cf4df0464c4724b73161e4f7721301616
* Document last modified: 2023-12-18T03:14:54.000Z

</details>

**Comment by skyclouds2001** [comment] 2023-12-19 18:08
possible reason: 

![image](https://github.com/mdn/content/assets/95597335/32080ff7-fd01-49f3-b27d-4a2a3b67ba89)

**Comment by hamishwillee** [comment] 2023-12-27 00:36
Closing. This is a duplicate of https://github.com/mdn/yari/issues/9646

**Closed by hamishwillee** 2023-12-27 00:36 UTC
Labels: Content:WebAPI, needs triage
