### ISSUE TITLE
Error with javascript example

### ISSUE THREAD

**Issue by Polyducks** [mdn/content#17037] opened 2022-06-06 17:41 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation
and
https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Compositing

### What specific section or headline is this issue about?

Operations

### What information was incorrect, unhelpful, or incomplete?

Bug in console showed ctx to be declared a const twice, causing "Operations" content not to show on both pages.

### What did you expect to see?

Demo content under "Operations" heading

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation
https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Compositing

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/canvasrenderingcontext2d/globalcompositeoperation`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/canvasrenderingcontext2d/globalcompositeoperation/index.md
* Last commit: https://github.com/mdn/content/commit/2fe4f1d446a52cbcb2d273833a5a2aca32d7a202
* Document last modified: 2022-06-05T05:31:19.000Z

</details>

**Comment by sideshowbarker** [comment] 2022-06-07 02:26
Thanks for raising this. The cause was a regression introduced in https://github.com/mdn/content/pull/16969 but subsequently fixed in https://github.com/mdn/content/pull/17019.

So this is fixed in the sources now — and I think it’s also now been deployed to the production site.

**Closed by sideshowbarker** 2022-06-07 02:26 UTC
Labels: Content:WebAPI
