### ISSUE TITLE
Misleading code description in the Custom Elements API documentation

### ISSUE THREAD

**Issue by kostasx** [mdn/content#28450] opened 2023-08-08 13:57 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_custom_elements

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_custom_elements#autonomous_custom_elements

### What information was incorrect, unhelpful, or incomplete?

In this section, the following description is misleading:

"**Inside the method connectedCallback**, we define all the functionality the element will have when the element is connected to the DOM. [...] **We don't use constructor()** because an element's attributes are unavailable until connected to the DOM."

- First of all, the code below the description should be contained within a method to make it clear that it will be part of that class method, for example:

```js
connectedCallback(){
  // Create a shadow root
  this.attachShadow({ mode: "open" }); // sets and returns 'this.shadowRoot'
 // rest of the code...
}
```
- Secondly, and most important, it is mentioned that the code below the description should be defined inside the `connectedCallback` method inside the `PopupInfo` class (_"We don't use constructor()..."_). A few lines below, we find a link to the full source code:

https://github.com/mdn/web-components-examples/blob/main/popup-info-box-web-component/main.js

Opening the link, we find the code being defined inside the `constructor` method of the `Popup` class instead. 

While following the guide, where one should define the sample code? Inside the `constructor` method (according to the source code) or inside the `connectedCallback` as mentioned in the description? 

### What did you expect to see?

I would expect to see the code and documentation description to be in-sync and reflect each other.

If the description mentions that the code should reside inside the `connectedCallback` method and not inside the `constructor`, I would expect the source code to reflect that setup. 

By going through this section and looking at the code, one is confused as to where the code must be placed.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/web_components/using_custom_elements`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_custom_elements
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/web_components/using_custom_elements/index.md
* Last commit: https://github.com/mdn/content/commit/270351317fdaa57ba9123a19aa281e9e40bb0baa
* Document last modified: 2023-06-20T19:01:21.000Z

</details>

**Comment by wbamberg** [comment] 2023-09-18 07:21
Duplicate of https://github.com/mdn/content/issues/22887.

**Closed by wbamberg** 2023-09-18 07:21 UTC
Labels: help wanted, Content:WebAPI
