### ISSUE TITLE
“Content categories” article: "sectioning root" link goes to "The HTML Section Heading elements" article

### ISSUE THREAD

**Issue by sonata-2t** [mdn/content#13920] opened 2022-03-15 20:37 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories

#### What information was incorrect, unhelpful, or incomplete?

Issue with "Content  categories":  the second note in the page "content categories" there a link to "sectioning root" , but is lead to "The HTML Section Heading elements" https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#sectioning_roots

#### Specific section or headline?

section

#### What did you expect to see?
another page

#### Did you test this? If so, how?

yes

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/guide/html/content_categories`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/guide/html/content_categories/index.md
* Last commit: https://github.com/mdn/content/commit/a590d73456035088e5f1cac116974488ebd867ef
* Document last modified: 2022-01-31T14:45:50.000Z

</details>

**Comment by AnilSeervi** [comment] 2022-03-19 11:04
`<footer>` page also has the same link - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/footer
There is no _sectioning root_ page or a Heading named _sectioning_root_ on the [Heading Elements(`<h1>-<h6>`)](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements) page.

`<body>` refers to sectioning root - https://developer.mozilla.org/en-US/docs/Web/HTML/Element#sectioning_root
Whereas the [`<body>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/body) page itself has a _sectioning root_ link in a table that again leads to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#sectioning_roots

**Comment by boundmaidlea** [comment] 2022-06-09 20:47
same for https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figure#usage_notes

> Being a [sectioning root](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#sectioning_roots), the outline...

**Comment by Josh-Cena** [comment] 2022-12-24 07:23
Duplicate of https://github.com/mdn/content/issues/19400

**Closed by Josh-Cena** 2022-12-24 07:23 UTC
Labels: Content:HTML, community
