### ISSUE TITLE
Test your skills missing finished example demo

### ISSUE THREAD

**Issue by Sasi30** [mdn/content#23154] opened 2022-12-23 14:31 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Test_your_skills:_Advanced_HTML_text

### What specific section or headline is this issue about?

In code part

### What information was incorrect, unhelpful, or incomplete?

dl ,dt are missing in code part

### What did you expect to see?

<dl> Llama
        <dt>
                tall,wooly quadruped,pointy ears.sometimes rideable,but grumpy and spits a lot.big fan of list items
        </dt>
    </dl>
    <dl>Anaconda
        <dt>a very large constrictor snake; travels rapidly by way of anchors to sneak up on his prey.</dt>
    </dl>

**Comment by wbamberg** [comment] 2022-12-23 17:35
If you are referring to https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Test_your_skills:_Advanced_HTML_text#task_1 - I think the point of this example is that the markup is missing, and the exercise is to add it:

> In this task, we want you to turn the provided animals and their definitions into a description list.
>
> Try updating the live code below to recreate the finished example:

**Comment by Josh-Cena** [comment] 2022-12-23 18:12
Part of the issue is that the text says "recreate the finished example", but there's no finished example. Same problem as https://github.com/mdn/content/issues/15834

**Comment by wbamberg** [comment] 2022-12-23 20:44
That's fair enough. I just opened a PR to the learning area repo to add a "finished" version, and when that's merged we can update this page to embed it.

@kylewcode is on the same road, it appears, in https://github.com/mdn/learning-area/pull/572, which is part of the fix for https://github.com/mdn/content/issues/21944.

**Closed** 2022-12-30 19:25 UTC
Labels: help wanted, Content:Learn:HTML
