### ISSUE TITLE
Missing and repeated content in the article JavaScript performance

### ISSUE THREAD

**Issue by Junaid-1993** [mdn/content#27791] opened 2023-07-06 13:11 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Performance/JavaScript

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Learn/Performance/JavaScript#battery_impact

### What information was incorrect, unhelpful, or incomplete?

A lot of information or content is missing **( not written )** in the [JavaScript performance](https://developer.mozilla.org/en-US/docs/Learn/Performance/JavaScript) article. Particularly the section [Battery Impact](https://developer.mozilla.org/en-US/docs/Learn/Performance/JavaScript#battery_impact) has no content at all it is just a heading with no paragraph. Also, the second bullet point in the section [Download Impact](https://developer.mozilla.org/en-US/docs/Learn/Performance/JavaScript#download_impact) also has no detail like the other bullet points.

The content is also repeated in multiple sections like the paragraph underneath the [Render Impact](https://developer.mozilla.org/en-US/docs/Learn/Performance/JavaScript#render_impact) is the same as the paragraph underneath the [Download Impact](https://developer.mozilla.org/en-US/docs/Learn/Performance/JavaScript#download_impact) which does not make sense.

### What did you expect to see?

Give the [Battery Impact](https://developer.mozilla.org/en-US/docs/Learn/Performance/JavaScript#battery_impact) section the proper content to explain how JavaScript can impact the battery. And also change the paragraph under the [Render Impact](https://developer.mozilla.org/en-US/docs/Learn/Performance/JavaScript#render_impact) so that it explains **render impact**, not the same content as in the [Download Impact](https://developer.mozilla.org/en-US/docs/Learn/Performance/JavaScript#download_impact) section.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/performance/javascript`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Performance/JavaScript
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/performance/javascript/index.md
* Last commit: https://github.com/mdn/content/commit/bb026bcb88b7f45374d602301b7b0db5a49ff303
* Document last modified: 2023-07-03T10:12:35.000Z

</details>

**Comment by Josh-Cena** [comment] 2023-07-06 13:16
Duplicate of https://github.com/mdn/content/issues/16022

**Closed by Josh-Cena** 2023-07-06 13:16 UTC
Labels: Content:Learn, needs triage
