### ISSUE TITLE
window.prompt javascript function not working on Firefox 132.0.1 (64-bit)

### ISSUE THREAD

**Issue by SergioGiacomoSammartano** [mdn/content#36781] opened 2024-11-13 20:50 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Strings

### What specific section or headline is this issue about?

Concatenation in context

### What information was incorrect, unhelpful, or incomplete?

In the tutorial, an example makes use of the window.prompt() function (at least, in theory) to collect string data (a name) from the user, but no pop-up window for the prompt is generated and therefore it is impossible to load the data into the const name variable, whose value is then displayed as "null". 

### What did you expect to see?

I expected to see a prompt window that would allow me to input a string, but no window is shown. The console shows no errors, no runtime exceptions during the execution of the function when pushing the "Press me" button. 
I suspected this was due to security restrictions implemented by the browser, like blocking notifications and not allowing pop-up windows, but I tried many times to allow these security settings for the developer.mozilla.org webpage, most times closing and reopening the browser, but I couldn't get the prompt to show up.

### Do you have anything more you want to share?

I have experienced this very same problem on two different laptops, one running Windows 11 and the other running Linux Mint 22 Wilma. On both machines I have tried a couple of times to erase the website's cookies and cache , but the problem was not solved. 
On the Windows laptop I browsed the page with Chrome as well, but I experienced the same problem. 
When trying to run a custom prompt command directly from the console (web developer tools), the prompt window shows up with the text I pass as an argument.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/first_steps/strings`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Strings
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/first_steps/strings/index.md
* Last commit: https://github.com/mdn/content/commit/23e1a97d50050a3b3518a4b2f67ccf42e5fd75b7
* Document last modified: 2024-06-28T03:14:04.000Z

</details>

**Comment by Josh-Cena** [comment] 2024-11-13 22:31
Duplicate of https://github.com/mdn/content/issues/36132

**Closed by Josh-Cena** 2024-11-13 22:31 UTC
Labels: needs triage, Content:Learn:JavaScript
