### ISSUE TITLE
Use of deprecated EmbedLiveSample parameters

### ISSUE THREAD

**Issue by cw118** [mdn/content#27801] opened 2023-07-06 21:41 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Forms/How_to_build_custom_form_controls

### What specific section or headline is this issue about?

Several (various EmbedLiveSample macros)

### What information was incorrect, unhelpful, or incomplete?

Based on the [EmbedLiveSample file in `yari`](https://developer.mozilla.org/en-US/docs/Learn/Forms/How_to_build_custom_form_controls), parameters $4-$6 are now deprecated, but it seems that this page still uses the `$4` parameter several times. (cf. [line 295](https://github.com/mdn/content/blob/main/files/en-us/learn/forms/how_to_build_custom_form_controls/index.md?plain=1#L295), [line 403](https://github.com/mdn/content/blob/main/files/en-us/learn/forms/how_to_build_custom_form_controls/index.md?plain=1#L403), etc.)

As a result, the [PR test workflow fails on this page](https://github.com/mdn/translated-content/actions/runs/5474194650/jobs/9968664926#step:7:60), at least in translated-content.

### What did you expect to see?

The `$4` url parameter of `{{EmbedLiveSample}}`s should be removed. I believe the live sample code in the files `Learn/Forms/How_to_build_custom_form_controls/Example_1`, `Learn/Forms/How_to_build_custom_form_controls/Example_2` and so on should be included in the `Learn/Forms/How_to_build_custom_form_controls` file instead?

If the live sample code is too long, then it could be hidden, and if we keep the `Learn/Forms/How_to_build_custom_form_controls/Example_1` etc. pages then we can also keep the links pointing to those pages, where readers can see the full code. 

I would be happy to open a PR if the above is correct. 

### Do you have any supporting links, references, or citations?

- [`EmbedLiveSample.ejs` on yari](https://github.com/mdn/yari/blob/main/kumascript/macros/EmbedLiveSample.ejs#L9)
- [Failed workflow due to EmbedLiveSample in the page "How to build custom form controls" on translated-content](https://github.com/mdn/translated-content/actions/runs/5474194650/jobs/9968664926#step:7:60)

**Comment by Josh-Cena** [comment] 2023-07-07 03:19
Duplicate of https://github.com/mdn/content/issues/25005

**Closed by Josh-Cena** 2023-07-07 03:20 UTC
Labels: needs triage
