### ISSUE TITLE
Misleading "try it" example for RegExp unicode flag

### ISSUE THREAD

**Issue by pewscorner** [mdn/content#36523] opened 2024-10-27 22:56 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/unicode

### What specific section or headline is this issue about?

The "try it" example.

### What information was incorrect, unhelpful, or incomplete?

The example uses `new RegExp('\u{61}', 'u')` with and without the `'u'` flag to demonstrate the difference. But `'\u{61}'` immediately gets converted to `'a'` (and becomes the value of the RegExp `source` property) as part of normal string literal interpretation **before** the string is passed to RegExp, so the `'u'` flag has no effect.

### What did you expect to see?

To introduce an effect, the example would need to be rewritten to use one of the following syntaxes:
1. `new RegExp('\\u{61}', 'u')` (note: 2 backslashes instead of 1)
2. `/\u{61}/u`

Furthermore, to make the effect of the flag clear, it is not enough to show the value of the `source` property. The result of a match needs to be shown, e.g.:
```
console.log(regex1.exec('a'));
// Expected output: null
console.log(regex1.exec('u'.repeat(61)));
// Expected output: Array ["uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu"]

console.log(regex2.exec('a'));
// Expected output: Array ["a"]
console.log(regex2.exec('u'.repeat(61)));
// Expected output: null
```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/regexp/unicode`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/unicode
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/regexp/unicode/index.md
* Last commit: https://github.com/mdn/content/commit/c2445ce1dc3a0170e2fbfdbee10e18a7455c2282
* Document last modified: 2023-09-12T02:17:31.000Z

</details>

**Comment by Josh-Cena** [comment] 2024-10-27 23:01
Duplicate of https://github.com/mdn/interactive-examples/issues/2490

**Closed by Josh-Cena** 2024-10-27 23:01 UTC
Labels: Content:JS, needs triage
