### ISSUE TITLE
Wrong description of value that `FileSystemDirectoryHandle.entries()` method returns

### ISSUE THREAD

**Issue by BSPR0002** [mdn/content#29003] opened 2023-09-08 21:12 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/FileSystemDirectoryHandle/entries

### What specific section or headline is this issue about?

intro, ### Return value

### What information was incorrect, unhelpful, or incomplete?

> The entries() method of the [FileSystemDirectoryHandle](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemDirectoryHandle) interface returns an array of a given object's own enumerable property [key, value] pairs, in the same order as that provided by a [for...in](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in) loop (the difference being that a for-in loop enumerates properties in the prototype chain as well).

> An array of the given FileSystemDirectoryHandle object's own enumerable property [key, value] pairs.

`FileSystemDirectoryHandle.entries()` returns a `FileSystemDirectoryIterator`. It's an iterator, not an array.

### What did you expect to see?

An asynchronous iterator that provides a given object's own enumerable property `[key, value]` pair

Or something else.

### Do you have any supporting links, references, or citations?

[File System Living Standard — Last Updated 24 July 2023 § 2.4.1. Directory iteration](https://fs.spec.whatwg.org/#api-filesystemdirectoryhandle-asynciterable)

![image](https://github.com/mdn/content/assets/42113148/0250f377-29f8-4d6e-954a-084d935c89ff)

**Comment by Josh-Cena** [comment] 2023-09-08 22:39
Basically duplicate of https://github.com/mdn/content/issues/25876

**Closed by Josh-Cena** 2023-09-08 22:39 UTC
Labels: Content:WebAPI, needs triage
