### ISSUE TITLE
Improve the explanation in `Intl.NumberFormat()` about `maximumSignificantDigits` property

### ISSUE THREAD

**Issue by Rafael-Martins** [mdn/content#34710] opened 2023-09-14 17:10 UTC
### Proposal

I think that we can add some clarification on how `maximumSignificantDigits` works, and also the relation with `roundingPriority`.

### Task list

- [ ] Reformulate docs for `maximumSignificantDigits`
- [ ] Reformulate docs for `roundingPriority`
- [ ] Reformulate docs for `maximumFractionDigits`

### Additional information

I will add more insight's about it soon as I can.

### Are you willing to support this work?

Yes

**Comment by Rumyra** [comment] 2024-07-08 10:04
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat

**Comment by Josh-Cena** [comment] 2024-07-08 14:15
@Rafael-Martins It is unclear what you want to see happening. Could you describe more about your intended change?

**Comment by Josh-Cena** [comment] 2024-08-10 05:04
From the linked issues, I think I have a better idea where the confusion comes from. The problem is that `new Intl.NumberFormat('en-US').format(3e-18)` returns `'0'`, but `new Intl.NumberFormat('en-US', { maximumSignificantDigits: 21 }).format(3e-18)` returns `0.000000000000000003`, even when we claim that `maximumSignificantDigits: 21` is the default value.

The problem is that "FractionDigits" and "SignificantDigits" are not unconditionally applied with the default values. You can observe this with `resolvedOptions`:

```js
new Intl.NumberFormat('en-US').resolvedOptions();
// {
//     "locale": "en-US",
//     "numberingSystem": "latn",
//     "style": "decimal",
//     "minimumIntegerDigits": 1,
//     "minimumFractionDigits": 0,
//     "maximumFractionDigits": 3,
//     "useGrouping": "auto",
//     "notation": "standard",
//     "signDisplay": "auto",
//     "roundingIncrement": 1,
//     "roundingMode": "halfExpand",
//     "roundingPriority": "auto",
//     "trailingZeroDisplay": "auto"
// }

new Intl.NumberFormat('en-US', { maximumSignificantDigits: 21 }).resolvedOptions();
// {
//     "locale": "en-US",
//     "numberingSystem": "latn",
//     "style": "decimal",
//     "minimumIntegerDigits": 1,
//     "minimumSignificantDigits": 1,
//     "maximumSignificantDigits": 21,
//     "useGrouping": "auto",
//     "notation": "standard",
//     "signDisplay": "auto",
//     "roundingIncrement": 1,
//     "roundingMode": "halfExpand",
//     "roundingPriority": "auto",
//     "trailingZeroDisplay": "auto"
// }
```

The "defaults" mentioned are only applied if at least one option from the group (`*SignificantDigits`/`*FractionDigits`) is specified. This means that the resolved options will always contain both or neither of `maximumSignificantDigits` and `minimumSignificantDigits` (ditto for `*FractionDigits`). However, we never mentioned what happens if none of the max/min options are specified.

We should be very explicit about when and how the SD/FD options are set in the resolved options:

1. If `roundingPriority` is not `auto`, then all four SD/FD options are set.
1. If `roundingPriority` is `auto`, and an SD option is explicitly set, then the two SD options are set. (And FD options are always ignored)
1. If `roundingPriority` is `auto`, and no SD option is explicitly set, then the two FD options are set. However, when `notation` is `compact`, none of the four SD/FD options may be set if they are all unspecified.

We need to fix both the constructor page and the `resolvedOptions` page to clarify these interactions.

**Comment by Rafael-Martins** [comment] 2024-08-27 01:26
Oh, that is exactly the problem, I can work on the clarifications in a near future, if you want!

**Comment by Josh-Cena** [comment] 2024-08-27 01:27
I will be working on this, as I already had plans for improving these Intl docs. Thanks for confirming though!

**Comment by Josh-Cena** [comment] 2024-09-27 20:45
This happens to be fixed by https://github.com/mdn/content/pull/36056!

**Closed by Josh-Cena** 2024-09-27 20:45 UTC
Labels: Content:JS, effort: medium, goal: clarity
