### ISSUE TITLE
Issue with "ARIA: button role": The example JavaScript has a logical error

### ISSUE THREAD

**Issue by Fettabachi** [mdn/content#12550] opened 2022-01-31 20:26 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role

#### What information was incorrect, unhelpful, or incomplete?
```
// Keypresses other then Enter and Space should not trigger a command
    if (event instanceof KeyboardEvent && event.key !== 'Enter' && event.key !== ' ') {
        return;
    }
```

#### What did you expect to see?
```
if (event instanceof KeyboardEvent && event.key !== 'Enter' || event.key !== ' ') {
        return;
    }
```

#### Did you test this? If so, how?
Yes, I tested the code. By using the provided code example `event.key !== 'Enter' && event.key !== ' '` I could execute my code by pressing any key. By changing the conditional to `||` the example will work as intended.

Change this "// Keypresses other then Enter and Space should not trigger a command" to read "// Keypresses other than Enter or Space should not trigger a command"

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/accessibility/aria/roles/button_role`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/accessibility/aria/roles/button_role/index.md
* Last commit: https://github.com/mdn/content/commit/54fd6eaad3924076e0b546e7eff1f6f466f6139f
* Document last modified: 2022-01-24T00:41:11.000Z

</details>

**Comment by sideshowbarker** [comment] 2022-02-01 01:43
> By using the provided code example `event.key !== 'Enter' && event.key !== ' '` I could execute my code by pressing any key.

I can’t reproduce that. When I enter some text in the **Enter you Name** input field and then I move focus to the <kbd>Add Name</kbd> button, the only ways I can trigger the submit are either by a mouse click on the <kbd>Add Name</kbd> button or by a pressing the Enter or Space keys — as expected. If I press any key other than Enter or Space, no submit is triggered.

**Comment by Fettabachi** [comment] 2022-02-01 13:00
Interesting. To me, the code reads that both the Enter key and the Space key must be pressed to avoid the return and my code works exactly like that. By using `&&`, any key will run my script but if I use `||` it only runs if the Space or Enter key is pressed. But, as you say, the provided code works but I don't understand why.

**Comment by sideshowbarker** [comment] 2022-02-01 16:38
> To me, the code reads that both the Enter key and the Space key must be pressed to avoid the return

What it says is, “if the key is not Enter and the key is not Space, then return”.

The code were instead `event.key === 'Enter' && event.key === ' '`, then that would be impossible, because `event.key` can never be both Enter and Space. It can only be one key.

But it’s possible for `event.key` to be both ”not Enter“ AND “not Space” — and that’s exactly what the existing code expresses.

So I’m going ahead and closing this issue, because the existing code is intentional and working as expected.

**Closed by sideshowbarker** 2022-02-01 16:38 UTC
Labels: Content:Accessibility, needs info
