### ISSUE TITLE
Next article button needed for all first topics in Learn

### ISSUE THREAD

**Issue by zoltanbiber** [mdn/content#28263] opened 2023-07-29 20:10 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML

### What specific section or headline is this issue about?

Whole page

### What information was incorrect, unhelpful, or incomplete?

Why isn't there a button/link to the next article in this section? All subsequent articles have the back/next buttons.

### What did you expect to see?

Why isn't there a button/link to the next article in this section? All subsequent articles have the back/next buttons.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/html/introduction_to_html`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/introduction_to_html/index.md
* Last commit: https://github.com/mdn/content/commit/751d58669499de0c6ea0d5b356e0e1448418c5d3
* Document last modified: 2023-06-30T06:21:35.000Z

</details>

**Comment by hamishwillee** [comment] 2023-07-30 22:55
Thanks. This is consistent - see the the other first topics in each section https://developer.mozilla.org/en-US/docs/Learn/HTML/Tables and https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding and so on - they are all the same.

I suspect that at some point the sidebar linked the first topic in the toggle, so the sub topics were nested: hence "next" made no sense.

Its a reasonable fix for someone to do across all the docs

**Comment by wbamberg** [comment] 2023-07-31 17:49
The sidebar never linked the first topic in the toggle - our sidebars never do that, because it's thought that it would be confusing to have two actions on different bits of the element (one to toggle the list, one to navigate to the linked page).

This means that almost everywhere, when there's a toggleable list of items in the sidebar, the "overview" item is listed twice, once, unlinked, in the `<summary>`, and then again, linked, as the first child:

```
Some topic
    Some topic overview
    The first article about it
    The second article about it
```

So the reason it doesn't get "Next" is because it's the module overview page, and only the child items - the actual module chapters - get next/previous/overview nav links. Logically, the overview page isn't part of the sequence of module chapters.

So this is working as intended. It's unfortunate IMO that the overview page appears in the list of children, but it's where we are.

**Comment by hamishwillee** [comment] 2023-07-31 21:55
@wbamberg Just because it is working as intended doesn't mean it isn't wrong. From a navigation point of view I'd happily argue that the Next makes sense given the rendering. But it isn't a problem enough for it ever to get to the top of my todo list. 

If you're saying you think things are better this way, perhaps we close as "not going to fix". Otherwise we should have an explicit statement that we do want it fixed.

**Comment by wbamberg** [comment] 2023-07-31 22:12
> Just because it is working as intended doesn't mean it isn't wrong.

That's true. But I think it isn't wrong, as I said above:

> Logically, the overview page isn't part of the sequence of module chapters.

So yes, I would vote to close this as not going to fix, and I'm not going to work on fixing it myself. And doing this will tend to break any effort to derive Next/Previous/Overview from page weight or sidebar structures. But who knows if we will ever get around to that I suppose.

**Comment by hamishwillee** [comment] 2023-07-31 22:24
Hmmmm. I think it is wrong. If you depict the topics as a linear sequence the sub topics aren't sub-topics. But I'm very much a fan of deriving the next/previous dynamically, so executive decision "Not going to fix". Thanks @wbamberg @zoltanbiber .

**Closed by hamishwillee** 2023-07-31 22:24 UTC
Labels: Content:Learn:HTML
