### ISSUE TITLE
The videos used in the Add-ons documentation are unavailable

### ISSUE THREAD

**Issue by silvioprog** [mdn/content#8132] opened 2021-08-20 03:35 UTC
Hi.

The videos used at the documentation page "[docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension)" are unavailable:

![Screenshot from 2021-08-20 00-32-50](https://user-images.githubusercontent.com/1456829/130174997-40ededcd-b3a5-4bbe-a247-c8035aea03d5.png)

cheers

**Comment by Rob--W** [comment] 2021-08-20 16:53
Duplicate of #7457

**Closed by Rob--W** 2021-08-20 16:53 UTC
Labels: duplicate
