### ISSUE TITLE
Issue with "POST": (short summary here please)

### ISSUE THREAD

**Issue by TRShark6002** [mdn/content#5098] opened 2021-05-18 17:59 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST

#### What information was incorrect, unhelpful, or incomplete?
12

#### Specific section or headline?

12
#### What did you expect to see?

yes
#### Did you test this? If so, how?
no

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/methods/post`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/methods/post/index.html
* Last commit: https://github.com/mdn/content/commit/8d4fd702d9668604cb2788da5bd9fc9b796ec30a
* Document last modified: 2021-03-17T20:27:56.000Z

</details>

**Comment by chrisdavidmills** [comment] 2021-05-19 07:20
This issue submission does not make it clear what the problem is, or what the fix should potentially be. It looks like spam, so I'm closing it.

**Closed by chrisdavidmills** 2021-05-19 07:20 UTC
