### ISSUE TITLE
Issue with "Style Editor": YouTube video not showing (set to private)

### ISSUE THREAD

**Issue by anghelos** [mdn/content#13675] opened 2022-03-09 01:23 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Style_Editor

#### What information was incorrect, unhelpful, or incomplete?
One of the YouTube videos of the “[The media sidebar](https://developer.mozilla.org/en-US/docs/Tools/Style_Editor#the_media_sidebar)” section is inaccessible, as it's set to private.

#### Specific section or headline?
[The media sidebar](https://developer.mozilla.org/en-US/docs/Tools/Style_Editor#the_media_sidebar)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/style_editor`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Style_Editor
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/style_editor/index.html
* Last commit: https://github.com/mdn/content/commit/0160aac0e623dacdce4019205f32f7b3d3e58019
* Document last modified: 2022-02-18T09:33:58.000Z

</details>

**Comment by wbamberg** [comment] 2022-03-09 01:55
Thanks for filing! This is a duplicate of https://github.com/mdn/content/issues/7457, I think?

**Closed by wbamberg** 2022-03-09 01:55 UTC
Labels: needs-triage
