### ISSUE TITLE
Broken link on page "HTMLImageElement: sizes property"

### ISSUE THREAD

**Issue by nikwen** [mdn/content#29249] opened 2023-09-22 17:24 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/sizes

### What specific section or headline is this issue about?

Example -> Result

### What information was incorrect, unhelpful, or incomplete?

The link "[viewed in its own window](https://live.mdnplay.dev/en-US/docs/Web/API/HTMLImageElement/sizes/runner.html?id=Selecting+an+image+to+fit+window+width)" no longer works. I get a blank page. (Tested on Firefox.)

### What did you expect to see?

I expected the link to work.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/htmlimageelement/sizes`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/sizes
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlimageelement/sizes/index.md
* Last commit: https://github.com/mdn/content/commit/acfe8c9f1f4145f77653a2bc64a9744b001358dc
* Document last modified: 2023-07-07T07:19:19.000Z

</details>

**Comment by wbamberg** [comment] 2023-09-23 22:50
@fiji-flo , I think this is a regression caused by the playground feature: [LiveSampleLink](https://github.com/mdn/yari/blob/main/kumascript/macros/LiveSampleLink.ejs) doesn't work any more, and pages that rely on it are broken. It has come up a few times before.

Usually pages want to use it when an iframed example doesn't work well to demonstrate the effect, as in this case.

Do you think this will be fixed? The workaround would be to replace these examples with `EmbedGHLiveSample`, which gives us standalone pages to link. But this isn't as good, because we end up duplicated the source code between the page and the GitHub repo, and they inevitably get out of sync.

**Comment by wbamberg** [comment] 2023-09-25 02:51
I think https://github.com/mdn/content/issues/29109 might be another such regression?

**Comment by fiji-flo** [comment] 2023-09-25 12:24
@wbamberg thank you for flagging me. I'll fix that in the next few days. I identified the two underlying issues.

**Closed** 2023-09-29 11:33 UTC
Labels: to move
