### ISSUE TITLE
Content bug: There is a bug in MDN CSS File from recent changes. Paragraphs are collapsing. No bottom spacing.

### ISSUE THREAD

**Issue by Junaid-1993** [mdn/content#10443] opened 2021-11-11 07:55 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Learn

#### What information was incorrect, unhelpful, or incomplete?
Hi, I read MDN docs regularly. For the past two days, I noticed that the paragraphs and headings in the docs have zero margins and therefore collapsing. If there are two paragraphs they are collapsing together because of no margin between them making them very hard to read.

#### Specific section or headline?
I think I check a lot of pages of MDN docs and found the same issue.

#### What did you expect to see?
Proper line breaks and spacing between each paragraph and headings. For better readability just like it was before 3 days ago.

#### Did you test this? If so, how?
Yes, and I found that there are some CSS reset rules are being applied to all the paragraphs and heading to "margin: 0" on all pages of MDN docs. I am also attaching the image for better understanding.

Thank you.

![mdn docs css](https://user-images.githubusercontent.com/75199051/141259639-20e71b96-39b2-4c6b-97de-0306dfabcb63.jpg)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/index.md
* Last commit: https://github.com/mdn/content/commit/07453ac2b659a397b0fee921fa71db5488e9ca62
* Document last modified: 2021-10-08T14:43:33.000Z

</details>

**Comment by Elchi3** [comment] 2021-11-11 08:28
Duplicate of https://github.com/mdn/yari/issues/4929

**Closed by Elchi3** 2021-11-11 08:28 UTC
