### ISSUE TITLE
Issue with "Math.sqrt()": Math is not showing correctly

### ISSUE THREAD

**Issue by BehdadEs** [mdn/content#4701] opened 2021-05-04 12:31 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/sqrt

#### What information was incorrect, unhelpful, or incomplete?
Second line where math is located is not showing math symbols correctly

#### What did you expect to see?
Correct math symbols!

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/math/sqrt`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/sqrt
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/math/sqrt/index.html
* Last commit: https://github.com/mdn/content/commit/b741df1720fa7408fd8072ae29575b758dde42e6
* Document last modified: 2021-04-28T16:04:31.000Z

</details>

**Comment by teoli2003** [comment] 2021-05-26 17:30
FYI, there is a discussion about the future of mathml tags inside mdn content in issue #3435 . Once this is decided, we will be able to fix this.

**Comment by sideshowbarker** [comment] 2021-06-04 18:56
Duplicate of #3435.

**Closed by sideshowbarker** 2021-06-04 18:56 UTC
