### ISSUE TITLE
Blink/Chrome does NOT support the defer attribute

### ISSUE THREAD

**Issue by jabcreations** [mdn/content#32708] opened 2024-03-16 07:19 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script

### What specific section or headline is this issue about?

Browser Support, defer row / Blink/Chrome intersection

### What information was incorrect, unhelpful, or incomplete?

Blink browsers incorrectly return false for the following (tested and verified in Chrome 34 and 121):

```
<html>
<head>
<script defer>
var r = document.getElementById('example');
console.log('r',r);
</script>
</head>

<body>

<div id="example"></div>

</body>
</html>
```

### What did you expect to see?

The developer console should return the referenced element; it does not.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/script`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/script/index.md
* Last commit: https://github.com/mdn/content/commit/fdd3ac5598c3ddceb71e59949b003936ae99f647
* Document last modified: 2024-02-22T19:57:33.000Z

</details>

**Comment by wbamberg** [comment] 2024-03-18 00:35
The [page for `<script>` says:](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#defer):

> Warning: This attribute must not be used if the src attribute is absent (i.e. for inline scripts), in this case it would have no effect.

Have you tested with a non-inline script?

**Comment by jabcreations** [comment] 2024-03-18 02:21
The link to my platform is on my profile though the short answer is all the script elements I use are external files for caching purposes. I've covered both scenarios. Additionally the "must" bit is clearly from someone with strong opinions and low comprehension. This applies in both scenarios.

**Comment by wbamberg** [comment] 2024-03-18 02:51
I just tested this in Chrome 122, with code like this:

HTML:
```html
<html>
  <head>
    <script src="page.js" defer></script>
  </head>

  <body>
    <div id="example"></div>
  </body>
</html>
```

JS:
```js
var r = document.getElementById("example");
console.log("r", r);
```

...and I see the expected output:

```
r <div id="example"></div>
```

> Additionally the "must" bit is clearly from someone with strong opinions and low comprehension.

If you are going to insult people, it's better that you don't participate in this repo.

**Comment by jabcreations** [comment] 2024-03-18 03:49
Fair enough example; that is where I actually started.

The live server primary script is here:
[https://www.jabcreations.com/scripts/index.js](https://www.jabcreations.com/scripts/index.js)

The `scroll_primary` global variable was previously assigned to `id_('body')` which is now referenced simply as `'body'` string and then loaded in to `id_()` later on in scripting. I wasn't having any issues with this since none of the global variables (all defined at the top) never directly referenced the DOM, just strings.

I think the difference here is that my platform's code is obviously going to be heavier than quick test files we throw together plus throw in a remote server versus local test files. I imagine that is what changes the timing of how the DOM versus the scripting loads. Regardless of the context if Blink browsers such as Chrome actually supported the `defer` attribute then the script would have waited until the DOM finished loading on my live server.

So I suppose the next step is attempting a different test case as close to the original circumstances to reproduce the scenario. I can throw together a quick test on my live server though it won't be a permanent test case in a live environment.

So on that script near the top (just below the global variables) I have defined a `z_test` variable and then have it `console.log(z_test);`. In Vivaldi it just returns `false` though Chrome 122 returns `false` and then for some reason returns a second time with the correct reference. I'm pretty sure you can figure out the correct URL, I'm not interested in doing self-promotion with links.

Lastly being critical of someone's mistake is required for progress. If you refuse to acknowledge that someone or something is wrong then you'll never make progress that requires correction. To conflate correcting others with insults without reason is to puppet, to do so with intention is to puppeteer.

**Comment by bsmth** [comment] 2024-03-18 08:34
@jabcreations: Everyone collaborating in Mozilla spaces, including online spaces such as GitHub repositories, must adhere to [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) (CPG). Being rude, dismissive, or disrespectful will not be tolerated. Please read the CPG and familiarize yourself with the [Open source etiquette](https://developer.mozilla.org/en-US/docs/MDN/Community/Open_source_etiquette) guide. Thank you.

**Comment by jabcreations** [comment] 2024-03-18 08:44
![offended](https://github.com/mdn/content/assets/5625045/0ad1ff5a-05b4-43c1-8ed2-4f6d3af1f255)

**Comment by skyclouds2001** [comment] 2024-03-18 09:24
see https://html.spec.whatwg.org/multipage/scripting.html#attr-script-defer

`defer` attribute does not take effect with classic script if no `src` attribute specified, and with module script

**Comment by jabcreations** [comment] 2024-03-18 09:41
@skyclouds2001 Right, I've already setup a live server test case to demonstrate that Blink based browsers do not support the defer attribute with script elements that do have the `src` attribute. Simply go to the front page of the website with the console open or reload if you had to open the console afterwards.

**Comment by wbamberg** [comment] 2024-03-19 19:45
We've discussed this issue among the MDN maintainers, and I'm going to close it.

1. It's absolutely not true that Chrome does not support defer. In this thread I posted an example that shows defer working in Chrome. Chrome has supported defer for a very long time and it's now a very widely used part of the Web. If Chrome did not support defer, we'd know about it.

2. I _can_ reproduce this problem with your site. It does look like Chrome is not respecting defer for your site. I don't understand why, although I have looked at your code. I have also got a very slightly adapted version of your code running locally, and I _can't_ reproduce the problem locally. This makes it impossible for me to understand why defer isn't working in Chrome for you, although I would very much like to know why. If you want us to look at this more I think you need to make a locally reproducible version of the issue. You might also consider filing this as a Chrome bug.

> If you refuse to acknowledge that someone or something is wrong then you'll never make progress that requires correction.

I don't refuse to acknowledge that I or the MDN docs might be wrong. There are hundreds, probably thousands, of errors in MDN. I spend most of my days trying to fix them. The difference is between saying something is wrong and, effectively, personalizing it by calling someone stupid: "someone with strong opinions and low comprehension". That's insulting, and that's what's unacceptable.

**Closed by wbamberg** 2024-03-19 19:45 UTC
Labels: Content:HTML, needs triage

**Comment by jabcreations** [comment] 2024-03-19 20:19
If it's not working it's not supported. If it works in some scenarios though not others it's bugged and therefore still, not supported.

>>The difference is between saying something is wrong and, effectively, personalizing it by calling someone stupid: "someone with strong opinions and low comprehension". That's insulting, and that's what's unacceptable.

No, changing the words that someone used and then using those words to attack someone is not acceptable.

**Comment by bsmth** [comment] 2024-03-19 21:02
I've locked this due to heated conversation. Please stay polite and respectful when collaborating in this project, especially when disagreements arise. Thank you.
