### ISSUE TITLE
Ignored call to 'print()'. The document is sandboxed, and the 'allow-modals' keyword is not set.

### ISSUE THREAD

**Issue by zeruniverse** [mdn/content#36382] opened 2024-10-16 18:07 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/@page

### What information was incorrect, unhelpful, or incomplete?

The demo right after 

Result
Clicking the print button will launch a print dialog with the html sections split into individual pages.

click "print webpage", it errored in console with:
Ignored call to 'print()'. The document is sandboxed, and the 'allow-modals' keyword is not set.

### What did you expect to see?

Click "print webpage", prompt the print window

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/@page`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/@page
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/@page/index.md
* Last commit: https://github.com/mdn/content/commit/ed9ebd794add41de1f2e759502b73e8650afe56b
* Document last modified: 2024-10-02T13:58:44.000Z

</details>

**Comment by Josh-Cena** [comment] 2024-10-16 20:27
Duplicate of https://github.com/mdn/content/issues/36132

**Closed by Josh-Cena** 2024-10-16 20:27 UTC
Labels: Content:CSS, needs triage
