### ISSUE TITLE
`Response.json` static method not listed in the docs

### ISSUE THREAD

**Issue by satyarohith** [mdn/content#25100] opened 2023-03-06 06:52 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Response/json

### What specific section or headline is this issue about?

Static methods

### What information was incorrect, unhelpful, or incomplete?

[Response.json()](https://fetch.spec.whatwg.org/#dom-response-json) static method is not documented. 

### What did you expect to see?

Document Response.json static method under the `Static methods` section and provide examples.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/response/json`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Response/json
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/response/json/index.md
* Last commit: https://github.com/mdn/content/commit/3b22c657f659c249cbe6e4fc6794370a5cb67a72
* Document last modified: 2023-03-01T11:11:40.000Z

</details>

**Comment by Josh-Cena** [comment] 2023-03-06 07:17
Duplicate of https://github.com/mdn/content/issues/21550

**Closed by Josh-Cena** 2023-03-06 07:17 UTC
Labels: needs triage
