### ISSUE TITLE
Issue with "HTMLElement.innerText": wrong innerText output in Result

### ISSUE THREAD

**Issue by maxdevjs** [mdn/content#9326] opened 2021-09-28 19:57 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/innerText

```
Firefox 89.0.2 (64-bit)
x86_64 GNU/Linux
```

#### What information was incorrect, unhelpful, or incomplete?

This is a bit weird. None was incorrect, at times. Other times, however, the output of [Result](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/innerText#result) rendered as:

![Screenshot_20210928_161643](https://user-images.githubusercontent.com/22229196/135155403-9a0ec023-2dbf-4eb7-be6e-3a2d1577df11.png)

I am unable to reproduce it consistently (and I did not test if it'd happen also in different pages).

#### What did you expect to see?

This

![Screenshot_20210928_161514](https://user-images.githubusercontent.com/22229196/135155755-0a83d655-485b-440e-b0af-124ce4af0f0d.png)

instead of

![Screenshot_20210928_161643](https://user-images.githubusercontent.com/22229196/135155403-9a0ec023-2dbf-4eb7-be6e-3a2d1577df11.png)

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/htmlelement/innertext`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/innerText
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlelement/innertext/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by wbamberg** [comment] 2022-01-12 04:47
That is weird. Have you been able to reproduce it since? Any particular browser you see it with?

**Comment by maxdevjs** [comment] 2022-01-29 02:58
No, I tried again a few times with `96.0.1 (64-bit)` (+ latest Chrome) and never happened again. 

Back when it happened, I was on

```
Firefox 89.0.2 (64-bit)
x86_64 GNU/Linux
```

**Comment by sideshowbarker** [comment] 2022-01-29 03:14
I’m going ahead and closing this, since it’s no longer reproducible. If it ends up happening again, this issue could be revisited.

**Closed by sideshowbarker** 2022-01-29 03:14 UTC
Labels: infra
