### ISSUE TITLE
Genre detail page: _id undefined

### ISSUE THREAD

**Issue by stalmen** [mdn/content#20409] opened 2022-09-08 00:01 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/Genre_detail_page

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/Genre_detail_page

### What information was incorrect, unhelpful, or incomplete?

At the end of the Genre_detail_page section, there is an info box (shaded in blue) that describes what to do if the ""_id" for model "Genre"" path returns a value of the wrong type. However, my project is not returning any value at all for _id. I'm getting an error that says the value is undefined, even though the _id values do appear in my local_library collection when I view it on MongoDB.

### What did you expect to see?

I expected the project code to successfully access the genre _id from mongoDB.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/displaying_data/genre_detail_page`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/Genre_detail_page
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/displaying_data/genre_detail_page/index.md
* Last commit: https://github.com/mdn/content/commit/fead53324d271aa05e93b369966a773bb328c64b
* Document last modified: 2022-08-09T16:39:29.000Z

</details>

**Comment by hamishwillee** [comment] 2023-05-19 05:33
Sorry I missed this when you posted. I'm going to close this, because many people have gone through this tutorial with no issue. Therefore this is likely to be an issue with you following the instructions. 

If you, or anyone, is stuck on a similar problem, the best way to debug is to first try reproduce with the "worked example" in your environment: https://github.com/mdn/express-locallibrary-tutorial

**Closed by hamishwillee** 2023-05-19 05:33 UTC
Labels: help wanted, Content:Learn:Express
