### ISSUE TITLE
Date Calculation is Missing

### ISSUE THREAD

**Issue by denik1981** [mdn/content#3061] opened 2021-03-12 11:34 UTC
https://github.com/mdn/learning-area/blob/59bfd052a8d3d8a06d0af552e3f79e03603bf03d/javascript/asynchronous/introducing/simple-sync-worker.html#L14

From  [javascript_is_single-threaded](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Concepts#javascript_is_single-threaded)

> This is a rewrite of our previous example that calculates the 10 million dates in a separate worker thread. Now when you click the button, the browser is able to display the paragraph before the dates have finished calculating

The code provided don't do anything with the new instance of the Worker.

**Comment by chrisdavidmills** [comment] 2021-03-12 11:44
Ah, wait. I'm going to close this as a dupe of https://github.com/mdn/content/issues/3060. We can deal with both repos at the same time.

**Closed by chrisdavidmills** 2021-03-12 11:44 UTC
Labels: Content:JS, Content:Learn, needs-triage
