### ISSUE TITLE
Issue with "Basic math in JavaScript — numbers and operators": expected to see in the Mozilla Developers Tools Console the result of typeof myInt but got an error while using MZF console

### ISSUE THREAD

**Issue by leandrojl** [mdn/content#4724] opened 2021-05-05 11:17 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Math

#### What information was incorrect, unhelpful, or incomplete?
Declaration of variable `let myInt, let myFloat"` in the Mozilla Firefox Developer Tools console.

#### Specific section or headline?
"It's all numbers to me"

#### What did you expect to see?
I expected to see in the Mozilla Developers Tools Console the result of `typeof myInt` but got an error while using MZF console.

#### Did you test this? If so, how?
Yes. I did get this [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Redeclared_parameter](url) during the declaration of variables to later know the `typeof letMyInt`. I solved it deleting the `let` declaration and just running in the Mozila Developer tools console: 
`myInt = 5;
myFloat= 6.667;
myInt;
myFloat;
typeof myInt;
typeof myFloat;`

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/first_steps/math`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Math
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/first_steps/math/index.html
* Last commit: https://github.com/mdn/content/commit/c7d9128559ed9526914c9be5bb461445fde5866a
* Document last modified: 2021-02-19T20:09:33.000Z

</details>

**Comment by dorward** [comment] 2021-06-03 11:53
Just running the code won't produce that problem, but it will happen if you run the code multiple times on a single page. This seems to be quite a common gotcha when dealing with the Console so maybe it would be better to not recommend it and point to a sandbox website like jsbin.com instead?

**Comment by sideshowbarker** [comment] 2021-06-04 08:26
> maybe it would be better to not recommend it and point to a sandbox website like jsbin.com instead?

Agreed — and if you’re interested in creating a PR, that’d be great (and this can be assigned to you). Otherwise, I can pick it up (or maybe another contributor will).

**Comment by dorward** [comment] 2021-06-04 08:28
Sure. Assign away.

**Comment by dorward** [comment] 2021-06-24 10:51
Just checking in since it has been a few weeks. I've take a look at this and noticed that the text which caused the issue is some boilerplate that is used across quite a lot of pages, so I'm looking at creating a central page with the advice and then referencing from all of those pages. Obviously this means it is a bit of a bigger job then I originally envisioned and I've had a few other demands on my time recently. I haven't forgotten this!

**Comment by sideshowbarker** [comment] 2021-06-24 10:54
@dorward Thanks for update — there’s no urgency anyway, and it definitely seems better to get it fixed the right way (i.e., the way you describe) rather than just doing a one-off.

**Comment by himanshugarg** [comment] 2021-09-05 12:40
[Redeclarations](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let#redeclarations) are documented here and it is an error to redeclare `let` variables. Unless this is a recurring complaint, back-linking even to this section from every page that uses `let` could mean too many changes for one incorrect usage.

**Comment by Josh-Cena** [comment] 2022-07-14 08:17
This is not a bug with the content itself, but the fact that the Firefox console doesn't allow variable redeclarations across REPL inputs, which IMO is hugely inconvenient. However we can't reiterate on basic grammar everywhere so we have to trust that you have a right testing environment. Since it's been open for more than a year and people seem to find it hard to approach and fix, I'm going to close it for now.

**Closed by Josh-Cena** 2022-07-14 08:17 UTC
Labels: Content:Learn:JavaScript, community, 🐌 idle

**Comment by teoli2003** [comment] 2022-07-14 08:31
Note that it may be interesting to report this as a problem in the Firefox dev tools.
