### ISSUE TITLE
The sound file download from demo example is not a standard audio file

### ISSUE THREAD

**Issue by hjy1210** [mdn/content#22343] opened 2022-11-16 15:04 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/MediaStream_Recording_API/Using_the_MediaStream_Recording_API

### What information was incorrect, unhelpful, or incomplete?

1. play at https://mdn.github.io/dom-examples/media/web-dictaphone/
2. record some sound
3. after play the reorded sound, save it as test.oga
4. write a  html page , which has an audio element with src as the above test.oga
5. get the audio.duration information,  got **Infinity**
6. If test.oga is a standard audio, audio.duration should be real sound duration in seconds

### What did you expect to see?

If test.oga is a standard audio, audio.duration should be real sound duration in seconds

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/mediastream_recording_api/using_the_mediastream_recording_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MediaStream_Recording_API/Using_the_MediaStream_Recording_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/mediastream_recording_api/using_the_mediastream_recording_api/index.md
* Last commit: https://github.com/mdn/content/commit/c7aeb96dac3e0ac2864cffe45c02d214ae1a5219
* Document last modified: 2022-08-27T16:31:08.000Z

</details>

**Comment by bsmth** [comment] 2023-01-26 11:25
I'm going to close this one for now. If you think this is a mistake or you still have questions, feel free to reply. Thank you :)

**Closed by bsmth** 2023-01-26 11:25 UTC
Labels: help wanted, Content:WebAPI

**Comment by Josh-Cena** [comment] 2023-01-26 16:27
@bsmth As I understand the issue, the problem is not that `.oga` looks wrong in itself, but when you source it from an `audio` element, the `duration` is infinity. Did you test that?

**Comment by bsmth** [comment] 2023-01-30 12:18
Thanks for chiming in. The example [is using `.ogg` as the codec](https://github.com/mdn/dom-examples/blob/main/media/web-dictaphone/scripts/app.js#L80), so when clicking "save this file" in Fx or Chrome, the file type is recognized as `.ogg` not `.oga` - this might be where the confusion is coming from. 

There's an example pen here that demonstrates using both of these file types in an `<audio>` element:

https://codepen.io/bsmth/pen/poZZBaV

Additionally, there's an example for checking duration when we have metadata about the file.
