### ISSUE TITLE
The arguments in the dictionary should be used instead of the arguments captured in the URL

### ISSUE THREAD

**Issue by Yang-Wei-Ting** [mdn/content#1286] opened 2021-01-14 05:29 UTC
#### What information was incorrect, unhelpful, or incomplete?

- Note: Both extra options and named captured patterns are passed to the view as named arguments. If you use the same name for both a captured pattern and an extra option then **only the captured pattern value will be sent to the view (the value specified in the additional option will be dropped)**.

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Generic_views
--> Passing additional options in your URL maps
--> Note

#### What did you expect to see?
https://docs.djangoproject.com/en/3.1/topics/http/urls/#passing-extra-options-to-view-functions
--> Dealing with conflicts

- It’s possible to have a URL pattern which captures named keyword arguments, and also passes arguments with the same names in its dictionary of extra arguments. When this happens, **the arguments in the dictionary will be used instead of the arguments captured in the URL.**

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mdn/contribute/feedback`
* MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Contribute/Feedback
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/mdn/contribute/feedback/index.html
* Report started: 2021-01-14T05:23:53.710Z

</details>

**Comment by hamishwillee** [comment] 2021-01-15 05:43
Thanks, you are correct. The issue is fixed by an updated note, which is part of https://github.com/mdn/content/pull/1342

**Closed** 2021-01-15 07:35 UTC
Labels: 30 minute task, Content:Other
