### ISSUE TITLE
For...of link broken

### ISSUE THREAD

**Issue by micahbf** [mdn/content#26260] opened 2023-04-17 20:53 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of

### What information was incorrect, unhelpful, or incomplete?

The link is broken. If you click on the suggested search for "for...of", and then click the top (correct) result, it brings you to the same broken link

### What did you expect to see?

The for...of page

**Comment by Josh-Cena** [comment] 2023-04-17 21:44
Duplicate of https://github.com/mdn/content/issues/26257

**Closed by Josh-Cena** 2023-04-17 21:44 UTC
Labels: Content:JS, needs triage
