### ISSUE TITLE
Issue with "Tutoriel Django - 6e partie : Vues génériques pour…": catalog/book_list.html template does not exist

### ISSUE THREAD

**Issue by tipizzo** [mdn/content#3189] opened 2021-03-16 13:26 UTC
MDN URL: https://developer.mozilla.org/fr/docs/Learn/Server-side/Django/Generic_views

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `fr/learn/server-side/django/generic_views`
* MDN URL: https://developer.mozilla.org/fr/docs/Learn/Server-side/Django/Generic_views
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/learn/server-side/django/generic_views/index.html
* Last commit: https://github.com/mdn/translated-content/commit/d49032372e1ad262a313dc974d8de6bb6efbf784
* Document last modified: 2021-03-16T00:26:29.000Z

</details>

**Comment by SphinxKnight** [comment] 2021-05-18 07:10
The template is expected to be created during the tutorial: https://developer.mozilla.org/fr/docs/Learn/Server-side/Django/Generic_views#cr%C3%A9er_le_template_pour_la_vue_liste 

I'm closing this one but feel free to reopen it if I missed anything. If the issue is related to the French translation rather than to the English content, feel free to file an issue on https://github.com/mdn/translated-content

**Closed by SphinxKnight** 2021-05-18 07:10 UTC
