### ISSUE TITLE
Issue with "MIME types (IANA media types)": Wrong default MIME type for javascript

### ISSUE THREAD

**Issue by ltshb** [mdn/content#13133] opened 2022-02-19 14:14 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types

#### What information was incorrect, unhelpful, or incomplete?

This page states that the current MIME type for javascript is `text/javascript` while the other MIME type like `application/javascript` are obsolete. However based on the official IANA doc, that's the other way around, `application/javascript` should be used while `text/javascript` is obsolete (see https://www.iana.org/assignments/media-types/text/javascript and https://www.iana.org/assignments/media-types/application/javascript)

#### Specific section or headline?

[text/javascript](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types#textjavascript)

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/basics_of_http/mime_types`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/basics_of_http/mime_types/index.md
* Last commit: https://github.com/mdn/content/commit/55f17d4608c3bdc3e31d0abfaba6fc61d78a0ff5
* Document last modified: 2022-01-31T23:00:43.000Z

</details>

**Comment by sideshowbarker** [comment] 2022-02-20 00:01
Duplicate of #4077

**Closed by sideshowbarker** 2022-02-20 00:01 UTC
Labels: duplicate, Content:HTTP
