### ISSUE TITLE
Issue with "Intl.DateTimeFormat.prototype.formatRangeToParts()": (the supported language disappears)

### ISSUE THREAD

**Issue by sutangu** [mdn/content#2038] opened 2021-02-03 08:33 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/formatRangeToParts

#### What information was incorrect, unhelpful, or incomplete?
When change to Japanese language, [language-] select doesn't contain Français language, but when selected English, it contains. And when change to Français, it doesn't contains Japanese. 

#### Specific section or headline?
Change language page select.

#### What did you expect to see?
Full list of supports language on any language page.

#### Did you test this? If so, how?
Just click to all three of these, and seem that trouble.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/intl/datetimeformat/formatrangetoparts`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/formatRangeToParts
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/global_objects/intl/datetimeformat/formatrangetoparts/index.html
* Last commit: https://github.com/mdn/content/commit/2d423bd1a98b85b8584f08990792ebf39fcea56b
* Document last modified: 2021-01-09T13:41:23.000Z

</details>

**Comment by Ryuno-Ki** [comment] 2021-02-03 09:07
Dear @sutangu,

thanks for reporting this. Right now, this is by design. There are technical reasons, @peterbe might describe, but it boils down to this is a somewhat workable state and the developer capacity is limited right now.

The team is aware of it, but other things have a higher priority right now.
If you're okay with it, I'd close this issue.

**Comment by sutangu** [comment] 2021-02-03 09:42
@Ryuno-Ki, no problems if so. But I think I can do it. Or can I help with something else from Issues tab?

**Comment by Ryuno-Ki** [comment] 2021-02-03 18:23
Okay, I'm closing it now.

Feel free to browse through the open issues. We can welcome additional hands.
If something is unclear, please ask.

**Closed by Ryuno-Ki** 2021-02-03 18:23 UTC
