### ISSUE TITLE
Unclear Web API Event Properties

### ISSUE THREAD

**Issue by statusdocs09234** [mdn/content#36940] opened 2024-11-23 17:51 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Element/copy_event

### What specific section or headline is this issue about?

Introduction

### What information was incorrect, unhelpful, or incomplete?

Each [`Event`](https://developer.mozilla.org/en-US/docs/Web/API/Event) has these three boolean properties: `bubbles`, `cancelable`, and `composed`, which contain fairly useful information for developers.

Some of the documentation for events, like the [`Element.copy`](https://developer.mozilla.org/en-US/docs/Web/API/Element/copy_event) documentation, mentions the value of these properties:

> This event [bubbles](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Event_bubbling), is [cancelable](https://developer.mozilla.org/en-US/docs/Web/API/Event/cancelable) and is [composed](https://developer.mozilla.org/en-US/docs/Web/API/Event/composed).

The associated [W3C spec](https://w3c.github.io/clipboard-apis/#clipboard-event-copy) also mentions it.

Unfortunately, this is the exception, and most event documentation doesn't mention any of the three. A smaller number of documentation pages mention one or two of the three, at most. This is true for MDN, W3C, and WHATWG.

It would be great if the documentation could have some standardized way of conveying this information for all events.

But since this covers a large number of events, can I please get some guidance on how I might find or derive this information for any given event?

I tried a quick approach to testing within a browser:

```ts
const event = new SomeEvent('someevent')
console.log(`${event.type} cancelable: ${event.cancelable}`)
console.log(`${event.type} bubbles: ${event.bubbles}`)
console.log(`${event.type} composed: ${event.composed}`)
```

This doesn't help, because the three properties are still set to their default values of `false`. I tested a few events and stopped when I saw results that conflicted with the few documentation pages that did mention the information. I imagine the only way to get accurate results using this kind of test is to manufacture a situation in which the specified event is fired, but I'm hoping for a more direct approach.

### What did you expect to see?

I would have liked to see the information regarding cancellation, bubbling, and whether an event is composed mentioned on all events, like it is for the `copy`, `cut`, and `paste` events.

**Comment by Josh-Cena** [comment] 2024-11-24 07:53
Duplicate of https://github.com/mdn/content/issues/19590

**Closed by Josh-Cena** 2024-11-24 07:53 UTC
Labels: Content:WebAPI, needs triage, Content:Learn:JavaScript
