### ISSUE TITLE
Restore event init options tables (bubbles, cancelable, composed)

### ISSUE THREAD

**Issue by Kaiido** [mdn/content#32832] opened 2024-03-26 00:59 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/toggle_event

### What specific section or headline is this issue about?

The event init flags table

### What information was incorrect, unhelpful, or incomplete?

In this particular case, there is no mention that this event does not bubble, or when it's cancelable ([when toggling from closed to open](https://html.spec.whatwg.org/multipage/popover.html#the-popover-attribute:event-beforetoggle), but [not the other way around](https://html.spec.whatwg.org/multipage/popover.html#the-popover-attribute:event-beforetoggle-4)).  

But the problem is more general than just this one case, for instance the [toggle](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/toggle_event) event is not cancelable and doesn't bubble, or the [invalid](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/invalid_event) event which doesn't bubble either, or the [animationstart](https://developer.mozilla.org/en-US/docs/Web/API/Element/animationstart_event) event isn't cancelable, and that's only the few I looked at. I'm afraid the vast majority is now wrong.

### What did you expect to see?

For every event, there used to be a table which listed the various event-init flags that a particular event would be created with, i.e. `bubbles`, `cancelable`, or, `composed`. This was
 - easy to read,
 - easy to review,
 - hard to forget when documenting a new event (which I guess is what happened for the popover case).

### Do you have any supporting links, references, or citations?

In this [duplicate but locked issue](https://github.com/mdn/content/issues/22198), @queengooborg explained

> during the migration to a new page layout for event pages, we removed those tables as we merged the information into the writing itself. If an event is cancellable or does not bubble, you will now see a line near the top that says "This event is not cancellable" or "This event does not bubble". In other words, the information has not been removed, it's just represented in a different form.

### Do you have anything more you want to share?

One issue here is that as the linked `beforetoggle` case demonstrates, it's not always obvious which flags are set for a particular event since it can differ based on where it's actually fired, so the table data can't really be automated.  
Still, I believe MDN *is* the place to document this and asking web-devs to do the hunting in the specs isn't appropriate, and I hope the old data is still available somewhere, which should help for the majority of events.

___
Ps: Sorry for opening a new issue when there was already #22198 but as I said, it's been locked and I can't comment on that one anymore.

**Comment by wbamberg** [comment] 2024-03-27 05:52
See also https://github.com/mdn/content/issues/19590 .

**Comment by Kaiido** [comment] 2024-03-27 06:12
Oh thanks, I missed that one. I guess I can move it as a comment there, or should I try to start the discussion that @teoli2003 was talking about directly?

**Comment by wbamberg** [comment] 2024-03-27 06:50
> should I try to start the discussion that @teoli2003 was talking about directly?

I think that's a good idea! But let's also close this as a duplicate of the other one.

**Closed by wbamberg** 2024-03-27 06:50 UTC
Labels: Content:WebAPI, needs triage

**Comment by wbamberg** [comment] 2024-04-01 22:21
I started the discussion->https://github.com/orgs/mdn/discussions/665.
