### ISSUE TITLE
Several CSS Reference pages lack "Formal syntax"

### ISSUE THREAD

**Issue by That-Guy977** [mdn/content#19149] opened 2022-08-04 10:26 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/linear-gradient#formal_syntax

### What specific section or headline is this issue about?

Format syntax, Formal definition

### What information was incorrect, unhelpful, or incomplete?

`{{csssyntax}}` tags break and yield "Error: could not find syntax for this item" on several pages. Case doesn't seem to matter, as I've found examples of both instances yielding the error

Some other examples:
- Other pages in the `<gradient>` group
- https://developer.mozilla.org/en-US/docs/Web/CSS/math-style#formal_syntax
- https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-text-security#formal_syntax (also has an issue in the "Formal definition" section above)

Example from `-webkit-text-security`:
![image](https://user-images.githubusercontent.com/72870724/182825269-7e7750c7-44b8-4981-a534-073bc77c9c2a.png)

### What did you expect to see?

A proper "Formal syntax"/"Formal definition" section

**Comment by Josh-Cena** [comment] 2022-08-04 11:45
Let's call it a duplicate of https://github.com/mdn/content/issues/18641 and https://github.com/mdn/content/issues/18780. They'll likely be fixed together anyway.

**Closed by Josh-Cena** 2022-08-04 11:45 UTC
Labels: duplicate, Content:CSS
