### ISSUE TITLE
Document the the X-Requested-With HTTP header

### ISSUE THREAD

**Issue by techsin** [mdn/content#4178] opened 2021-04-16 15:24 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers

#### What information was incorrect, unhelpful, or incomplete?
X-Requested-With link is broken!

#### Specific section or headline?
It's under Other

#### What did you expect to see?
documentation about X-Requested-With header

#### Did you test this? If so, how?
click the link

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/headers`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/index.html
* Last commit: https://github.com/mdn/content/commit/fc36604b19a172f3fbedb2629e2403180f2eda55
* Document last modified: 2021-03-19T23:16:59.000Z

</details>

**Comment by sideshowbarker** [comment] 2021-04-17 09:14
Yeah the cause is, nobody has yet written the https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Requested-With article.

So the task for whoever works on this would be to write that article.

**Comment by techsin** [comment] 2021-04-22 15:29
how do I find out who works on that?

**Comment by hamishwillee** [comment] 2021-04-23 01:36
@techsin This is open source, so it could be anyone - you're most welcome to take it on. At some point if my list of things got small enough I might take it on.

**Comment by himanshugarg** [comment] 2021-05-24 06:18
Using a link checker found the following headers with broken links:-

- Viewport-Width
- Width
- Max-Forwards
- Origin-Isolation
- X-Download-Options
- X-Permitted-Cross-Domain-Policies
- X-Powered-By
- Last-Event-ID
- Ping-From
- Ping-To
- Report-To
- Sec-WebSocket-Key
- Sec-WebSocket-Extensions
- Sec-WebSocket-Protocol
- Sec-WebSocket-Version
- Accept-Push-Policy
- Accept-Signature
- Push-Policy
- Signature
- Signed-Headers
- Service-Worker-Allowed
- X-Firefox-Spdy
- X-Pingback
- X-Requested-With
- X-Robots-Tag
- X-UA-Compatible

**Comment by techsin** [comment] 2021-05-24 13:56
say if someone wanted to fill out the docs, would they be using w3specs as
a reference?

**Comment by hamishwillee** [comment] 2021-05-25 01:09
Yes. Though there are plenty of headers that are not in W3C specs - e.g. the Sec-* ones I talk about here: https://github.com/mdn/content/pull/4907#issuecomment-845694070

But yes, over time we should aim to document all headers that have been broadly implemented. I will get to that first one sometime soon as part of https://github.com/mdn/content/pull/4907

**Comment by Josh-Cena** [comment] 2022-12-22 23:12
Duplicate of https://github.com/mdn/content/issues/1458

**Closed by Josh-Cena** 2022-12-22 23:12 UTC
Labels: help wanted, Content:HTTP, effort: medium, document not written
