### ISSUE TITLE
Add `inert` attribute

### ISSUE THREAD

**Issue by SebastianZ** [mdn/content#19075] opened 2022-08-02 23:01 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes

### What specific section or headline is this issue about?

List of global attributes

### What information was incorrect, unhelpful, or incomplete?

The specifications list and the browser compat table already include the global `inert` attribute but the list of attributes is still missing it.

### What did you expect to see?

A description of the `inert` attribute.

### Do you have any supporting links, references, or citations?

There is already a separate page describing the related [`inert` DOM property](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/inert).

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/global_attributes`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/global_attributes/index.md
* Last commit: https://github.com/mdn/content/commit/5a9f418517a21e5f9d066cc507b2e4b28dbfbb95
* Document last modified: 2022-07-20T07:39:49.000Z

</details>

**Comment by Isaac108** [comment] 2022-08-03 03:24
Looking into it.

**Comment by Isaac108** [comment] 2022-08-03 04:23
Submitted a pull that gave a general overview of the inert attribute.

**Comment by Malvoz** [comment] 2022-10-27 19:10
Duplicate of #11128

**Closed** 2022-11-21 21:26 UTC
Labels: good first issue, help wanted, Content:HTML, time: -30mins
