### ISSUE TITLE
Issue with "zoom": in Firefox the zoom examples are not displayed as should. no problems in safari or chrome or brave.

### ISSUE THREAD

**Issue by mirmuis** [mdn/content#12887] opened 2022-02-10 11:14 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/zoom

#### What information was incorrect, unhelpful, or incomplete?
the zooming examples
#### Specific section or headline?
First and second example 
#### What did you expect to see?
Zoomed examples
#### Did you test this? If so, how?
yes by trying different browsers (chrome, safari, brave). they work fine. but Firefox doesnt, neither in a Mac or in Debian.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/zoom`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/zoom
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/zoom/index.md
* Last commit: https://github.com/mdn/content/commit/6a12a6452bb6b19af442c56667ded995b889e85f
* Document last modified: 2022-01-22T12:26:48.000Z

</details>

**Comment by sideshowbarker** [comment] 2022-02-10 11:29
Hi and thanks for raising this.

https://developer.mozilla.org/en-US/docs/Web/CSS/zoom states that `zoom` is non-standard:

> Non-standard: This feature is non-standard and is not on a standards track. Do not use it on production sites facing the Web: it will not work for every user. There may also be large incompatibilities between implementations and the behavior may change in the future.

…and the Browser Compatibility table at https://developer.mozilla.org/en-US/docs/Web/CSS/zoom#browser_compatibility shows that Firefox doesn’t support it.

So I’m going ahead and closing this — because it doesn’t seem like any further changes are needed to the article (the fact that the examples don’t work in Firefox is expected behavior per the information the article already contains).

**Closed by sideshowbarker** 2022-02-10 11:29 UTC
Labels: Content:CSS
