### ISSUE TITLE
Can't get Pow to work on Firefox

### ISSUE THREAD

**Issue by worldOfVerdure** [mdn/content#26636] opened 2023-05-08 04:44 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/pow

### What specific section or headline is this issue about?

Compatibility

### What information was incorrect, unhelpful, or incomplete?

It states Pow works in firefox, but it doesn't for me.

### What did you expect to see?

That it isn't supported.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/pow`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/pow
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/pow/index.md
* Last commit: https://github.com/mdn/content/commit/676065ed85f246825b45579ac6228e41357dbdad
* Document last modified: 2023-04-22T05:15:34.000Z

</details>

**Comment by teoli2003** [comment] 2023-05-08 05:14
Works for me: Which version of Firefox are you using?

![Capture d’écran 2023-05-08 à 07 13 45](https://user-images.githubusercontent.com/1466293/236739590-3b14729b-c4b9-41bc-8ac6-e265e003e674.png)

**Comment by worldOfVerdure** [comment] 2023-05-11 14:01
Thank you for your response, I can show what I was attempting to do:

![css](https://github.com/mdn/content/assets/112784057/0b84f80c-0506-4616-abe3-4507c0d153e5)
![versionFox](https://github.com/mdn/content/assets/112784057/e4b69819-f9da-476f-aa67-6a5bd0e05c5b)
![result](https://github.com/mdn/content/assets/112784057/9a409eb9-72bf-43b5-865c-4183506c7891)

**Comment by wbamberg** [comment] 2023-05-11 22:50
Codepen: https://codepen.io/willbamberg/pen/KKGepyJ

For me this works in Firefox Nightly (114) but not Firefox release (113). Maybe the BCD is wrong?

**Comment by teoli2003** [comment] 2023-05-17 05:09
Ok, I dug into the code. 
This has never been published outside Nightly version (which explains why it works for me and not for you).

The [code](https://phabricator.services.mozilla.com/D170842) is: 
![Capture d’écran 2023-05-17 à 07 03 47](https://github.com/mdn/content/assets/1466293/d463bad2-ce48-4041-8eb7-e5b041d755b9)


Also, @dletorey asked developers in the Mozilla bug questions that were never answered.

So it has been added in Fx 112 in Nightly, and I think no release version has been released with it, but I've not dug more. There may have been more changes.

@dletorey, can you double-check and fix bcd, release notes, and Firefox experimental features if this is confirmed? It would be nice.

**Comment by evilpie** [comment] 2023-05-31 19:26
A Firefox [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1836134) was reported due the the wrong MDN data.

**Comment by Josh-Cena** [comment] 2023-09-24 21:30
Fixed by https://github.com/mdn/browser-compat-data/pull/20652

**Closed by Josh-Cena** 2023-09-24 21:30 UTC
Labels: Content:CSS
