### ISSUE TITLE
Issue with "Floats": (short summary here please)

### ISSUE THREAD

**Issue by Pacoromo** [mdn/content#9415] opened 2021-10-01 12:51 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Floats

#### Specific section or headline?
The code snippets are giving me this error quite often. I tried reload, reset, but no luck.
![2021-10-01](https://user-images.githubusercontent.com/65608609/135622190-38c20c8e-1ba3-49bb-abdd-4584c2c59679.png)

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/css_layout/floats`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Floats
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/css_layout/floats/index.html
* Last commit: https://github.com/mdn/content/commit/b7c594e7a8e5eb31a70bcf3e07d931e4603d201b
* Document last modified: 2021-09-03T05:34:55.000Z

</details>

**Comment by wbamberg** [comment] 2021-10-01 17:28
> quite often

When you say this, do you mean it's intermittent, or do you see it all the time? I can't reproduce it right now. @escattone , do you have any idea why people might be seeing this error?

**Comment by Pacoromo** [comment] 2021-10-01 21:37
It started this morning. I tried in my Mac using Safari and it was ok. It only shows this warning in Firefox in a PC.

Francisco J. Romo

**Comment by escattone** [comment] 2021-10-01 22:50
@Pacoromo @wbamberg I can't reproduce it either. I suspect what's happening is that the request for the live-sample page `/en-US/docs/Learn/CSS/CSS_layout/Floats/_sample_.display_flow-root.html` is using a cached value from the browser that has the `X-Frame-Options` header as `DENY`, but of course that's just a guess. We had an issue in the past where that header was erroneously added. I would try clearing all cached content in your Firefox browser, and then reloading the page.

**Comment by himanshugarg** [comment] 2021-10-05 00:15
At least one other user has reported this - https://github.com/mdn/content/issues/9323 and I hope there are not many others. Is there a way we can confirm from the server logs?

**Comment by wbamberg** [comment] 2021-10-05 00:42
@himanshugarg : I closed the other issue as the reporter says it's no longer reproducible. For your question, if I understand Ryan's response, server logs wouldn't help because it's a client-side problem. @Pacoromo , did clearing your cache help?

**Comment by himanshugarg** [comment] 2021-10-05 00:54
@wbamberg : yes the other issue should have been closed because it was an isolated one (then). But given this issue and MDN scale I thought there might be others seeing this. As server logs won't help perhaps I could ask for the client details to see if there is a pattern.

**Comment by Pacoromo** [comment] 2021-10-05 19:49
Sorry for the late reply...  I haven't seen the problem for the last coupe of days. I haven't cleared cache.I'll let you know if the problem comes back. On Oct. 4, 2021, at 8:43 p.m., wbamberg ***@***.***> ***@***.*** : I closed the other issue as the reporter says it's no longer reproducible. For your question, if I understand Ryan's response, server logs wouldn't help because it's a client-side problem. @Pacoromo , did clearing your cache help?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wbamberg** [comment] 2021-10-05 20:25
Thanks! I'll close this but please let us know if it comes back.

**Closed by wbamberg** 2021-10-05 20:25 UTC
