### ISSUE TITLE
Example using object URLs to display images is broken because of a CSP error.

### ISSUE THREAD

**Issue by guillaumebrunerie** [mdn/content#28255] opened 2023-07-29 13:52 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/File_API/Using_files_from_web_applications

### What specific section or headline is this issue about?

Example: Using object URLs to display images

### What information was incorrect, unhelpful, or incomplete?

The example is supposed to show how to use object URLs to display images, but the images are not displayed because of a Content Security Policy error. I guess it is because the iframe has a different origin, but I don’t know enough about MDN or CSP to know how to fix it.

### What did you expect to see?

A working example.

### Do you have anything more you want to share?

Click on "Select some files", select an image, and notice that the thumbnail isn’t shown (even though showing a thumbnail is the whole point of the example).

![Skärmbild från 2023-07-29 15-47-48](https://github.com/mdn/content/assets/787865/f085c5d6-155d-4210-9e46-59988011d338)

**Comment by Josh-Cena** [comment] 2023-07-29 14:56
Duplicate of https://github.com/mdn/yari/issues/9360

**Closed by Josh-Cena** 2023-07-29 14:56 UTC
Labels: Content:WebAPI, needs triage
