### ISSUE TITLE
What happens in the case of invalid JSON?

### ISSUE THREAD

**Issue by ronkorving** [mdn/content#33726] opened 2024-05-23 07:32 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Response/json

### What specific section or headline is this issue about?

Return value

### What information was incorrect, unhelpful, or incomplete?

Incomplete

### What did you expect to see?

Some explanation about what happens when the data that is being parsed by the .json() method is invalid JSON. Will it throw? If so, what kind of error? Or will it return undefined or null? Or something else entirely?

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/response/json`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Response/json
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/response/json/index.md
* Last commit: https://github.com/mdn/content/commit/1a91b0b63f0cbaca9125bd48d4e5bc8afed2a7a3
* Document last modified: 2024-03-07T17:23:45.000Z

</details>

**Comment by ragul1697** [comment] 2024-05-24 12:21
.json() will throw a `SyntaxError` with a message that `response is not a valid json`

**Comment by ronkorving** [comment] 2024-06-04 02:35
@ragul1697 Cheers 👍 Would be good for the docs to reflect that.

**Comment by Josh-Cena** [comment] 2024-06-05 10:38
Duplicate of https://github.com/mdn/content/issues/13208. We need to systematically add "Exceptions" to this page.

**Closed by Josh-Cena** 2024-06-05 10:38 UTC
Labels: Content:WebAPI, area: Fetch/XMLHttpRequest, goal: completeness
