### ISSUE TITLE
ReferenceError: Crafty : 2D collision tutorial

### ISSUE THREAD

**Issue by lx78WyY0J5** [mdn/content#31449] opened 2024-01-01 16:19 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Games/Techniques/2D_collision_detection

### What specific section or headline is this issue about?

2D collision detection

### What information was incorrect, unhelpful, or incomplete?

Scripts dont run as crafty is not "well" defined or outdated or deprecated

### What did you expect to see?

Squares & circles (For collision detection demo)
Only text placeholder remain (as they aren't from script)

### Do you have any supporting links, references, or citations?

the script included `src="https://cdnjs.cloudflare.com/ajax/libs/crafty/0.5.4/crafty-min.js"`
`Crafty.init(200, 200);` this line will trigger reference error

Running with Chrome (v101) & Mozilla firefox (v121)

### Do you have anything more you want to share?

![hRy8a7JblI](https://github.com/mdn/content/assets/84735589/46a2d392-c60e-4cc9-b3bb-0259103078b2)
Nota bene : this is the default code showed on the tutorial

Love you ❤️

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/games/techniques/2d_collision_detection`
* MDN URL: https://developer.mozilla.org/en-US/docs/Games/Techniques/2D_collision_detection
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/games/techniques/2d_collision_detection/index.md
* Last commit: https://github.com/mdn/content/commit/acfe8c9f1f4145f77653a2bc64a9744b001358dc
* Document last modified: 2023-07-07T07:19:19.000Z

</details>
```[tasklist]
### Tasks
```

**Comment by lx78WyY0J5** [comment] 2024-01-01 16:26
Nota bene : 

this script fiddle is found inside markdown page, and still work

jsfiddle.net/jlr7245/teb4znk0/20/ 
[URL](https://jsfiddle.net/jlr7245/teb4znk0/20/)

**Comment by hamishwillee** [comment] 2024-01-01 22:26
Thank you. This is a duplicate of https://github.com/mdn/yari/issues/9346 (it is a bug in the infrastructure that loads crafty after it is needed)

**Closed by hamishwillee** 2024-01-01 22:26 UTC
Labels: needs triage, Content:Games
