### ISSUE TITLE
Content bug: Many Pages' line spacinig is way too little

### ISSUE THREAD

**Issue by harryyeTKL** [mdn/content#10440] opened 2021-11-11 02:31 UTC
## What page(s) did you find the problem on?

This situation seems to be pretty common.
[Graceful asynchronous programming with Promises](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Promises)
[Making asynchronous programming easier with async and await](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Promises)

## What is the problem?

The line spacing is way too small and the text at the end is not aligned.

## What did you expect to see?

Probably some major CSS is broken, cos the pages looked great about 3 days ago. may need to roll back.

**Comment by Junaid-1993** [comment] 2021-11-11 07:20
Yes, you are right. I am a regular reader of the MDN docs and everything was good about three days ago and now there are no line breaks and proper line spacing between paragraphs in CSS Modules. I think there is something wrong with the .css file I hope they fix it soon otherwise it is very hard to read paragraphs.

**Comment by Elchi3** [comment] 2021-11-11 08:28
Duplicate of https://github.com/mdn/yari/issues/4929

**Closed by Elchi3** 2021-11-11 08:28 UTC
Labels: needs-triage
