### ISSUE TITLE
Issue with "Getting started with Svelte": …

### ISSUE THREAD

**Issue by davidecr2010** [mdn/content#1501] opened 2021-01-19 17:41 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Svelte_getting_started

#### What information was incorrect, unhelpful, or incomplete?
The tutorial suggest making change in the section: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Svelte_getting_started#making_a_couple_of_changes. 
And specifies that changes should automatically be available in the running app ("_Just save your changes and the app running at localhost:5000 will be automatically updated._")

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Svelte_getting_started#making_a_couple_of_changes

#### What did you expect to see?
The change should be reflected automatically as suggested (Hot reloading?) but even after reloading the page in the browser does the content get updated.

#### Did you test this? If so, how?
Make the changes on the App.svelte file as suggested in the tutorial. After that I checked in the official documentation of Svelte and it seems that this is not still available as per version 3 of Svelte. Hot reloading needs some sort of extra plugin (https://github.com/sveltejs/svelte/issues/2377) 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/tools_and_testing/client-side_javascript_frameworks/svelte_getting_started`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Svelte_getting_started
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/svelte_getting_started/index.html
* Report started: 2021-01-19T15:41:52.128Z

</details>

**Comment by chrisdavidmills** [comment] 2021-03-18 11:31
This si quite an important detail to get right. Whoever fixes this would need to get a svelte app running, check the nature of hot reloading by default, and change the article text accordingly if this is not the case.

**Comment by himanshugarg** [comment] 2021-05-19 12:03
Cannot reproduce on Ubuntu 16, Node v14.16.0 with setup as described. Changing the text and saving the file in editor updates the text in the browser window automatically.

**Comment by sideshowbarker** [comment] 2021-06-06 09:05
Closing as not reproducible per https://github.com/mdn/content/issues/1501#issuecomment-844036810 (thanks @himanshugarg).

@davidecr2010 If you can still reproduce the problem, this issue can be revisited.

**Closed by sideshowbarker** 2021-06-06 09:05 UTC
Labels: 30 minute task, Content:Learn, P1, good first issue, help wanted
