### ISSUE TITLE
Issue trying to run "Using IndexedDB > Full IndexedDB example"

### ISSUE THREAD

**Issue by BigBoulard** [mdn/content#11806] opened 2022-01-07 08:38 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB

#### What information was incorrect, unhelpful, or incomplete?
The "Full IndexedDB example" doesn't seem to work (regular Chrome not Canary release), no error message etc.

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB#full_indexeddb_example

#### What did you expect to see?
An error message would be a good start

#### Did you test this? If so, how?
Took the code locally with VSCode & live-server

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/indexeddb_api/using_indexeddb`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/indexeddb_api/using_indexeddb/index.md
* Last commit: https://github.com/mdn/content/commit/5f82874a394e6f53fbd9fbebe42e235e8b5095db
* Document last modified: 2021-11-02T19:34:20.000Z

</details>

**Comment by wbamberg** [comment] 2022-01-15 03:37
I think this might be a duplicate of https://github.com/mdn/content/issues/10941 ?

**Comment by wbamberg** [comment] 2022-01-17 18:24
It's a little unclear from the description, but I think this is a duplicate of https://github.com/mdn/content/issues/10941 so I'm closing it.

I have tried out https://mdn.github.io/dom-examples/indexeddb-api/index.html in Chrome and it seems to work OK.

**Closed by wbamberg** 2022-01-17 18:24 UTC
Labels: help wanted, Content:WebAPI, time: -3hr
