### ISSUE TITLE
Issue with "Style Editor": (Video unavailable)

### ISSUE THREAD

**Issue by TheBicPen** [mdn/content#7626] opened 2021-08-05 17:25 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Style_Editor

#### What information was incorrect, unhelpful, or incomplete?
An embedded video on the page is unavailable

#### Specific section or headline?
The media sidebar, last video in that section (https://youtu.be/XeocxoW2NYY)

#### What did you expect to see?
A video

#### Did you test this? If so, how?
Visiting the page, visiting the URL of the video

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/style_editor`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Style_Editor
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/style_editor/index.html
* Last commit: https://github.com/mdn/content/commit/6e59c64149037dd061cd56064b92ac18684368a7
* Document last modified: 2021-05-07T07:36:48.000Z

</details>

**Comment by sideshowbarker** [comment] 2021-08-05 17:55
Root cause is same at https://github.com/mdn/content/issues/7457

**Comment by wbamberg** [comment] 2021-10-04 02:17
Closing as a duplicate of This issue is being tracked as https://github.com/mdn/content/issues/7457..

**Closed by wbamberg** 2021-10-04 02:17 UTC
Labels: Content:DevTools
