### ISSUE TITLE
<input pattern> changed to set the RegExp 'v' flag

### ISSUE THREAD

**Issue by zcorpan** [mdn/content#27347] opened 2023-06-15 11:34 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input

### What specific section or headline is this issue about?

#pattern

### What information was incorrect, unhelpful, or incomplete?

The HTML spec was changed to set the new 'v' flag instead of the 'u' flag.

### What did you expect to see?

Mention of the 'v' flag and that it changed from 'u' in 2023.

### Do you have any supporting links, references, or citations?

https://github.com/whatwg/html/pull/7908
https://chromestatus.com/feature/5149507107422208
https://bugzilla.mozilla.org/show_bug.cgi?id=pattern-v
https://bugs.webkit.org/show_bug.cgi?id=pattern-v

### Do you have anything more you want to share?

Also see https://github.com/mdn/content/issues/27346

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/input`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/input/index.md
* Last commit: https://github.com/mdn/content/commit/e04d8d2766c468f149445c0bf438d09f9b2d188c
* Document last modified: 2023-06-13T08:10:47.000Z

</details>

**Comment by Josh-Cena** [comment] 2023-06-15 11:42
Duplicate of https://github.com/mdn/content/issues/26907

**Closed by Josh-Cena** 2023-06-15 11:42 UTC
Labels: Content:HTML, needs triage
