### ISSUE TITLE
MDN Most of the Korean documentation go to the not found page

### ISSUE THREAD

**Issue by TakhyunKim** [mdn/content#27516] opened 2023-06-24 03:28 UTC
### MDN URL

https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach

### What specific section or headline is this issue about?

Not found page Error

### What information was incorrect, unhelpful, or incomplete?

When navigating to a detail page for an API such as Array reduce or map, an error occurs.

In MDN, the [HTML](https://developer.mozilla.org/ko/docs/Web/HTML), [Web APIs](https://developer.mozilla.org/ko/docs/Web/API), and [HTTP](https://developer.mozilla.org/ko/docs/Web/HTTP) category index pages output normally. 
If you navigate to see more details on each page, you'll get a 404 error.

### What did you expect to see?

It should output Korean documentation for that API.

### Not Found Page List

The attached link is not the only one.

- [Array forEach Docs](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach)
- [Array AbortController](https://developer.mozilla.org/ko/docs/Web/API/AbortController)

### Pages that work

- [MDN Web Javascript docs](https://developer.mozilla.org/ko/docs/Web/JavaScript)
- [MDN Web learn docs](https://developer.mozilla.org/ko/docs/Learn)

### Do you have anything more you want to share?

Example video 1

https://github.com/mdn/content/assets/64253365/b30afb97-5b63-4112-8fc1-41d4db15da13

https://github.com/mdn/content/assets/64253365/06482599-2b3d-4ecc-973d-62c8d40d9539

**Comment by Josh-Cena** [comment] 2023-06-24 10:43
Duplicate of https://github.com/mdn/yari/issues/9154

**Closed by Josh-Cena** 2023-06-24 10:43 UTC
Labels: to move
