### ISSUE TITLE
Issue with "Element.scrollTop": Negative values are possible

### ISSUE THREAD

**Issue by Elipzer** [mdn/content#10968] opened 2021-12-04 11:37 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTop

#### What information was incorrect, unhelpful, or incomplete?
scrollTop doesn't respond to negative values; instead, it sets itself back to 0.

#### Specific section or headline?
Syntax caveats

#### What did you expect to see?
I'm seeing negative scrollTop on a flex column-reverse div of mine (electron/chromium)
I expect that column-reverse divs behave differently with scrollTop

#### Did you test this? If so, how?
Messed with scrollTop in the browser console on a column-reverse div
![image](https://user-images.githubusercontent.com/9081748/144708008-c25556ea-be3f-477b-8c44-45fd3a580137.png)
![image](https://user-images.githubusercontent.com/9081748/144707977-5aee30ab-70f8-4607-8030-c6fa0353b393.png)
![image](https://user-images.githubusercontent.com/9081748/144707995-99a8abb6-ec2d-4f34-a4d3-1eb7ce90b4af.png)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/element/scrolltop`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTop
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/element/scrolltop/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by Josh-Cena** [comment] 2022-12-26 02:35
Duplicate of #4142

**Closed** 2022-12-26 02:35 UTC
Labels: help wanted, Content:WebAPI, effort: medium
