### ISSUE TITLE
Reporting API's browser compatibility is stale

### ISSUE THREAD

**Issue by agektmr** [mdn/content#34055] opened 2024-06-11 14:01 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Reporting_API

### What specific section or headline is this issue about?

Browser Compatibility

### What information was incorrect, unhelpful, or incomplete?

The information described here does not reflect the reality.

### What did you expect to see?

Ideally Browser Comatibility Data table but since Reporting API isn't included there, maybe a table of supported headers? Or a list of headers.

### Do you have any supporting links, references, or citations?

See the latest availability here https://developer.chrome.com/docs/capabilities/web-apis/reporting-api#browser_support

**Comment by Josh-Cena** [comment] 2024-06-11 14:18
I could call this a duplicate of https://github.com/mdn/content/issues/29292 since the whole API docs are outdated.

**Closed by Josh-Cena** 2024-06-11 14:18 UTC
Labels: Content:WebAPI, needs triage
