### ISSUE TITLE
In the "Using custom elements" guide and related pages, add a disclaimer that WebKit does not plan to support Customized built-in elements

### ISSUE THREAD

**Issue by njanssoone** [mdn/content#30968] opened 2023-12-12 17:40 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_custom_elements

### What specific section or headline is this issue about?

Types of custom element

### What information was incorrect, unhelpful, or incomplete?

The guide does not warn users that using Customized Built-in Elements currently does not work on WebKit-based browsers, and that it won't change for now because the WebKit team is refuting this part of the Web Components spec.

Also, on the ["CustomElementRegistry.prototype.define()" page](https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/define), the compatibility section does show the `define` method as fully supported by Safari (both desktop and mobile).

### What did you expect to see?

In the "Using custom elements" guide, part "Types of custom element": a disclaimer panel indicating that this type of custom elements is currently not supported by WebKit-based browsers.

In the "CustomElementRegistry.prototype.define()" page, part "Browser compatibility": a dedicated row for the `{ extend: 'tagName' }` option's compatibility, indicating WebKit's missing support.

### Do you have any supporting links, references, or citations?

https://bugs.webkit.org/show_bug.cgi?id=182671
https://github.com/WebKit/standards-positions/issues/97
https://github.com/WICG/webcomponents/issues/509

**Comment by pepelsbey** [comment] 2024-01-05 12:24
Hey! Nice catch :) I just stumbled upon the same part of the guide, but there’s already an issue for that. Thanks! This part of the guide would definitely benefit from clearing this out. It might be in the form of a note, linking to the WebKit’s standard position. Feel free to suggest a PR, or we can wait for the community to pick it up.

As for the compatibility table, this is something that’s based on [BCD repository](https://github.com/mdn/browser-compat-data/), and there’s a link on top of the table to file an issue with the data. Could you please file a feature request for documenting the `extend` support?

**Comment by davidpcaldwell** [comment] 2024-04-12 16:31
I filed my own duplicate of this that I'll link for reference. https://github.com/mdn/content/issues/33063

Here's the gist of what I wrote:

### What information was incorrect, unhelpful, or incomplete?

It seems like the page should mention somewhere that (as things stand) "customized built-in elements" will never be widely supported because [Safari has decided not to support them](https://bugs.webkit.org/show_bug.cgi?id=182671) on iOS or macOS.

### What did you expect to see?

Many MDN pages (for example, the [Web Components](https://developer.mozilla.org/en-US/docs/Web/API/Web_components) index page itself) have compatibility information at the bottom.

But even absent that, I think it should probably be mentioned in the introduction to the two custom element types themselves.

**Closed** 2024-07-21 13:30 UTC
Labels: help wanted, Content:WebAPI, effort: small, area: Web Components, needs BCD update
