### ISSUE TITLE
Issue with "HTMLImageElement.sizes": Image not found

### ISSUE THREAD

**Issue by duandzgp** [mdn/content#9354] opened 2021-09-30 02:15 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/sizes

#### What information was incorrect, unhelpful, or incomplete?
The image /files/16869/new-york-skyline-4by3.jpg could not be found.

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/sizes#result

#### What did you expect to see?
The image show properly

#### Did you test this? If so, how?
Just open the webpage

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/htmlimageelement/sizes`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/sizes
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlimageelement/sizes/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by digi-booster** [comment] 2021-09-30 05:45
Thanks for raising this issue but it has already been reported by @letharion in #9313.

**Comment by wbamberg** [comment] 2022-01-12 04:49
Closing as a duplicate of https://github.com/mdn/content/issues/9313 , thanks @digi-booster .

**Closed by wbamberg** 2022-01-12 04:49 UTC
Labels: needs-triage
