### ISSUE TITLE
Error after deleting the hello world components

### ISSUE THREAD

**Issue by dduclayan** [mdn/content#20071] opened 2022-08-29 00:53 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Vue_getting_started

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Vue_getting_started#making_a_couple_of_changes

### What information was incorrect, unhelpful, or incomplete?

I deleted the following lines per the article:

1. `<img alt="Vue logo" src="./assets/logo.png">`
2. `<HelloWorld msg="Welcome to Your Vue.js App"/>`
3. `import HelloWorld from './components/HelloWorld.vue'`
4. `components: {HelloWorld}`

After deleting line 4, per the article I should not have any errors. Yet, I do. 

```
 ERROR  Failed to compile with 1 error                                                                        7:42:34 PM

[eslint]
C:\Users\Devin Duclayan\WebstormProjects\vue-test\app\moz-todo-vue\src\App.vue
  1:1  error  The template requires child element  vue/valid-template-root

✖ 1 problem (1 error, 0 warnings)
```

### What did you expect to see?

No errors after deleting line `components: {HelloWorld}`

### Do you have any supporting links, references, or citations?

Vue version:
PS C:\Users\Devin Duclayan> vue --version
@vue/cli 5.0.8

Full error:
```
 ERROR  Failed to compile with 1 error                                                                        7:42:34 PM

[eslint]
C:\Users\Devin Duclayan\WebstormProjects\vue-test\app\moz-todo-vue\src\App.vue
  1:1  error  The template requires child element  vue/valid-template-root

✖ 1 problem (1 error, 0 warnings)


You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
ERROR in [eslint]
C:\Users\Devin Duclayan\WebstormProjects\vue-test\app\moz-todo-vue\src\App.vue
  1:1  error  The template requires child element  vue/valid-template-root

✖ 1 problem (1 error, 0 warnings)


webpack compiled with 1 error
```

### Do you have anything more you want to share?

Uncommenting `<!--<section></section>-->` fixes the error for me. 

App.vue content:
```
<template>
<!--<section></section>-->
</template>

<script>
export default {
  name: 'App',
}
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
```
HelloWorld.vue content:

```
<template>
  <div class="hello">
    <h1>{{ msg }}</h1>
    <p>
      For a guide and recipes on how to configure / customize this project,<br>
      check out the
      <a href="https://cli.vuejs.org" target="_blank" rel="noopener">vue-cli documentation</a>.
    </p>
    <h3>Installed CLI Plugins</h3>
    <ul>
      <li><a href="https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-plugin-babel" target="_blank" rel="noopener">babel</a></li>
      <li><a href="https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-plugin-eslint" target="_blank" rel="noopener">eslint</a></li>
    </ul>
    <h3>Essential Links</h3>
    <ul>
      <li><a href="https://vuejs.org" target="_blank" rel="noopener">Core Docs</a></li>
      <li><a href="https://forum.vuejs.org" target="_blank" rel="noopener">Forum</a></li>
      <li><a href="https://chat.vuejs.org" target="_blank" rel="noopener">Community Chat</a></li>
      <li><a href="https://twitter.com/vuejs" target="_blank" rel="noopener">Twitter</a></li>
      <li><a href="https://news.vuejs.org" target="_blank" rel="noopener">News</a></li>
    </ul>
    <h3>Ecosystem</h3>
    <ul>
      <li><a href="https://router.vuejs.org" target="_blank" rel="noopener">vue-router</a></li>
      <li><a href="https://vuex.vuejs.org" target="_blank" rel="noopener">vuex</a></li>
      <li><a href="https://github.com/vuejs/vue-devtools#vue-devtools" target="_blank" rel="noopener">vue-devtools</a></li>
      <li><a href="https://vue-loader.vuejs.org" target="_blank" rel="noopener">vue-loader</a></li>
      <li><a href="https://github.com/vuejs/awesome-vue" target="_blank" rel="noopener">awesome-vue</a></li>
    </ul>
  </div>
</template>

<script>
export default {
  name: 'HelloWorld',
  props: {
    msg: String
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
h3 {
  margin: 40px 0 0;
}
ul {
  list-style-type: none;
  padding: 0;
}
li {
  display: inline-block;
  margin: 0 10px;
}
a {
  color: #42b983;
}
</style>
```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/tools_and_testing/client-side_javascript_frameworks/vue_getting_started`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Vue_getting_started
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/vue_getting_started/index.md
* Last commit: https://github.com/mdn/content/commit/51f2cde58fff4a44242577b2540bdfdfc525dda4
* Document last modified: 2022-08-13T04:30:09.000Z

</details>

**Comment by Josh-Cena** [comment] 2022-08-29 04:20
Duplicate of https://github.com/mdn/content/issues/16843

**Comment by Josh-Cena** [comment] 2022-08-29 04:20
It's really unfortunate that all these starter templates (CVA, CRA, etc.) decide to show ESLint errors in build steps. It only confuses beginners. There's nothing preventing your code from actually working.

**Closed by Josh-Cena** 2022-08-29 04:20 UTC
Labels: needs-triage, Content:Learn:Client-side
