### ISSUE TITLE
Issue with "JavaScript basics": <script src="scripts/main.js"></script> did not work as described

### ISSUE THREAD

**Issue by timneill99** [mdn/content#10867] opened 2021-11-29 15:38 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/JavaScript_basics

#### What information was incorrect, unhelpful, or incomplete?
The js example 
     const myHeading = document.querySelector('h1');
     myHeading.textContent = 'Hello world!';

failed to change the element h1

I had to add charset attribute charset to <script> operator.

so
    <script src="scripts/main.js"></script>

changed to 

     <script src="scripts/main.js" charset="utf-8"></script>
    
This was using FireFox 78.15.0esr (64-bit)

#### Specific section or headline?

A Hello world! example

#### What did you expect to see?

Content of h1 changing to Hello World!

#### Did you test this? If so, how?

Moving the original 

   <script src="scripts/main.js"></script>

to different places in html document made it crash at the position of this operation.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/getting_started_with_the_web/javascript_basics`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/JavaScript_basics
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/getting_started_with_the_web/javascript_basics/index.md
* Last commit: https://github.com/mdn/content/commit/07453ac2b659a397b0fee921fa71db5488e9ca62
* Document last modified: 2021-10-08T14:43:33.000Z

</details>

**Comment by sideshowbarker** [comment] 2021-12-09 05:10
I can’t reproduce this. Adding the `charset="utf-8"` attribute isn’t necessary — utf-8 is the default encoding anyway.

**Comment by wbamberg** [comment] 2022-01-12 01:06
I couldn't reproduce this either, closing.

**Closed by wbamberg** 2022-01-12 01:06 UTC
Labels: Content:Learn, needs info
