### ISSUE TITLE
navigator.doNotTrack needs to say what people should use instead

### ISSUE THREAD

**Issue by Pomax** [mdn/content#26232] opened 2023-04-15 18:55 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/doNotTrack

### What specific section or headline is this issue about?

the deprecation box

### What information was incorrect, unhelpful, or incomplete?

There is a huge box that basically uses 75 words to say "don't use this anymore" without actually saying what _should_ be used.

### What did you expect to see?

A big box going "don't use this, it's no longer supported, use (link to modern equivalent) instead".

### Do you have any supporting links, references, or citations?

No idea, that's why I came to MDN in the first place.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/navigator/donottrack`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/doNotTrack
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/navigator/donottrack/index.md
* Last commit: https://github.com/mdn/content/commit/ef75c1741b450c2331204be5563ee964ad5f4c48
* Document last modified: 2023-04-07T06:16:45.000Z

</details>

**Comment by Josh-Cena** [comment] 2023-04-15 19:06
Duplicate of https://github.com/mdn/content/issues/12912

**Closed by Josh-Cena** 2023-04-15 19:07 UTC
Labels: Content:WebAPI, needs triage
