### ISSUE TITLE
Issue with ":host-context()": link to example does not demonstrate usage

### ISSUE THREAD

**Issue by WebMechanic** [mdn/content#11621] opened 2021-12-31 12:10 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:host-context

#### What information was incorrect, unhelpful, or incomplete?
The example to demonstrate the usage of the `:host-context()` pseudo class selector is identical to that of `:host()` and does not contain (and depict) any of the CSS features described on the page.

#### Specific section or headline?
Examples

Link given on the page as the `:host-context()` example:
- https://github.com/mdn/web-components-examples/tree/master/host-selectors

#### What did you expect to see?
A dedicated example that demonstrates the usage of :host-context() pseudo class.

#### Did you test this? If so, how?
The whole "Example" section appears to be an unedited exact copy of the [example for `:host()`](https://developer.mozilla.org/en-US/docs/Web/CSS/:host()).

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/_colon_host-context()`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:host-context()
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/_colon_host-context()/index.md
* Last commit: https://github.com/mdn/content/commit/26f50bdaeb1228f458d21dbdf7dc110387b20daa
* Document last modified: 2021-08-12T23:59:09.000Z

</details>

**Comment by Josh-Cena** [comment] 2023-07-15 06:38
Hi, I'm unsure what the issue is asking (which is why no one is contributing). That single example in `host-selectors` demonstrates `:host`, `:host()`, and `:host-context()`. I'll close this issue because it's also more than 1.5 years old, but feel free to comment if I missed anything.

**Closed by Josh-Cena** 2023-07-15 06:38 UTC
Labels: help wanted, Content:CSS, effort: medium

**Comment by WebMechanic** [comment] 2023-07-17 08:51
I frankly don't recall, just that the content was "confusing" with all this "host" and "context" jargon 😇 

The live example doesn't seem to work, i.e. there is no italic text anywhere to be seen nor does generated `content` show up. If it's supposed to teach how to use these pseudos and their difference: it doesn't - or I'm looking for the wrong things... I was only able to "hack" the appearance of the custom component itself.

https://mdn.github.io/web-components-examples/host-selectors/

Thanks.

**Comment by Josh-Cena** [comment] 2023-07-17 09:00
<img width="769" alt="image" src="https://github.com/mdn/content/assets/55398995/5a48593f-80f1-49e7-88b9-15ab4e630b50">

—This is italic, because the component is within an `h1`.

I'm not sure what you mean by "generated content show up". The text content of the custom component is rendered, and the style is present:

<img width="447" alt="image" src="https://github.com/mdn/content/assets/55398995/7d6a5f2e-c245-488f-bbbe-90229197e89d">

**Comment by WebMechanic** [comment] 2023-07-17 11:44
It's the `no links in headers` that I referred to. 
I saw the styles in the shadow DOM, but this is what I get w/o the italic and w/o the `content`:

![image](https://github.com/mdn/content/assets/638340/69c411a6-e457-4e32-b8ca-4bac0d6845b0)

I use FF Dev 116.0b5 and none of this is visible. Only changes to the `span` selector would render.
🤷‍♂️
