### ISSUE TITLE
Possible typo in example, use of "const" keyword instead of "var"

### ISSUE THREAD

**Issue by Junaid-1993** [mdn/content#22471] opened 2022-11-22 06:28 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Missing_semicolon_before_statement

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Missing_semicolon_before_statement#declaring_properties_with_var

### What information was incorrect, unhelpful, or incomplete?

Declaring properties with ### var
You cannot declare properties of an object or array with a ### var declaration.

`
const obj = {};
const obj.foo = 'hi'; // SyntaxError missing ; before statement

const array = [];
const array[0] = 'there'; // SyntaxError missing ; before statement

`
Instead, omit the ### var keyword:

`const obj = {};
obj.foo = 'hi';

const array = [];
array[0] = 'there';`

### What did you expect to see?

This section is saying that we cannot declare properties with ### var keyword. But there is no keyword var used in the example below it is using ### const in the below line as well. Also later it is saying to omit the ### var keyword: Again there is no var keyword used in the first example which is making confusing for me.

I think what the example meant is this:

`const obj = {};
 var obj.foo = 'hi'; // SyntaxError missing ; before statement

const array = [];
var array[0] = 'there'; // SyntaxError missing ; before statement
`

I hope this is clear enough thank you.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/errors/missing_semicolon_before_statement`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Missing_semicolon_before_statement
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/errors/missing_semicolon_before_statement/index.md
* Last commit: https://github.com/mdn/content/commit/968e6f1f3b6f977a09e116a0ac552459b741eac3
* Document last modified: 2022-09-09T05:25:05.000Z

</details>

**Comment by Josh-Cena** [comment] 2022-11-22 06:34
Duplicate of https://github.com/mdn/content/issues/18265

**Closed by Josh-Cena** 2022-11-22 06:34 UTC
Labels: Content:JS, needs-triage
