### ISSUE TITLE
Update the type attribute row in the Attribute List table

### ISSUE THREAD

**Issue by bencemeszaros** [mdn/content#36630] opened 2024-11-03 12:49 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes

### What specific section or headline is this issue about?

Outdated and/or incorrect and/or missing information

### What information was incorrect, unhelpful, or incomplete?

The Attribute List table on this page lists "style" and "menu" as having a type attribute. The type attribute is deprecated on the "style" element, while the type attribute is not officially defined for the "menu" element as it only supports global attributes. Also, the "a" element does have a type attribute, but this attribute doesn't define a built-in functionality, it is used as a hint only.

### What did you expect to see?

"a" should be added to the type attribute, "style" should be removed from the type attribute, "menu" should be removed from the type attribute

### Do you have any supporting links, references, or citations?

type attribute on "style": https://developer.mozilla.org/en-US/docs/Web/HTML/Element/style#type
"menu" only has global attributes: https://html.spec.whatwg.org/multipage/grouping-content.html#the-menu-element
type attribute on "a": https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#type

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/attributes`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/attributes/index.md
* Last commit: https://github.com/mdn/content/commit/5bd9fe2b25c6eee2a14d0406ce7116998fa48c13
* Document last modified: 2024-09-25T13:57:00.000Z

</details>

**Comment by Josh-Cena** [comment] 2024-11-06 17:32
Hi, this whole page is under consideration for rewrite, in which case the table will probably be gone. There are a lot of stuff missing, outdated, and incomplete about these entries. I'm going to close this as a duplicate of https://github.com/mdn/content/issues/32229 / https://github.com/orgs/mdn/discussions/688.

**Closed by Josh-Cena** 2024-11-06 17:32 UTC
Labels: Content:HTML, needs triage
