### ISSUE TITLE
Problem with "Test your skills: HTML text basics"

### ISSUE THREAD

**Issue by atxdev7605** [mdn/content#24283] opened 2023-02-08 20:28 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Test_your_skills:_HTML_text_basics

### What specific section or headline is this issue about?

This is about each of the three tasks.

### What information was incorrect, unhelpful, or incomplete?

In each example they want you to update the live code to recreate the finished example.

### What did you expect to see?

The finished example(s), but I never saw them. I could only imagine what the finished examples looked like. This was easy for Task 2, but not as easy for Tasks 1 and 3

### Do you have anything more you want to share?

Perhaps, you can already tell, but in case not: I was running this in Safari (ver. 16.2).

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/html/introduction_to_html/test_your_skills_colon__html_text_basics`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Test_your_skills:_HTML_text_basics
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/introduction_to_html/test_your_skills_colon__html_text_basics/index.md
* Last commit: https://github.com/mdn/content/commit/4f6ba2f5a1615fe155292cac416c7ab6b9d711ec
* Document last modified: 2022-09-11T17:33:19.000Z

</details>

**Comment by Josh-Cena** [comment] 2023-02-08 20:40
Duplicate of #21944

**Closed by Josh-Cena** 2023-02-08 20:40 UTC
Labels: needs triage, Content:Learn:HTML
