### ISSUE TITLE
Mongoose model methods now return promises

### ISSUE THREAD

**Issue by Neil-Carruthers** [mdn/content#25071] opened 2023-03-05 02:23 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose

### What specific section or headline is this issue about?

populatedb.js

### What information was incorrect, unhelpful, or incomplete?

Please be advised that Mongoose no longer accepts callbacks for many of the model methods.

Calling save in this way is no longer accurate and will throw an error:
```
bookinstance.save(function (err) {
    if (err) {
      console.log('ERROR CREATING BookInstance: ' + bookinstance);
      cb(err, null)
      return
    }
    console.log('New BookInstance: ' + bookinstance);
    bookinstances.push(bookinstance)
    cb(null, book)
  }  );
```

### What did you expect to see?

I expected the contents of https://raw.githubusercontent.com/mdn/express-locallibrary-tutorial/main/populatedb.js to work

### Do you have any supporting links, references, or citations?

https://mongoosejs.com/docs/migrating_to_7.html#dropped-callback-support

### Do you have anything more you want to share?

The aforementioned code block should be replaced with:
```
try {
    const result = await bookinstance.save();
    console.log("New Book: " + result);
    bookinstances.push(result);
    cb(null, result);
  } catch (err) {
    cb(err, null);
  }
```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/mongoose`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/mongoose/index.md
* Last commit: https://github.com/mdn/content/commit/4def230f85756724b59660e3cd9de363db724ef8
* Document last modified: 2023-02-24T00:05:28.000Z

</details>

**Comment by Neil-Carruthers** [comment] 2023-03-05 02:33
This tutorial does specify Mongoose 6.9 [here](https://raw.githubusercontent.com/mdn/express-locallibrary-tutorial/main/package.json)  but I think it might be worth placing a note somewhere in the tutorial to warn readers about the breaking change, maybe somewhere around [here](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose#install_mongoose)

**Comment by Josh-Cena** [comment] 2023-03-05 03:17
Duplicate of https://github.com/mdn/content/issues/24972

**Closed by Josh-Cena** 2023-03-05 03:17 UTC
Labels: needs triage
