### ISSUE TITLE
Issue with "Finishing up": (When you add `requestAnimationFrame(draw)` the mouse no longer controls the paddles)

### ISSUE THREAD

**Issue by JerryGarcia** [mdn/content#5740] opened 2021-06-06 23:33 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Games/Tutorials/2D_Breakout_game_pure_JavaScript/Finishing_up

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/games/tutorials/2d_breakout_game_pure_javascript/finishing_up`
* MDN URL: https://developer.mozilla.org/en-US/docs/Games/Tutorials/2D_Breakout_game_pure_JavaScript/Finishing_up
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/games/tutorials/2d_breakout_game_pure_javascript/finishing_up/index.html
* Last commit: https://github.com/mdn/content/commit/c7d9128559ed9526914c9be5bb461445fde5866a
* Document last modified: 2021-02-19T20:09:33.000Z

</details>

**Comment by bsmth** [comment] 2022-10-20 15:46
Hi @JerryGarcia thanks a lot for raising this one. I can't reproduce your issue, however - the examples work as expected and are reflected in [the accompanying JSFiddle](https://jsfiddle.net/raymondjplante/dfh2tpu1/).

I'm going to close this one for now as fixed, but if you think this is a mistake, feel free to comment. Thank you! :)

**Closed by bsmth** 2022-10-20 15:46 UTC
Labels: Content:Games, 🐌 idle
