### ISSUE TITLE
Issue with "String.prototype.replace()": …

### ISSUE THREAD

**Issue by keul** [mdn/content#1854] opened 2021-01-28 14:57 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace

#### What information was incorrect, unhelpful, or incomplete?

Internal link to "Specifying a function as a parameter"

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#parameters

#### What did you expect to see?

Clicking on

> The arguments supplied to this function are described in the &lt;a&gt;Specifying a function as a parameter&lt;/a&gt; section below.

Should move users to…

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#specifying_a_string_as_a_parameter

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/string/replace`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/global_objects/string/replace/index.html
* Last commit: https://github.com/mdn/content/commit/934549cd98cbb101f36a09d6833773037221b9ab
* Document last modified: 2021-01-27T15:36:01.000Z

</details>

**Comment by kauer3** [comment] 2021-01-30 13:18
Hello, I would like to take this as my first issue.

**Comment by Ryuno-Ki** [comment] 2021-01-30 13:22
Sounds great, @kauer3.
I've assigned it to you.

The lines in question are

https://github.com/mdn/content/blob/d54141e8f5fac3effe8ed12fcde9369617e655ba/files/en-us/web/javascript/reference/global_objects/string/replace/index.html#L46

and

https://github.com/mdn/content/blob/d54141e8f5fac3effe8ed12fcde9369617e655ba/files/en-us/web/javascript/reference/global_objects/string/replace/index.html#L68

I guess.

**Comment by kauer3** [comment] 2021-01-30 14:32
So, inspecting the [page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#parameters) I can see that both "Specifying a function as a parameter" and "Specifying a string as a parameter" internal links have typos, but [the file on GitHub](https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/global_objects/string/replace/index.html) is a bit different and does not contain the typos. How should I proceed?

**Comment by Ryuno-Ki** [comment] 2021-01-30 14:47
Hm, okay.

Are you familiar with Node.js and/or git?
If so, you could set up a local environment:
https://github.com/mdn/content#more-substantial-changes
and test the changes there.

If not I can check it out for you.

The idea is to be able to make changes locally (= on your machine) and check whether it fixes the problem. If you need help, let us know.

**Comment by kauer3** [comment] 2021-01-30 15:05
With git, yes.
I'll check if it works!

**Comment by kauer3** [comment] 2021-01-30 19:46
The links are working fine, there was no need to change anything.

**Comment by Ryuno-Ki** [comment] 2021-01-30 20:34
Hm. As far as I know, at build time, the ID get's lowercased.
Could you submit a PR with both (id and href) using a lowercased version?
It can take up to 48h after a PR gets merged to show up on production.

**Comment by kauer3** [comment] 2021-01-30 20:53
Ok, so I'll do that to every id and href on this page, not just those mentioned earlier, because all of them are uppercased.

**Comment by Ryuno-Ki** [comment] 2021-01-30 20:55
Yes, please! Looking forward to your PR :-)
(I'm going to be offline for the rest of the day)

**Comment by kauer3** [comment] 2021-01-30 21:39
#1906

**Comment by peterbe** [comment] 2021-02-01 17:55
Oh no. It's either a regression or it's a matter of some code that hasn't landed yet :(

But if the raw HTML is this:
```html
<a href="#Specifying_a_function_as_a_parameter">Specifying a function as a parameter</a>
```

it *should* become...

```html
<a href="#specifying_a_function_as_a_parameter">Specifying a function as a parameter</a>
```

...when it gets rendered out. 
I'll take care of looking into this on the Yari side.

**Comment by Ryuno-Ki** [comment] 2021-02-01 18:01
Thanks for tracking this, @peterbe

**Comment by peterbe** [comment] 2021-02-01 18:26
I'm going to make https://github.com/mdn/yari/issues/2763 a priority. What's happening is that the anchor links only get "corrected" in build-time if you have flaw detection enabled. Something we don't have when we run the prod builds.

**Comment by peterbe** [comment] 2021-02-03 21:33
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace now works. Yay! If, at the time of writing/reading this, you still see the old behavior, mess with the casing of the URL pathname so the CDN serves you a "cold" hit rather than something from our 24h caching.

**Closed by peterbe** 2021-02-03 21:33 UTC
Labels: 10 minute task, Content:JS
