### ISSUE TITLE
Issue with "Basic usage of canvas": (short summary here please)

### ISSUE THREAD

**Issue by bjkeefe** [mdn/content#10331] opened 2021-11-06 13:50 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Basic_usage

#### What information was incorrect, unhelpful, or incomplete?

Obsolescent markup:
<script type="text/javascript">
<style type="text/css">

#### Specific section or headline?

Two instances:
A skeleton template
A simple example

https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Basic_usage#a_skeleton_template
https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Basic_usage#a_simple_example

#### What did you expect to see?

Saw what I expected

#### Did you test this? If so, how?

Ran my file (straight copy of code on tutorial page) through the The W3C Markup Validation Service
https://validator.w3.org/#validate_by_upload

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/canvas_api/tutorial/basic_usage`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Basic_usage
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/canvas_api/tutorial/basic_usage/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by Rumyra** [comment] 2021-11-08 15:16
Hi @bjkeefe thanks for submitting the issue.

Can you explain what errors you found please - thank you!

**Comment by Rumyra** [comment] 2021-11-09 17:35
Thanks for clarifying @bjkeefe - I closed the other issue as it seemed like a duplicate of this one - apologies if it wasn't.

This one will remain open as I think it'd be good to take a closer look at these examples 👍

**Comment by bjkeefe** [comment] 2021-11-09 18:50
@Rumyra I guess I must have goofed during the original report and inadvertently submitted twice.  Sorry for my n00byness.  Thanks for letting me know about why the other was closed.

**Closed** 2021-11-18 14:37 UTC
Labels: Content:WebAPI, needs-triage
