### ISSUE TITLE
:root interactive example not found

### ISSUE THREAD

**Issue by MagnusMarx** [mdn/content#23256] opened 2022-12-29 08:22 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/:root

### What specific section or headline is this issue about?

try it demo isn't working

### What information was incorrect, unhelpful, or incomplete?

404 not found

### What did you expect to see?

an example

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/_colon_root`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:root
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/_colon_root/index.md
* Last commit: https://github.com/mdn/content/commit/818c49d581a7f6d7b0ffa2aeb1ad5f6fe34f0067
* Document last modified: 2022-12-19T10:05:19.000Z

</details>

**Comment by wbamberg** [comment] 2022-12-29 16:40
Thanks for filing!

This is a duplicate of https://github.com/mdn/content/issues/23083, and I filed a fix at https://github.com/mdn/content/pull/23260.

**Closed** 2022-12-29 22:08 UTC
Labels: Content:CSS, needs triage
