### ISSUE TITLE
Issue with "Select an element": (the videos are not available)

### ISSUE THREAD

**Issue by neobitte** [mdn/content#10541] opened 2021-11-15 10:42 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Select_an_element

#### What information was incorrect, unhelpful, or incomplete?
The three videos on this page are not available.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/page_inspector/how_to/select_an_element`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Select_an_element
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/page_inspector/how_to/select_an_element/index.html
* Last commit: https://github.com/mdn/content/commit/05b71a290b2ab444b23e0f35f619d93203c7e2d8
* Document last modified: 2021-02-02T16:31:29.000Z

</details>

**Comment by wbamberg** [comment] 2021-11-15 18:40
Thanks. for filing! This is a duplicate of https://github.com/mdn/content/issues/7457.

**Closed by wbamberg** 2021-11-15 18:40 UTC
