### ISSUE TITLE
onscroll performance optimization

### ISSUE THREAD

**Issue by Britnell** [mdn/content#18843] opened 2022-07-27 08:44 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Document/scroll_event

### What specific section or headline is this issue about?

"the optimization below is often unnecessary"

### What information was incorrect, unhelpful, or incomplete?

I think giving the example while saying it is often unnecessary is confusing, there should be a  little more information on when and why it is necessary, or give a different example. There are many different opinions on this around the internet and no clear resources / answer, so I was hoping for a better / clearer answer from MDN. Or a link to further resources?

E.g. [the top answer in this thread](https://stackoverflow.com/questions/41740082/scroll-events-requestanimationframe-vs-requestidlecallback-vs-passive-event-lis) suggests that onscroll and AF are synced and it will never fire? and suggests "_However the scroll event is triggered every time the browser renders a scroll position change._" - you simply state they "_fire at about the same rate_" - can you give any more precise information?

in my own tests i actually found that onscroll events never fire more often than RAF ( in firefox they actually fire 1 to 1) so wouldnt it be better to leave scroll logic in a passive onscroll event? 
and if we use raf for optimisation, couldnt the logic be entirely moved to raf loop - isnt that already enough "debouncing"? the example you give confused  me as I'm not sure what it demonstrates and in which cases it should be used. 

Sorry if my question / problem is not super clear - but im basically saying this is a tricky topic and some more / clearer info on MDN docs you be fantastic, and what I hoped for as usually MDN are the go-to resource.

Thanks for all the great work,

Thomas Britnell

### What did you expect to see?

more explanation on when this is necessary or not. 
couldnt scroll logic be completely moved to raf? (when it is animating something) 
what should / could be done in onScroll event then?

### Do you have any supporting links, references, or citations?

see these topics on stackoverflow - they are obviously of interest and unclear to people 
https://stackoverflow.com/questions/41740082/scroll-events-requestanimationframe-vs-requestidlecallback-vs-passive-event-lis

also
https://stackoverflow.com/questions/51329892/javascript-onscroll-performance-comparison

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/document/scroll_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/scroll_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/document/scroll_event/index.md
* Last commit: https://github.com/mdn/content/commit/ddf7070d8b148756fef2e84ed395c3613bc33233
* Document last modified: 2022-07-14T13:27:06.000Z

</details>

**Comment by Josh-Cena** [comment] 2022-12-23 16:43
Duplicate of https://github.com/mdn/content/issues/12701

**Comment by Josh-Cena** [comment] 2022-12-23 16:44
Indeed, the example looks like an anti-pattern, and the two paragraphs almost directly contradict each other.

**Closed by Josh-Cena** 2022-12-23 16:44 UTC
Labels: help wanted, Content:WebAPI
