### ISSUE TITLE
Issue with "object-fit": (div element is missed in the HTML)

### ISSUE THREAD

**Issue by MenaiAla** [mdn/content#3598] opened 2021-03-28 12:02 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit

#### What information was incorrect, unhelpful, or incomplete?

In the CSS file there's a <code>div</code> element while it missed in the HTML file.

#### Specific section or headline?

Example -> HTML file

#### What did you expect to see?

`div` at the top of the `section` element.

 Or changing the `div` to `section` in CSS file.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/object-fit`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/object-fit/index.html
* Last commit: https://github.com/mdn/content/commit/f4fb4c2d90a134366c280eec6cb599825981ad5d
* Document last modified: 2021-03-15T17:55:56.000Z

</details>

**Comment by rachelandrew** [comment] 2021-03-28 14:23
Closing as this is a duplicate of #3499

**Closed by rachelandrew** 2021-03-28 14:23 UTC
Labels: Content:CSS, needs-triage
