### ISSUE TITLE
Issue with "icons": …

### ISSUE THREAD

**Issue by robMolloy** [mdn/content#1346] opened 2021-01-15 10:12 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/icons

#### What information was incorrect, unhelpful, or incomplete?
"icons": {
  "48": "icon.svg",
  "96": "icon.svg"
}

Gives the following error in chromium;

"Manifest: property 'icons' ignored, type array expected."

Example that does not give error;

"icons": [
    {
      "src": "favicon.ico",
      "sizes": "64x64 32x32 24x24 16x16",
      "type": "image/x-icon"
    },
    {
      "src": "logo192.png",
      "type": "image/png",
      "sizes": "192x192",
      "purpose": "any maskable"
    },
    {
      "src": "logo512.png",
      "type": "image/png",
      "sizes": "512x512"
    }
  ]

Hope this helps

**Comment by chrisdavidmills** [comment] 2021-01-15 10:36
Do you fancy having a look at this one, @rpl ?

**Comment by rpl** [comment] 2021-01-15 15:02
> Do you fancy having a look at this one, @rpl ?

sure, I'm on it.

**Comment by rpl** [comment] 2021-01-15 15:12
@robMolloy did you got the error you reported in the issue description with an extension manifest or a webapp manifest? I think that is the format for a web app manifest.json and not for the extensions, see the additional details below.

The doc page you linked in the issue description ( https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/icons) is related to the manifest.json file for a WebExtension, that icons property is expected to be an object and not an array (as also confirmed by the [the jsonschema of the icons property in Firefox sources](https://searchfox.org/mozilla-central/rev/03224522336f60a1a61a87e1fcd4feb0a0315a9b/toolkit/components/extensions/schemas/manifest.json#100-105)).

Based on the docs related to the Chrome extensions, the same format is also used for the extensions on Chrome:

- https://developer.chrome.com/docs/extensions/mv2/manifest/icons/ (and it doesn't seem to be different in the docs for the upcoming manifest v3: https://developer.chrome.com/docs/extensions/mv3/manifest/icons/)

On the contrary, the MDN docs for the `icons` property in a **web app manifest.json** file (which does have the same name but it is used for a different purpose and it does have a different format) seems to be already documented to have the format you mention in the issue description:

- https://developer.mozilla.org/en-US/docs/Web/Manifest/icons

For the above reasons I'm closing this issue as invalid, nevertheless feel free to reopen it and mention me in a new comment if I'm misread your issue report.

**Closed** 2021-01-15 15:12 UTC
Labels: 30 minute task, Content:WebExt, invalid

**Comment by robMolloy** [comment] 2021-01-15 19:31
Hi, thanks a lot, I was a bit out of my depth there and that looks correct to me. Sorry for wasting your time!
