### ISSUE TITLE
Issue with "Window.devicePixelRatio": Code example does not match the relavent description perfectly.

### ISSUE THREAD

**Issue by krave1986** [mdn/content#873] opened 2021-01-03 10:45 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio#Monitoring_screen_resolution_or_zoom_level_changes

#### What information was incorrect, unhelpful, or incomplete?
The doc states that `The JavaScript code creates the media query that monitors the device resolution and checks the value of devicePixelRatio **any time** it changes.` which is not true.
Because the media query only set once at the initial time with the initial window.devicePixelRatio which may likely be 1 or 2. If you zoom up or down succesive twice, it will not detect the 2nd time.

#### Specific section or headline?
Monitoring screen resolution or zoom level changes

#### What did you expect to see?
Code example which actually do what the doc demonstrates.

#### Did you test this? If so, how?
Yes, copy code from MDN and zoom up twice.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/window/devicepixelratio`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/api/window/devicepixelratio/index.html
* Report started: 2021-01-03T09:20:26.332Z

</details>

**Comment by chrisdavidmills** [comment] 2021-01-04 10:33
The example does seem to work more than once, but it is broken and in need of improvement. I'm pretty sure it uses outdated syntax, plus it shows 90%/0.9 when you zoom out once, and 110%/1.1 when you zoom in once, but it doesn't change beyond that with further zooming. So it needs looking at certainly.

**Comment by himanshugarg** [comment] 2023-01-14 04:56
The example does seem to work as described on FF and Chrome. Is there more to it than that:
![Recording 2023-01-14 at 10 22 51](https://user-images.githubusercontent.com/2392803/212456620-f49d6cbf-41a8-4259-b8d4-40d4763e4bb5.gif)
![Recording 2023-01-14 at 10 25 12](https://user-images.githubusercontent.com/2392803/212456622-6043ebd5-91d3-482e-b1d4-fd8c22579da1.gif)

**Comment by Josh-Cena** [comment] 2023-01-14 05:52
Duplicate of #4478 and fixed by #22769

**Closed** 2023-01-14 05:53 UTC
Labels: Content:WebAPI, effort: medium
