### ISSUE TITLE
Dark mode feature

### ISSUE THREAD

**Issue by diamant3** [mdn/content#10714] opened 2021-11-23 05:18 UTC
I request this feature to helps learners/developers reading or studying at night or in dark environments.

Benefits:

* enhances visual ergonomics by reducing eye strain.
* increase the battery life on your device.

[Source](https://www.healthline.com/health/is-dark-mode-better-for-your-eyes#benefits-of-dark-mode)

**Comment by wbamberg** [comment] 2021-11-23 05:20
Duplicate of https://github.com/mdn/yari/discussions/2539 (along with many others).

**Closed by wbamberg** 2021-11-23 05:20 UTC
