### ISSUE TITLE
scrollbar is not visible when there is no need for scrolling but tutorial says otherwise

### ISSUE THREAD

**Issue by gampu** [mdn/content#22722] opened 2022-12-04 20:23 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Overflowing_content

### What specific section or headline is this issue about?

The overflow property

### What information was incorrect, unhelpful, or incomplete?

Remove some content from the box below. Notice how the scrollbars remain, even if there is no need for scrolling.

### What did you expect to see?

Remove some content from the box below. Notice how the scrollbar disappears when there is no need for scrolling.

### Do you have anything more you want to share?

https://plnkr.co/edit/GJqehWGctEcOW0PJ: With `overflow: scroll`, scrollbar is visible only when it is needed, i.e., only when the content overflows. However, the tutorial says otherwise.

We need community confirmation on this.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/building_blocks/overflowing_content`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Overflowing_content
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/overflowing_content/index.md
* Last commit: https://github.com/mdn/content/commit/dd52f7e4915810060d525ce62a870dcf1ae17a63
* Document last modified: 2022-11-30T07:34:47.000Z

</details>

**Comment by bsmth** [comment] 2022-12-12 10:36
Thanks for opening the issue @gampu. I can confirm that the scrollbars are not shown when there is no need for scrolling on the example you are pointing to. Additionally, I had a look at https://developer.mozilla.org/en-US/docs/Web/CSS/overflow#values which shows:

>**Scroll:** Content is clipped if necessary to fit the padding box. Browsers always display scrollbars whether or not any content is actually clipped, preventing scrollbars from appearing or disappearing as content changes. Printers may still print overflowing content.

Looks like it needs some more investigation if specs have changed since or which browsers observe this. I tested on Firefox nightly `109.0a1 (2022-11-26)`

**Comment by bsmth** [comment] 2022-12-12 10:44
Sorry, my mistake, the section you are pointing to is demonstrating `overflow: auto`:

> If you only want scrollbars to appear when there is more content than can fit in the box, use `overflow: auto`. This allows the browser to determine if it should display scrollbars.

If you change this property to `overflow: scroll`, the scrollbars will remain with non-overflowing content, but they are not scrollable:

![image](https://user-images.githubusercontent.com/43580235/207025434-58d14f06-8e85-4c79-a9dd-efe57993c350.png)

I am going to close this one, let me know if I've answered your question or if you need more details.

Thank you :)

**Closed by bsmth** 2022-12-12 10:44 UTC
Labels: help wanted, Content:Learn:CSS
