### ISSUE TITLE
Make use of DownloadURL drag type instead of mozSetDataAt() in Recommended Drag Types page

### ISSUE THREAD

**Issue by GHolk** [mdn/content#21619] opened 2022-10-18 06:04 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API/Recommended_drag_types

### What specific section or headline is this issue about?

Dragging Files, Dragging Images and Dragging files to an operating system folder

### What information was incorrect, unhelpful, or incomplete?

The `dataTrnasfer.mozSetDataAt()` method is deprecated, but the page still make use of it.
Some code even use the `nsIFile` class; Is it still supported?
Chromium use the `DownloadURL` type to allowed to drag file to system folder, and there is a bugzilla issue about it.

### What did you expect to see?

Are there other ways to drag file out from firefox?
and can you mention DownloadURL data type?

### Do you have any supporting links, references, or citations?

- DownloadURL issue on bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=570164
- Use DownloadURL to drag file (the new html5rock): https://web.dev/box-dnd-download/

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/html_drag_and_drop_api/recommended_drag_types`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API/Recommended_drag_types
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/html_drag_and_drop_api/recommended_drag_types/index.md
* Last commit: https://github.com/mdn/content/commit/a122e87245c624ba56197641b4d7b21b643a6021
* Document last modified: 2022-09-14T06:08:23.000Z

</details>

**Comment by Josh-Cena** [comment] 2023-01-09 08:32
Let's call it a duplicate of https://github.com/mdn/content/issues/8404

**Closed by Josh-Cena** 2023-01-09 08:32 UTC
Labels: help wanted, Content:WebAPI, effort: medium
