### ISSUE TITLE
Issue with "Game over": (short summary here please)

### ISSUE THREAD

**Issue by Lolacat101** [mdn/content#7632] opened 2021-08-05 21:49 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Games/Tutorials/2D_Breakout_game_pure_JavaScript/Game_over

#### What information was incorrect, unhelpful, or incomplete?
There was no example of the code that was correct at the end of the article. Usually, I see the correct code at the end of the article, but there's nothing there.

#### Specific section or headline?
"Compare your code"

#### What did you expect to see?

I expected to see the example code, in javascript, HTML, and css. It was just blank under the subheading. 
#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/games/tutorials/2d_breakout_game_pure_javascript/game_over`
* MDN URL: https://developer.mozilla.org/en-US/docs/Games/Tutorials/2D_Breakout_game_pure_JavaScript/Game_over
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/games/tutorials/2d_breakout_game_pure_javascript/game_over/index.html
* Last commit: https://github.com/mdn/content/commit/c7d9128559ed9526914c9be5bb461445fde5866a
* Document last modified: 2021-02-19T20:09:33.000Z

</details>

**Comment by sideshowbarker** [comment] 2021-08-06 03:40
Thanks for raising this

@NegiAkash890 This seems to be the same problem as https://github.com/mdn/content/issues/7571, though in a different article.

Have you isolated the root cause and are you working on a patch with a fix?

**Comment by sideshowbarker** [comment] 2021-08-06 09:34
OK, I’ve opened https://github.com/mdn/yari/pull/4428 with a fix for this

**Closed** 2021-08-06 14:42 UTC
Labels: Content:Learn
