### ISSUE TITLE
Hi. vector-effect="non-scaling-size" doesn't work to <rect>.

### ISSUE THREAD

**Issue by AlexandUlyanov** [mdn/content#4955] opened 2021-05-12 21:15 UTC
`<svg xmlns="http://www.w3.org/2000/svg" stroke-width="8" fill="none" viewBox="0 0 312 48" preserveAspectRatio="none" onclick="(document.fullscreenElement)?document.exitFullscreen():this.requestFullscreen()"><rect width="8" height="8" fill="red" vector-effect="non-scaling-size"/></svg>`

**Comment by wbamberg** [comment] 2021-05-13 03:37
Hi @AlexandUlyanov ! Is this a bug report against the content at developer.mozilla.org? If so, please let us know which page has the problem, and what the problem is.

**Comment by AlexandUlyanov** [comment] 2021-05-13 09:36
Hi @Wbamberg ! This page says: As a presentation attribute, it can be applied to any element but it has effect only on the following ten elements: ... <rect> ... But this is not the case. This attribute does not work for the <rect> tag. Maybe you made a mistake in including the <rect> in this list? I sent you a code **↑** to make it easier for you to check this.

**Comment by Rumyra** [comment] 2021-05-19 14:53
Thanks @AlexandUlyanov can you provide a url to the page this is present on? Thanks!

**Comment by sideshowbarker** [comment] 2021-06-09 06:59
@AlexandUlyanov thanks for reporting this.

So this is about https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/vector-effect.

As far as what the spec says, https://svgwg.org/svg2-draft/coords.html#VectorEffectProperty says:

> Applies to: | graphics elements and ‘use’

…where _graphics elements_ is a link to https://svgwg.org/svg2-draft/struct.html#TermGraphicsElement, which says:

> **graphics element**
>
> One of the element types that can cause graphics to be drawn onto the target canvas. Specifically: ‘circle’, ‘ellipse’, ‘foreignObject’, ‘image’, ‘line’, ‘path’, ‘polygon’, ‘polyline’, ‘rect’, ‘text’, ‘textPath’ and ‘tspan’.

Notice that `rect` is in fact included in that list in the spec.

So, what we have documented in MDN does actually match what the spec says.

And as far as `vector-effect="non-scaling-size"` not working with `rect` — the problem isn’t actually specific to `rect`; instead it’s that in Gecko at least, `vector-effect="non-scaling-size"` hasn’t yet been implemented at all, for any elements. See https://bugzilla.mozilla.org/show_bug.cgi?id=1318208.

And @AlexandUlyanov, I noticed that you posted a comment to that bug already — so I think what’s best is that you probably just want to keep following that bug and see if there’s any progress.

But as far as MDN goes, there’s no change we can properly make to the MDN content itself to document this — that’s because it’s about browser support for the feature, and the place where we track data for browser support is in the https://github.com/mdn/browser-compat-data repo.

So I’m going to go ahead and close this issue here — but feel free to still comment further here if there’s more clarification needed.

**Closed** 2021-06-09 07:00 UTC
Labels: Content:SVG, needs-triage
