### ISSUE TITLE
Browser storage llimits and eviction criteria page seems incorrect

### ISSUE THREAD

**Issue by captainbrosset** [mdn/content#23557] opened 2023-01-11 15:18 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Browser_storage_limits_and_eviction_criteria

### What information was incorrect, unhelpful, or incomplete?

I think this article has become a little bit outdated and is a lot more Firefox-specific than other pages.

* [x] [What technologies use browser data storage?](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Browser_storage_limits_and_eviction_criteria#what_technologies_use_browser_data_storage) starts with a Firefox-only list, and then adds a paragraph for Chrome and Opera. It seems like this could be restructured in a global list for all browsers. Or maybe a table.
* [x] [Different types of data storage](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Browser_storage_limits_and_eviction_criteria#different_types_of_data_storage): I think `temporary` is now known as `best-effort` according to the [spec](https://storage.spec.whatwg.org/#buckets) and according to [this other MDN article](https://developer.mozilla.org/en-US/docs/Web/API/Storage_API).
* [x] [Where is the data stored?](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Browser_storage_limits_and_eviction_criteria#where_is_the_data_stored): is very Firefox-specific (I guess other user-agents store data in different places), and I don't know whether this is super important for a web developer knowing that the data can usually be inspected via DevTools.
* [x] [Storage limits](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Browser_storage_limits_and_eviction_criteria#storage_limits): this section starts by talking about the 50% of the free disk space. I think this only for Firefox, and I don't think this is calculated based on the free space, but rather on the total disk space (for security reasons). It's 80% for Chromium browsers (and 60% per origin), which might need to be documented somewhere here too.
* [x] That section also talks about a group limit which states that a group (eTLD+1) is limited to 2GB of storage maximum. This feels odd if the entire browser can have 50% of the total disk space, why limit a group to 2GB max. Also, I tested quickly with [this demo app](https://storage-quota.glitch.me/) and this does not seem to be the case. I was able to go above the 2GB limit.
* [x] The section has a note about how the storage quota changed in Chrome with version 66 and links to a line in the source code. I don't think this is super friendly to readers. We should find a way to understand the rules in Chrome and document them in this article directly instead.
* [x] [LRU policy](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Browser_storage_limits_and_eviction_criteria#lru_policy) is likely Firefox-specific too. It's good information to have, but it should be clear to the reader which browser works this way. I think each browser has its own way of dealing with stale data.
* [x] [See also](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Browser_storage_limits_and_eviction_criteria#see_also): both links go to the same website. 
* [x] The page should not be nested under IDB since it applies to multiple web technologies.

### What did you expect to see?

This page is in need of a global update. It might have been written a while ago, and data storage in user agents changes often and is usually super complicated.

### Do you have any supporting links, references, or citations?

The most up to date resource on this topic is probably this web.dev article: https://web.dev/storage-for-the-web/

**Comment by asutherland** [comment] 2023-01-18 01:58
### Firefox Details

Chiming in as a member of the DOM: Lifecycle, Workers & Storage team.  For Firefox, in bug https://bugzilla.mozilla.org/show_bug.cgi?id=1735713 we changed limits such that:

- We no longer use free disk space as the basis for our storage limit, but instead use 50% of the disk size the profile lives on, capped at 8 TiB.  [The relevant code is here](https://searchfox.org/mozilla-central/rev/5bcbe6ae54ee5b152f6cef29dc5627ec7c0e1f1e/dom/quota/ActorsParent.cpp#2441-2474).
- The max group limit was upgraded to 10 GiB from 2 GiB.  If the limit is not hit, the group limit continues to be 20% of the storage limit calculated above, or 10% of the disk size. [The relevant code is here](https://searchfox.org/mozilla-central/rev/5bcbe6ae54ee5b152f6cef29dc5627ec7c0e1f1e/dom/quota/ActorsParent.cpp#6122-6133).  Note that we plan to remove the group limit as it exists as part of https://bugzilla.mozilla.org/show_bug.cgi?id=1305665.

Data clearing on storage pressure continues to be LRU-based although this may change in the future.

### Chrome Details

The Chrome stroage team maintains a very nice document [Chrome Web Storage and Quota Concepts](https://docs.google.com/document/d/19QemRTdIxYaJ4gkHYf2WWBNPbpuZQDNMpUVf8dQxj4U/edit?usp=sharing) which has lots of good information.  Note that there are 2 sections on "Quota Eviction", "Quota/Eviction" which is present and has nice diagrams and then "Clearing Browsing Data/Quota Eviction" which is just a link to a (at this time) non-public document (and I don't have access).

**Comment by anthonymcglone2022** [comment] 2023-02-01 16:59
@captainbrosset / @sideshowbarker could I take a look at this issue?

**Comment by captainbrosset** [comment] 2023-02-01 17:03
I'm certainly not opposed to it 😁

I did do a fair bit of research on this topic, which might be a helpful way to get started (on top of the web.dev article mentioned before, and all the links shared by Andrew): https://patrickbrosset.com/articles/2023-01-17-web-storage/

**Comment by sideshowbarker** [comment] 2023-02-02 03:30
@anthonymcglone2022 Thanks for the ping — I’ve gone ahead and had the system mark this as being assigned to you

**Comment by anthonymcglone2022** [comment] 2023-02-10 15:51
Apparently Safari (or WebKit) has implemented `StorageManager.estimate()` according to these [release notes](https://webkit.org/blog/13839/release-notes-for-safari-technology-preview-163/). A note here, to find out if the [StorageManager](https://developer.mozilla.org/en-US/docs/Web/API/StorageManager/estimate) Browser compatibilty needs to be updated.

**Comment by captainbrosset** [comment] 2023-02-10 15:56
That's awesome!

**Comment by captainbrosset** [comment] 2023-02-21 10:06
This page is currently located inside the IndexedDB reference docs, but is meant to be more generally about all types of browser storage.
So, I'm wondering if we should take the opportunity of this issue to move the page to a different place.

In fact, there is also this more general storage page: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Client-side_storage
Perhaps the way forward is to merge the quota and eviction page content inside this more general page.

Context: we are also refreshing the Progressive Web Apps docs on MDN at the moment, and storage is an important topic when it comes to PWAs. We'll definitely want to link to the storage docs from the PWA docs. Being able to link to a general location would make a lot more sense than linking to some page located inside the IndexedDB folder.

**Comment by asutherland** [comment] 2023-02-21 17:17
> This page is currently located inside the IndexedDB reference docs, but is meant to be more generally about all types of browser storage. So, I'm wondering if we should take the opportunity of this issue to move the page to a different place.

This seems appropriate/correct, yes.  There are historical reasons the page is under IndexedDB, but it has not been an appropriate location for a while.  Specifically, IndexedDB pre-dated the Gecko Quota Manager, which evolved out of IndexedDB.  Spec-wise, https://storage.spec.whatwg.org/ is decisively the home for all of this now.

**Comment by anthonymcglone2022** [comment] 2023-02-22 09:11
I'm unable to work on this due to a number of factors, so removing my assignment so someone else can look into it. Apologies.

**Comment by captainbrosset** [comment] 2023-02-28 14:50
> Apparently Safari (or WebKit) has implemented `StorageManager.estimate()` according to these [release notes](https://webkit.org/blog/13839/release-notes-for-safari-technology-preview-163/). A note here, to find out if the [StorageManager](https://developer.mozilla.org/en-US/docs/Web/API/StorageManager/estimate) Browser compatibilty needs to be updated.

I filed this BCD issue to update it: https://github.com/mdn/browser-compat-data/issues/19032

> I'm unable to work on this so removing my assignment.

I will try to work on it.

**Comment by captainbrosset** [comment] 2023-03-02 11:06
@asutherland 

> We no longer use free disk space as the basis for our storage limit, but instead use 50% of the disk size the profile lives on, capped at 8 TiB. [The relevant code is here](https://searchfox.org/mozilla-central/rev/5bcbe6ae54ee5b152f6cef29dc5627ec7c0e1f1e/dom/quota/ActorsParent.cpp#2441-2474).

Is this new? Last time I tested (which was maybe a month ago or so), Firefox was letting my origin store up to 10% of the total disk space in best-effort/temporary mode, and 50% only in persistent mode (i.e. after I called navigator.storage.persist() and approved the prompt).

**Comment by captainbrosset** [comment] 2023-03-02 18:09
I have a first draft for the new page that I'll push here in a minute. It probably has all sorts of problems, but I'm at the point where I need feedback from others.

**Comment by asutherland** [comment] 2023-03-02 21:24
@captainbrosset 
> > We no longer use free disk space as the basis for our storage limit, but instead use 50% of the disk size the profile lives on, capped at 8 TiB. [The relevant code is here](https://searchfox.org/mozilla-central/rev/5bcbe6ae54ee5b152f6cef29dc5627ec7c0e1f1e/dom/quota/ActorsParent.cpp#2441-2474).
> 
> Is this new? Last time I tested (which was maybe a month ago or so), Firefox was letting my origin store up to 10% of the total disk space in best-effort/temporary mode, and 50% only in persistent mode (i.e. after I called `navigator.storage.persist()` and approved the prompt).

Your experience is accurate and the behavior since [bug 1735713](https://bugzilla.mozilla.org/show_bug.cgi?id=1735713) landed in Firefox 97 which hit release over a year ago; that bullet was meant to only capture our change from using free space to total disk space as the starting point for the 10% (without navigator.storage.persist() granted) and 50% (with navigator.storage.persist()) granted which the 2nd bullet was intended to cover.  (Although I don't think I expressed the navigator.storage.persist() implications.)

**Closed** 2023-03-21 12:46 UTC
Labels: Content:WebAPI, effort: large
