### ISSUE TITLE
Import rules loads always the linked css file independent of a media query

### ISSUE THREAD

**Issue by ikabod** [mdn/content#23429] opened 2023-01-06 06:36 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/@import

### What specific section or headline is this issue about?

Importing CSS rules conditionally

### What information was incorrect, unhelpful, or incomplete?

So for instance, the last @import rule will load the...

### What did you expect to see?

So for instance, the last @import rule will apply the...

### Do you have anything more you want to share?

The @import rule makes not much sense with media queries as long as all defined import rules will load the linked css file even if a media query does not apply.

If I want to have the complete css in the browser I load it and use media query rules instead.

So there should be a difference for the use of @import and @media.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/@import`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/@import
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/@import/index.md
* Last commit: https://github.com/mdn/content/commit/4d97aee4ab56beaf371e8b32b3cb2caaf170fe15
* Document last modified: 2022-12-14T02:43:09.000Z

</details>

**Comment by Josh-Cena** [comment] 2023-01-06 06:39
Duplicate of https://github.com/mdn/content/issues/16198

**Closed** 2023-01-06 06:39 UTC
Labels: Content:CSS, needs triage
