### ISSUE TITLE
Getting a Route.get() requires a callback function but got a [object Undefined] ERROR

### ISSUE THREAD

**Issue by jvanstone** [mdn/content#1109] opened 2021-01-08 21:14 UTC
Hi There,

 I learning Node.js through [Express tutorial 4](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/routes). 

 I got to the part where I added the routes to the catalog, and I am now getting an error 
```
Route.get() requires a callback function but got a [object Undefined]
at Route.<computed> [as get] (/Users/home/express-locallibrary-tutorial/node_modules/express/lib/router/route.js:202:15)
    at Function.proto.<computed> [as get] (/Users/home/express-locallibrary-tutorial/node_modules/express/lib/router/index.js:510:19)
    at Object.<anonymous> (/Users/home/express-locallibrary-tutorial/routes/catalog.js:98:8).
```
What I don't get is there seems to be any error between my code and the Github code. 

Here is  my app.js
```
var createError = require('http-errors');
var express = require('express');
var path = require('path');
var cookieParser = require('cookie-parser');
var logger = require('morgan');

var wikiRouter = require('./routes/wiki');
var indexRouter = require('./routes/index');
var usersRouter = require('./routes/users');
var catalogRouter = require('./routes/catalog');

var app = express();

//Import the mongoose module
var mongoose = require('mongoose');

//Set up default mongoose connection
var mongoDB = 'mongodb+srv://{{user}}:{{pass}}@cluster0.4esdd.mongodb.net/local_library?retryWrites=true&w=majority';
mongoose.connect(mongoDB, {useNewUrlParser: true, useUnifiedTopology: true});

//Get the default connection
var db = mongoose.connection;

//Bind connection to error event (to get notification of connection errors)
db.on('error', console.error.bind(console, 'MongoDB connection error:'));


// view engine setup
app.set('views', path.join(__dirname, 'views')); 
app.set('view engine', 'jade');

app.use(logger('dev'));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));

app.use('/', indexRouter);
app.use('/users', usersRouter);
app.use('/wiki', wikiRouter);
app.use('/catalog', catalogRouter);

// catch 404 and forward to error handler
app.use(function(req, res, next) {
  next(createError(404));
});

// error handler
app.use(function(err, req, res, next) {
  // set locals, only providing error in development
  res.locals.message = err.message;
  res.locals.error = req.app.get('env') === 'development' ? err : {};

  // render the error page
  res.status(err.status || 500);
  res.render('error');
});

module.exports = app;
```

here is my routes/catalog.js The error has to do with the line.... 
```
// GET request for creating a BookInstance. NOTE This must come before route that displays BookInstance (uses id).
router.get('/bookinstance/create', book_instance_controller.bookinstance_create_get);
```

```var express = require('express');
var router = express.Router();


// Require our controllers.
var book_controller = require('../controllers/bookController'); 
var author_controller = require('../controllers/authorController');
var genre_controller = require('../controllers/genreController');
var book_instance_controller = require('../controllers/bookinstanceController');


/// BOOK ROUTES ///

// GET catalog home page.
router.get('/', book_controller.index);  

// GET request for creating a Book. NOTE This must come before routes that display Book (uses id).
router.get('/book/create', book_controller.book_create_get);

// POST request for creating Book.
router.post('/book/create', book_controller.book_create_post);

// GET request to delete Book.
router.get('/book/:id/delete', book_controller.book_delete_get);

// POST request to delete Book.
router.post('/book/:id/delete', book_controller.book_delete_post);

// GET request to update Book.
router.get('/book/:id/update', book_controller.book_update_get);

// POST request to update Book.
router.post('/book/:id/update', book_controller.book_update_post);

// GET request for one Book.
router.get('/book/:id', book_controller.book_detail);

// GET request for list of all Book.
router.get('/books', book_controller.book_list);

/// AUTHOR ROUTES ///

// GET request for creating Author. NOTE This must come before route for id (i.e. display author).
router.get('/author/create', author_controller.author_create_get);

// POST request for creating Author.
router.post('/author/create', author_controller.author_create_post);

// GET request to delete Author.
router.get('/author/:id/delete', author_controller.author_delete_get);

// POST request to delete Author
router.post('/author/:id/delete', author_controller.author_delete_post);

// GET request to update Author.
router.get('/author/:id/update', author_controller.author_update_get);

// POST request to update Author.
router.post('/author/:id/update', author_controller.author_update_post);

// GET request for one Author.
router.get('/author/:id', author_controller.author_detail);

// GET request for list of all Authors.
router.get('/authors', author_controller.author_list);


/// GENRE ROUTES ///

// GET request for creating a Genre. NOTE This must come before route that displays Genre (uses id).
router.get('/genre/create', genre_controller.genre_create_get);

// POST request for creating Genre.
router.post('/genre/create', genre_controller.genre_create_post);

// GET request to delete Genre.
router.get('/genre/:id/delete', genre_controller.genre_delete_get);

// POST request to delete Genre.
router.post('/genre/:id/delete', genre_controller.genre_delete_post);

// GET request to update Genre.
router.get('/genre/:id/update', genre_controller.genre_update_get);

// POST request to update Genre.
router.post('/genre/:id/update', genre_controller.genre_update_post);

// GET request for one Genre.
router.get('/genre/:id', genre_controller.genre_detail);

// GET request for list of all Genre.
router.get('/genres', genre_controller.genre_list);


/// BOOKINSTANCE ROUTES ///

// GET request for creating a BookInstance. NOTE This must come before route that displays BookInstance (uses id).
router.get('/bookinstance/create', book_instance_controller.bookinstance_create_get);

// POST request for creating BookInstance.
router.post('/bookinstance/create', book_instance_controller.bookinstance_create_post);

// GET request to delete BookInstance.
router.get('/bookinstance/:id/delete', book_instance_controller.bookinstance_delete_get);

// POST request to delete BookInstance.
router.post('/bookinstance/:id/delete', book_instance_controller.bookinstance_delete_post);

// GET request to update BookInstance.
router.get('/bookinstance/:id/update', book_instance_controller.bookinstance_update_get);

// POST request to update BookInstance.
router.post('/bookinstance/:id/update', book_instance_controller.bookinstance_update_post);

// GET request for one BookInstance.
router.get('/bookinstance/:id', book_instance_controller.bookinstance_detail);

// GET request for list of all BookInstance.
router.get('/bookinstances', book_instance_controller.bookinstance_list);


module.exports = router;`

here is my routes/index.js 

`var express = require('express');
var router = express.Router();

// GET home page.
router.get('/', function(req, res) {
  res.redirect('/catalog');
});

module.exports = router;
```

Thanks for the help!

**Comment by hamishwillee** [comment] 2021-01-18 02:37
@jvanstone Sorry for the delay, I've been on holiday.

If the problem is indeed this line:
```
// GET request for creating a BookInstance. NOTE This must come before route that displays BookInstance (uses id).
router.get('/bookinstance/create', book_instance_controller.bookinstance_create_get);
```
Then from the error I would **guess** that `bookinstance_create_get` is not defined (or not imported). It is pretty hard to debug this stuff from code dumps like this. If you need help, could you:
- upload a version of your project to github and point me to the link? 
- explain how you reproduce - ie what do you have in the db. What link you press to get this error.

Thanks!

**Comment by hamishwillee** [comment] 2021-01-22 03:50
Closing for now. Reopen when/if you are able to come back with the provided information.

**Closed by hamishwillee** 2021-01-22 03:50 UTC
Labels: Content:Other

**Comment by jvanstone** [comment] 2021-01-25 14:19
Hi Hamish,

 Thanks for getting back to me. The version I am working on is here (https://github.com/jvanstone/express-locallibrary-tutorial.)
 I double checked my database and I was note getting an error there.

Thanks for your help!
 Jason

**Comment by hamishwillee** [comment] 2021-01-29 01:50
@jvanstone Well, the error is reported as

```
Route.get() requires a callback function but got a [object Undefined]
at Route.<computed> [as get] (/Users/home/express-locallibrary-tutorial/node_modules/express/lib/router/route.js:202:15)
    at Function.proto.<computed> [as get] (/Users/home/express-locallibrary-tutorial/node_modules/express/lib/router/index.js:510:19)
    at Object.<anonymous> (/Users/home/express-locallibrary-tutorial/routes/catalog.js:98:8).
```
That says basically that at [routes/catalog.js#L98](https://github.com/jvanstone/express-locallibrary-tutorial/blob/master/routes/catalog.js#L98) it can't find a callback.
```
// GET request for creating a BookInstance. NOTE This must come before route that displays BookInstance (uses id).
router.get('/bookinstance/create', book_instance_controller.bookinstance_create_get);
```
Above you can see the callback is `book_instance_controller.bookinstance_create_get`, but if you search on `bookinstance_create_get` in your project this is the only instance of it. i.e. bookinstance_create_get is not defined.

How can this be? Well, if you look in the folder where it should be here https://github.com/jvanstone/express-locallibrary-tutorial/blob/master/controllers/bookinstanceController.js you will see that has Genre code :-)

You may find other errors. Easiest way to debug is to compare to the official code https://github.com/mdn/express-locallibrary-tutorial

Cheerio
H

**Comment by jvanstone** [comment] 2021-01-31 22:25
Thank you Hamish!!  I am not sure how I missed that. 

All the best! 
Jason
