### ISSUE TITLE
Sidebar navigation fails to match the current sub-page

### ISSUE THREAD

**Issue by erosman** [mdn/content#28125] opened 2023-07-22 18:16 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/action/disable

### What specific section or headline is this issue about?

Sidebar Navigation

### What information was incorrect, unhelpful, or incomplete?

The issue is not limited to single page and the following is given as an example.

When navigating to sub-pages, the sidebar fails to display the current page (`<details>` is closed).

- Starting from [JavaScript APIs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API)
  Sidebar highlight matches the content
- Navigate to [action](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/action)
  Sidebar highlight matches the content
- Navigate to [action.disable()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/action/disable)
 Sidebar section "JavaScript APIs" `<details>` is closed and thus fails to match the current content
  After opening the `<details>`, it matches the current content
 
 
 Another example:

[JavaScript APIs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API) -> [i18n](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/i18n) -> [i18n.getMessage()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/i18n/getMessage)

### What did you expect to see?

Sidebar navigation matching the current page

**Comment by sideshowbarker** [comment] 2023-07-22 18:46
Is this a Yari issue rather than a content issue?

**Comment by roy9495** [comment] 2023-07-22 19:40
I think this issue is actually copy of [this](https://github.com/mdn/yari/issues/8628) issue

**Comment by Josh-Cena** [comment] 2023-07-23 06:19
Yes, duplicate of https://github.com/mdn/yari/issues/8628

**Closed by Josh-Cena** 2023-07-23 06:19 UTC
Labels: Content:WebExt
