### ISSUE TITLE
Unable to connect MongoDB Atlas to the code tutorial in VS Code

### ISSUE THREAD

**Issue by jacobwwarner** [mdn/content#23587] opened 2023-01-12 22:20 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose

### What specific section or headline is this issue about?

"Connect to MongoDB" & "Testing - create some items"

### What information was incorrect, unhelpful, or incomplete?

Connect to MongoDB tells us to...
"Open /app.js (in the root of your project) and copy the following text below where you declare the Express application object (after the line `const app = express();`). Replace the database URL string (`'insert_your_database_url_here'`) with the location URL representing your own database (i.e. using the information from mongoDB Atlas)."
... these are the steps I followed:
1. While viewing the cluster, I selected the connect button.
2. Connect your application.
3. I copied & used to the string in step 2 "Add your connection string into your application code"
So, that string snippet is populated in this code app.js...

```js
    // Set up mongoose connection
    const mongoose = require("mongoose");
    const mongoDB = "insert_your_database_url_here"; <-- pasted that string there.
    mongoose.connect(mongoDB, { useNewUrlParser: true, useUnifiedTopology: true });
    const db = mongoose.connection;
    db.on("error", console.error.bind(console, "MongoDB connection error:"));
```

Later in this tutorial guide, "Testing - create some items"
1. I downloaded and transferred the populatedb.js file into my VS Code working directory.
2. npm install async
3. and ran the script using `npm populatedb "my_database_url_string"`

Continue reading below...

### What did you expect to see?

I'm not sure what I expected to see. Maybe some kind of descriptive text in the terminal showing the data being stored in my version of MongoDB Atlas. Instead, it threw a bunch of errors:
General view of what came out in the terminal:

```
MongoDB connection error: MongoServerError: bad auth : authentication failed
    at ...
    at ...
    at ...
    at ... {
        ok: 0,
        code: 8000,
        codeName: 'AtlasError',
        connectionGeneration: 0,
        [Symbol(errorLabels)]: Set(2) { 'HandshakeError', 'ResetPool' }
    }
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);

MongoServerError: bad auth : authentication failed
    at ...
    at ...
    at ...
    at ... {
        ok: 0,
          code: 8000,
          codeName: 'AtlasError',
          connectionGeneration: 0,
          [Symbol(errorLabels)]: Set(2) { 'HandshakeError', 'ResetPool' }
}

Node.js v18.12.1
```

### Do you have anything more you want to share?

Cna you make it more descriptive in setting the connection between our working code and the MongoDB Atlas database? I'd need to hunt down some kind of specific documentation on their website to do this on my own and I'm sure many others would have to do the same thing which is a little overwhelming when you're new to both Node.js / Express and MongoDB.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/mongoose`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/mongoose/index.md
* Last commit: https://github.com/mdn/content/commit/1f4c6bc8ea56c9ee2aa0087ce69b89343bc66fd9
* Document last modified: 2022-12-19T10:07:55.000Z

</details>

**Comment by hamishwillee** [comment] 2023-01-24 00:01
@jacobwwarner Thanks for posting - that must be frustrating. First we need to work out the cause, then we can look at whether possible remedies are needed.

This a relatively complicated project and there are lots of things that might go wrong. Commonly developers miss a step in following the instructions. Sometimes the underlying dependencies change in a breaking way, so you're doing nothing wrong. I can tell you that I updated populatedb just before christmas and it worked then against my test account. You might want to try running populatedb with the URL it suggests if you don't enter one and see if it works. That's for my account, and that "should work".

To work out what is going on, another thing to do is try the worked project using an environment set up with this set of dependencies: https://github.com/mdn/express-locallibrary-tutorial/blob/main/package.json - that has been tested, so you know that the dependencies work and the code is good. The "replace me" password and user id will probably just work for you, writing to my database (I clean that database up from time to time).

If you can get the demo repo working then you know that you are working with the tested environment. If you insert your URL in https://github.com/mdn/express-locallibrary-tutorial/blob/main/app.js#L20 and it doesn't work then that means your URL is badly formatted in some way. If it does work it indicates either your code or environment was wrong. 

You can compare to the repo to check your code.

If I had to guess from the console log I'd say that you have not granted the user you're using in the URL permissions to access the database. If you use your default account, at least in the past, the user got the permissions to access the database by default.

**Comment by hamishwillee** [comment] 2023-05-19 05:44
Closing as no further response.

Note, the database interaction has recently changed to use await/async code - it is a bit different now.

**Closed by hamishwillee** 2023-05-19 05:44 UTC
Labels: help wanted, Content:Learn:Express
