### ISSUE TITLE
contentBoxSize example is incorrect

### ISSUE THREAD

**Issue by altay** [mdn/content#27943] opened 2023-07-14 07:50 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserverEntry/contentBoxSize

### What specific section or headline is this issue about?

Examples

### What information was incorrect, unhelpful, or incomplete?

The example for `contentBoxSize` seems to be copied+pasted from the `borderBoxSize` example here: https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserverEntry/borderBoxSize

The `contentBoxSize` example doesn't actually demonstrate usage of `contentBoxSize`. 

I think maybe I'll stick to `contentRect` for now... :)

### What did you expect to see?

Expected an example using `contentBoxSize.`

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserverEntry/contentBoxSize

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/resizeobserverentry/contentboxsize`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserverEntry/contentBoxSize
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/resizeobserverentry/contentboxsize/index.md
* Last commit: https://github.com/mdn/content/commit/954612667bafd71241a93e8554e8f11afc474ff3
* Document last modified: 2023-04-07T19:50:09.000Z

</details>

**Comment by Josh-Cena** [comment] 2023-07-14 08:58
Duplicate of https://github.com/mdn/content/issues/25364

**Closed by Josh-Cena** 2023-07-14 08:58 UTC
Labels: Content:WebAPI, needs triage
