### ISSUE TITLE
IE 11 has ended on June 15, 2022

### ISSUE THREAD

**Issue by KimberlyYen** [mdn/content#17773] opened 2022-06-29 14:41 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Pages_sites_servers_and_search_engines

### What specific section or headline is this issue about?

IE stop

### What information was incorrect, unhelpful, or incomplete?

web page
A document which can be displayed in a web browser such as Firefox, Google Chrome, Opera, Microsoft ~Internet Explorer or~ Edge, or Apple's Safari. These are also often called just "pages."

### What did you expect to see?

web page
A document which can be displayed in a web browser such as Firefox, Google Chrome, Opera, Microsoft Edge, or Apple's Safari. These are also often called just "pages."

### Do you have any supporting links, references, or citations?

Microsoft Edge is the recommended browser by Microsoft
Support for Internet Explorer 11 has ended on June 15, 2022. If any site you visit needs Internet Explorer 11, you can reload it with Internet Explorer mode in Microsoft Edge.

[Microsoft Edge is the recommended browser by Microsoft
](https://support.microsoft.com/en-us/windows/internet-explorer-downloads-d49e1f0d-571c-9a7b-d97e-be248806ca70)

### Do you have anything more you want to share?

no

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/common_questions/pages_sites_servers_and_search_engines`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Pages_sites_servers_and_search_engines
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/common_questions/pages_sites_servers_and_search_engines/index.md
* Last commit: https://github.com/mdn/content/commit/b06d0695cf809707b421f5202495209928e3519d
* Document last modified: 2022-04-27T05:45:53.000Z

</details>

**Comment by teoli2003** [comment] 2022-06-29 14:55
Duplicate of mdn/browser-compat-data#15333

**Closed by teoli2003** 2022-06-29 14:55 UTC
