### ISSUE TITLE
Issue with "Intl.NumberFormat() constructor": (minimum/maximumFractionDigits with minimum/maximumSignificantDigits)

### ISSUE THREAD

**Issue by floratmin** [mdn/content#14783] opened 2022-04-07 15:17 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat

#### What information was incorrect, unhelpful, or incomplete?
The following properties fall into two groups: `minimumIntegerDigits`, `minimumFractionDigits`, and `maximumFractionDigits` in one group, `minimumSignificantDigits` and `maximumSignificantDigits` in the other. If at least one property from the second group is defined, then the first group is ignored.

#### Specific section or headline?
Parameters

#### What did you expect to see?
According to the definition on ICU > Formatting > [Number Skeletons > Fraction Precision](https://unicode-org.github.io/icu/userguide/format_parse/numbers/skeletons.html) `minimumFractionDigits` and `maximumFractionDigits` should not be ignored when specifying `mimumSignificantDigits` or `maximumSignificantDigits`.

The equivalent settings for the skeletons should be:
| Skeleton | Options |
|-|-|
| `.##/@@@*` or `.##/@##r` | `{maximumFractionDigits: 2, minimumSignificantDigits: 1, maximumSignificantDigits: 3, roundingPriority: 'morePrecision'}` |
| `.##/@@@r` | `{maximumFractionDigits: 2, minimumSignificantDigits: 3, maximumSignificantDigits: 3, roundingPriority: 'morePrecision'}` |
| `.00/@##` or `.00/@##s` | `{minimumFractionDigits: 2, maximumFractionDigits: 2, minimumSignificantDigits: 1, maximumSignificantDigits: 3, roundingPriority: 'lessPrecision'}` |
| `.00/@@@s`\* | `{minimumFractionDigits: 2, maximumFractionDigits: 2, minimumSignificantDigits: 3, maximumSignificantDigits: 3, roundingPriority: 'lessPrecision'}` |

\* Is wrongly listed as `.00/@##s`

#### Did you test this? If so, how?
No, at the moment it is not implemented in Chrome, Firefox, and Node.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/intl/numberformat/numberformat`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/intl/numberformat/numberformat/index.md
* Last commit: https://github.com/mdn/content/commit/c456a1f80c39a127880c9808f64ccefee7f60ec4
* Document last modified: 2022-03-29T08:11:58.000Z

</details>

**Comment by hamishwillee** [comment] 2022-07-19 09:54
The statement is correct for all current implementations, because none of them support `roundingPriority` - though this is now present in Firefox Nightly (FF104). 

But as you say, this will be incorrect for `roundingPriority` options other than `auto`. I'll update that as part of https://github.com/mdn/content/pull/18505

Just FYI, the expected behaviour here has recently changed and will be as identified in https://tc39.es/ecma402/#sec-setnfdigitoptions
Essentially the code was ignoring the minimum fraction digits, assuming that any zero-suffix they added should be ignored. So the new way will be to calculate the digits using both approaches. Then select the on that has more or less precision, where precision simply means number of fractional digits in the rendering.

**Comment by hamishwillee** [comment] 2022-07-22 04:05
Fixed  - see this comment on the changed line: https://github.com/mdn/content/pull/18505/files#r927269273

**Closed** 2022-07-29 05:02 UTC
Labels: Content:JS
