### ISSUE TITLE
Issue with "String.prototype.replace()": Wrong order of parameters

### ISSUE THREAD

**Issue by mplungjan** [mdn/content#11743] opened 2022-01-05 07:12 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace

#### What information was incorrect, unhelpful, or incomplete?

`function upperToHyphenLower(match, offset, string) {`

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#using_an_inline_function_that_modifies_the_matched_characters

#### What did you expect to see?

`function upperToHyphenLower(match, string, offset) {`

#### Did you test this? If so, how?
https://stackoverflow.com/a/70588678/295783

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/string/replace`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/string/replace/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by sideshowbarker** [comment] 2022-01-05 21:43
Thanks for catching this — I’ve opened #11770 with a fix.

After that fix is merged, this issue will automatically be marked as resolved, and closed.

**Comment by mplungjan** [comment] 2022-01-06 05:05
Great thanks

**Comment by sideshowbarker** [comment] 2022-01-14 06:17
Closing per https://github.com/mdn/content/pull/11770#pullrequestreview-845997341

**Comment by mplungjan** [comment] 2022-01-14 07:02
Apologies for not returning - I was not aware I needed to sign off

Here is the test

https://jsfiddle.net/mplungjan/473n2yv0/

Both work - the offset will be the second to last parameter

function replacer(match, p1, p2, p3, offset, string) {
  // p1 is nondigits, p2 digits, and p3 non-alphanumerics
  console.log("match",match)
  console.log("p1",p1)
  console.log("p2",p2)
  console.log("p3",p3)
  console.log("offset",offset)
  console.log("string",string)
  
  return [p1, p2, p3].join(' - ');
}
let newString = 'abc12345#$*%'.replace(/([^\d]*)(\d*)([^\w]*)/, replacer);
console.log(newString);  // abc - 12345 - #$*%


function styleHyphenFormat(propertyName) {
  function upperToHyphenLower(match, offset, string) {
  console.log("m",match,"o", offset,"s", string) 
  
    return (offset > 0 ? '-' : '') + match.toLowerCase();
  }
  return propertyName.replace(/[A-Z]/g, upperToHyphenLower);
}

console.log(styleHyphenFormat('borderTop'))

**Comment by sideshowbarker** [comment] 2022-01-15 04:33
As indicated over at https://github.com/mdn/content/pull/11770#pullrequestreview-845997341, `> « searchString, 𝔽(position), string »` seems to be what’s correct per-spec. So as far as I can see, the existing MDN content is consistent with the spec.

So I’m un-assigning myself from this, and opening it back up to anybody else who wants to spend more time investigating.

**Comment by wbamberg** [comment] 2022-01-15 05:27
I'm not sure what the issue is here. The extra parameters `p1, p2, p3` in the example are for capturing groups in the regex. 

That is documented in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#specifying_a_function_as_a_parameter. In the example: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#using_an_inline_function_that_modifies_the_matched_characters there aren't any capturing groups, so `offset` is the second argument.

So as far as I can see the docs are correct here.

**Comment by sideshowbarker** [comment] 2022-01-20 21:15
Closing per https://github.com/mdn/content/issues/11743#issuecomment-1013616140

**Closed by sideshowbarker** 2022-01-20 21:15 UTC
Labels: help wanted, Content:JS, time: -3hr
