### ISSUE TITLE
Issue with "Intensive JavaScript": (short summary here please)

### ISSUE THREAD

**Issue by hossammourad** [mdn/content#10517] opened 2021-11-14 18:28 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Performance/Scenarios/Intensive_JavaScript

#### What information was incorrect, unhelpful, or incomplete?
the video walkthrough link is broken

#### Specific section or headline?
Intro

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/performance/scenarios/intensive_javascript`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Performance/Scenarios/Intensive_JavaScript
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/performance/scenarios/intensive_javascript/index.html
* Last commit: https://github.com/mdn/content/commit/2ffef3f139146ecb3d6f403459ca8a890027c999
* Document last modified: 2021-02-02T15:23:50.000Z

</details>

**Comment by wbamberg** [comment] 2021-11-14 21:55
Thanks for filing! 

This is a duplicate of https://github.com/mdn/content/issues/7457.

**Closed by wbamberg** 2021-11-14 21:55 UTC
