### ISSUE TITLE
execCommand obsolete

### ISSUE THREAD

**Issue by daslicht** [mdn/content#629] opened 2020-12-24 14:51 UTC
Hi,
this article refers to the execCommand which is now marked as [obsolete](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand),
https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Editable_content
Shount there be a notice in teh article with suggested alternatives?

**Comment by mattiapontonio** [comment] 2020-12-27 15:19
https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API
_This API is designed to supersede accessing the clipboard using document.execCommand()._

**Comment by mattiapontonio** [comment] 2020-12-27 15:21
Should you do a Regex to check all `document.execCommand()`?

**Comment by daslicht** [comment] 2020-12-27 15:53
```document.execCommand()``` consists of more than just the clipboard :
[](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand#Commands)

> Should you do a Regex to check all `document.execCommand()`?
I don't know

**Comment by mattiapontonio** [comment] 2020-12-27 15:59
And where all these commands are gone? 🤔

**Comment by Ryuno-Ki** [comment] 2020-12-27 19:29
Regarding the HTTP Header: Would it make sense to pass a timestamp instead?
This way, it could be flagged as „obsolete since X”.

**Comment by mattiapontonio** [comment] 2020-12-27 20:37
> Regarding the HTTP Header: Would it make sense to pass a timestamp instead?
> This way, it could be flagged as „obsolete since X”.

🤔 Obsolete is hardcoded or computed at the origin?

**Comment by Ryuno-Ki** [comment] 2020-12-27 20:42
As far as I understood, the API (and thus, the page describing it) became obsolete and replaced by a set of other APIs (and thus documents).
I'd see some kind of timestamp declaring the point in time as of when I shouldn't use it anymore (I can see some intersection with BCD here).

**Comment by mattiapontonio** [comment] 2020-12-27 21:05
> As far as I understood, the API (and thus, the page describing it) became obsolete and replaced by a set of other APIs (and thus documents).
> I'd see some kind of timestamp declaring the point in time as of when I shouldn't use it anymore (I can see some intersection with BCD here).

Intresting 🤔
Witch headers?
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers
(I'm not really Expert in http but seems the thing that connect the dots...)

**Comment by mattiapontonio** [comment] 2020-12-27 23:30
> 410 Gone
> Indicates that the resource requested is no longer available and will not be available again. This should be used when a resource has been intentionally removed and the resource should be purged. Upon receiving a 410 status code, the client should not request the resource in the future. Clients such as search engines should remove the resource from their indices.[42] Most use cases do not require clients and search engines to purge the resource, and a "404 Not Found" may be used instead.

?
https://en.m.wikipedia.org/wiki/List_of_HTTP_status_codes

**Comment by mattiapontonio** [comment] 2020-12-28 00:49
https://github.com/mdn/content/search?q=document.execCommand%28%29&type=

**Comment by Ryuno-Ki** [comment] 2020-12-28 15:05
>  Wich headers?

Your Content-Obsolete?

>  (I'm not really Expert in http but seems the thing that connect the dots...)

You can define custom ones. There was a time, when it was common to prefix them with `X-`, but that is not strictly required anymore AFAIK.

**Comment by Ryuno-Ki** [comment] 2020-12-28 15:06
> 410 Gone
> 
> The requested resource is no longer available at the server and no forwarding address is known. This condition is expected to be considered permanent. Clients with link editing capabilities SHOULD delete references to the Request-URI after user approval. If the server does not know, or has no facility to determine, whether or not the condition is permanent, the status code 404 (Not Found) SHOULD be used instead. This response is cacheable unless indicated otherwise.
>
> The 410 response is primarily intended to assist the task of web maintenance by notifying the recipient that the resource is intentionally unavailable and that the server owners desire that remote links to that resource be removed. Such an event is common for limited-time, promotional services and for resources belonging to individuals no longer working at the server's site. It is not necessary to mark all permanently unavailable resources as "gone" or to keep the mark for any length of time -- that is left to the discretion of the server owner.

It's not „gone”, but „obsolete”. That is, if you run an older browser (e.g. Point-of-sale, bank, enterprise), you can still use it.

**Comment by mattiapontonio** [comment] 2020-12-28 15:15
@Ryuno-Ki thanks 🙏. Looking forward to find a way to move comments between repositories.

**Comment by mattiapontonio** [comment] 2020-12-28 16:21
For some reason i can't di this search with the GitHub search anyway i actually count **8** matches of `execCommand` (hoping Is the right filename, path, extension, branch and repository).

https://github.com/mdn/content/blob/main/files/en-us/web/guide/html/editable_content/index.html

![Screenshot_20201228-171902.png](https://user-images.githubusercontent.com/44380480/103228375-fc97d980-4930-11eb-9cd7-58907c3b7d8d.png)

**Comment by Ryuno-Ki** [comment] 2020-12-28 16:46
There're more:

```
$ grep -l execCommand -r files/en-us/
files/en-us/plugins/flash_to_html5/clipboard/index.html
files/en-us/mozilla/add-ons/webextensions/interact_with_the_clipboard/index.html
files/en-us/mozilla/add-ons/webextensions/manifest.json/permissions/index.html
files/en-us/mozilla/firefox/releases/64/index.html
files/en-us/mozilla/firefox/releases/41/index.html
files/en-us/mozilla/firefox/releases/8/index.html
files/en-us/mozilla/firefox/releases/69/index.html
files/en-us/mozilla/firefox/releases/60/index.html
files/en-us/mozilla/firefox/releases/82/index.html
files/en-us/mozilla/firefox/releases/14/index.html
files/en-us/_wikihistory.json
files/en-us/_redirects.txt
files/en-us/web/guide/html/editable_content/index.html
files/en-us/web/guide/html/editable_content/rich-text_editing_in_mozilla/index.html
files/en-us/web/guide/html/editable_content/rich-text_editing_in_mozilla/class_xbdesignmode/index.html
files/en-us/web/api/textrange/index.html
files/en-us/web/api/clipboard_api/index.html
files/en-us/web/api/document/execcommand/index.html
files/en-us/web/api/document/querycommandstate/index.html
files/en-us/web/api/document/index.html
files/en-us/web/api/document/querycommandenabled/index.html
files/en-us/web/api/document/querycommandsupported/index.html
files/en-us/web/api/clipboard/index.html
```

**Comment by mattiapontonio** [comment] 2020-12-28 16:51
> There're more:
> 
> ```
> $ grep -l execCommand -r files/en-us/
> files/en-us/plugins/flash_to_html5/clipboard/index.html
> files/en-us/mozilla/add-ons/webextensions/interact_with_the_clipboard/index.html
> files/en-us/mozilla/add-ons/webextensions/manifest.json/permissions/index.html
> files/en-us/mozilla/firefox/releases/64/index.html
> files/en-us/mozilla/firefox/releases/41/index.html
> files/en-us/mozilla/firefox/releases/8/index.html
> files/en-us/mozilla/firefox/releases/69/index.html
> files/en-us/mozilla/firefox/releases/60/index.html
> files/en-us/mozilla/firefox/releases/82/index.html
> files/en-us/mozilla/firefox/releases/14/index.html
> files/en-us/_wikihistory.json
> files/en-us/_redirects.txt
> files/en-us/web/guide/html/editable_content/index.html
> files/en-us/web/guide/html/editable_content/rich-text_editing_in_mozilla/index.html
> files/en-us/web/guide/html/editable_content/rich-text_editing_in_mozilla/class_xbdesignmode/index.html
> files/en-us/web/api/textrange/index.html
> files/en-us/web/api/clipboard_api/index.html
> files/en-us/web/api/document/execcommand/index.html
> files/en-us/web/api/document/querycommandstate/index.html
> files/en-us/web/api/document/index.html
> files/en-us/web/api/document/querycommandenabled/index.html
> files/en-us/web/api/document/querycommandsupported/index.html
> files/en-us/web/api/clipboard/index.html
> ```

The problem with editing too many files in 1 PR is that if the CI fails you may not understand which file caused it to fail ...

**Comment by daslicht** [comment] 2021-07-22 09:52
So what is the official replacement now for the execComamnd ? 
Why is it obsolete ? 
An example how to sole things without the execCommand would be helpful

**Comment by daslicht** [comment] 2021-07-22 09:56
Here related:
`This spec is to meant to help implementations in standardizing these existing features. It is predicted that in the future both specs will be replaced by Content Editable and Input Events.`
source: [execCommand](https://w3c.github.io/editing/docs/execCommand)

**Comment by Rumyra** [comment] 2022-08-26 09:54
The task here is to add a note to the `execCommand` page with alternatives as per:

> This spec is to meant to help implementations in standardizing these existing features. It is predicted that in the future both specs will be replaced by Content Editable and Input Events.

**Comment by OphyBoamah** [comment] 2023-01-12 22:42
@mdn/mdn-community-engagement @Rumyra if this isn't already done and hasn't been assigned, I'd like to work on it.

**Comment by himanshugarg** [comment] 2023-01-14 03:13
Hello @OphyBoamah , as the issue is still open , please feel free to go ahead and create a pull request with your changes. Thanks

**Comment by dscotese** [comment] 2023-06-19 01:12
If any of the docs listed below are still unsatisfactory, it makes sense to keep this issue open. I have starred the ones I think are satisfactory, usually because they mention https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API or deprecation, but see my note at the bottom recommending closure.

files/en-us/plugins/flash_to_html5/clipboard/index.html
files/en-us/mozilla/add-ons/webextensions/interact_with_the_clipboard/index.html
files/en-us/mozilla/add-ons/webextensions/manifest.json/permissions/index.html
files/en-us/mozilla/firefox/releases/64/index.html
files/en-us/mozilla/firefox/releases/41/index.html
files/en-us/mozilla/firefox/releases/8/index.html
files/en-us/mozilla/firefox/releases/69/index.html
files/en-us/mozilla/firefox/releases/60/index.html
files/en-us/mozilla/firefox/releases/82/index.html
files/en-us/mozilla/firefox/releases/14/index.html
files/en-us/_wikihistory.json
files/en-us/_redirects.txt
 * I can't find these pages, and didn't bother looking for those listed above:
+files/en-us/web/guide/html/editable_content/index.html
+files/en-us/web/guide/html/editable_content/rich-text_editing_in_mozilla/index.html
+files/en-us/web/guide/html/editable_content/rich-text_editing_in_mozilla/class_xbdesignmode/index.html
+files/en-us/web/api/textrange/index.html 
* files/en-us/web/api/clipboard_api/index.html
* files/en-us/web/api/document/execcommand/index.html
* files/en-us/web/api/document/querycommandstate/index.html
* files/en-us/web/api/document/index.html
* files/en-us/web/api/document/querycommandenabled/index.html
* files/en-us/web/api/document/querycommandsupported/index.html
* files/en-us/web/api/clipboard/index.html

In fact, I believe this issues should be closed because every page that has "execCommand" on it, according to [this search](https://developer.mozilla.org/en-US/search?q=%22execCommand%22) mentions that it's deprecated or can no longer be found.

**Comment by daslicht** [comment] 2023-06-19 12:29
An simple example how to use the **Content Editable** and **Input Events** to achive the same as with execCommnd would be beneficial and answer many questions.

**Comment by dscotese** [comment] 2023-06-20 03:52
It looks like execCommand provided a lot of useful little shortcuts which are not available through the Clipboard API.  While I don't think it's in the interest of MDN to provide a replacement custom Javascript function that would do what execCommand used to do, it's possible and seems like the best way forward for people who would visit https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Editable_content or the original page where execCommand is described as deprecated.

I still recommend closing this issue.

**Comment by daslicht** [comment] 2023-06-20 09:23
> An simple example how to use the **Content Editable** and **Input Events** to achive the same as with execCommnad (and NOT use execCommnad) would be beneficial and answer many questions.

The Clipboard API doent provoide functions liek bold, add link, etc for such function we need to use Input Events...

**Comment by dscotese** [comment] 2023-06-20 21:40
Okay, if leaving an issue open on the Editable content page is the best way to signal that to anyone willing to take on the job, maybe the next step here is to identify the following steps:

1. List the execCommand features each as a task requiring that code to replace it be added to the  page at https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand
2. Change the link in the first comment above to point to that document.
3. Establish a standard operating procedure for deprecations so that users of the site can expect that a deprecation notice will also include a link to the new way to do what they wanted to do.

There is the little trashcan icon that goes next to deprecated items in our documentation.  The mechanism that causes it to appear next to a term should include a link to the "modern way".  That would take care of #3.

**Comment by dscotese** [comment] 2023-06-24 21:10
The task list is below but I don't think it's worth doing until there are more parties interested in these features.  Deprecation is a sensitive topic because people start relying on something and then it could disappear.  I'd like to see MDN work on adding to "software culture" (or perhaps simply embellishing an existing aspect of it) the coupling of a deprecation notice with "the new way" to do the same thing, as I mentioned previously.  I don't think this issue is worth working on (except for @daslicht for those execCommand features he wants) until MDN is able to collect enough user input to justify it.  Plus, this plan I've concocted is not documentation but actual new software.

- [ ] Add execCommand commands to this task list if they aren't here already
- [ ] Develop a function to be added to an "execCmd" object intended to replace execCommand and point to it from the task
- [ ] Update the document at https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand to direct readers to a new file that has the "execCmd" object and the functions developed.
- [ ] If the "click the trashcan to see this feature's 'best-practices' replacement" strategy is implemented, go through the list of "execCommand" hits earlier in these comments and have it point to the section of the execCommand document where the new "execCmd" object file is presented.
- [ ] backcolor
- [ ] bold
- [ ] contentReadOnly
- [ ] copy
- [ ] createLink
- [ ] cut
- [ ] decreaseFontSize
- [ ] defaultParagraphSeparator
- [ ] delete
- [ ] enableAbsolutePositionEditor
- [ ] enableInlineTableEditing
- [ ] enableObjectResizing
- [ ] fontName
- [ ] fontSize
- [ ] foreColor
- [ ] formatBlock
- [ ] forwardDelete
- [ ] heading
- [ ] hiliteColor
- [ ] increaseFontSize
- [ ] indent
- [ ] insertBrOnReturn
- [ ] insertHorizontalRule
- [ ] insertHTML
- [ ] insertImage
- [ ] insertOrderedList
- [ ] insertUnorderedList
- [ ] insertParagraph
- [ ] insertText
- [ ] italic
- [ ] justifyCenter
- [ ] justifyFull
- [ ] justifyLeft
- [ ] justifyRight
- [ ] outdent
- [ ] paste
- [ ] redo
- [ ] removeFormat
- [ ] selectAll
- [ ] strikeThrough
- [ ] subscript
- [ ] superscript
- [ ] underline
- [ ] undo
- [ ] unlink
- [ ] styleWithCSS
- [ ] AutoUrlDetect

**Comment by daslicht** [comment] 2023-06-25 08:39
Thank you. 
You explicit name me for wanting those features, but anyone else who like to build a custom rte editor also need theses things.

**Comment by schalkneethling** [comment] 2024-04-18 22:01
@Rumyra and @OphyBoamah - I did a search across the content repo using GitHub and found these:
https://github.com/search?q=repo:mdn/content%20execCommand&type=code

These are primarily pages linking to the primary `execCommand` page which has a clear deprecation warning. However, there is one instance where the `{{Deprecated_Inline}}` macro is used. Might it be beneficial to also add it to some of the other instances? I know the project generally wants to move away from macros, but perhaps this is one of the macros that will still stick around for some time. Thanks!

**Comment by Josh-Cena** [comment] 2024-06-07 07:58
I'm going to close this as completed. We only use `Deprecated_Inline` in the landing page's API list. There are some remnants in WebExt but that's left for the WebExt team (for example, https://github.com/mdn/content/issues/4864)

**Closed by Josh-Cena** 2024-06-07 07:58 UTC
Labels: good first issue, Content:WebAPI, effort: small
