### ISSUE TITLE
Issue with "Compiling from Rust to WebAssembly": …

### ISSUE THREAD

**Issue by trebsirk** [mdn/content#1340] opened 2021-01-15 04:27 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/WebAssembly/Rust_to_wasm

#### What information was incorrect, unhelpful, or incomplete?
Incomplete info

#### Specific section or headline?
"Note that you need to fill in your own username, after the @, in the dependencies section." 

#### What did you expect to see?
There was no @ symbol in the preceding code. 

#### Did you test this? If so, how?
no. 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/webassembly/rust_to_wasm`
* MDN URL: https://developer.mozilla.org/en-US/docs/WebAssembly/Rust_to_wasm
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/webassembly/rust_to_wasm/index.html
* Report started: 2021-01-15T03:51:35.515Z

</details>

**Comment by chrisdavidmills** [comment] 2021-01-16 12:15
Closing this; duplicate of https://github.com/mdn/content/issues/505

**Closed by chrisdavidmills** 2021-01-16 12:15 UTC
Labels: 30 minute task, Content:Other
