### ISSUE TITLE
escape characters

### ISSUE THREAD

**Issue by J3es2e2** [mdn/content#22498] opened 2022-11-23 12:58 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Create_book_form

### What specific section or headline is this issue about?

book_create_get

### What information was incorrect, unhelpful, or incomplete?

```
reader&#x2F;herbalist. This book has been my foundational resource for the years I&#x27;ve pursued herbs since 1978. I really have haven&#x27;t found
```

### What did you expect to see?

```
reader/herbalist. This book has been my foundational resource for the years I've pursued herbs since 1978. I really have haven't found
```

### Do you have any supporting links, references, or citations?

I suspect the problem is here the bookcontroller

```js
exports.book_create_get
```
or
```js
 exports.book_create_post 
  body("summary", "Summary must not be empty.")
    .trim()
    .isLength({ min: 1 })
    .escape(),
```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/forms/create_book_form`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Create_book_form
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/forms/create_book_form/index.md
* Last commit: https://github.com/mdn/content/commit/f4f8e2f18ccf19a0bee59e1fe78753e276b98232
* Document last modified: 2022-09-09T07:06:10.000Z

</details>

**Comment by hamishwillee** [comment] 2022-11-24 23:17
I don't understand the problem you are seeing - the problem and your expectation look pretty much the same.

Can you explain more clearly?

**Comment by Josh-Cena** [comment] 2022-12-23 19:00
@hamishwillee I've edited the post. It seems the issue is that the escape sequences get directly rendered to screen.

**Comment by Josh-Cena** [comment] 2022-12-29 18:44
Duplicate of #5320

**Closed by Josh-Cena** 2022-12-29 18:44 UTC
Labels: Content:Learn:Express, needs info
