### ISSUE TITLE
Desktop & Mobile Browsers Mixed Up In Compatibility Table

### ISSUE THREAD

**Issue by pbuchi2000-adiacom** [mdn/content#16229] opened 2022-05-19 10:45 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/setSinkId

### What specific section or headline is this issue about?

Browser Compatibility

### What information was incorrect, unhelpful, or incomplete?

Opera & Safari are listed under mobile
Chrome Android & Firefox Android are listed under computer

![image](https://user-images.githubusercontent.com/79928749/169275787-0f697e49-4a8a-4ce9-8565-9eee27e27ac6.png)

### What did you expect to see?

Opera & Safari listed under computer
Chrome Android & Firefox Android listed under mobile

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/htmlmediaelement/setsinkid`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/setSinkId
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlmediaelement/setsinkid/index.md
* Last commit: https://github.com/mdn/content/commit/a96425a7d086b16485b8ddb12ef2e6c8185b3d26
* Document last modified: 2022-05-16T05:20:14.000Z

</details>

**Comment by teoli2003** [comment] 2022-05-19 10:49
Thank you!

This is a duplicate of mdn/yari#6314, so I'm closing this issue. (It should be fixed quickly)

**Closed by teoli2003** 2022-05-19 10:49 UTC
Labels: Content:WebAPI, needs-triage
