### ISSUE TITLE
Hyperlink to "Custom Error" page is not found

### ISSUE THREAD

**Issue by jacob-lee** [mdn/content#27153] opened 2023-06-05 20:25 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/ValidityState

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/API/ValidityState/customError

### What information was incorrect, unhelpful, or incomplete?

This link, https://developer.mozilla.org/en-US/docs/Web/API/ValidityState/customError

is dead, but found on the https://developer.mozilla.org/en-US/docs/Web/API/ValidityState

page

### What did you expect to see?

Documentation of customError

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/validitystate`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/ValidityState
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/validitystate/index.md
* Last commit: https://github.com/mdn/content/commit/6b1e3eebf22abf1b73bb219581335b1147b75d7a
* Document last modified: 2023-03-12T09:29:44.000Z

</details>

**Comment by bsmth** [comment] 2023-06-16 08:09
Hi @jacob-lee - thanks for raising the issue. This link is added from the [BCD table](https://github.com/mdn/content/blob/main/files/en-us/web/api/validitystate/index.md?plain=1#LL5C1-L5C34) via https://github.com/mdn/browser-compat-data/blob/main/api/ValidityState.json#L86

We may want to remove the `mdn_url` from the BCD table - the property doesn't have a dedicated page and likely won't have one as this seems to be all there is to say about it:

>customError: A boolean value indicating whether the element's custom validity message has been set to a non-empty string by calling the element's [setCustomValidity()](https://developer.mozilla.org/en-US/docs/Web/API/HTMLObjectElement/setCustomValidity) method.

Let me know if that makes sense :)

**Comment by jacob-lee** [comment] 2023-06-16 12:33
It does make sense. Just clicked on link because it implied there was more
to learn about it. Cheers.

**Comment by Josh-Cena** [comment] 2023-06-26 15:52
Duplicate of https://github.com/mdn/content/issues/26522

**Closed by Josh-Cena** 2023-06-26 15:52 UTC
Labels: Content:WebAPI
