### ISSUE TITLE
Issue with "MIME types (IANA media types)": PHP block instead of link to article

### ISSUE THREAD

**Issue by the-J** [mdn/content#10177] opened 2021-10-30 09:56 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types

#### Specific section or headline?
'Image Types'.

Under 'Image Types' section there is php block that does not display link to 'table-of-image-file-types'.
https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types 

#### What did you expect to see?
Link to table of image types. 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/basics_of_http/mime_types`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/basics_of_http/mime_types/index.md
* Last commit: https://github.com/mdn/content/commit/d9a333d16fa31a598e23d71e66da77714eaf1ebc
* Document last modified: 2021-10-28T07:36:04.000Z

</details>

**Comment by hamishwillee** [comment] 2021-10-31 23:39
Thanks for reporting. Closing as duplicate of #10181 which will be fixed by  #10193

**Closed by hamishwillee** 2021-10-31 23:39 UTC
