### ISSUE TITLE
a11y - blockquote example does not follow html spec

### ISSUE THREAD

**Issue by enumiton** [mdn/content#29446] opened 2023-10-03 18:07 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/blockquote

### What specific section or headline is this issue about?

The 'try it' section

### What information was incorrect, unhelpful, or incomplete?

The 'try it' section incorrectly shows you can put attribution within the `<blockquote>` element, however [the HTML spec](https://html.spec.whatwg.org/multipage/grouping-content.html#the-blockquote-element) notes that's incorrect and that you should put attributions outside said element.

> Attribution for the quotation, if any, must be placed outside the [`blockquote`](https://html.spec.whatwg.org/multipage/grouping-content.html#the-blockquote-element) element.

### What did you expect to see?

I suggest to follow the spec example.

```html
<blockquote cite="https://www.huxley.net/bnw/four.html">
  <p>Words can be like X-rays, if you use them properly—they’ll go through anything. You read and you’re pierced.</p>
</blockquote>
<p>— Aldous Huxley, <cite>Brave New World</cite></p>
```

Or using a figure.

```html
<figure>
  <blockquote cite="https://www.huxley.net/bnw/four.html">
    <p>Words can be like X-rays, if you use them properly—they’ll go through anything. You read and you’re pierced.</p>
  </blockquote>
  <figcaption>
    — Aldous Huxley, <cite>Brave New World</cite>
  </figcaption>
</figure>
```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/blockquote`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/blockquote
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/blockquote/index.md
* Last commit: https://github.com/mdn/content/commit/e04d8d2766c468f149445c0bf438d09f9b2d188c
* Document last modified: 2023-06-13T08:10:47.000Z

</details>

**Comment by Josh-Cena** [comment] 2023-10-03 20:01
Duplicate of https://github.com/mdn/content/issues/28401

**Closed by Josh-Cena** 2023-10-03 20:01 UTC
Labels: Content:HTML, needs triage
