### ISSUE TITLE
A bit misleading subsection!

### ISSUE THREAD

**Issue by ShihaabYF** [mdn/content#22483] opened 2022-11-22 20:45 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Aligning_Items_in_a_Flex_Container

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Aligning_Items_in_a_Flex_Container#creating_gaps_between_items

### What information was incorrect, unhelpful, or incomplete?

**The [column-gap](https://developer.mozilla.org/en-US/docs/Web/CSS/column-gap) property creates gaps between items on the main axis.**

### What did you expect to see?

This is only true if **flex-direction: row;**, otherwise {*flex-direction:column*} is **NOT**,
if we have explicitly set the **flex-direction** property to **column**, we may add the **column-gap** property to our container waiting for the gap to appear, but it will not, it only gonna work in the case of **flex-direction: row;**,
If we have a flex container that has a vertical layout {*flex-direction: column*} and our goal was to separate them we need *simply* to use the **row-gap** property!

### Do you have anything more you want to share?

[code snippet](https://jsfiddle.net/ShihaabYF/dupz4rwf/) 
Please check lines `28 & 29` in the CSS file.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/css_flexible_box_layout/aligning_items_in_a_flex_container`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Aligning_Items_in_a_Flex_Container
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_flexible_box_layout/aligning_items_in_a_flex_container/index.md
* Last commit: https://github.com/mdn/content/commit/71c4bc0b6329ec40ddbefd8d3124547e91cfa612
* Document last modified: 2022-09-28T03:40:57.000Z

</details>

**Comment by Josh-Cena** [comment] 2022-11-22 22:03
Duplicate of https://github.com/mdn/content/issues/14415

**Closed** 2022-11-22 22:04 UTC
Labels: duplicate, Content:CSS

**Comment by ShihaabYF** [comment] 2022-11-23 10:52
@Josh-Cena thanks, it's a bit more complicated than I thought!
