### ISSUE TITLE
Overwrapped UI for "Try it" section.

### ISSUE THREAD

**Issue by JeanBaek** [mdn/content#20915] opened 2022-09-20 08:33 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/throw#try_it

### What information was incorrect, unhelpful, or incomplete?

The line numbers and the content of the JavaScript Demo code are overlapped on the UI.

It seems that the latest version of the UI is not released for this page.

### What did you expect to see?

I expected that the line numbers and content of the JavaScript Demo code would be displayed properly separated.

For example, like this page below.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at#try_it

**Comment by Josh-Cena** [comment] 2022-09-20 13:04
Duplicate of https://github.com/mdn/yari/issues/6805

**Closed** 2022-09-20 13:04 UTC
Labels: Content:JS, needs-triage
