### ISSUE TITLE
Issue with "Trailer": page says all browsers are compatible but there is no way to use this feature

### ISSUE THREAD

**Issue by nickform-ost** [mdn/content#7137] opened 2021-07-21 15:59 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Trailer

#### What information was incorrect, unhelpful, or incomplete?

The page says that Trailers are available for use in all major browsers. In fact, it seems it there is no way to use them from javascript.

#### Specific section or headline?

"Browser compatibility" is the main culprit but also, given the information in [this](https://stackoverflow.com/a/48180203) SO answer, I'm a little lost as to why this page exists at all. 

#### What did you expect to see?

Maybe a thumbs down icon with a deprecation warning. I may be missing something.

#### Did you test this? If so, how?

We implemented the server side of this, encouraged by this page. Now we come to depend on that from the client side we find we can't use it from the browser (neither fetch nor XMPHttpRequest) despite wall-to-wall green in the browswer compatibility table. I'd really like to understand the disconnect here (may of course be my own understanding) but in any case, I would encourage some kind of health warning on the page if possible for future visitors.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/http/headers/trailer`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Trailer
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/trailer/index.html
* Last commit: https://github.com/mdn/content/commit/30440f2523a2c29c5c12aa18b239ee42e3f2fabc
* Document last modified: 2021-07-08T09:12:33.000Z

</details>

**Comment by nickform-ost** [comment] 2021-07-21 16:04
Just to say, I'm *incredibly* grateful for MDN in general and though I've been burned a bit here, I'm well ahead in hours saved by this wonderful resource so thank you to all the maintainers.

**Comment by sideshowbarker** [comment] 2021-07-21 23:51
@mnot, can you please advise on what at this point we should be saying about `Trailer`?

**Comment by mnot** [comment] 2021-07-22 04:00
There are two things going on here --

* Trailer fields in general -- see [the most recent spec text](https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#trailer.fields)

* The `Trailer` header field -- see [spec text](https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#field.trailer).

Firefox supports the `Server-Timing` field in trailers; I'm not aware of any other browser that does. See [this issue on Fetch](https://github.com/whatwg/fetch/issues/981) about making trailers available in browsers generally.

`Trailer` is really just a hint; there isn't any tangible what that browsers can "support" it, beyond just making it available as any other header is. Of courser, many entries in MDN state that a header is "supported" in this fashion, so I don't know that it needs to change.

However, be aware that the most recent revision of HTTP changed how headers and trailers interact -- they're now separate "buckets", and you can't just arbitrarily promote a header into a trailer, or vice versa, unless its spec says you can. 

See [this text](https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#trailers.limitations). So, I think the example given needs to change.

**Comment by nickform-ost** [comment] 2021-09-23 15:53
Thanks for the comments and the useful links. I think on reflection I should have targeted this issue at the `trailers` directive on the `TE` request header [page](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/TE). There seems to be no way that javascript can set this directive on a request in order to tell the server to include trailers.

Given that, I am still unsure what the green on the `Trailer` page means - there is no way to use the feature from javascript. What test has been met in order to decide whether a browser is compatible or not?

**Comment by hamishwillee** [comment] 2021-09-27 01:04
>  I am still unsure what the green on the Trailer page means - there is no way to use the feature from javascript. What test has been met in order to decide whether a browser is compatible or not?

No idea, but it is a general question/problem what to do about recording compatibility in BCD: https://github.com/mdn/browser-compat-data/issues/12533

**Comment by lidel** [comment] 2022-01-28 19:11
I wrote some ideas how to reduce confusion caused by the [Trailer](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Trailer) docs in https://github.com/mdn/browser-compat-data/issues/14703

In case a drive-by reader is curious about the current state, 
**no major browser engine supports reading trailers via Fetch API (from JS)**:

- Firefox: not supported – https://bugzilla.mozilla.org/show_bug.cgi?id=1339096
- Chromium: closed as **Wont Fix** – https://bugs.chromium.org/p/chromium/issues/detail?id=691599
- Webkit: https://bugs.webkit.org/show_bug.cgi?id=168232

**Comment by bsmth** [comment] 2024-11-25 08:49
Thanks for raising this. This should be resolved in the linked PR now, so I'm closing as done. See also: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Trailer#browser_compatibility

**Closed by bsmth** 2024-11-25 08:49 UTC
Labels: help wanted, Content:HTTP
