### ISSUE TITLE
`justify-self`: Missing 'Browser Compatibility' for 'block-level boxes'

### ISSUE THREAD

**Issue by felixhabib** [mdn/content#37102] opened 2024-12-05 01:01 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/justify-self

### What specific section or headline is this issue about?

justify-self

### What information was incorrect, unhelpful, or incomplete?

Missing 'Browser Compatibility' section for 'block-level boxes'

### What did you expect to see?

'block-level boxes' section in 'Browser Compatibility'. This is mentioned in the [CSS Spec](https://drafts.csswg.org/css-align/#overview) and is supported in at least Chrome version 130.

### Do you have any supporting links, references, or citations?

[CSS Spec](https://drafts.csswg.org/css-align/#overview)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/justify-self`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/justify-self
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/justify-self/index.md
* Last commit: https://github.com/mdn/content/commit/d35f4ae5143418c3b64d4f4f2c7e79419b9d434c
* Document last modified: 2024-12-03T21:38:14.000Z

</details>

**Comment by Josh-Cena** [comment] 2024-12-05 03:36
Duplicate of https://github.com/mdn/browser-compat-data/issues/24844

**Closed by Josh-Cena** 2024-12-05 03:36 UTC
Labels: Content:CSS, needs triage
