### ISSUE TITLE
Registering example does not match description

### ISSUE THREAD

**Issue by ncallaway** [mdn/content#15870] opened 2022-05-10 15:22 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/registerProtocolHandler/Web-based_protocol_handlers

### What specific section or headline is this issue about?

Registering / Example

### What information was incorrect, unhelpful, or incomplete?

The last paragraph of the body of the registering example

Registering the same protocol handler more than once will pop up a different notification, indicating that the protocol handler is already registered. **Therefore, it is a good idea to guard your call to register the protocol handler with a check to see if it is already registered, such as in the example below**.

The example itself, however, does not guard the protocol handler as promised:

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<head>
  <title>Web Protocol Handler Sample - Register</title>
  <script type="text/javascript">
    navigator.registerProtocolHandler("web+burger",
                                  "http://www.google.co.uk/?uri=%s",
                                  "Burger handler");
  </script>
</head>
<body>
  <h1>Web Protocol Handler Sample</h1>
  <p>This web page will install a web protocol handler for the <code>web+burger:</code> protocol.</p>
</body>
</html>
```

### What did you expect to see?

I expected the example to match the description text.

**Either** the description text should not promise an example which shows the registration being guarded, **or** the example should include the registration call being guarded.

I cannot find in the documentation any API for checking if the protocol handlers are already registered, so I suspect the description needs to be updated.

### Do you have any supporting links, references, or citations?

I went looking at the history of this file, to see if I could revert either the description or the example such that they matched, but this issue appears to exist since the initial commit:

https://github.com/mdn/content/blob/main/files/en-us/web/api/navigator/registerprotocolhandler/web-based_protocol_handlers/index.md?plain=1

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/navigator/registerprotocolhandler/web-based_protocol_handlers`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/registerProtocolHandler/Web-based_protocol_handlers
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/navigator/registerprotocolhandler/web-based_protocol_handlers/index.md
* Last commit: https://github.com/mdn/content/commit/4959ec02b2f5b673b48498c8a34d35316ca52429
* Document last modified: 2022-04-17T05:45:52.000Z

</details>

**Comment by laurolima** [comment] 2023-02-20 20:05
This looks like a duplicate of https://github.com/mdn/content/issues/15870

**Comment by sideshowbarker** [comment] 2023-02-21 08:50
Closing per https://github.com/mdn/content/issues/15870#issuecomment-1437496934

**Closed by sideshowbarker** 2023-02-21 08:50 UTC
Labels: Content:WebAPI
