### ISSUE TITLE
Issue with "MouseEvent.clientX": on mousemove im getting co ordinates only when i click on screen why i dont get it on hovering on screen?

### ISSUE THREAD

**Issue by KanadKJ** [mdn/content#9406] opened 2021-10-01 07:05 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/clientX

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/mouseevent/clientx`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/clientX
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/mouseevent/clientx/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by hamishwillee** [comment] 2021-10-03 23:24
I am closing because this is a technical support query, not a bug report against the docs.

That said, I just tried this on the current desktop firefox, chrome, and opera and it works as expected - moving the mouse in this area updates the position.
![image](https://user-images.githubusercontent.com/5368500/135775368-1d362eed-f15c-4399-89f7-9da39dc10411.png)

What you need to do is raise a bug against the browser that you are testing this against.

**Closed** 2021-10-03 23:25 UTC
