### ISSUE TITLE
populatedb.js uses callbacks in Model.protoype.save() which is no longer supported

### ISSUE THREAD

**Issue by cameronlyman** [mdn/content#25021] opened 2023-03-02 22:31 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose

### What specific section or headline is this issue about?

Testing — create some items

### What information was incorrect, unhelpful, or incomplete?

When running the populatedb.js script, it crashes with the MongooseError: "Model.prototype.save() no longer accepts a callback". I am using Mongoose v.7.0.0. 

### What did you expect to see?

The script to add objects to the database.

### Do you have any supporting links, references, or citations?

https://mongoosejs.com/docs/migrating_to_7.html#dropped-callback-support

### Do you have anything more you want to share?

MongooseError: Model.prototype.save() no longer accepts a callback
    at model.save (C:\Git\express-tutorial\express-locallibrary-tutorial\node_modules\mongoose\lib\model.js:497:11)
    at authorCreate (C:\Git\express-tutorial\express-locallibrary-tutorial\populatedb.js:37:10)
    at eachOfSeries (C:\Git\express-tutorial\express-locallibrary-tutorial\node_modules\async\dist\async.js:813:16)
    at awaitable (C:\Git\express-tutorial\express-locallibrary-tutorial\node_modules\async\dist\async.js:211:32)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/mongoose`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/mongoose/index.md
* Last commit: https://github.com/mdn/content/commit/4def230f85756724b59660e3cd9de363db724ef8
* Document last modified: 2023-02-24T00:05:28.000Z

</details>

**Comment by Josh-Cena** [comment] 2023-03-02 22:38
Duplicate of https://github.com/mdn/content/issues/24972

**Closed by Josh-Cena** 2023-03-02 22:38 UTC
Labels: needs triage
