### ISSUE TITLE
Live example of `@page` can't run

### ISSUE THREAD

**Issue by skyclouds2001** [mdn/content#37017] opened 2024-11-28 23:27 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/@page

### What information was incorrect, unhelpful, or incomplete?

the live example can't propertyly

### What did you expect to see?

make the example run correctly

### Do you have any supporting links, references, or citations?

see also https://github.com/mdn/yari/pull/11693

### Do you have anything more you want to share?

This happens because `Window.print()` can't run inside an `<iframe>` unless its `sandbox` attribute has the value `allow-modals`.

We may either:

- add a `allow-modals` value inside the `{{EmbedLiveSample}}` macros
- or instead add a button to tell people to open the example in the separate tab

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/@page`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/@page
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/@page/index.md
* Last commit: https://github.com/mdn/content/commit/ed9ebd794add41de1f2e759502b73e8650afe56b
* Document last modified: 2024-10-02T13:58:44.000Z

</details>

**Comment by skyclouds2001** [comment] 2024-11-28 23:33
similar macros include `JSFiddleEmbed` `EmbedLiveSample` `EmbedInteractiveExample` `EmbedYouTube` `EmbedGHLiveSample`

**Comment by Josh-Cena** [comment] 2024-11-29 02:23
Duplicate of https://github.com/mdn/content/issues/36132

**Closed by Josh-Cena** 2024-11-29 02:23 UTC
Labels: Content:CSS, needs triage
