### ISSUE TITLE
Making asynchronous processing easier - fetch example

### ISSUE THREAD

**Issue by rolandwales10** [mdn/content#13216] opened 2022-02-22 23:51 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Async_await

#### What information was incorrect, unhelpful, or incomplete?
I like your approach, but I have an example of fetch which returns json from a server and I'm not getting the data back

Here is the code I'm trying to convert:

fetch(this.contextPath + 'CITIZEN_AGREEMENTS/UpdateRow', requestOptions)
                        .then(response => response.json())
                        .then(data => {
                           this.msgs = data.messages;
                           this.ca = data.citizenAgreementsClient;
etc.

#### Did you test this? If so, how?
Yes.  I converted the above code to the following:
                    let response = await fetch(this.contextPath + 'CITIZEN_AGREEMENTS/UpdateRow', requestOptions);
response returned OK, but did not have the data I need retuned from fetch.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/asynchronous/async_await`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Async_await
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/asynchronous/async_await/index.md
* Last commit: https://github.com/mdn/content/commit/0160aac0e623dacdce4019205f32f7b3d3e58019
* Document last modified: 2022-02-18T09:33:58.000Z

</details>

**Comment by wbamberg** [comment] 2022-02-23 18:07
Thanks for filing! If there is a specific issue in the documentation, please indicate exactly where it is, if possible with a reproducible test case we can use to verify the issue. Putting a few lines of non-executable code in the comment isn't actionable for us.

Also please note that [I'm currently trying to rewrite all these pages](https://github.com/mdn/content/pull/12930), so we're unlikely to accept a specific fix in the current pages (although of course we should ensure that the issue is fixed in the new pages).

**Comment by sideshowbarker** [comment] 2022-03-08 03:39
Closing for lack of response

**Closed by sideshowbarker** 2022-03-08 03:39 UTC
Labels: Content:JS, needs info
