### ISSUE TITLE
Issue with "Using IndexedDB": "Updating an entry in the database" example does not work

### ISSUE THREAD

**Issue by ale-jr** [mdn/content#5463] opened 2021-05-30 02:45 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB

#### What information was incorrect, unhelpful, or incomplete?
The code at "Updating an entry in the database" is adding a new entry instead of updating the existing one 

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB#updating_an_entry_in_the_database

#### What did you expect to see?
According to the [ObjectStore put docs](https://developer.mozilla.org/en-US/docs/Web/API/IDBObjectStore/put), to update an entry it is required to have a key as a second parameter, the current example calls put like this: `var requestUpdate = objectStore.put(data);` and it should be something like `var requestUpdate = objectStore.put(data,"444-44-4444");`

#### Did you test this? If so, how?
I tried to execute the example as is and it adds a new entry, adding the key as a second param updates the entry

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/indexeddb_api/using_indexeddb`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/indexeddb_api/using_indexeddb/index.html
* Last commit: https://github.com/mdn/content/commit/12024ee393c3fe3101b03903561c640444b38646
* Document last modified: 2021-04-08T14:57:07.000Z

</details>

**Comment by bsmth** [comment] 2022-10-20 15:27
Hi @ale-jr, thanks a lot for raising this one. I tried to reproduce this, but it looks like the examples are correctly editing records in-place with `put()`. New entries are created with `put()` if not already existing. The key is optional `put(item, key)`, but in our case, we are editing after an explicit `get()` and we have the object already:

```js
const request = objectStore.get("444-44-4444");
request.onsuccess = (event) => {
  const data = event.target.result;
  // updating
  age = 42;
  // Putting this object back
  const requestUpdate = objectStore.put(data);
// ...
```

I've created a gist that reproduces these examples in one go, feel free to take a look and try it: https://gist.github.com/bsmth/427078c8024a62ec8d14e326baeb04ad

I'm going to close this one for now. If you think this is a mistake or doesn't make sense, feel free to leave another comment. Thank you :)

**Closed by bsmth** 2022-10-20 15:27 UTC
Labels: help wanted, Content:WebAPI, time: -30mins, 🐌 idle
