### ISSUE TITLE
Issue with "console": Substitution Strings row appears multiple times in Browser Compatibility table

### ISSUE THREAD

**Issue by DreadLordMikey** [mdn/content#14434] opened 2022-03-29 16:18 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/console

#### What information was incorrect, unhelpful, or incomplete?
Substitution Strings appears multiple times in the Browser Compatibility table. The number of times it appears seems to change each time you view the age.

#### Specific section or headline?
Browser Compatibility table

#### What did you expect to see?
Substitution Strings should only appear once.

#### Did you test this? If so, how?
Yes; viewing the page. Refreshing the page. Closing the page and re-opening it.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/console`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/console
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/console/index.md
* Last commit: https://github.com/mdn/content/commit/672bace59f60c4931e5cdde8eb32919c924bd191
* Document last modified: 2022-03-14T00:26:56.000Z

</details>

**Comment by teoli2003** [comment] 2022-03-29 16:51
They are subfeatures. But I agree it isn't clear that they are such.

mdn/yari#5851 is a PR trying to fix this.

I'm closing this as a duplicate of mdn/yari#5843, feel free to reopen if I'm mistaken.

**Closed by teoli2003** 2022-03-29 16:51 UTC
Labels: needs-triage
