### ISSUE TITLE
Error in example launch_handlers example

### ISSUE THREAD

**Issue by salsaverde123** [mdn/content#28931] opened 2023-09-04 18:06 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Manifest/launch_handler

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/Manifest/launch_handler#examples

### What information was incorrect, unhelpful, or incomplete?

"launch_handler": {
    "client_mode": ["focus-existing, auto"]
}

### What did you expect to see?

"launch_handler": {
    "client_mode": ["focus-existing", "auto"]
}

### Do you have anything more you want to share?

![image](https://github.com/mdn/content/assets/23236388/39d5fabc-ea94-4108-811a-c7ddf14a18f1)

This is the error that it shows when use the example code.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/manifest/launch_handler`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Manifest/launch_handler
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/manifest/launch_handler/index.md
* Last commit: https://github.com/mdn/content/commit/0c015b80f786ecc4547c3e37a70c7f6aafdfbf74
* Document last modified: 2023-06-28T16:16:20.000Z

</details>

**Comment by wbamberg** [comment] 2023-09-04 23:46
Duplicate of https://github.com/mdn/content/issues/28899. Thanks for filing, though!

**Closed by wbamberg** 2023-09-04 23:46 UTC
Labels: needs triage, Content:Manifest
