### ISSUE TITLE
prompt() call in code example does not fire

### ISSUE THREAD

**Issue by cyphersept** [mdn/content#36172] opened 2024-10-03 05:18 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Strings

### What specific section or headline is this issue about?

Concatenation in context

### What information was incorrect, unhelpful, or incomplete?

The demo code uses `prompt()` to demonstrate concatenation. However, when the button is clicked, the prompt call from the code snippet context is ignored, and the displayed message immediately becomes "Hello null, nice to see you!“

Chromium browsers log: "Ignored call to 'prompt()'. The document is sandboxed, and the 'allow-modals' keyword is not set."

### What did you expect to see?

A pop-up prompt asking "What is your name?"

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/first_steps/strings`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Strings
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/first_steps/strings/index.md
* Last commit: https://github.com/mdn/content/commit/23e1a97d50050a3b3518a4b2f67ccf42e5fd75b7
* Document last modified: 2024-06-28T03:14:04.000Z

</details>

**Comment by Josh-Cena** [comment] 2024-10-03 05:44
Duplicate of https://github.com/mdn/content/issues/7566

**Closed by Josh-Cena** 2024-10-03 05:44 UTC
Labels: needs triage, Content:Learn:JavaScript
