### ISSUE TITLE
Dialog: Closing via method="dialog" (or `formmethod`) does nothing

### ISSUE THREAD

**Issue by hicallmeal** [mdn/content#36676] opened 2024-11-06 13:54 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/close_event

### What specific section or headline is this issue about?

The live example

### What information was incorrect, unhelpful, or incomplete?

The `<button>Close via method="dialog"</button>` does nothing on click

Firefox latest (132) and Chrome latest (130).

### What did you expect to see?

My understanding of `method="dialog"` forms and `formmethod="dialog"` buttons is that they close dialogs without form submission, however, the dialogs do not close.

### Do you have any supporting links, references, or citations?

This happens on at least these examples/pages
[\<Dialog> page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog#handling_the_return_value_from_the_dialog) (**"Cancel"** button)
[returnValue page](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/returnValue#examples) (**"(x)"** button)

And I'm sure there can be more examples found.

### Do you have anything more you want to share?

Semi-related, the same behaviour (of nothing happening) occurs in [this example](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog#closing_a_dialog_with_a_required_form_input) too, for two buttons.

I'd like to note, that I'm this has been the case for a few months now, but I never went to report it.
So it's not from the latest versions (or last ~15, I'd estimate). 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/htmldialogelement/close_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/close_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmldialogelement/close_event/index.md
* Last commit: https://github.com/mdn/content/commit/981ab25c61986b40213d0c84131432438d5a7903
* Document last modified: 2024-08-14T10:26:22.000Z

</details>

**Comment by Josh-Cena** [comment] 2024-11-06 15:14
Duplicate of https://github.com/mdn/yari/issues/11460

**Closed by Josh-Cena** 2024-11-06 15:14 UTC
Labels: Content:HTML, Content:WebAPI, needs triage
