### ISSUE TITLE
Conflicting documentation

### ISSUE THREAD

**Issue by julian-hansen** [mdn/content#26165] opened 2023-04-12 17:52 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event

### What specific section or headline is this issue about?

deprecation of returnValue

### What information was incorrect, unhelpful, or incomplete?

The sample suggests that the returnValue on the event be set to tell the browser to show a stay on page / leave message. However in this doc https://developer.mozilla.org/en-US/docs/Web/API/Event/returnValue there is a deprecation warning saying don't use it. I would change it however still searching for what the replacement is for the solution presented. Omitting the assignment to the returnValue property breaks the functionality of showing the stay on page / leave dialog

### What did you expect to see?

Consistency between the two pages AND an alternative solution to the befureunload handler to show the stay on page / leave message

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/API/Event/returnValue

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/window/beforeunload_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/window/beforeunload_event/index.md
* Last commit: https://github.com/mdn/content/commit/cc070123f72376faec06e36622c4fc723a75325f
* Document last modified: 2023-04-08T06:57:07.000Z

</details>

**Comment by Josh-Cena** [comment] 2023-04-12 17:59
Duplicate of #23837

**Closed by Josh-Cena** 2023-04-12 17:59 UTC
Labels: Content:WebAPI, needs triage
