### ISSUE TITLE
tspan example does not display correctly in Safari Version 16.3 (18614.4.6.1.6) on MacOS Ventura 13.2.1 (22D68)

### ISSUE THREAD

**Issue by gskluzacek** [mdn/content#34328] opened 2024-06-21 16:37 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Texts

### What specific section or headline is this issue about?

tspan

### What information was incorrect, unhelpful, or incomplete?

when browsing the web page with Safari, the part of the text that is supposed to be displayed in red bold was not rendered where you could see all of it, one could only see the last line of pixels of the red bold text. Like the "dominant-baseline: hanging" style was not applied to it. Additionally, if I save the svg given in the example as a file to my Mac and select the file and press the command space-bar to preview the file, it also does not display correctly. 

this is what is shown in Safari (incorrect)
![image](https://github.com/mdn/content/assets/15515/328584fb-0a71-4199-b1c7-0f748055d6d6)

this is what is shown in the Finder (incorrect)
![image](https://github.com/mdn/content/assets/15515/e9722ed4-535a-4824-b563-bad80210aace)

and this is what is shown in Google Chrome
![image](https://github.com/mdn/content/assets/15515/8bf34fd6-f06c-47db-935e-f0729b6dfd63)

### What did you expect to see?

I expected to see the red bold text on the same baseline as the black text

### Do you have anything more you want to share?

for some reason, the example svg code given, when displayed in both Safari and Google Chrome, displays the XML CDATA text instead of just the style text... see below (from Google Chrome). I've seen this in multiple code examples.

![image](https://github.com/mdn/content/assets/15515/c5a42e58-ee21-4892-aa7b-ff4931c0057d)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/svg/tutorial/texts`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Texts
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/tutorial/texts/index.md
* Last commit: https://github.com/mdn/content/commit/32d1c9ff83019f8efae3e7987a55e83035e4b926
* Document last modified: 2023-08-25T22:38:09.000Z

</details>

**Comment by Josh-Cena** [comment] 2024-06-21 16:43
I can confirm it's an issue with Safari but someone should look more into why.

As for the CDATA, that's because we are literally writing the CDATA in the source code for this SVG.

**Comment by Josh-Cena** [comment] 2024-06-21 19:04
The issue is that the `tspan` is not inheriting `dominant-baseline` from `text`, causing it to go above the window. It's this issue: https://bugs.webkit.org/show_bug.cgi?id=139258

Since it's a browser bug, I'm going to close it. There are a lot of related SVG bugs with Safari.

**Closed by Josh-Cena** 2024-06-21 19:04 UTC
Labels: Content:SVG, needs triage
