### ISSUE TITLE
Docs for Image srcset has a note about a required sizes attributes which seems wrong

### ISSUE THREAD

**Issue by eins78** [mdn/content#30777] opened 2023-12-04 14:43 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/srcset

### What specific section or headline is this issue about?

HTMLImageElement: srcset property

### What information was incorrect, unhelpful, or incomplete?

> Note: If the [srcset](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#srcset) attribute uses width descriptors, the sizes attribute must also be present, or the srcset itself will be ignored.

### What did you expect to see?

According to the spec, and browser behaviour (Firefox, Chrome, Safari) this note is wrong. The `srcset` attribute is not ignored when no `sizes` are set, or at least not in all cases (I did not read the whole spec, but at least for my sample code it works).

### Do you have any supporting links, references, or citations?

spec: https://html.spec.whatwg.org/multipage/embedded-content.html#dom-img-srcset

### Do you have anything more you want to share?

my test code, the source set is used:

```
<picture>
        <img
            src="images/440x293/nasa.jpg"
            srcset="
                images/362x242/nasa.jpg   362w,
                images/456x304/nasa.jpg   456w,
                images/440x293/nasa.jpg   440w,
                images/500x334/nasa.jpg   500w,
                images/725x484/nasa.jpg   725w,
                images/728x485/nasa.jpg   728w,
                images/880x586/nasa.jpg   880w,
                images/912x608/nasa.jpg   912w,
                images/1000x668/nasa.jpg 1000w,
                images/1456x970/nasa.jpg 1456w
            "
            alt="Blog"
    /></picture>
```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/htmlimageelement/srcset`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/srcset
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlimageelement/srcset/index.md
* Last commit: https://github.com/mdn/content/commit/2f56f8532de673cfcf4d37fe26503739b95d54ef
* Document last modified: 2023-10-23T14:39:09.000Z

</details>

**Comment by Josh-Cena** [comment] 2023-12-04 17:11
Duplicate of https://github.com/mdn/content/issues/27291

**Closed by Josh-Cena** 2023-12-04 17:11 UTC
Labels: Content:HTML, Content:WebAPI, needs triage
