### ISSUE TITLE
Example does not work as expected

### ISSUE THREAD

**Issue by mangelozzi** [mdn/content#28523] opened 2023-08-11 15:38 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog

### What specific section or headline is this issue about?

Advanced example -> Javascript

### What information was incorrect, unhelpful, or incomplete?

The example is supposed to close the dialogue when one clicks:
```
<button value="cancel" formmethod="dialog">Cancel</button>
```
It does not work for me in Chrome 114 or in Firefox 116.

### What did you expect to see?

The dialog to close

### Do you have any supporting links, references, or citations?

[Advanced example](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog#advanced_example)
The text says:
> In this example, the "Cancel" button closes the dialog via the dialog form method and the "Confirm" closes the dialog via the [HTMLDialogElement.close()](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/close) method.

However the "form method" does not close it

### Do you have anything more you want to share?

MDN docs are really great thanks!

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/dialog`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/dialog/index.md
* Last commit: https://github.com/mdn/content/commit/e04d8d2766c468f149445c0bf438d09f9b2d188c
* Document last modified: 2023-06-13T08:10:47.000Z

</details>

**Comment by alabhyajindal** [comment] 2023-08-14 17:16
Hey, I tried reproducing the issue you mentioned but failed. 

The dialog box is closing for me on Firefox 116 and Chrome 115 on clicking the 'Close' button. I have attached a video for your reference. 

https://github.com/mdn/content/assets/52493077/3c75e726-e74b-4a2f-b8a6-3e597525a82b

**Comment by hamishwillee** [comment] 2023-08-14 21:53
Closing as unable to reproduce - I've tested this on FF116 and Chrome 115.

It may be that this was a transient issue on your computer as the code itself is correct.

**Closed by hamishwillee** 2023-08-14 21:53 UTC
Labels: help wanted, Content:HTML, Content:WebAPI
