### ISSUE TITLE
Issue with "Marking up a letter": expects that the user already understand what is a css file, which no happened on previous lessons

### ISSUE THREAD

**Issue by flaviomorgado** [mdn/content#11730] opened 2022-01-04 18:00 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Marking_up_a_letter

#### What information was incorrect, unhelpful, or incomplete?
This assessment expects that the user already understand what is a css file, which no happened on previous lessos

#### What did you expect to see?
A CSS primer on previous lessons before the assessment be proposed.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/introduction_to_html/marking_up_a_letter`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Marking_up_a_letter
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/html/introduction_to_html/marking_up_a_letter/index.md
* Last commit: https://github.com/mdn/content/commit/07453ac2b659a397b0fee921fa71db5488e9ca62
* Document last modified: 2021-10-08T14:43:33.000Z

</details>

**Comment by Josh-Cena** [comment] 2022-12-23 03:47
Duplicate of https://github.com/mdn/content/issues/11728

**Closed by Josh-Cena** 2022-12-23 03:47 UTC
Labels: Content:Learn
