### ISSUE TITLE
-moz-drag-over has no compatibility data

### ISSUE THREAD

**Issue by Akindin** [mdn/content#32724] opened 2024-03-18 14:02 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/:-moz-drag-over

### What information was incorrect, unhelpful, or incomplete?

No compatibility information

### What did you expect to see?

Compatibility information or possibly page removal as it seems like this pseudo-class not supported in modern Firefox.

### Do you have anything more you want to share?

https://codepen.io/Akindin/pen/oNOBXbz

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/_colon_-moz-drag-over`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:-moz-drag-over
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/_colon_-moz-drag-over/index.md
* Last commit: https://github.com/mdn/content/commit/31c12da682b2d4d370f3e1f00342a3b06a438144
* Document last modified: 2023-06-12T16:06:42.000Z

</details>

**Comment by hamishwillee** [comment] 2024-03-18 23:21
Perhaps first raise a https://bugzilla.mozilla.org/show_bug.cgi report and cross link? (I searched and can't find anything indicating that this is expected).

**Comment by bsmth** [comment] 2024-03-21 16:54
The (empty) compat section was removed here:

- [x] https://github.com/mdn/content/pull/27247

And there's a duplicate of this issue: 

- [x] https://github.com/mdn/content/issues/27256

I have a suspicion the pseudo has been long-removed since drag and drop APIs were introduced.

**Comment by hamishwillee** [comment] 2024-03-21 23:37
Cool! @Akindin Did you raise an issue? Can you cross link it?

**Comment by Akindin** [comment] 2024-03-22 11:32
@hamishwillee I don't know how, I have not worked with bugzilla

**Comment by bsmth** [comment] 2024-03-22 13:43
Actually it looks like this is still supported:

* https://searchfox.org/mozilla-central/source/servo/components/style/gecko/non_ts_pseudo_class_list.rs#48
* https://searchfox.org/mozilla-central/source/dom/events/test/bug591249_iframe.xhtml

Demo based on bug591249: https://codepen.io/bsmth/pen/qBwmqOz

**Comment by hamishwillee** [comment] 2024-03-24 23:11
Thanks @bsmth - I wrote a similar example that didn't work - must have screwed up. Anyway, have created https://github.com/mdn/content/pull/32814 that replaces the examples with your codepen. That verifies this works, so when merged will close this issue.

**Closed** 2024-03-26 08:34 UTC
Labels: needs triage

**Comment by hamishwillee** [comment] 2024-03-31 23:55
FWIW  page still doesn't have compatibility data, but it is at least easy to test compatibility now.
