### ISSUE TITLE
Missing HTML attributes meta issue

### ISSUE THREAD

**Issue by rachelandrew** [mdn/content#1712] opened 2021-01-25 11:26 UTC
In looking into https://github.com/mdn/content/issues/1510 realised we don't have docs for a whole bunch of attributes. I'm going to pick them off, but I thought I would list them here and if anyone else fancies writing one just add a comment.

The page that lists them is at: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes

It is likely that some of these are documented but within details of the element they relate to, in that case it may just be that the link needs updating. At the moment all of these 404.

- [ ] `accept-charset`
- [ ] `action`
- [ ] `align`
- [ ] `allow`
- [ ] `alt`
- [ ] `async`
- [ ] `autofocus`
- [ ] `autoplay`
- [ ] `buffered`
- [ ] `charset`
- [ ] `checked`
- [ ] `cite`
- [ ] `code`
- [ ] `codebase`
- [ ] `cols`
- [ ] `colspan`
- [ ] `content`
- [ ] `contextmenu`
- [ ] `controls`
- [ ] `coords`
- [ ] `data`
- [ ] `datetime`
- [ ] `decoding`
- [ ] `default`
- [ ] `defer`
- [ ] `dirname`
- [ ] `download`
- [ ] `enctype`
- [ ] `enterkeyhint`
- [x] `for`
- [ ] `form`
- [ ] `formaction`
- [ ] `formenctype`
- [ ] `formmethod`
- [ ] `formnovaliddate`
- [ ] `formtarget`
- [ ] `headers`
- [ ] `high`
- [ ] `href`
- [ ] `hreflang`
- [ ] `http-equiv`
- [ ] `icon`
- [ ] `importance`
- [ ] `kind`
- [ ] `label`
- [ ] `language`
- [ ] `loading`
- [ ] `list`
- [ ] `loop`
- [ ] `low`
- [ ] `media`
- [ ] `method`
- [ ] `muted`
- [ ] `name`
- [ ] `novalidate`
- [ ] `open`
- [ ] `optimum`
- [ ] `placeholder`
- [ ] `poster`
- [ ] `preload`
- [ ] `referrer-policy`
- [ ] `reversed`
- [ ] `rows`
- [ ] `rowspan`
- [ ] `scope`
- [ ] `scoped`
- [ ] `selected`
- [ ] `shape`
- [ ] `sizes`
- [ ] `slot`
- [ ] `span`
- [ ] `src`
- [ ] `srcdoc`
- [ ] `srclang`
- [ ] `srcset`
- [ ] `start`
- [ ] `summary`
- [ ] `target`
- [ ] `type`
- [ ] `usemap`
- [ ] `value`
- [ ] `width`
- [ ] `wrap`

**Comment by Ryuno-Ki** [comment] 2021-01-25 20:20
Thank you so much!
Do you have a preferred „template” to structure the documents? (In case somebody is picking up an article)

Would there be value in „stubbed” articles which contain basic information, but perhaps lack certain details?

**Comment by rachelandrew** [comment] 2021-01-25 20:30
There are guidelines in the docs, these are going to be similar to an [HTML element reference page](https://developer.mozilla.org/en-US/docs/MDN/Structures/Page_types#html_element_reference_page) however being an attribute they will all be a little different to each other. The attributes don't apply to all elements, and apply differently depending on where they are used.

**Comment by Ryuno-Ki** [comment] 2021-01-25 20:35
I just discovered https://github.com/mdn/content/issues/1707 also.

The mentioned guidelines likely refer to https://github.com/mdn/content#adding-a-new-document

However, I'm more concerned about the structure (like, which headlines should be included. What other data can be used? (Interactive Demos, BCD table etc), which links are apt for being shown in the „see also” part at the end).

This way, it comes down to „fill in the blanks” instead of thinking about how to start.
Copying from an existing document implies, that there is already an agreed upon format (which I cannot confirm).

**Comment by Elchi3** [comment] 2021-01-27 14:06
I've been trying to get all the global attributes documented under https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes, however I wonder if It really makes sense to have a similar page tree for non-global attributes under https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes

If you document non-global attributes under that tree, then you get into the awkward situation of describing several uses of the attribute, like done on https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/for. So, what's the motivation for this page? Do people search for "html for attribute" and then need a disambiguation page? Wouldn't they rather want to search for "for label element" or so? The page reads to me like you would always need to go to either the `<label>` page or the `<output>` page if you want to really know about it. So, if we really want to populate such a tree for non-global attributes, how can we make the pages useful?

**Comment by rachelandrew** [comment] 2021-01-27 14:25
@Elchi3 the page for `for` was exactly because someone was looking for information on `for`, so yes people are doing that.

It may be that some atts don't need their own page if we can have a way of linking to them within an element. Atts that only ever apply to one element for example, however atts that apply to some but not all elements I think there is a strong case for documenting. If a person is trying to use that attribute and it doesn't work, perhaps due to it not applying to the element they are using it on, they are very likely to search for the attribute.

**Comment by Ryuno-Ki** [comment] 2021-01-31 14:53
@Aayushap1 is going to work on the `async` attribute page (perhaps also `defer`) and tracks the progress in #1899

**Comment by Aayushap1** [comment] 2021-02-01 09:30
@Ryuno-Ki you can assign this task to me

**Comment by Aayushap1** [comment] 2021-02-01 09:30
> @Aayushap1 is going to work on the `async` attribute page (perhaps also `defer`) and tracks the progress in #1899

this one

**Comment by Elchi3** [comment] 2021-02-01 09:49
> @Elchi3 the page for `for` was exactly because someone was looking for information on `for`, so yes people are doing that.

Thanks for elaborating this some more, @rachelandrew! Makes sense to me then.


> @Ryuno-Ki you can assign this task to me

@Aayushap1 looks like #1899 is already assigned to you. Cheers!

**Comment by Aayushap1** [comment] 2021-02-01 09:51
Ok sir

**Comment by Aayushap1** [comment] 2021-02-01 10:21
sir, please provide me data or link which I have to add in **async and defer.**

**Comment by Aayushap1** [comment] 2021-02-01 10:47
I got it !!!! and I started working on **asyn** so I will submit PR with in 24 hours from now

**Comment by Aayushap1** [comment] 2021-02-01 12:48
@rachelandrew , @Ryuno-Ki ,  @Elchi3 I solved the issue #1899 please review and merge my pull request

**Comment by Aayushap1** [comment] 2021-02-01 17:49
Hello @Ryuno-Ki  @rachelandrew ,
I need your help, after first review when I updated the pull request file. It is **getting 1 check failure**. I have checked several times, but the I feel code is correct. Please help me in merging my pull request to your repo. 
Please **review my pull request**

**Comment by Ryuno-Ki** [comment] 2021-02-01 18:02
Dear @Aayushap1,
I just came back from my work. Give me some minutes to check the PR.
Thanks for your patience.

**Comment by Ryuno-Ki** [comment] 2021-02-01 18:05
Okay, it looks like you confused some bits: https://github.com/Aayushap1/content/pull/1
The PR needs to go against `mdn/content` and not against the fork you've opened to add changes.

Or perhaps the PR is https://github.com/mdn/content/pull/1943 ?

**Comment by Aayushap1** [comment] 2021-02-01 18:23
sorry I named wrong name to the file.
Now every thing is fine
Please  review my pull request #1943 and merge

**Comment by Ryuno-Ki** [comment] 2021-02-01 18:26
I can confirm, that the tests pass now. I leave the review to Rachel.

**Comment by Aayushap1** [comment] 2021-02-01 18:26
Thanks sir

**Comment by Aayushap1** [comment] 2021-02-02 05:38
@rachelandrew I fixed #1899 .  Please review my PR #1943.

**Comment by Ryuno-Ki** [comment] 2021-02-02 07:06
@Aayushap1 Please be patient. Rachel will take a look at it when she got time.

**Comment by Aayushap1** [comment] 2021-02-02 07:08
Ok sir

**Comment by Aayushap1** [comment] 2021-02-02 13:35
I send a PR #2007 it is getting an error.
When anyone is free, please help in resolving that.
I created a file for accept-charset

**Comment by Aayushap1** [comment] 2021-02-02 16:12
#2007 just need to reviewed. Please review @rachelandrew when you are free.

**Comment by Aayushap1** [comment] 2021-02-02 16:32
I solved 

- [ ] action                     PR #2013
- [ ] accept-charset        PR #2007 
- [ ] async  - [ ] defer      PR #1943

**Comment by Aayushap1** [comment] 2021-02-03 16:10
@rachelandrew @Ryuno-Ki  . Mam, I request you please review last time  #1943 #2007 #2013 .
I want to make lot of contributions as much as I can to your repo .
Please help me by reviewing my PR.

**Comment by Aayushap1** [comment] 2021-02-03 16:31
@rachelandrew Please review my PR #1943

**Comment by chrisdavidmills** [comment] 2021-02-03 19:03
@Aayushap1 Hello there. I must first say thank you for your interest in contributing to our project. This is much appreciated.

I do however have a couple of points to bring to your attention:

1. @rachelandrew and I reviewed your pull requests (#1943 #2007 #2013) and found that in all three cases, the content contained passages copied from W3Schools. It is not acceptable to copy content from other sources onto MDN. We pride outselves in having original content wherever possible, and the other sources will likely either be copyrighted (meaning that using their content is not permitted) or published under an open license (meaning that using the content has certain conditions attached to it).

   We have a policy on copying content recorded here: https://github.com/mdn/content/blob/main/README.md#can-i-copy-content-from-other-sources-to-put-on-MDN 

   Generally I would say that you are welcome to use other sites as information sources, as long as you rewrite the content in your own words.

   I am therefore going to close your current PRs, and request that you open new ones featuring original content. 

2. You seem to be very impatient about getting reviews. Please remember that our community members are very busy, and in a lot of cases they are doing this work in their spare time, unpaid. It is reasonable to ping someone to remind them about a review after a few days, but several times in a couple of days is a bit much.

Thanks for listening, and again, we appreciate your contributions.

**Comment by Aayushap1** [comment] 2021-02-04 12:39
@rachelandrew @Ryuno-Ki 
I solved : 
- [x] async  and defer      PR #2070
- [x] accept-charset         PR #2072  
- [ ] action                     PR

**Comment by Rumyra** [comment] 2022-08-26 10:25
I'm closing this issue until we have a consensus here https://github.com/mdn/mdn-community/discussions/200 in which case we can reference it and create new issues with smaller tasks for the work 👍

**Closed by Rumyra** 2022-08-26 10:25 UTC
Labels: Content:HTML, idle, 🐌 idle
