### ISSUE TITLE
Using custom elements - contradicting information

### ISSUE THREAD

**Issue by caldwell-63** [mdn/content#25797] opened 2023-03-31 05:27 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements

### What specific section or headline is this issue about?

Autonomous custom elements, second code snippet | https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements#autonomous_custom_elements

### What information was incorrect, unhelpful, or incomplete?

"Inside the method connectedCallback, we define all the functionality the element will have when the element is connected to the DOM. In this case we attach a shadow root to the custom element, use some DOM manipulation to create the element's internal shadow DOM structure — which is then attached to the shadow root — and finally attach some CSS to the shadow root to style it. We don't use constructor() because an element's attributes are unavailable until connected to the DOM."

- **"Inside the method connectedCallback"**
- **"We don't use constructor() because an element's attributes are unavailable until connected to the DOM."**

Then, directly under that is some part of a snippet, that does bunch of things but it is not clear where does it belong.

We look into the linked the full example and see:

https://github.com/mdn/web-components-examples/blob/main/popup-info-box-web-component/main.js
```js
class PopUpInfo extends HTMLElement {
  constructor() {
    // Always call super first in constructor
    super();

    // Create a shadow root
    const shadow = this.attachShadow({mode: 'open'});

   // ......
```

The code is in fact in the constructor directly contradicting previous statements.

???

### What did you expect to see?

Not contradicting information

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/web_components/using_custom_elements`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/web_components/using_custom_elements/index.md
* Last commit: https://github.com/mdn/content/commit/b01008f185ef0f6ca6603b02b71fb784c109e0ac
* Document last modified: 2023-03-03T04:47:01.000Z

</details>

**Comment by Josh-Cena** [comment] 2023-03-31 05:28
Duplicate of #22887

**Closed by Josh-Cena** 2023-03-31 05:28 UTC
Labels: needs triage
