### ISSUE TITLE
Adding Bootstrap tutorial

### ISSUE THREAD

**Issue by Sazidul008** [mdn/content#8756] opened 2021-09-07 03:09 UTC
Hey there, MDN team, please add full length of tutorial of bootstrap, thank you

**Comment by himanshugarg** [comment] 2021-09-08 22:54
Possible duplicate of issue #8748

**Comment by sideshowbarker** [comment] 2021-09-09 05:54
Closing as a duplicate of #8748

**Closed by sideshowbarker** 2021-09-09 05:54 UTC
Labels: duplicate
