### ISSUE TITLE
Font color is to white

### ISSUE THREAD

**Issue by BerndHme** [mdn/content#34880] opened 2024-07-17 05:41 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label

### What information was incorrect, unhelpful, or incomplete?

The main content is pure white color.
It burns in the readers eyes.

### What did you expect to see?

A soft grey font color.

### Do you have any supporting links, references, or citations?

To me it's obvious that a default white fontcolor is to bright in darkmode.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/accessibility/aria/attributes/aria-label`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/accessibility/aria/attributes/aria-label/index.md
* Last commit: https://github.com/mdn/content/commit/019ca5c9ce641bfa02825e1ba0444f35dfb646cc
* Document last modified: 2024-04-17T05:19:10.000Z

</details>

**Comment by Josh-Cena** [comment] 2024-07-17 13:13
Assuming you are talking about MDN itself: duplicate of https://github.com/mdn/yari/issues/7705

**Closed by Josh-Cena** 2024-07-17 13:13 UTC
Labels: Content:Accessibility, needs triage
