### ISSUE TITLE
The example before improvement is the same as after improvement

### ISSUE THREAD

**Issue by Aeolusw** [mdn/content#19515] opened 2022-08-13 16:11 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Strings

### What specific section or headline is this issue about?

Concatenation using "+"

### What information was incorrect, unhelpful, or incomplete?

![image](https://user-images.githubusercontent.com/32787759/184501486-c1ad4da3-0322-40d0-a421-a336dd497e45.png)
The example before improvement is the same as after improvement

### What did you expect to see?

The example before improvement should be less readable using the + operator.
May like:
``console.log(`${greeting}` + `, ${name}`); // "Hello, Chris"``

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/first_steps/strings`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Strings
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/first_steps/strings/index.md
* Last commit: https://github.com/mdn/content/commit/b2c68bee3964b6f1984ba1234d46f62223a825a2
* Document last modified: 2022-08-12T04:29:59.000Z

</details>

**Comment by Josh-Cena** [comment] 2022-08-13 18:14
Duplicate of #19510

**Closed** 2022-08-13 18:14 UTC
Labels: duplicate, Content:Learn:JavaScript
