### ISSUE TITLE
Issue with "position": fixed 

### ISSUE THREAD

**Issue by Germxu** [mdn/content#5044] opened 2021-05-17 04:02 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/position

#### What information was incorrect, unhelpful, or incomplete?

**Fixed:**  It is positioned relative to the initial containing block established by the viewport, 
**except when one of its ancestors has a transform, perspective, or filter property set to something other than none**
 (see the CSS Transforms Spec), in which case that ancestor behaves as the containing block.

**NEW SPEC REPORT** :   When filter property was set to opacity, blur, grayscale, invert, contrast, brightness... , not transforms, Fixed will still work relative to the initial containing block established by the viewport, I found this issue in Chrome , but Firefox worked like MDN spec

#### Specific section or headline?
syntax / fixed

#### Did you test this? If so, how?
I just found this spec in Chrome latest version

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/position`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/position
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/position/index.html
* Last commit: https://github.com/mdn/content/commit/775066d2fc8d1561d5da61983d137c1297899315
* Document last modified: 2021-05-08T09:57:47.000Z

</details>

**Comment by rachelandrew** [comment] 2021-05-17 08:04
Hi @Germxu do you have a test case as I am struggling to understand the issue, are you reporting a problem with Chrome?

As per the spec: https://www.w3.org/TR/filter-effects-1/#FilterProperty

> "A value other than none for the filter property results in the creation of a containing block for absolute and fixed positioned descendants unless the element it applies to is a document root element in the current browsing context."

So I believe MDN to be correct in this case.

**Comment by Germxu** [comment] 2021-05-17 11:25
Sorry I made a mistake, this issue actually is **When I set  these filter properties to the html node, not body or other sub nodes,  there will be some different between Firefox and Chrome** 
Look on https://codepen.io/germxu/pen/eYvdOrj

**Comment by Germxu** [comment] 2021-05-17 13:06
I see this is a bug on Firefox, Chrome is right, so this doc should  make a update( about filter on root element won`t be  established a containing block)?
https://bugzilla.mozilla.org/show_bug.cgi?id=1423746

**Comment by rachelandrew** [comment] 2021-05-17 15:12
I think probably the place to raise the issue is on the BCD repo as it's in that table this should be noted https://developer.mozilla.org/en-US/docs/Web/CSS/position#browser_compatibility

**Comment by rachelandrew** [comment] 2021-05-19 05:55
BCD issue is here https://github.com/mdn/browser-compat-data/issues/10510 so I'll close this as any change will be via BCD updates.

**Closed by rachelandrew** 2021-05-19 05:55 UTC
Labels: Content:CSS, needs info
