### ISSUE TITLE
“Styling links” article: I have some confusion about the example for styling links as button

### ISSUE THREAD

**Issue by solunk** [mdn/content#16743] opened 2022-05-28 16:44 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Styling_links

### What specific section or headline is this issue about?

Styling links as buttons

### What information was incorrect, unhelpful, or incomplete?

The explanation of css of the emxaple said list items are all put on the same line as each other., however, the last list item is broken onto a new line that is displayed in the output box. I am confused about it. I don't know if it is my problem or something else wrong.

### What did you expect to see?

Could you please explain what's going on there?

### Do you have any supporting links, references, or citations?

#

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/css/styling_text/styling_links`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Styling_links
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/styling_text/styling_links/index.md
* Last commit: https://github.com/mdn/content/commit/093b2e08fb72d88c66cca53a6e88e5ca471631f4
* Document last modified: 2022-05-16T14:30:33.000Z

</details>

**Comment by wbamberg** [comment] 2022-05-29 03:06
You are right. It looks like this issue was caused by https://github.com/mdn/content/pull/15830/files, which added line breaks to the HTML for readability: however as the page says:

> You may have noticed that the list items in the HTML are all put on the same line as each other. This is done because spaces/line breaks in between inline block elements create spaces on the page, just like the spaces in between words; however, such spaces would break our horizontal navigation menu layout. So we've removed them. You can find more information about this problem (and solutions) at [Fighting the space between inline block elements](https://css-tricks.com/fighting-the-space-between-inline-block-elements/).

Here's a version with the linebreaks removed, and you can see it works as expected: https://codepen.io/willbamberg/pen/mdXXMpE .

But I wonder if flexbox would be a better fit for this, something like: https://codepen.io/willbamberg/pen/XWZZaEO ? @estelle , what do you think?

**Comment by solunk** [comment] 2022-05-29 09:20
Thank you for your help

**Comment by wbamberg** [comment] 2022-05-31 05:37
Fixed by https://github.com/mdn/content/pull/16794.

**Closed by wbamberg** 2022-05-31 05:37 UTC
Labels: help wanted, time: -30mins, Content:Learn:CSS

**Comment by solunk** [comment] 2022-05-31 05:42
Thank you for your help.
