### ISSUE TITLE
there is error pop-up when " npx parcel src/index.html"

### ISSUE THREAD

**Issue by WaliAblikim** [mdn/content#19919] opened 2022-08-24 08:34 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Introducing_complete_toolchain

### What specific section or headline is this issue about?

 Introducing a complete toolchain

### What information was incorrect, unhelpful, or incomplete?

may some plugin is wrong   
after start server has error lik this 
"/Users/user/practice/will-it-miss/src/index.css:undefined:undefined: plugin is not a function"

### What did you expect to see?

should br run successfully like this, 
as mentioned is guide 
"Server running at http://localhost:1234
✨  Built in 129ms.
"

### Do you have any supporting links, references, or citations?

i see many people has enconter same issue 
https://github.com/mdn/content/issues/18439

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/tools_and_testing/understanding_client-side_tools/introducing_complete_toolchain`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Introducing_complete_toolchain
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/tools_and_testing/understanding_client-side_tools/introducing_complete_toolchain/index.md
* Last commit: https://github.com/mdn/content/commit/831aabc34db752bfd7fac701577870d7692b2804
* Document last modified: 2022-04-28T05:11:47.000Z

</details>

**Comment by Josh-Cena** [comment] 2022-08-24 12:23
Duplicate of #18439

**Closed** 2022-08-24 12:23 UTC
Labels: needs-triage, Content:Learn:Client-side
