### ISSUE TITLE
Dark gray lighter than gray

### ISSUE THREAD

**Issue by nishantsing** [mdn/content#33682] opened 2024-05-20 18:09 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/named-color

### What information was incorrect, unhelpful, or incomplete?

I see in the page that darkgray color is lighter than the gray color.

### What did you expect to see?

I think it should have more black value than the normal gray.

### Do you have any supporting links, references, or citations?

https://jsfiddle.net/nsnishant/p6gb54ea/

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/named-color`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/named-color
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/named-color/index.md
* Last commit: https://github.com/mdn/content/commit/1c4eb0bfb5f72a26fcc21a83fac91aa3e66c2fb8
* Document last modified: 2024-01-02T16:00:45.000Z

</details>

**Comment by hamishwillee** [comment] 2024-05-20 23:39
Closing because this is not a bug - your jsfiddle shows the same thing. 

![image](https://github.com/mdn/content/assets/5368500/d5624f90-9069-41be-b640-d2e3efc104b4)

It doesn't make "sense", but this is what the CSS standard defines. I understand that the standard grey comes from HTML and is defined to be 50% brightness, while darkgrey comes from the X11 color set (in which grey was 75% and darkgrey is at 66%). 
Source - https://forum.qt.io/topic/135769/in-qml-why-is-the-color-grey-darker-than-darkgrey/2?_=1716248063891&lang=en-US

**Closed by hamishwillee** 2024-05-20 23:39 UTC
Labels: Content:CSS, needs triage
