### ISSUE TITLE
Private Methods

### ISSUE THREAD

**Issue by malvinmuthuuri47** [mdn/content#26226] opened 2023-04-15 08:15 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Classes_in_JavaScript

### What specific section or headline is this issue about?

Private Methods

### What information was incorrect, unhelpful, or incomplete?

The code runs despite you specifying in the documentation that when you try to access the private method, a syntaaaaax error will be generated.

### What did you expect to see?

Syntax error as you specified.

### Do you have any supporting links, references, or citations?

![Screenshot from 2023-04-15 11-14-31](https://user-images.githubusercontent.com/113608203/232199872-0cd9ab6f-161b-41bc-ad95-3d7308279572.png)

### Do you have anything more you want to share?

No.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/objects/classes_in_javascript`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Classes_in_JavaScript
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/objects/classes_in_javascript/index.md
* Last commit: https://github.com/mdn/content/commit/ad3d16a5acd46253a4f5e2861fd4fba4e4497110
* Document last modified: 2023-03-25T07:33:21.000Z

</details>

**Comment by Josh-Cena** [comment] 2023-04-15 16:20
Duplicate of https://github.com/mdn/content/issues/25411

**Closed by Josh-Cena** 2023-04-15 16:20 UTC
Labels: needs triage, Content:Learn:JavaScript
