### ISSUE TITLE
Issue with "Examine and edit CSS": (short summary here please)

### ISSUE THREAD

**Issue by GeorgeDaris** [mdn/content#13833] opened 2022-03-13 18:36 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_and_edit_CSS

#### What information was incorrect, unhelpful, or incomplete?

Some of the videos contained in this article, such as the one under the "element{}" section, are set as private and can't be viewed.

#### Specific section or headline?

"element{}"

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/page_inspector/how_to/examine_and_edit_css`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_and_edit_CSS
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/page_inspector/how_to/examine_and_edit_css/index.html
* Last commit: https://github.com/mdn/content/commit/526608c380abfb84b3b98b8419206d83e1327f54
* Document last modified: 2022-02-18T09:18:43.000Z

</details>

**Comment by wbamberg** [comment] 2022-03-13 19:14
Duplicate of https://github.com/mdn/content/issues/7457 .

**Closed by wbamberg** 2022-03-13 19:14 UTC
Labels: needs-triage
