### ISSUE TITLE
Operations section is blank

### ISSUE THREAD

**Issue by Peddle** [mdn/content#17036] opened 2022-06-06 16:24 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation

### What specific section or headline is this issue about?

Operations

### What information was incorrect, unhelpful, or incomplete?

There's no information displaying. Tried in Safari Version 15.1 (17612.2.9.1.20), as well as Chrome Version 101.0.4951.64

### What did you expect to see?

A list of the operations

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/canvasrenderingcontext2d/globalcompositeoperation`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/canvasrenderingcontext2d/globalcompositeoperation/index.md
* Last commit: https://github.com/mdn/content/commit/2fe4f1d446a52cbcb2d273833a5a2aca32d7a202
* Document last modified: 2022-06-05T05:31:19.000Z

</details>

**Comment by sideshowbarker** [comment] 2022-06-07 02:25
Thanks for raising this. The cause was a regression introduced in https://github.com/mdn/content/pull/16969 but subsequently fixed in https://github.com/mdn/content/pull/17019.

So this is fixed in the sources now — and I think it’s also now been deployed to the production site.

**Closed by sideshowbarker** 2022-06-07 02:25 UTC
Labels: Content:WebAPI
