### ISSUE TITLE
Reusing MutationObservers

### ISSUE THREAD

**Issue by lapcat** [mdn/content#35269] opened 2024-08-01 16:33 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver/observe

### What specific section or headline is this issue about?

#reusing_mutationobservers

### What information was incorrect, unhelpful, or incomplete?

If you call `observe()` on a node that's already being observed by the same `MutationObserver`, all existing observers are automatically removed from all targets being observed before the new observer is activated.

### What did you expect to see?

I think it should say something like "all existing observers are automatically removed from the target being observed" rather than _all_ targets. The current text makes it sound like the entire `MutationObserver` is disconnected, but that's not what happens. Only the target of `observe(target, options)` is affected.

### Do you have any supporting links, references, or citations?

https://dom.spec.whatwg.org/#dom-mutationobserver-observe

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/mutationobserver/observe`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver/observe
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/mutationobserver/observe/index.md
* Last commit: https://github.com/mdn/content/commit/b71d118ffc6d72b77efad9661110fcc9ede464eb
* Document last modified: 2024-07-25T14:22:56.000Z

</details>

**Comment by Josh-Cena** [comment] 2024-08-01 16:34
Duplicate of https://github.com/mdn/content/issues/29814

**Closed by Josh-Cena** 2024-08-01 16:34 UTC
Labels: Content:WebAPI, needs triage
