### ISSUE TITLE
Browser inconsistency on Element click event types (MouseEvent versus PointerEvent)

### ISSUE THREAD

**Issue by sorcererinferior** [mdn/content#21567] opened 2022-10-15 06:34 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Element/click_event

### What specific section or headline is this issue about?

Event Type

### What information was incorrect, unhelpful, or incomplete?

It says event type is "MouseEvent". This is the case for Firefox now, but Chrome returns "PointerEvent".

If I didn't try for myself on Chrome, I would think there is no easy way to distinguish between clicks of "mouse", "pen" or "touch".

https://w3c.github.io/uievents/#event-type-click

Spec says "Interface    PointerEvent"

### What did you expect to see?

Page should show that according to spec, click event is PointerEvent and it should show its related properties like "pointerType".

### Do you have any supporting links, references, or citations?

https://w3c.github.io/uievents/#event-type-click

### Do you have anything more you want to share?

```html
<div>CLICK ME</div>
```

```javascript
document.querySelector("div").addEventListener("click", console.log);
```

Try this on Firefox and Chrome. I tested on:
Firefox 105.0.2 (64-bit)
Chrome Version 106.0.5249.119 (Official Build) (64-bit)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/element/click_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/click_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/element/click_event/index.md
* Last commit: https://github.com/mdn/content/commit/5cfd1335ca537802bb064f33d22f3c58f69f6ea1
* Document last modified: 2022-09-22T08:13:42.000Z

</details>

**Comment by bsmth** [comment] 2022-10-20 13:47
Thanks for raising this one, I can also reproduce with your example: https://codepen.io/bsmth/pen/dyeBKod 

>event type is "MouseEvent" in Firefox now, but Chrome returns "PointerEvent"

**Comment by Josh-Cena** [comment] 2023-07-14 15:29
Since https://github.com/mdn/content/issues/27929 has a better description of the situation, closing this in favor of that :)

**Closed by Josh-Cena** 2023-07-14 15:29 UTC
Labels: help wanted, Content:WebAPI
