### ISSUE TITLE
font assets not available to download

### ISSUE THREAD

**Issue by JustWaveThings** [mdn/content#19592] opened 2022-08-15 14:50 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Forms/Styling_web_forms

### What specific section or headline is this issue about?

Organizing your assets

### What information was incorrect, unhelpful, or incomplete?

Both fonts were not able to be downloaded from fontsquirrel.com due to their concerns about the commercial legality of their usage. Also, on fontsquirrel, none of the used typewriter fonts were available to download. If there is another source, i'd recommend that. I just did my best to find any working font from that site. 

### What did you expect to see?

I expected to see that the content directed to use was available.

### Do you have any supporting links, references, or citations?

https://www.fontsquirrel.com/error 
https://www.fontsquirrel.com/fonts/Secret-Typewriter

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/forms/styling_web_forms`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/Styling_web_forms
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/forms/styling_web_forms/index.md
* Last commit: https://github.com/mdn/content/commit/586a27ce15c9be3fdf6aa8abfab40f2224947bd6
* Document last modified: 2022-07-11T05:24:25.000Z

</details>

**Comment by Josh-Cena** [comment] 2022-08-15 16:57
Duplicate of #19425

**Closed** 2022-08-15 16:57 UTC
Labels: needs-triage, Content:Learn:Forms
