### ISSUE TITLE
“:host-context” article: Example shows nested selector, which doesn't work

### ISSUE THREAD

**Issue by AnupamKhosla** [mdn/content#20188] opened 2022-09-01 00:42 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/:host-context

### What specific section or headline is this issue about?

Examples on the page

### What information was incorrect, unhelpful, or incomplete?

There is an example used on the page as following:  

```
:host-context(main article) {
  font-weight: bold;
}
```

This doesn't work. May be it was meant to have a comma `:host-context(main, article) `

### What did you expect to see?

I expected it to work

### Do you have any supporting links, references, or citations?

https://mdn.github.io/web-components-examples/host-selectors/

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/_colon_host-context`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:host-context
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/_colon_host-context/index.md
* Last commit: https://github.com/mdn/content/commit/5b0c481e21e073e7e192f4a7e3cb6065ab980d57
* Document last modified: 2022-07-01T10:50:05.000Z

</details>

**Comment by estelle** [comment] 2023-11-14 18:22
the syntax examples section no longer exists on the page, so the issue is resolved ;) closing.

**Closed by estelle** 2023-11-14 18:22 UTC
Labels: help wanted, Content:CSS
