### ISSUE TITLE
Scroll issue

### ISSUE THREAD

**Issue by Disney-Banje** [mdn/content#25629] opened 2023-03-25 13:13 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map

### What specific section or headline is this issue about?

Guide section

### What information was incorrect, unhelpful, or incomplete?

Inside the guide section when you open the site you are unable to scroll to see the hidden content. Before the full content of the guide section was visible and had a scroll action. 

### What did you expect to see?

I expected to see the whole content of the guide section, and the scroll action to be able to work.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array/map`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/map/index.md
* Last commit: https://github.com/mdn/content/commit/194d3e00cb93a6e5ea44812548f4131cb17f0381
* Document last modified: 2023-02-21T00:33:25.000Z

</details>

**Comment by Josh-Cena** [comment] 2023-03-25 14:26
Hi, what is the "guide section" referring to? Could you attach screenshots? Also, platform issues go into https://github.com/mdn/yari.

**Comment by teoli2003** [comment] 2023-03-25 15:31
Duplicate of mdn/yari#8494

**Closed by teoli2003** 2023-03-25 15:31 UTC
Labels: to move

**Comment by Disney-Banje** [comment] 2023-03-25 17:25
Here is the screenshot of the guide section.

![developer mozilla org_en-US_docs_Learn (1)](https://user-images.githubusercontent.com/91415009/227732265-977a4710-05bc-49b5-becc-f5eaf53c3f45.png)

**Comment by teoli2003** [comment] 2023-03-25 17:31
Yes, there is an actual problem with Yari.

**Comment by Disney-Banje** [comment] 2023-03-25 17:35
Thanks for confirming.
