### ISSUE TITLE
Implicitly misleading into confusion of concepts: "Grouping operator ( )"

### ISSUE THREAD

**Issue by stken2050** [mdn/content#9317] opened 2021-09-28 11:25 UTC
## What page(s) did you find the problem on?
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Grouping

## What information was incorrect, unhelpful, or incomplete?

>Notice in these examples that the left-to-right order of evaluation is still preserved. In other words, the order in which the operators evaluate has changed, but the order in which the operands evaluate has not. For example in this code:

`a() * (b() + c())`

>The function a will be called before the function `b`, which will be called before the function `c`.

## Specific section or headline?
Examples
Using the grouping operator

## What is the problem?

The description for the behavior of the example code arises due to [eager evaluation of JavaScript](https://en.wikipedia.org/wiki/Evaluation_strategy#Eager_evaluation), which should be substantially another off-topic here.

The topic matter: Grouping operator `( )` itself behaves in the same/common manner regardless of the difference of evaluation strategies. eager or lazy whatever.

**As the operator illustrated, `+` or `*` is arithmetic operators, so readers naturally consider that the topic is told in the context of algebra.** 

Without clarifying the substantial concept of eager evaluation of JavaScript, as a result, the document actively and implicitly misleads readers into confusion of concepts of **algebraic functionality of Grouping operator `( )`** and eager evaluation of JavaScript.

Grouping operator `( )` itself constructs the dependency graphs of the expressions along with other operators in algebraic sense.
Also, the expressions are resolved following to dependency graphs created by them.

https://en.wikipedia.org/wiki/Dependency_graph

>In mathematics, computer science and digital electronics, a dependency graph is a directed graph representing dependencies of several objects towards each other. It is possible to derive an **evaluation order** or the absence of an evaluation order that respects the given dependencies from the dependency graph.

This operation is provided purely in a mathematical manner, and the behavior should not be confused with evaluation strategies of programming languages.

The newly added document does not only clarify in this aspect but also mislead readers actively.

-----

At the same time, with the functionality of Grouping operator `()`, example codes are illustrated:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Expressions_and_Operators

Return value and chaining

>When chaining these expressions, each assignment is evaluated **right-to-left**. 

- `w = z = x = y` is equivalent to `w = (z = (x = y))` or `x = y; z = y; w = y`
- `z += x *= y` is equivalent to `z += (x *= y)` or `tmp = x * y; x *= y; z += tmp` (except without the `tmp`).

We have another descriptions mentioning the evaluation order becomes   **right-to-left** etc. , so it's extraordinary unnatural to mention as if it's to be "**_left-to-right order of evaluation is still preserved_**" in a general principle of JavaScript:

>Notice in these examples that the left-to-right order of evaluation is still preserved. In other words, the order in which the operators evaluate has changed, but the order in which the operands evaluate has not.

## What did you expect to see?

Here, at least, there are 2 independent concepts:

- Grouping operator `( )` that follows the rule of mathematics in the form of dependency graph (the main target topic here)
- Eager evaluation of JavaScript (off-topic, if really needed, substantial explanations are required to clarify the relation to the main target topic here)

Readers should not be Implicitly misguided into confusion of these independent concepts.

Once an example code that behavior is due to the another substantial off-topic concept is presented, the document should explicitly clarify the concept, or should not provide such a confusing example from the first.

This issue is related to 
https://github.com/mdn/content/issues/9306
https://github.com/mdn/content/pull/9243
 , however, unfortunately, the factors claimed here has not been examined.

**Comment by ddbeck** [comment] 2021-09-28 15:47
@stken2050 This is a duplicate of https://github.com/mdn/content/issues/9306, which has been closed (see https://github.com/mdn/content/issues/9306#issuecomment-929020714 for the rationale). Do not open duplicate issues for closed issues. This behavior disrupts productive activity on the repository and won't be tolerated going forward. If you have further questions about expected behavior, please review the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/). Thank you for your understanding.

**Closed by ddbeck** 2021-09-28 15:47 UTC
Labels: duplicate, needs-triage
