### ISSUE TITLE
Issue with "Your first extension": Videos are unavailable (set to private)

### ISSUE THREAD

**Issue by SteveVaneeckhout** [mdn/content#9426] opened 2021-10-01 17:31 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension

#### What information was incorrect, unhelpful, or incomplete?
This page embeds 3 YouTube videos. They all show the message: "This video is not available".

#### Specific section or headline?
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension#installing 1 video unavailable
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension#testing 2 videos unavailable

https://youtu.be/cer9EUKegG4
https://youtu.be/rxBQl2Z9IBQ
https://youtu.be/NuajE60jfGY

The videos are marked as private. I've noticed that YouTube automatically marks videos posted before a certain date as private because of a certain regulation. The owner of the videos should login to his a account and set the videos to public again.

#### What did you expect to see?
I expected to see a video.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/your_first_webextension`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/your_first_webextension/index.html
* Last commit: https://github.com/mdn/content/commit/c7d9128559ed9526914c9be5bb461445fde5866a
* Document last modified: 2021-02-19T20:09:33.000Z

</details>

**Comment by digi-booster** [comment] 2021-10-01 17:44
Thanks for raising this issue but it has already been reported in [Some YouTube videos in articles in the Tools and Mozilla/Add-ons subtrees are no longer available #7457](https://github.com/mdn/content/issues/7457).

**Comment by wbamberg** [comment] 2021-10-01 21:49
Closing as a duplicate of https://github.com/mdn/content/issues/7457.

**Closed by wbamberg** 2021-10-01 21:49 UTC
