### ISSUE TITLE
Language problem

### ISSUE THREAD

**Issue by ansidev** [mdn/content#2234] opened 2021-02-10 06:58 UTC
- Link: https://developer.mozilla.org/vi/docs/Web/JavaScript/Reference/Global_Objects/Array/flat

- Problem: Language menu only shows 2 langs: Vietnamese and English (compare with https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat)

**Comment by Ryuno-Ki** [comment] 2021-02-10 07:34
Hey @ansidev,

this is currently by design.

**Comment by ansidev** [comment] 2021-02-11 11:33
@Ryuno-Ki As a user, I think it's inconsistence design. It's not a good practice. To me, it should be changed! :)

**Comment by CreaTorAlexander** [comment] 2021-02-11 11:52
@ansidev have you tried to go back to english? When you change to english then it will show all the other available languages.

**Comment by ansidev** [comment] 2021-02-11 11:56
@CreaTorAlexander Of course I know, but I don't know about that until I created this issue. That's a workaround so it's a bad practice, bad design.

**Comment by Ryuno-Ki** [comment] 2021-02-11 12:12
@schalkneethling Can you pick this up for https://github.com/mdn/yari/issues/1486 ?

**Comment by schalkneethling** [comment] 2021-02-11 13:19
> @schalkneethling Can you pick this up for [mdn/yari#1486](https://github.com/mdn/yari/issues/1486) ?

That particular issue is about the UI only, what is displayed in the dropdown I think would be more @peterbe domain.

**Comment by peterbe** [comment] 2021-02-11 13:27
@ansidev You landed on that Vietnamese page and you wanted to switch to what other non-English locale?

The old MDN (when it was a Wiki) used to have all *other* translations for a document. But the new MDN you have switch to English and from there switch to some other locale. 
The original reason for the change was technical. Chicken-and-egg problem when you're building the whole site from scratch. But then it occurred that the use-case to switch from one non-English to another non-English isn't particularly realistic. 

And besides, only having to list English is actually a good think for web performance since the `hreflang` meta tags are fewer and the drop-down is smaller. 

We'll keep an eye out for more people desperately needing to switch from one non-English to a different non-English. Perhaps it's super common. But for now, I doubt it.

**Closed** 2021-02-11 13:37 UTC
