### ISSUE TITLE
Mongoose & Callbacks

### ISSUE THREAD

**Issue by AbdulKadri** [mdn/content#25157] opened 2023-03-08 00:11 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/Home_page

### What specific section or headline is this issue about?

Async Parallel along with countDocuments()

### What information was incorrect, unhelpful, or incomplete?

mongoose current version no longer supports callbacks on countDocuments and when i was following along with the express local library project i had an error. 

### What did you expect to see?

i expect to see dynamic content on my page instead i get an error i found using this code below solved my problem

exports.index = async (req, res) => {
  try {
    const bookCount = await Book.countDocuments({});
    const bookInstanceCount = await BookInstance.countDocuments({});
    const bookInstanceAvailableCount = await BookInstance.countDocuments({ status: "Available" });
    const authorCount = await Author.countDocuments({});
    const genreCount = await Genre.countDocuments({});

    res.render("index", {
      title: "Local Library Home",
      data: {
        book_count: bookCount,
        book_instance_count: bookInstanceCount,
        book_instance_available_count: bookInstanceAvailableCount,
        author_count: authorCount,
        genre_count: genreCount,
      },
    });
  } catch (err) {
    res.render("error", {
    message: "Error occurred while fetching data",
    error: err,
    });
  }
};

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/Home_page

under the controller section

### Do you have anything more you want to share?

there was also an issue with mongoose and the save() function also not accepting callbacks. i had to use a promise instead to get no errors.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/displaying_data/home_page`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/Home_page
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/displaying_data/home_page/index.md
* Last commit: https://github.com/mdn/content/commit/4def230f85756724b59660e3cd9de363db724ef8
* Document last modified: 2023-02-24T00:05:28.000Z

</details>

**Comment by Josh-Cena** [comment] 2023-03-08 00:45
Duplicate of https://github.com/mdn/content/issues/25071

**Closed by Josh-Cena** 2023-03-08 00:45 UTC
Labels: needs triage

**Comment by hamishwillee** [comment] 2023-03-10 01:04
Note that the docs explicitly require mongoose 5 ... for now. I will update the tutorial sometime soon.
