### ISSUE TITLE
Small typo in WebGL tutorial.

### ISSUE THREAD

**Issue by jkerls** [mdn/content#36477] opened 2024-10-24 03:11 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Using_textures_in_WebGL

### What specific section or headline is this issue about?

Using Textures in Web GL

### What information was incorrect, unhelpful, or incomplete?

The code samples for the fragment shader are incorrect and don't match the content in Github - I only got the example to work by going to Github and looking at the files there.

Specifically the text:
```
    out vec4 fragColor;

    void main(void) {
      fragColor = texture(uSampler, vTextureCoord);
    }
```
is actually this on github:
```
void main(void) {
    gl_FragColor = texture2D(uSampler, vTextureCoord);
  }
```

### What did you expect to see?

The correct fragment shader code, as specified above.

### Do you have any supporting links, references, or citations?

Just compare the live page to the github at https://github.com/mdn/dom-examples/blob/main/webgl-examples/tutorial/sample6/webgl-demo.js

### Do you have anything more you want to share?

I really appreciate MDN; it's a great resource.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/webgl_api/tutorial/using_textures_in_webgl`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Using_textures_in_WebGL
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/webgl_api/tutorial/using_textures_in_webgl/index.md
* Last commit: https://github.com/mdn/content/commit/44c4ec928281dc2d7c5ea42b7d2c74a2013f16ac
* Document last modified: 2024-07-26T15:41:23.000Z

</details>

**Comment by Josh-Cena** [comment] 2024-10-24 13:45
Duplicate of https://github.com/mdn/content/issues/32537. The content code example is changed on purpose, so before you change it back you should at least read that PR and check the motivation.

**Closed by Josh-Cena** 2024-10-24 13:45 UTC
Labels: Content:WebAPI, needs triage, area: WebGL
