### ISSUE TITLE
Issue with "Arrays": (Active learning: Printing those products!)

### ISSUE THREAD

**Issue by Gitthuma** [mdn/content#4023] opened 2021-04-12 00:03 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Arrays

#### What information was incorrect, unhelpful, or incomplete?

totalBox.textContent = 'Total: $' + total.toFixed(2); 
does not print total on screen because I think it is outside the loop

#### Specific section or headline?
Arrays
Active learning: Printing those products!
Ref: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Arrays

ln github repository
Ref: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/first_steps/arrays/index.html
line 247

#### What did you expect to see?
Print the total of the active learning exercise on screen after solving the problem

#### Did you test this? If so, how?
Yes I tested this inside the text area. If I put the line inside the loop it prints the total on screen

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/first_steps/arrays`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Arrays
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/first_steps/arrays/index.html
* Last commit: https://github.com/mdn/content/commit/6dba7f1c6006efd5b984e34d7731c12da73f4a6c
* Document last modified: 2021-02-09T13:00:30.000Z

</details>

**Comment by sideshowbarker** [comment] 2021-04-12 04:12
This seems to be a duplicate of https://github.com/mdn/content/issues/4022

**Closed by sideshowbarker** 2021-04-12 04:12 UTC
Labels: duplicate
