### ISSUE TITLE
Content bug: Error when launching the WebSocket server

### ISSUE THREAD

**Issue by nand-porko** [mdn/content#7458] opened 2021-07-30 13:15 UTC
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_client_applications

## Specific page section or heading?

In the introduction part, in the second note. Right above the Creating a WebSocket object section.

## What is the problem?

When I click the "try out the example for yourself" link, I land in a page which says "Safari can’t open the page “https://mdn-samples.mozilla.org/s/websocket-chat” because Safari can’t find the server “mdn-samples.mozilla.org”. "

## What did you expect to see?

Expected to see a working WebSocket chat.

## Did you test this? If so, how?

By clicking on the link.

**Comment by sideshowbarker** [comment] 2021-07-30 13:25
Thanks for reporting this. This is an issue that the MDN team is aware of, and it’s already being tracked at https://github.com/mdn/content/discussions/5772 — so I’m going ahead and closing this out as a duplicate of that.

**Closed by sideshowbarker** 2021-07-30 13:25 UTC
Labels: duplicate
