### ISSUE TITLE
[JavaScript] Document “AsyncGenerator” & “AsyncGeneratorFunction”

### ISSUE THREAD

**Issue by DerekNonGeneric** [mdn/content#2803] opened 2021-03-02 12:34 UTC
# 📒 JavaScript Reference Docs Problem

## Location

_Section of the site where the content exists_

Affected URL(s):

- [RED] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference#control_abstraction
- [RED] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects#control_abstraction_objects
- [404] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AsyncGenerator
- [404] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AsyncGeneratorFunction

## Description

_Concise explanation of the problem_

The [“Control abstraction objects” section](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects#control_abstraction_objects) of the [“Standard built-in objects” page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects) is missing pages for the [`AsyncGenerator`](https://tc39.es/ecma262/#sec-asyncgenerator-objects) and [`AsyncGeneratorFunction`](https://tc39.es/ecma262/#sec-asyncgeneratorfunction-objects) objects. Having these documents available is important because they would be needed in order for https://github.com/mdn/content/issues/2248 to move towards completion.

---

- [x] I would like to work on this issue and
      submit a pull request.

**Comment by Ryuno-Ki** [comment] 2021-03-04 08:12
I chatted with @DerekNonGeneric on Matrix.
He's got a library who link out to these pages (`AsyncGenerator` and `AsyncGeneratorFunction`).

It's documented [how to add a new document](https://github.com/mdn/content#adding-a-new-document) and the directory holding these files is

https://github.com/mdn/content/tree/4a94f3c5088877279571d381d13b4cd44222f975/files/en-us/web/javascript/reference/global_objects

@mdn/yari-content-javascript would you assist with questions? Or shall Derek just get started and you'll provide feedback once a PR is opened?

**Comment by sideshowbarker** [comment] 2021-03-04 10:05
> Or shall Derek just get started and you'll provide feedback once a PR is opened?

Yes, that sounds best

**Comment by wbamberg** [comment] 2021-03-04 17:32
See also: https://github.com/mdn/content/issues/1459 and https://github.com/mdn/content/issues/2248.

**Comment by DerekNonGeneric** [comment] 2022-05-28 00:52
I am pretty sure this is still unfulfilled.

/cc @Rumyra

**Comment by wbamberg** [comment] 2022-05-28 00:54
Yes, for some reason a robot closed lots of issues just a little while ago. I hope the relevant issues (including this one) will get reopened!

**Comment by Josh-Cena** [comment] 2022-06-18 13:16
There's a linked PR but it's closed, promising there will be follow-up PRs in Markdown. @Rumyra do you have one in place?

**Comment by teoli2003** [comment] 2022-06-18 13:49
Given the issue is more than a year old, feel free to take this over, if you want.

**Comment by Josh-Cena** [comment] 2022-06-18 13:58
I guess I just have to pick up #2861 and convert it to Markdown 😄

**Comment by teoli2003** [comment] 2022-06-18 14:46
I think so. I would like to be sure that @DerekNonGeneric is credited for his work, though. I guess having it reviewing the Markdown conversion and/or adding some to it will make sure he gets the credit as co-author of the article.

**Comment by Josh-Cena** [comment] 2022-06-18 14:47
Yes, I am going to. I'll just checkout that branch & rebase it, which means he'll be credited as the author of those commits.

**Comment by sideshowbarker** [comment] 2022-06-22 03:25
> Yes, I am going to. I'll just checkout that branch & rebase it, which means he'll be credited as the author of the initial commits.

Note that when this PR gets merged to the main branch, the commits from here will necessarily all be squashed — because this repo’s settings apparently were changed some time ago to disallow rebase merges and to only allow squash merges.

That said, this PR itself will preserve the original commit history even after the squashed commit is merged to main.

**Comment by Josh-Cena** [comment] 2022-06-22 03:27
Yes, but when merging, the authors of all commits on that branch would become co-authors of the squashed commit (even when they are only a co-author of a single commit), which is still desirable.

**Closed** 2022-07-16 14:53 UTC
Labels: Content:JS, document-not-written, idle
