### ISSUE TITLE
Issue with "<menu>: The Menu element": the css does not load. Wrong MIME type

### ISSUE THREAD

**Issue by jasonmerry** [mdn/content#12204] opened 2022-01-19 22:40 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menu

#### What information was incorrect, unhelpful, or incomplete?
From console: 'Refused to apply style from 'https://developer.mozilla.org/static/css/main.cd55b6e0.chunk.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.'

#### What did you expect to see?
The normal style sheet applied to most other pages I have viewed :)

#### Did you test this? If so, how?
I linked to the page from `https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#sectioning_content`

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/menu`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menu
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/menu/index.md
* Last commit: https://github.com/mdn/content/commit/da7f599549a6a36371b9bd9848fa0e3d51379196
* Document last modified: 2021-10-25T20:11:36.000Z

</details>

**Comment by sideshowbarker** [comment] 2022-01-20 01:05
Which browser are you using?

**Comment by jasonmerry** [comment] 2022-01-21 09:24
Chrome Version 97

**Comment by sideshowbarker** [comment] 2022-01-21 09:26
What happens when you try in Firefox?

**Comment by jasonmerry** [comment] 2022-01-21 09:27
Just checked again in incog and looking ok today.

For reference, this happened on the day
<img width="1680" alt="Screenshot 2022-01-19 at 22 31 56" src="https://user-images.githubusercontent.com/12991499/150501927-dd6db0a1-1ac6-44a2-851a-af969a4ea8b1.png">

**Comment by sideshowbarker** [comment] 2022-01-21 09:47
> Just checked again in incog and looking ok today.

OK, I’m going ahead and closing this (on the assumption that if you can’t reproduce it in Incognito mode, it must be due to and extension or something)

**Closed by sideshowbarker** 2022-01-21 09:47 UTC
Labels: needs info, infra
