### ISSUE TITLE
video of this article was deleted!

### ISSUE THREAD

**Issue by goashir** [mdn/content#13985] opened 2022-03-17 14:33 UTC
hi, I was study this article on mozilla and I watched this youtube videos are deleted or get private attribute

content Url:
https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_and_edit_the_box_model

screenshot:
<img src="https://i.ibb.co/0jCbfdt/Screenshot-from-2022-03-17-17-54-35.png">

https://i.ibb.co/0jCbfdt/Screenshot-from-2022-03-17-17-54-35.png

**Comment by dipikabh** [comment] 2022-03-17 19:24
Duplicate of #7457

**Closed by dipikabh** 2022-03-17 19:24 UTC
Labels: needs-triage

**Comment by goashir** [comment] 2022-03-18 08:20
I make new video for this article in firefox 98:
for first private video:
<video src="https://www.dropbox.com/s/btwjbzeq219lsp2/firefox-one.mp4?dl=1" type="video/mp4" width="320" height="240" controls></video>
https://www.dropbox.com/s/btwjbzeq219lsp2/firefox-one.mp4?dl=1

for second private video:
https://www.dropbox.com/s/s05d0uxlujex9no/firefox-two.mp4?dl=1
