### ISSUE TITLE
Issue with "Viewport concepts": innerWidth differs between Chrome and Firefox

### ISSUE THREAD

**Issue by PageNotes** [mdn/content#11021] opened 2021-12-07 07:12 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/Viewport_concepts

#### What information was incorrect, unhelpful, or incomplete?
"If you query the width or height of the window and document in Chrome or Firefox, you may get:
document.documentElement.clientWidth /* 1200 */"

#### Specific section or headline?
Viewport sizes are mutable

#### What did you expect to see?
My Lenovo laptop is 1280 CSS pixels wide, and with the window zoomed 100%, I expected to see 1280 in both Chrome and Firefox.

#### Did you test this? If so, how?
I tested on both Chrome and Firefox with the zoom set to 100%. On Firefox, I got 1280 as expected. But on Chrome, I got 978.
My test script reads
<script>
alert(document.documentElement.clientWidth);
</script>

I get the same discrepancy with window.innerWidth 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/viewport_concepts`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/Viewport_concepts
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/viewport_concepts/index.md
* Last commit: https://github.com/mdn/content/commit/26f50bdaeb1228f458d21dbdf7dc110387b20daa
* Document last modified: 2021-08-12T23:59:09.000Z

</details>

**Comment by Andrew-Cottrell** [comment] 2021-12-07 08:02
That's quite a large discrepancy. I could not reproduce using Chrome 96, although I tested with a greater CSS pixel width.

Both of the following would be substantially reduced if the developer tools were open & docked at the left or right of the document within the browser window.
```javascript
document.documentElement.clientWidth; // excludes widths of developer tools, borders, margins, and vertical scrollbar
window.innerWidth; // excludes width of developer tools, but includes width of borders, margins, and vertical scrollbar
```
Might the developer tools have been open & docked during your test?

**Comment by PageNotes** [comment] 2021-12-07 10:03
Thanks for checking!

**Comment by sideshowbarker** [comment] 2021-12-09 04:35
Closing as not-reproducible per https://github.com/mdn/content/issues/11021#issuecomment-987665423

**Closed by sideshowbarker** 2021-12-09 04:35 UTC
