### ISSUE TITLE
pow function obviously not working in FF 114.0.2 on macOS 13.4

### ISSUE THREAD

**Issue by uwemutz** [mdn/content#27445] opened 2023-06-20 18:33 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/pow

### What specific section or headline is this issue about?

The examples don't work

### What information was incorrect, unhelpful, or incomplete?

The examples concerning the font-size don't work (macOS 13.4, Firefox 114.0.2). The pow function doesn't seem to work.

### What did you expect to see?

I expected to see a correct example using the pow function which works
<img width="1792" alt="Bildschirmfoto 2023-06-20 um 20 31 59" src="https://github.com/mdn/content/assets/13882592/dabc255b-b677-44ac-9235-366a177db76d">

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/pow`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/pow
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/pow/index.md
* Last commit: https://github.com/mdn/content/commit/676065ed85f246825b45579ac6228e41357dbdad
* Document last modified: 2023-04-22T05:15:34.000Z

</details>

**Comment by Josh-Cena** [comment] 2023-06-20 18:36
Duplicate of https://github.com/mdn/content/issues/26636

**Closed by Josh-Cena** 2023-06-20 18:36 UTC
Labels: Content:CSS, needs triage
