### ISSUE TITLE
SVG slope attribute can be used on <feFunc*> elements

### ISSUE THREAD

**Issue by estelle** [mdn/content#24935] opened 2023-02-28 00:02 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/slope

### What specific section or headline is this issue about?

deprecated and list of related elements on which it can be used.

### What information was incorrect, unhelpful, or incomplete?

The [`<feFuncR>`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feFuncR), [`<feFuncB>`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feFuncB), [`<feFuncG>`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feFuncG), and [`<feFuncA>`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feFuncA) elements all support the `slope` attribute, and use it to set values for linear filters, such as brightness. This page says it's deprecated and only relevant to font. I arrived at the page from https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute#transfer_function_attributes. It is definitely not deprecated. 

### What did you expect to see?

information on how to use the slope attribute to define linear multipliers.

### Do you have any supporting links, references, or citations?

It's used in this spec: https://drafts.fxtf.org/filter-effects-1/#element-attrdef-fecomponenttransfer-slope

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/svg/attribute/slope`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/slope
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/attribute/slope/index.md
* Last commit: https://github.com/mdn/content/commit/c0eef9c5828e919c8128c99e0f95cc7a0bcdbc4e
* Document last modified: 2022-12-09T17:22:31.000Z

</details>

**Comment by Josh-Cena** [comment] 2024-06-10 17:50
I'm closing this as duplicate of https://github.com/mdn/content/issues/32449 since that one has more traffic

**Closed by Josh-Cena** 2024-06-10 17:50 UTC
Labels: Content:SVG
