### ISSUE TITLE
Global id attribute specification do not match with HTML spec

### ISSUE THREAD

**Issue by electrolinux** [mdn/content#25225] opened 2023-03-10 12:25 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id

### What specific section or headline is this issue about?

The Note, just before the specification

### What information was incorrect, unhelpful, or incomplete?

and the value for an id attribute should start with a letter

### What did you expect to see?

The [id](https://html.spec.whatwg.org/multipage/dom.html#the-id-attribute) attribute specifies its element's [unique identifier (ID)](https://dom.spec.whatwg.org/#concept-id).

There are no other restrictions on what form an ID can take; in particular, IDs can consist of just digits, **start with a digit, start with an underscore**, consist of just punctuation, etc.

### Do you have any supporting links, references, or citations?

https://html.spec.whatwg.org/multipage/dom.html#global-attributes:the-id-attribute-2

### Do you have anything more you want to share?

The problem is that mozilla firefox v.110 on linux choke when a href contains an id starting with a digit.

* [link 1](#1-link)
* [link 2](#2-link)

<a id="1-link">Link 1, with id starting with a digit</a>

<a id="2-link">Link 2, with id starting with a digit</a>

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/global_attributes/id`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/global_attributes/id/index.md
* Last commit: https://github.com/mdn/content/commit/ba96f2f183353872db6d9242c7d2dffe2dbc0c35
* Document last modified: 2023-02-24T05:52:35.000Z

</details>

**Comment by teoli2003** [comment] 2023-03-10 13:09
Duplicate of #25200

**Closed by teoli2003** 2023-03-10 13:09 UTC
Labels: Content:HTML, needs triage
