### ISSUE TITLE
Issue with "<input type="month" pattern="[0-9]{4}-[0-9]{2}>": (not compatible with firefox)

### ISSUE THREAD

**Issue by Codefeak** [mdn/content#3268] opened 2021-03-18 13:23 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/month

#### What information was incorrect, unhelpful, or incomplete?
```
<form>
  <div>
    <label for="month">What month would you like to visit us? (Summer months only, yyyy-mm)</label>
    <input id="month" type="month" name="month"
           min="2017-06" max="2017-09" required
           pattern="[0-9]{4}-[0-9]{2}">
    <span class="validity"></span>
  </div>
  <div>
      <input type="submit" value="Submit form">
  </div>
</form>
```

#### Specific section or headline?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/month#handling_browser_support
>>>>Handling browser support

#### What did you expect to see?
compatibility with firefox

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/html/element/input/month`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/month
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/input/month/index.html
* Last commit: https://github.com/mdn/content/commit/2a14c0eac061493b1160076a3e72ec8e346d2223
* Document last modified: 2021-02-19T18:56:36.000Z

</details>

**Comment by Leokuma** [comment] 2021-03-21 18:40
I believe there's no problem in the article.

The article says that Firefox does not yet support `<input type="month">`:

> only Chrome/Opera and Edge support it on desktop

The workaround provided (using `pattern`) works as intended for me in FF 86.0.1.

**Comment by hamishwillee** [comment] 2021-03-21 23:01
The compatibility information on the page is correct - Firefox does not support the month input type. You can see this by comparing FF and Chrome on the example on the page you point to. FF (the top item below) does not support the input so you have to enter text, while chrome does, so you have a date picker. I also checked bugzilla and there are open bug reports against this.

![image](https://user-images.githubusercontent.com/5368500/111923565-f8282a80-8af3-11eb-8a9b-f4b18b96401f.png)

Thank @Leokuma for confirming this.  Closing.

**Closed by hamishwillee** 2021-03-21 23:01 UTC
Labels: Content:HTML

**Comment by Codefeak** [comment] 2021-03-23 13:11
Thank You @hamishwillee & @Leokuma for the clarification. I thought using pattern I will be able to have date picker too. :cry:
