### ISSUE TITLE
Manifest v3 Edge support

### ISSUE THREAD

**Issue by NathanVerkerk** [mdn/content#23512] opened 2023-01-10 10:01 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/manifest_version

### What specific section or headline is this issue about?

Browser Compatibility

### What information was incorrect, unhelpful, or incomplete?

The page says manifest v3 is not supported on Edge, but it is.
Manifest version 3 is supported in Edge.

### What did you expect to see?

Edge, manifest v3, supported

### Do you have any supporting links, references, or citations?

https://techcommunity.microsoft.com/t5/articles/manifest-v3-changes-are-now-available-in-microsoft-edge/m-p/1780254

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/manifest.json/manifest_version`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/manifest_version
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/manifest.json/manifest_version/index.md
* Last commit: https://github.com/mdn/content/commit/a85da51771ba1653616356db82d1bd1e1e1981bd
* Document last modified: 2022-10-25T03:16:13.000Z

</details>

**Comment by Josh-Cena** [comment] 2023-01-10 20:50
Duplicate of https://github.com/mdn/browser-compat-data/issues/16147

**Closed by Josh-Cena** 2023-01-10 20:50 UTC
Labels: Content:WebExt, needs triage
