### ISSUE TITLE
Active learning crashed

### ISSUE THREAD

**Issue by Leandrys-Dev** [mdn/content#31413] opened 2023-12-30 15:48 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code

### What specific section or headline is this issue about?

Active learning: Launch countdown

### What information was incorrect, unhelpful, or incomplete?

while i was attempting to complete the first *active learning section* i have noted that when i type `while{}` the text area not respond.
The first thing i did was to delete the comment slashes from the third line ( i would be the line of ` //let i = 10`), then i wrote the **while** keyword and when i have tried to close the courly braces, the playground crashes and not respond again.

i'm currently using a device *Acer Chromebook 315* ,  the problem happens in *Google Chrome browser* and *Mozilla Firefox* (at least are the two browsers i have.) using POP-OS! [linux debian-based ] system and i'm using slow 4g connection.

i hope the info would be enough.

### What did you expect to see?

i was expecting the textarea display the code that i type when i'm trying to complete the exercise.

### Do you have any supporting links, references, or citations?

**This is the console log in Firefox:**
```
Content-Security-Policy: The page’s settings blocked the loading of a resource at inline (“script-src-elem”). utils.js:42:9
Error: Promised response from onMessage listener went out of scope vendors.chunk.js:1:525956
Clear-Site-Data header forced the clean up of “cookies” data. runner.html
Clear-Site-Data header forced the clean up of “storage” data. runner.html
Content-Security-Policy: Ignoring ‘unsafe-eval’ or ‘wasm-unsafe-eval’ inside “script-src-elem”. runner.html
Partitioned cookie or storage access was provided to “https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=looping_code_example” because it is loaded in the third-party context and dynamic state partitioning is enabled.
(Glean.core.Upload.PingUploadManager) Ping f0fb6f98-2aa7-4bae-ac11-d44a46552b2e successfully sent 200. log.js:15:23
(Glean.core.Upload.PingUploadManager) Ping a32bf440-20d1-4153-9168-a28cf52b5198 successfully sent 200. log.js:15:23
(Glean.core.Upload.PingUploadManager) Ping a96ed43c-4b38-4c92-9e06-31d3857bfc1b successfully sent 200. log.js:15:23
Error: Promised response from onMessage listener went out of scope vendors.chunk.js:1:525956
DataCloneError: URL object could not be cloned. 6 get-iframes.js:9
Content-Security-Policy: Ignoring ‘unsafe-eval’ or ‘wasm-unsafe-eval’ inside “script-src-elem”. runner.html
Partitioned cookie or storage access was provided to “https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown” because it is loaded in the third-party context and dynamic state partitioning is enabled.
(Glean.core.Upload.PingUploadManager) Ping e1163637-3ecd-44c9-a3bf-65163878585f successfully sent 200. log.js:15:23
Clear-Site-Data header forced the clean up of “cookies” data. runner.html
Clear-Site-Data header forced the clean up of “storage” data. runner.html
SyntaxError: unterminated regular expression literal
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
runner.html:47:27
Uncaught SyntaxError: unterminated regular expression literal
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
runner.html:4:13
SyntaxError: unterminated regular expression literal
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
    onkeyup https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:97
runner.html:47:27
Uncaught SyntaxError: unterminated regular expression literal
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
    onkeyup https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:97
runner.html:4:13
ReferenceError: w is not defined
    <anonymous> https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript line 8 > eval:6
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
runner.html:47:27
Uncaught ReferenceError: w is not defined
    <anonymous> https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript line 8 > eval:6
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
runner.html:6:1
ReferenceError: w is not defined
    <anonymous> https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript line 8 > eval:6
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
    onkeyup https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:97
runner.html:47:27
Uncaught ReferenceError: w is not defined
    <anonymous> https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript line 8 > eval:6
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
    onkeyup https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:97
runner.html:6:1
ReferenceError: wh is not defined
    <anonymous> https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript line 8 > eval:6
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
runner.html:47:27
Uncaught ReferenceError: wh is not defined
    <anonymous> https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript line 8 > eval:6
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
runner.html:6:1
ReferenceError: whi is not defined
    <anonymous> https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript line 8 > eval:6
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
runner.html:47:27
Uncaught ReferenceError: whi is not defined
    <anonymous> https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript line 8 > eval:6
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
runner.html:6:1
ReferenceError: whi is not defined
    <anonymous> https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript line 8 > eval:6
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
    onkeyup https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:97
runner.html:47:27
Uncaught ReferenceError: whi is not defined
    <anonymous> https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript line 8 > eval:6
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
    onkeyup https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:97
runner.html:6:1
ReferenceError: whi is not defined
    <anonymous> https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript line 8 > eval:6
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
    onkeyup https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:97
runner.html:47:27
Uncaught ReferenceError: whi is not defined
    <anonymous> https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript line 8 > eval:6
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
    onkeyup https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:97
runner.html:6:1
ReferenceError: whi is not defined
    <anonymous> https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript line 8 > eval:6
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
    onkeyup https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:97
runner.html:47:27
Uncaught ReferenceError: whi is not defined
    <anonymous> https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript line 8 > eval:6
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
    onkeyup https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:97
runner.html:6:1
ReferenceError: whil is not defined
    <anonymous> https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript line 8 > eval:6
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
runner.html:47:27
Uncaught ReferenceError: whil is not defined
    <anonymous> https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript line 8 > eval:6
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
runner.html:6:1
SyntaxError: missing ( before condition
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
runner.html:47:27
Uncaught SyntaxError: missing ( before condition
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
runner.html:11:1
SyntaxError: missing ( before condition
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
    onkeyup https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:97
runner.html:47:27
Uncaught SyntaxError: missing ( before condition
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
    onkeyup https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:97
runner.html:11:1
SyntaxError: missing ( before condition
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
    onkeyup https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:97
runner.html:47:27
Uncaught SyntaxError: missing ( before condition
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
    onkeyup https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:97
runner.html:11:1
SyntaxError: expected expression, got end of script
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
runner.html:47:27
Uncaught SyntaxError: expected expression, got end of script
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
runner.html:11:1
SyntaxError: expected expression, got end of script
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
    onkeyup https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:97
runner.html:47:27
Uncaught SyntaxError: expected expression, got end of script
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
    onkeyup https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:97
runner.html:11:1
Error: Promised response from onMessage listener went out of scope vendors.chunk.js:1:525956
SyntaxError: expected expression, got end of script
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
    onkeyup https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:97
runner.html:47:27
Uncaught SyntaxError: expected expression, got end of script
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
    onkeyup https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:97
runner.html:11:1
SyntaxError: missing ) after condition
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
runner.html:47:27
Uncaught SyntaxError: missing ) after condition
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
runner.html:11:1
SyntaxError: missing ) after condition
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
    onkeyup https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:97
runner.html:47:27
Uncaught SyntaxError: missing ) after condition
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
    onkeyup https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:97
runner.html:11:1
SyntaxError: missing ) after condition
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
runner.html:47:27
Uncaught SyntaxError: missing ) after condition
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
runner.html:11:1
SyntaxError: missing ) after condition
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
    onkeyup https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:97
runner.html:47:27
Uncaught SyntaxError: missing ) after condition
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
    onkeyup https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:97
runner.html:11:1
SyntaxError: expected expression, got end of script
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
runner.html:47:27
Uncaught SyntaxError: expected expression, got end of script
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
runner.html:11:1
SyntaxError: expected expression, got end of script
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
runner.html:47:27
Uncaught SyntaxError: expected expression, got end of script
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
runner.html:11:1
SyntaxError: expected expression, got end of script
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
    onkeyup https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:97
runner.html:47:27
Uncaught SyntaxError: expected expression, got end of script
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
    onkeyup https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:97
runner.html:11:1
SyntaxError: expected expression, got end of script
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
    onkeyup https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:97
runner.html:47:27
Uncaught SyntaxError: expected expression, got end of script
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
    onkeyup https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:97
runner.html:11:1
SyntaxError: expected expression, got end of script
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
    onkeyup https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:97
runner.html:47:27
Uncaught SyntaxError: expected expression, got end of script
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
    onkeyup https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:97
runner.html:11:1
SyntaxError: missing ) after condition
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
runner.html:47:27
Uncaught SyntaxError: missing ) after condition
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
runner.html:11:1
SyntaxError: missing ) after condition
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
    onkeyup https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:97
runner.html:47:27
Uncaught SyntaxError: missing ) after condition
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
    onkeyup https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:97
runner.html:11:1
SyntaxError: expected expression, got end of script
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
runner.html:47:27
Uncaught SyntaxError: expected expression, got end of script
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
runner.html:11:1
SyntaxError: expected expression, got end of script
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
    onkeyup https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:97
runner.html:47:27
Uncaught SyntaxError: expected expression, got end of script
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
    onkeyup https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:97
runner.html:11:1
SyntaxError: expected expression, got end of script
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
    onkeyup https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:97
runner.html:47:27
Uncaught SyntaxError: expected expression, got end of script
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
    onkeyup https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:97
runner.html:11:1
SyntaxError: missing } in compound statement
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
runner.html:47:27
Uncaught SyntaxError: missing } in compound statement
    updateCode https://live.mdnplay.dev/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code/runner.html?id=active_learning_launch_countdown line 122 > injectedScript:8
runner.html:11:1note: { opened at line 6, column 13runner.html:6:13
```

### Do you have anything more you want to share?

**Mozilla crash moment**

![Screenshot from 2023-12-30 10-27-36](https://github.com/mdn/content/assets/142987654/92219d49-c3c6-4908-a96d-414603c556b7)

**Chrome browser simulating *NestHub Max* device**

![Screenshot from 2023-12-30 10-16-17](https://github.com/mdn/content/assets/142987654/03bbc9e9-9bf5-43c3-b589-3ac4a3985d1c)

**Chrome browser trying to seek the error,  while simulating *NestHub Max* device**

![Screenshot from 2023-12-30 10-11-09](https://github.com/mdn/content/assets/142987654/968c79a6-4245-44ee-8bc0-637d702fd22a)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/building_blocks/looping_code`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/building_blocks/looping_code/index.md
* Last commit: https://github.com/mdn/content/commit/289d6314f3368aa3e28524e7d090f6e9c704e3b1
* Document last modified: 2023-11-28T20:48:44.000Z

</details>

**Comment by hamishwillee** [comment] 2024-01-01 23:13
Can someone with rights move this to the yari repo?

Note that I did not yet a Firefox or runner crash. However I did get lots of incorrect/spurious warnings when I typed anything - like this. Essentially anything I typed gave this error.

![image](https://github.com/mdn/content/assets/5368500/a4e60ab6-755f-4c8c-9091-9ebedb086f11)

**Comment by wbamberg** [comment] 2024-01-02 04:13
I don't think this is a Yari bug - "playground" in the report refers I think to the text box in the page, not the Yari "play" thing. These active learning examples work by watching the text box and eval-ing the contents of it whenever it changes: 
 

https://github.com/mdn/content/blob/612ef81fa7372eb8025717f30562e482fe4a65ea/files/en-us/learn/javascript/building_blocks/looping_code/index.md?plain=1#L835-L934

So you will absolutely see spurious errors as you type, along the lines of:

```
ReferenceError: w is not defined
ReferenceError: wh is not defined
ReferenceError: whi is not defined
ReferenceError: whil is not defined
```

I expect what's happening is that the reporter entered something like: `while(1) {}` which put the editor (and therefore the page) into an infinite loop. I can reproduce this.

If I'm right, this would seem to be not easy to fix.

**Comment by Leandrys-Dev** [comment] 2024-01-02 12:40
> I don't think this is a Yari bug - "playground" in the report refers I think to the text box in the page, not the Yari "play" thing. These active learning examples work by watching the text box and eval-ing the contents of it whenever it changes:
> 
> https://github.com/mdn/content/blob/612ef81fa7372eb8025717f30562e482fe4a65ea/files/en-us/learn/javascript/building_blocks/looping_code/index.md?plain=1#L835-L934
> 
> So you will absolutely see spurious errors as you type, along the lines of:
> 
> ```
> ReferenceError: w is not defined
> ReferenceError: wh is not defined
> ReferenceError: whi is not defined
> ReferenceError: whil is not defined
> ```
> 
> I expect what's happening is that the reporter entered something like: `while(1) {}` which put the editor (and therefore the page) into an infinite loop. I can reproduce this.
> 
> If I'm right, this would seem to be not easy to fix.

No, it's not the case, i have typed while(condition) {} , in the close courly bracket, the editor has crashed. Check the pictures, are clearly displayed. this error was tested at least 5 times with different browsers. I have invested time looking for the problem root throghout the console error mesages but... i didn't found it due to my lower knowlendge

**Comment by wbamberg** [comment] 2024-01-02 15:49
> No, it's not the case, i have typed while(condition) {} , in the close courly bracket, the editor has crashed. 

In your screenshot, you can see this code:

```js
let i = 10;

while (i > 0) {
```

...but I believe you have actually typed the last closing bracket:

```js

let i = 10;

while (i > 0) {}
```

...which is going to enter an infinite loop, _before_ the displayed text is updated. So you don't see the last closing bracket.

At any rate, this is what I see.

To test this, try writing the code in a different order:

(1) uncomment the counter variable:

```js
let i = 10;
```

(2) decrement the counter:

```js
let i = 10;

i--;
```

(3) write the loop _around the decrement call_:

```js
let i = 10;

while(i > 0) {
    i--;
}
```

...that will work.

Now I read the page, there's even a warning about this issue:

> **Note:** If you start typing the loop (for example (while(i>=0)), the browser might get stuck because you have not yet entered the end condition. So be careful with this. You can start writing your code in a comment to deal with this issue and remove the comment after you finish.

**Comment by Leandrys-Dev** [comment] 2024-01-02 16:21
i know that the loop at this time is infinite, because have not been set a post-decrement statement... but i can't write more code later of  i type {} because the editor crash completely. Here is the problem, the editor should not crash never... at least doing the normal workflow. I have tested every active learning text-area (at least every i have studied) and i have never seen this behavior and i know this is not correct.

if we have not a correct solution, let's to wait for someone with the required knowledge to detect the error or generate an optimal solution

**NOTE:** i'm not english speaker, if you don't understand what i'm writing, sorry, just notice me and i will use a translator to enhance the translation

**Comment by wbamberg** [comment] 2024-01-02 16:54
> i know that the loop at this time is infinite, because have not been set a post-decrement statement... but i can't write more code later of i type {} because the editor crash completely.

Of course, once the script enters the infinite loop you can't enter more code. Have you tried the solution I offered in my comment, of writing the code in a different order?

> Here is the problem, the editor should not crash never...

I agree. But as I also said in my previous comment, it's not that easy to build infinite loop protection into a playground editor. So we might decide it's not worth doing, especially since I have never seen another issue about this, and we have a note warning people about it. See also https://github.com/mdn/interactive-examples/issues/50 for a discussion of what it might take to do this, which in the end we closed as "not going to fix" (this is for interactive examples, not these Learn exercises, but the principle is the same).

**Comment by Leandrys-Dev** [comment] 2024-01-02 20:33
i've tried your solution, it works!. But i'm not happy after all, at least will be useful to put a note with a warning. Due to this is not the first issue opened of this kind. The goal is to provide a good user experience.

I've tested the same steps that raise the problem, and the editor works fine. It seems very confusing. I let you close the issue, thanks for the attention.

**Comment by wbamberg** [comment] 2024-01-02 21:27
>  at least will be useful to put a note with a warning

Since the page already does this, I'm closing this issue.

**Closed by wbamberg** 2024-01-02 21:27 UTC
Labels: needs triage, Content:Learn:JavaScript
