### ISSUE TITLE
Issue with "JSON viewer": youtube video on page is private

### ISSUE THREAD

**Issue by niij** [mdn/content#13957] opened 2022-03-16 19:31 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/JSON_viewer

#### What information was incorrect, unhelpful, or incomplete?

The embedded Youtube video on this page is private (screenshot attached):

![image](https://user-images.githubusercontent.com/16074300/158674916-7d2f9858-facd-4262-b94c-6fc9cbb2dc2e.png)

**Comment by wbamberg** [comment] 2022-03-16 23:10
Duplicate of https://github.com/mdn/content/issues/7457

**Closed by wbamberg** 2022-03-16 23:10 UTC
Labels: needs-triage
