### ISSUE TITLE
SVG tutorial Bézier curve images are 404

### ISSUE THREAD

**Issue by saizai** [mdn/content#28536] opened 2023-08-12 19:13 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths#b%C3%A9zier_curves

### What information was incorrect, unhelpful, or incomplete?

These are 404:
https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths/cubic_b%C3%A9zier_curves_with_grid.png
https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths/shortcut_cubic_b%C3%A9zier_with_grid.png
https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths/quadratic_b%C3%A9zier_with_grid.png
https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths/shortcut_quadratic_b%C3%A9zier_with_grid.png

### What did you expect to see?

Images as documented. Preferably as actual inline SVGs, not PNGs.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/svg/tutorial/paths`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/svg/tutorial/paths/index.md
* Last commit: https://github.com/mdn/content/commit/b4f998244660723175f8e06b5d77f68cfb1d1f1a
* Document last modified: 2023-03-06T23:38:10.000Z

</details>

**Comment by Josh-Cena** [comment] 2023-08-12 19:31
Duplicate of https://github.com/mdn/content/issues/28341

**Closed by Josh-Cena** 2023-08-12 19:31 UTC
Labels: Content:SVG, needs triage
