### ISSUE TITLE
Issue with "Contact us": the link on this page to file a bug report for addons.mozilla.org goes to github.com/mozilla/addons/issues/new should it actually go to github.com/mozilla/addons-server/issues/new ?

### ISSUE THREAD

**Issue by st333v** [mdn/content#3914] opened 2021-04-07 15:13 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Contact_us

#### What information was incorrect, unhelpful, or incomplete?

Possible Issue with the "Contact us" page,  the link on this page to file a bug report for addons.mozilla.org goes to github.com/mozilla/addons/issues/new should it actually go to github.com/mozilla/addons-server/issues/new 
?

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mozilla/add-ons/contact_us`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Contact_us
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/contact_us/index.html
* Last commit: https://github.com/mdn/content/commit/949677748336f7ce68d4c0b3942407fbb8d9b6f9
* Document last modified: 2020-12-23T18:33:36.000Z

</details>

**Comment by sideshowbarker** [comment] 2021-06-08 22:28
Added the Content:WebExt label to this, since this seems like it needs the attention of the @mdn/yari-content-mozilla-add-ons team?

**Comment by caitmuenster** [comment] 2021-06-08 22:32
Thanks @sideshowbarker! 

@st333v, this is expected behavior. :) AMO's code is split between two repositories (frontend and server), and it's not always obvious which repo to file an issue to. It's easy for us to generally tell folks to file an issue to the addons repo and then move it to the frontend or server.

**Comment by sideshowbarker** [comment] 2021-06-08 22:48
Thanks @caitmuenster — so I’m going ahead and closing this as resolved per https://github.com/mdn/content/issues/3914#issuecomment-857224829

**Closed by sideshowbarker** 2021-06-08 22:48 UTC
Labels: Content:Other, Content:WebExt, wontfix
