### ISSUE TITLE
Design bug

### ISSUE THREAD

**Issue by sanjarbek-ismatov** [mdn/content#25635] opened 2023-03-25 15:06 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Keyed_collections

### What specific section or headline is this issue about?

design

### What information was incorrect, unhelpful, or incomplete?

Side panel isn't showing bottom links. Scroll is not visible
![Снимок экрана (8)](https://user-images.githubusercontent.com/65501439/227725410-f808293e-a08e-4934-9735-9a6aa6df09f0.png)
![Снимок экрана (9)](https://user-images.githubusercontent.com/65501439/227725413-59b1bc20-bcd7-4ff7-8a9a-e68bdf282c80.png)
![Снимок экрана (10)](https://user-images.githubusercontent.com/65501439/227725414-9d26a323-2ef0-4941-a072-03af0e734589.png)

### What did you expect to see?

I want to see next links

### Do you have anything more you want to share?

overflow-y: scroll; must add to nav (sidebar-inner class)
![Снимок экрана (11)](https://user-images.githubusercontent.com/65501439/227725789-7314f6cb-965c-4304-8144-c1d35b750247.png)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/guide/keyed_collections`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Keyed_collections
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/keyed_collections/index.md
* Last commit: https://github.com/mdn/content/commit/9c4fb236cd9ced12b1eb8e7696d8e6fcb8d8bad3
* Document last modified: 2023-02-21T01:35:45.000Z

</details>

**Comment by teoli2003** [comment] 2023-03-25 15:31
Duplicate of mdn/yari#8494

**Closed by teoli2003** 2023-03-25 15:31 UTC
Labels: Content:JS, needs triage
