### ISSUE TITLE
Code snippets "over-displaying" sidebar

### ISSUE THREAD

**Issue by dostonnabotov** [mdn/content#26233] opened 2023-04-16 01:16 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base

### What specific section or headline is this issue about?

Sidebar and Code snippets

### What information was incorrect, unhelpful, or incomplete?

When opening a sidebar on mobile device, code snippets display on top of the sidebar, making it harder to read and a bad user experience. 

### What did you expect to see?

I was expecting code snippets act the same as the rest of the content. On the same layer. 

### Do you have any supporting links, references, or citations?

![screenshot display the issue on a mobile device](https://user-images.githubusercontent.com/96492656/232260819-96ebf496-1d7f-46b2-b085-e1184206c9b3.jpg)

### Do you have anything more you want to share?

I think that there might be `z-index` applied on code snippets in styles that is causing this issue. Perhaps, bumping up the `z-index` on sidebar *might* solve the problem.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/base`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/base/index.md
* Last commit: https://github.com/mdn/content/commit/942a529383ee7ee3996fb234187641c08935f3ff
* Document last modified: 2023-04-13T06:13:15.000Z

</details>

**Comment by Josh-Cena** [comment] 2023-04-16 02:01
Duplicate of https://github.com/mdn/yari/issues/8646

**Closed by Josh-Cena** 2023-04-16 02:01 UTC
Labels: Content:HTML, needs triage
