### ISSUE TITLE
Eyedropper Issue

### ISSUE THREAD

**Issue by rkawkxkdwlq** [mdn/content#28067] opened 2023-07-20 02:22 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/EyeDropper

### What specific section or headline is this issue about?

Eyedropper

### What information was incorrect, unhelpful, or incomplete?

I'm trying to use the browser's built-in eyedropper, but after using the open method, the windows ime is not being set properly.
If I click outside of the browser to break the focus state of that window or another tap and come back in, it starts working normally.

![image](https://github.com/mdn/content/assets/24672968/33ae6771-078f-45c2-9483-ba7929bbba5d)

https://github.com/mdn/content/assets/24672968/646a5a51-3939-4df3-b88c-a503bffa78b3

example)
After using the eyedropper inside https://developer.mozilla.org/en-US/docs/Web/API/EyeDropper, you can see that the IME settings are not working properly in the search input tag at the top.

### What did you expect to see?

The keyboard's korean/english keys work normally after the eyedropper action

**Comment by kemilbeltre** [comment] 2023-07-20 16:25
Which browser are you using? and also what is the IME ([?](https://www.google.com/intl/en-GB/inputtools/services/features/input-method.html))? thanks

**Comment by rkawkxkdwlq** [comment] 2023-07-20 23:43
> Which browser are you using? and also what is the IME ([?](https://www.google.com/intl/en-GB/inputtools/services/features/input-method.html))? thanks

i'm using Chrome browser and also Edge Browser.
IME is mode for Language.
cannot change keyboard language in browser

**Comment by IOxCyber** [comment] 2023-07-21 15:25
Check it out, might help.
https://superuser.com/questions/1323593/windows-10-default-input-method-always-resetted-to-english-currently-using-kore

**Comment by kemilbeltre** [comment] 2023-07-23 21:07
Probably I'm wrong, but this look like a bug with the API rather than the documentation and if that's true, there's nothing we can't do about it.

**Comment by kemilbeltre** [comment] 2023-07-23 21:11
On the other hand, I can't reproduce the error.

**Comment by rkawkxkdwlq** [comment] 2023-07-26 08:08
> This problem seems to occur only in Windows browsers.
It doesn't occur on Mac

**Comment by Josh-Cena** [comment] 2023-08-08 23:33
Yes, let's close this one because it appears to be an integration issue which will be too much to document for us :)

**Closed by Josh-Cena** 2023-08-08 23:33 UTC
Labels: help wanted, Content:WebAPI, needs info
