### ISSUE TITLE
Issue with "Express Tutorial Part 3: Using a Database (with Mo…": (short summary here please)

### ISSUE THREAD

**Issue by JanSladky65** [mdn/content#3319] opened 2021-03-20 16:32 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose

#### What information was incorrect, unhelpful, or incomplete?
trying to create the database name local_library on  mongodb atlas leads to an error for me.
seems the underscore in the name causes an error.
omitting the underscore and using locallibrary leads to successful creation of the database.

#### Did you test this? If so, how?
entering locallibrary

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/mongoose`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/mongoose/index.html
* Last commit: https://github.com/mdn/content/commit/adc309da4235ec6c01f40e3212168ea5b98358c9
* Document last modified: 2021-01-29T01:56:44.000Z

</details>

**Comment by hamishwillee** [comment] 2021-03-22 01:19
Works for me. Here is local library:
![image](https://user-images.githubusercontent.com/5368500/111928660-61b23400-8b08-11eb-9fa9-9f8d516b3177.png)

If I do "Create database" 

![image](https://user-images.githubusercontent.com/5368500/111928783-b35abe80-8b08-11eb-9791-15555b2fdce7.png)
 
 YOu can see the item created.

![image](https://user-images.githubusercontent.com/5368500/111928819-cec5c980-8b08-11eb-8501-a9e13275d489.png)

So something else is going on here. 

Can you please show me what you are seeing exactly.

**Comment by hamishwillee** [comment] 2021-03-29 23:56
I'm closing this as "unable to reproduce". Feel free to reopen with additional information if you need help debugging.

**Closed by hamishwillee** 2021-03-29 23:56 UTC
