### ISSUE TITLE
iframes not working

### ISSUE THREAD

**Issue by CH4R4F** [mdn/content#9864] opened 2021-10-17 00:13 UTC
MDN: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Add_a_button_to_the_toolbar
I was trying to learn how to create an extension on firefox but I found that a lot of videos don't work.
not just on this page but a lot of pages in the `WebExtensions` subdomain afaik have an invalid iframe src link
![Screenshot 2021-10-17 at 01-07-31 Add a button to the toolbar - Mozilla MDN](https://user-images.githubusercontent.com/74823355/137605126-1ae2f25c-6159-49b2-9a18-14ee2abf4561.png)

**Comment by wbamberg** [comment] 2021-10-17 00:42
Closing as a duplicate of https://github.com/mdn/content/issues/7457.

**Closed by wbamberg** 2021-10-17 00:42 UTC
