### ISSUE TITLE
Issue with "Intl.NumberFormat() constructor": currencyDisplay: "narrowSymbol" does not seem to be supported in Safari

### ISSUE THREAD

**Issue by waiteb** [mdn/content#3053] opened 2021-03-12 03:58 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat

#### What information was incorrect, unhelpful, or incomplete?

It appears that `currencyDisplay: "narrowSymbol"` is not supported by Safari.

#### What did you expect to see?
I expected to see this incompatibility listed in the browser compatibility sections.

#### Did you test this? If so, how?
I executed the following in the console:

```
// This results in: RangeError: currencyDisplay must be either "code", "symbol", or "name"
new Intl.NumberFormat("en-US", {currency: "USD", currencyDisplay: "narrowSymbol", style: "currency"}).format(100)
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/intl/numberformat/numberformat`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/intl/numberformat/numberformat/index.html
* Last commit: https://github.com/mdn/content/commit/3b80812a1d4f68e57f35fca763f50bf3e5dfe997
* Document last modified: 2021-02-19T19:57:02.000Z

</details>

**Comment by sideshowbarker** [comment] 2021-03-12 08:59
@waiteb Thanks for taking time to report this. At https://github.com/mdn/browser-compat-data/pull/9371, I actually already have a patch with a fix for this. And we also have an open issue for it over there at https://github.com/mdn/browser-compat-data/issues/9319.

So I’m going to go ahead and close this issue here as a duplicate of that BCD done. Feel free of course to subscribe to https://github.com/mdn/browser-compat-data/issues/9319 if you want to know when that patch has landed — which should be some time next week.

But note that after it does land, it will take some time for it to get deployed. If it lands next week, the earliest the change will actually appear in the production MDN site is the week of March 22nd.

**Closed by sideshowbarker** 2021-03-12 08:59 UTC
Labels: Content:JS, duplicate, needs-triage
