### ISSUE TITLE
Content bug: Link prefetching FAQ need to be update

### ISSUE THREAD

**Issue by Jxck** [mdn/content#13958] opened 2022-03-16 19:37 UTC
## What page(s) did you find the problem on?

This issue is tags for old content.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Link_prefetching_FAQ

is last updated at March 3, 2003 and mentioning Old Firefox implementation.
Need to be updated.

## Specific page section or heading?

totally on this page

## What is the problem?

too old information based on old implementation.

## What did you expect to see?

- update with current spec
- update with current implementation
- mentioning not only Firefox but also others or make it more general

## Did you test this? If so, how?

N/A

**Comment by wbamberg** [comment] 2022-03-16 23:13
Duplicate of https://github.com/mdn/content/issues/13249. But yes, it does need to be updated!

**Closed by wbamberg** 2022-03-16 23:13 UTC
Labels: needs-triage
