### ISSUE TITLE
Inconsistent Web Components > Using custom elements documentation

### ISSUE THREAD

**Issue by ecyrb** [mdn/content#26447] opened 2023-04-27 05:23 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_custom_elements

### What specific section or headline is this issue about?

Multiple sections in the page regarding use of  `connectedCallback`.

### What information was incorrect, unhelpful, or incomplete?

`connectedCallback` is discussed as being used instead of constructors, but in the linked-to code samples, `connectedCallback` is not used.

> Inside the method `connectedCallback`, we define all the functionality the element will have when the element is connected to the DOM. In this case we attach a shadow root to the custom element, use some DOM manipulation to create the element's internal shadow DOM structure — which is then attached to the shadow root — and finally attach some CSS to the shadow root to style it. We don't use constructor() because an element's attributes are unavailable until connected to the DOM.

> Note: You can see the [full JavaScript source](https://github.com/mdn/web-components-examples/blob/main/popup-info-box-web-component/main.js) code here.

### What did you expect to see?

I don't actually know what the correct approach is.

### Do you have anything more you want to share?

The documentation is really great and helpful. Thank you!

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/web_components/using_custom_elements`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_custom_elements
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/web_components/using_custom_elements/index.md
* Last commit: https://github.com/mdn/content/commit/ac2874857a3de0be38430e58068597edf0afa2b2
* Document last modified: 2023-04-13T22:52:32.000Z

</details>

**Comment by Josh-Cena** [comment] 2023-04-27 05:54
Duplicate of https://github.com/mdn/content/issues/22887

**Closed by Josh-Cena** 2023-04-27 05:54 UTC
Labels: Content:WebAPI, needs triage
