### ISSUE TITLE
Issue with "The JavaScript input interpreter": Multiline Console: Previous Expression button does not show previous expression

### ISSUE THREAD

**Issue by ZianAtFirstWatch** [mdn/content#3464] opened 2021-03-24 17:57 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Web_Console/The_command_line_interpreter

#### What information was incorrect, unhelpful, or incomplete?
The article says:

> In multi-line mode, use the  ⋀ and ⋁ icons in the editing panel's toolbar.

In reality, those buttons don't do anything.

#### Specific section or headline?
Execution history

#### What did you expect to see?
1+1;

#### Did you test this? If so, how?
1. Launch Firefox
2. Press F12
3. Go to the multi-line console (assuming it is already enabled)
4. Type `1+1;` and press CTRL+Enter.
5. Observe that "2" appears on the right-hand side.
6. Type `2+2;` and press CTRL+Enter.
7. Observe that "4" appears on the right-hand side.
8. Click the Previous Expression button. `1+1;` will not appear.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/web_console/the_command_line_interpreter`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Web_Console/The_command_line_interpreter
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/web_console/the_command_line_interpreter/index.html
* Last commit: https://github.com/mdn/content/commit/7529c9923e0f47c32d405f79dffdf0a22d57153e
* Document last modified: 2021-02-15T16:37:40.000Z

</details>

**Comment by himanshugarg** [comment] 2021-09-07 02:19
Unless the issue is about the very first click on ⋀, which doesn't seem to do anything, the buttons work as expected. i.e. take you to the previous / next expression.

**Comment by sideshowbarker** [comment] 2021-09-07 04:18
@ZianAtFirstWatch Can you please https://github.com/mdn/content/issues/3464#issuecomment-913941997 and respond?

**Comment by sideshowbarker** [comment] 2022-01-18 02:44
Closing for lack of response

**Comment by ZianAtFirstWatch** [comment] 2022-01-18 23:19
> Unless the issue is about the very first click on ⋀, which doesn't seem to do anything, the buttons work as expected. i.e. take you to the previous / next expression.

Yes, I am referring to the first click. I don't see anything in the F12 window or the documentation that says I should click two times to see the previous expression.

**Comment by ddbeck** [comment] 2022-03-24 11:56
Hi, I'm closing this issue because [Firefox DevTools User Docs](https://firefox-source-docs.mozilla.org/devtools-user/index.html#firefox-devtools-user-docs) have moved off of MDN (see https://github.com/mdn/content/pull/14140 for details on content moved). If this issue is still applicable to the relocated documentation, please see the Firefox Source Docs site for details on raising bugs and contributing. Thanks for your understanding!

**Closed by ddbeck** 2022-03-24 11:56 UTC
Labels: Content:DevTools, idle
