### ISSUE TITLE
Issue with "Other form controls": …

### ISSUE THREAD

**Issue by grind-t** [mdn/content#1152] opened 2021-01-10 14:42 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/Other_form_controls

#### What information was incorrect, unhelpful, or incomplete?
There is no description of the &lt;output&gt; element, although at the beginning of the article and in the previous article it was written that the element will be discussed in more detail.

#### Specific section or headline?
[Other form features](https://developer.mozilla.org/en-US/docs/Learn/Forms/Other_form_controls#other_form_features).

#### What did you expect to see?
&lt;output&gt; element description.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/forms/other_form_controls`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/Other_form_controls
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/learn/forms/other_form_controls/index.html
* Report started: 2021-01-10T13:43:27.058Z

</details>

**Comment by rachelandrew** [comment] 2021-01-11 10:49
@chrisdavidmills do you know what was intended to be added to this page?

The previous page at https://developer.mozilla.org/en-US/docs/Learn/Forms/HTML5_input_types goes into a reasonable amount of detail about `<output>`. As mentioned in the issue, the page https://developer.mozilla.org/en-US/docs/Learn/Forms/Other_form_controls says it will talk about it, but then doesn't.

I'm not really sure what else needs to be included in Learn materials, given that we already have details of this element.

**Comment by chrisdavidmills** [comment] 2021-01-11 15:52
Oops, looks like I made a mistake while writing this ;-)

I think I meant to add an H3 covering a bit more detail about `<ouput>`, underneath https://developer.mozilla.org/en-US/docs/Learn/Forms/Other_form_controls#other_form_features.

Explain what output is for, why it is more accessible than just using a `<p>` element to contain the output, show a simple example, that kind of thing.

But I'm happy for you to fix this in any way you think makes sense. We do cover it in the previous article, so perhaps repeating the content here would be overkill.

**Comment by Ryuno-Ki** [comment] 2021-01-31 17:36
So if I got that right, the task is for @rachelandrew to add more content?

**Comment by rachelandrew** [comment] 2021-01-31 18:08
@Ryuno-Ki yes, it's assigned to me so it's on my list.

**Closed** 2021-06-18 22:04 UTC
Labels: Content:HTML, Content:Learn, needs-triage
