### ISSUE TITLE
Invalid example code in docs/Web/JavaScript/Reference/Global_Objects/Atomics/load

### ISSUE THREAD

**Issue by sgbeal** [mdn/content#19410] opened 2022-08-11 13:30 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Atomics/load

### What specific section or headline is this issue about?

The "Try It" block at the top

### What information was incorrect, unhelpful, or incomplete?

The Try It code block contains:

```js
// create a SharedArrayBuffer with a size in bytes
const buffer = new SharedArrayBuffer(16);
const uint8 = new Uint8Array(buffer);
uint8[0] = 5;

// 5 + 2 = 7
console.log(Atomics.add(uint8, 0, 2));
// expected output: 5
console.log(uint8[0]);
console.log(Atomics.load(uint8, 0));
// expected output: 7
```

Tapping "run" for that code block simply produces:

```js
Error: SharedArrayBuffer is not defined
```

in both Firefox v103 and Chrome v104 on Linux x86/64.

### What did you expect to see?

The output suggested by the comments in the code snippet.

### Do you have any supporting links, references, or citations?

N/A

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/atomics/load`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Atomics/load
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/atomics/load/index.md
* Last commit: https://github.com/mdn/content/commit/c4388033d7bb7a1e394fe540f9f7e8c8f5a2a192
* Document last modified: 2021-08-22T06:58:09.000Z

</details>

**Comment by Josh-Cena** [comment] 2022-08-11 13:52
Duplicate of #15169

**Closed by Josh-Cena** 2022-08-11 13:52 UTC
Labels: Content:JS, needs-triage
