### ISSUE TITLE
PostCSS example doesn't work

### ISSUE THREAD

**Issue by risa-r** [mdn/content#21541] opened 2022-10-14 01:39 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Introducing_complete_toolchain

### What specific section or headline is this issue about?

Using future features

### What information was incorrect, unhelpful, or incomplete?

In the instruction of using postcss-preset-env, it says "1. Add a single file called .postcssrc to the root of your project directory". 
I think the file name ".postcssrc" is misspelled (missing a "s"), as with this file name an error occurred ("will-it-miss/src/index.css:undefined:undefined: plugin is not a function") and the app did not work.

### What did you expect to see?

I think the correct file title is "postcsssrc". With that change, the app worked properly.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/tools_and_testing/understanding_client-side_tools/introducing_complete_toolchain`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Introducing_complete_toolchain
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/tools_and_testing/understanding_client-side_tools/introducing_complete_toolchain/index.md
* Last commit: https://github.com/mdn/content/commit/4f6ba2f5a1615fe155292cac416c7ab6b9d711ec
* Document last modified: 2022-09-11T17:33:19.000Z

</details>

**Comment by Josh-Cena** [comment] 2022-10-14 02:13
`.postcssrc` is the correct name. The `rc` suffix is a convention for "configuration". The fact that your misspelled file works is because it causes PostCSS to work with no config at all.

The reason why the config we present throws an error is a separate story that needs investigation. Possibly a major version incompatibility.

**Comment by Josh-Cena** [comment] 2023-06-29 18:33
Duplicate of https://github.com/mdn/content/issues/12495

**Closed by Josh-Cena** 2023-06-29 18:33 UTC
Labels: help wanted, effort: medium, Content:Learn:Client-side
