### ISSUE TITLE
Page should not have Baseline 

### ISSUE THREAD

**Issue by estelle** [mdn/content#34393] opened 2024-06-25 02:43 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Compatibility_tables

### What specific section or headline is this issue about?

The Baseline banner

### What information was incorrect, unhelpful, or incomplete?

There should be no Baseline banner at the top of the page. This page is a writing guidelines page, not a web feature page

### What did you expect to see?

no banner

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mdn/writing_guidelines/page_structures/compatibility_tables`
* MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Compatibility_tables
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mdn/writing_guidelines/page_structures/compatibility_tables/index.md
* Last commit: https://github.com/mdn/content/commit/cb1c745168764c4646631e7c4289319d782cc83b
* Document last modified: 2024-02-22T22:59:05.000Z

</details>

**Comment by Josh-Cena** [comment] 2024-06-25 04:21
Duplicate of https://github.com/mdn/yari/issues/11328

**Closed by Josh-Cena** 2024-06-25 04:21 UTC
Labels: needs triage, Content:Meta
