### ISSUE TITLE
“Introducing a complete toolchain”: Problem with starting the server

### ISSUE THREAD

**Issue by tari-w** [mdn/content#18439] opened 2022-07-17 08:08 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Introducing_complete_toolchain

### What specific section or headline is this issue about?

Using future features

### What information was incorrect, unhelpful, or incomplete?

I followed the tutorial along and got stuck with starting up the server. First it got stuck in the building process after running the command `npx parcel src/index.html`. After 5 minutes, I canceled the command and tried it again. Then it threw the following error: `🚨  /Desktop/will-it-miss/src/index.css:undefined:undefined: plugin is not a function`. I found out that using the command `npm install postcss-preset-env` as recommended at https://preset-env.cssdb.org worked fine for me. 

### What did you expect to see?

Please find out if that's just a mistake of mine or wether the tutorial needs an update.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/tools_and_testing/understanding_client-side_tools/introducing_complete_toolchain`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Introducing_complete_toolchain
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/tools_and_testing/understanding_client-side_tools/introducing_complete_toolchain/index.md
* Last commit: https://github.com/mdn/content/commit/831aabc34db752bfd7fac701577870d7692b2804
* Document last modified: 2022-04-28T05:11:47.000Z

</details>

**Comment by WaliAblikim** [comment] 2022-08-24 08:26
@tari-w  I got the same problem, how did you solved could you please more spesific

**Comment by WaliAblikim** [comment] 2022-08-24 08:27
@tari-w  I got the same problem, how did you solved could you please more spesific

**Comment by tari-w** [comment] 2022-08-24 10:22
I can't recall the problem anymore in detail. But try to start the server as described here: https://github.com/csstools/postcss-plugins/tree/main/plugin-packs/postcss-preset-env#usage

**Comment by Josh-Cena** [comment] 2023-06-27 13:13
Duplicate of https://github.com/mdn/content/issues/12495

**Closed by Josh-Cena** 2023-06-27 13:13 UTC
Labels: Content:Learn:Client-side
