### ISSUE TITLE
Errors index.css file 

### ISSUE THREAD

**Issue by Khushboo-123** [mdn/content#23216] opened 2022-12-27 07:45 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Introducing_complete_toolchain

### What information was incorrect, unhelpful, or incomplete?

got 9+ errors in index.css of src folder  transformation between nested CSS and natively supported CSS with the help of PostCSS, is not happening  .

### What did you expect to see?

exprexted to see postcss  working properly but its not 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/tools_and_testing/understanding_client-side_tools/introducing_complete_toolchain`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Introducing_complete_toolchain
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/tools_and_testing/understanding_client-side_tools/introducing_complete_toolchain/index.md
* Last commit: https://github.com/mdn/content/commit/e0de864abf4c85888c0a790058e0d6f46462ca3a
* Document last modified: 2022-11-18T21:06:31.000Z

</details>

**Comment by bsmth** [comment] 2023-02-09 09:30
Hi @Khushboo-123, thanks a lot for opening the issue. I can't reproduce it with the following steps:

```bash
# clone the repo
git clone git@github.com:remy/mdn-will-it-miss.git
# install deps
npm i
# run parcel
npx parcel src/index.html
```

Could you try again or let us know what steps you took to get the errors? Thank you :)

**Comment by wbamberg** [comment] 2023-03-23 21:43
Closing as unresponsive.

**Closed by wbamberg** 2023-03-23 21:43 UTC
Labels: help wanted, Content:Learn:Client-side
