### ISSUE TITLE
Issue with "Document: scroll event": bad example, needs to be replaced

### ISSUE THREAD

**Issue by Kaiido** [mdn/content#10580] opened 2021-11-17 02:52 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/scroll_event

#### What information was incorrect, unhelpful, or incomplete?
The Examples section states that scroll events can fire at high rate, and that it is recommended to throttle it through requestAnimationFrame.  
The scroll event actually already fires in the [rendering steps](https://html.spec.whatwg.org/multipage/webappapis.html#update-the-rendering) of the event loop (step 7), just like requestAnimationFrame callbacks (step 13), so throttling this event using requestAnimationFrame makes no sense at all, and using anything else makes only very little sense.

#### Specific section or headline?
Examples > "Scroll event throttling"

#### What did you expect to see?
Maybe an actual example on how to use the event, but not this.

#### Did you test this? If so, how?
https://jsfiddle.net/aujqx28L/

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/document/scroll_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/scroll_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/document/scroll_event/index.md
* Last commit: https://github.com/mdn/content/commit/2279e5ae6c229c707a014a22aa1ec4635a0f981f
* Document last modified: 2021-09-14T18:08:09.000Z

</details>

**Comment by Josh-Cena** [comment] 2022-12-23 16:43
Duplicate of https://github.com/mdn/content/issues/12701. I'm going to track in that issue because that one seems to offer more details, but cross-linking both so we get the full picture.

**Closed by Josh-Cena** 2022-12-23 16:43 UTC
Labels: help wanted, Content:WebAPI, effort: medium
