### ISSUE TITLE
offsetParent affected by transform, filter, etc

### ISSUE THREAD

**Issue by m1gu3l** [mdn/content#33252] opened 2024-04-24 08:56 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetParent

### What information was incorrect, unhelpful, or incomplete?

It seems that there are other conditions that affect this property.

### What did you expect to see?

Complete list of CSS properties that would affect offsetParent.

### Do you have any supporting links, references, or citations?

https://stackoverflow.com/questions/52937708/why-does-applying-a-css-filter-on-the-parent-break-the-child-positioning#52937920

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/htmlelement/offsetparent`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetParent
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmlelement/offsetparent/index.md
* Last commit: https://github.com/mdn/content/commit/a3d9f61a8990ba7b53bda9748d1f26a9e9810b18
* Document last modified: 2023-04-07T00:39:15.000Z

</details>

**Comment by Josh-Cena** [comment] 2024-06-30 19:03
Duplicate of https://github.com/mdn/content/issues/28991

**Closed by Josh-Cena** 2024-06-30 19:03 UTC
Labels: help wanted, Content:WebAPI
