### ISSUE TITLE
Issue with "Understanding WebAssembly text format": …

### ISSUE THREAD

**Issue by Kylebrown9** [mdn/content#755] opened 2020-12-30 05:06 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/WebAssembly/Understanding_the_text_format

#### What information was incorrect, unhelpful, or incomplete?
In the "Signatures and parameters section", there is a link on the phrase "later this will be relaxed" to the following URL.
https://webassembly.org/docs/future-features#multiple-return

#### Specific section or headline?
Signatures and parameters

#### What did you expect to see?
A link to the WASM Multi-value feature overview, which can be found at the following URL and reached from the webassembly.org website.
https://github.com/WebAssembly/spec/blob/master/proposals/multi-value/Overview.md

#### Did you test this? If so, how?
I visited the link on the phrase "later this will be relaxed", which brought me to a 404 page.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/webassembly/understanding_the_text_format`
* MDN URL: https://developer.mozilla.org/en-US/docs/WebAssembly/Understanding_the_text_format
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/webassembly/understanding_the_text_format/index.html
* Report started: 2020-12-30T04:59:55.578Z

</details>

**Comment by chrisdavidmills** [comment] 2020-12-30 12:04
Closing this as a dupe of #756

**Comment by chrisdavidmills** [comment] 2020-12-30 12:05
oops, my mistake, sorry!

**Closed** 2021-04-26 00:03 UTC
Labels: 30 minute task, Content:wasm, P2, help wanted
