### ISSUE TITLE
CanvasRenderingContext2D needs improved `fontStretch` property example

### ISSUE THREAD

**Issue by bsmth** [mdn/content#20208] opened 2022-09-01 14:39 UTC
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/fontStretch

> This example doesn't show different text renderings to me (in Chrome).
>[Like in CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/font-stretch#examples), should a new FontFace be added to the document first?

```javascript
let ff = new FontFace('myfont', url);
ff.stretch = "condensed";
document.fonts.add(ff);

document.fonts.ready.then(() => {
    ctx.font = '25px myfont';
    ctx.fontStretch = "condensed";
}
```
_Originally posted by @Elchi3 in https://github.com/mdn/content/pull/19859#discussion_r955770449_

**Comment by hamishwillee** [comment] 2022-09-01 23:31
I was still investigating this when the previous issue merged.

The problem is that you can only stretch a variable font that supports stretching. So yes, we do need to add a font that does this. 

The ideal would be to load it from the same folder but that isn't supported yet - see https://github.com/mdn/yari/issues/5727 (ideal because then we could steal the font used in the CSS version of this interactive example). Can't load it from github as that results in a cross-side fetch error. 

What I have been trying in the meantime is loading from google fonts. However defining a URL that actually provides the required stretchable font hasn't worked. Still trying.

**Comment by bsmth** [comment] 2022-09-02 08:06
OK, I'll leave this one in your court while you try to get it working. Let me know if you'd like to hand it over, happy to pick it up.

**Closed** 2022-09-23 13:51 UTC
Labels: help wanted, Content:WebAPI
