### ISSUE TITLE
Resize observer example outdated

### ISSUE THREAD

**Issue by zba** [mdn/content#1848] opened 2020-11-06 06:24 UTC
It does not have check for entry.contentBoxSize.inlineSize[0]

**Comment by himanshugarg** [comment] 2021-08-30 12:48
@zba Sorry this question is coming late and I might be missing something. I could not locate the code snippet `entry.contentBoxSize.inlineSize[0]`. Further `entry.contentBoxSize.inlineSize` does not seem to be an array. Could you please add the check you want added and the page you want it on?

**Comment by sideshowbarker** [comment] 2021-09-07 04:12
Closing for lack of response

**Comment by MarcSymonds** [comment] 2021-09-08 13:03
I think the issue is that the specification - [https://drafts.csswg.org/resize-observer/#resize-observer-entry-interface](https://drafts.csswg.org/resize-observer/#resize-observer-entry-interface) - specifies the **contentBoxSize** and **borderBoxSize** properties of the _ResizeObserverEntry_ interface as **FrozenArrays** and not a single instance.

The example [resize-observer-border-radius.html](https://mdn.github.io/dom-examples/resize-observer/resize-observer-border-radius.html) treats these properties as single instances. This example does work in FF (which suggests that FF is not following the specification), but it does not work in Chrome or Edge.

I believe the OP is pointing out that this part of the example:-
```
for (let entry of entries) {
          if(entry.contentBoxSize) {
            entry.target.style.borderRadius = Math.min(100, (entry.contentBoxSize.inlineSize/10)  +
                      (entry.contentBoxSize.blockSize/10)) + 'px';
          } else {
            entry.target.style.borderRadius = Math.min(100, (entry.contentRect.width/10) +
                      (entry.contentRect.height/10)) + 'px';
          }
        }
```

should be changed to:-
```
for (let entry of entries) {
          if(entry.contentBoxSize) {
            entry.target.style.borderRadius = Math.min(100, (entry.contentBoxSize[0].inlineSize/10)  +
                      (entry.contentBoxSize[0].blockSize/10)) + 'px';
          } else {
            entry.target.style.borderRadius = Math.min(100, (entry.contentRect.width/10) +
                      (entry.contentRect.height/10)) + 'px';
          }
        }
```

Which would also mean that FF also be modified accordingly.

**Comment by wbamberg** [comment] 2022-01-13 19:15
I think this would be fixed by https://github.com/mdn/dom-examples/pull/84 ?

**Comment by sideshowbarker** [comment] 2022-02-02 03:14
Fixed by https://github.com/mdn/dom-examples/pull/84

**Closed by sideshowbarker** 2022-02-02 03:14 UTC
Labels: Content:WebAPI, needs info
