### ISSUE TITLE
Function not up to date?

### ISSUE THREAD

**Issue by tari-w** [mdn/content#18418] opened 2022-07-16 12:28 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Package_management

### What specific section or headline is this issue about?

Having fun with Parcel

### What information was incorrect, unhelpful, or incomplete?

First of all  I am new to this kind of world, so most likely it's my mistake, anyway:

I followed the tutorial along and got stuck with this line of code:

> import { formatDistanceToNow } from 'date-fns'
> 
> const date = '1996-09-13 10:00:00';
> document.body.textContent = formatDistanceToNow(new Date(date)) + ' ago';

For me this only worked out without the time included:

> const date = '1996-09-13'

Maybe the newest Version of date-fns needs a different input?

### What did you expect to see?

A updated version of the code block. 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/tools_and_testing/understanding_client-side_tools/package_management`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Package_management
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/tools_and_testing/understanding_client-side_tools/package_management/index.md
* Last commit: https://github.com/mdn/content/commit/73ea2b0f8ebfab23630b86e64b14a7b1f7577679
* Document last modified: 2022-05-13T04:41:50.000Z

</details>

**Comment by Josh-Cena** [comment] 2022-07-16 13:12
What does "work" refer to when you say "this only worked"? You are converting it to a `Date` first, at which step it's a pure JS API.

**Comment by tari-w** [comment] 2022-07-16 13:46
While using `const date = '1996-09-13 10:00:00';` server returns an empty html file. To be more precise, the browser shows a blank page. As soon as I'm changing the value of the const data to `'1996-09-13'` the browser shows "26 years ago". (Something like that, I don't have it in front of me now.) By that I conclude, that the function can't make sense of the value '1996-09-13 10:00:00'.

**Comment by Josh-Cena** [comment] 2022-07-16 13:53
I cannot reproduce that on my end. Here's my package.json:

```json
{
  "dependencies": {
    "date-fns": "^2.28.0",
    "parcel-bundler": "^1.12.5"
  }
}
```

Everything's working as described with the `index.html` and `index.js` provided.

**Comment by tari-w** [comment] 2022-07-17 08:13
Here is my js-code:

`import { formatDistanceToNow } from 'date-fns'

const date = '1996-09-13 20:00:00';
document.body.textContent = formatDistanceToNow(new Date(date)) + ' ago';`

and here is my package.json:

`{
  "name": "parcel-experiment",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "dev": "parcel serve index.html"
  },
  "author": "tari",
  "license": "ISC",
  "dependencies": {
    "date-fns": "^2.28.0",
    "parcel-bundler": "^1.12.5"
  }
}`

**Comment by sideshowbarker** [comment] 2022-11-07 06:48
@Josh-Cena Not sure how to proceed on this one? Should be close it?

**Comment by Josh-Cena** [comment] 2022-11-07 07:08
I'm not sure—I wasn't able to reproduce it in any way, so maybe we can close it since others aren't complaining either.

**Comment by sideshowbarker** [comment] 2022-11-07 07:28
OK, yeah, let’s go ahead and close it, then

@tari-w We’re closing this because we’ve not been able to reproduce it and we’ve not gotten any other problem reports about it. If you end up having some new information about how to reproduce it, this issue can be revisited.

**Closed by sideshowbarker** 2022-11-07 07:28 UTC
Labels: needs info, Content:Learn:Client-side
