### ISSUE TITLE
Issue with "Compiling from Rust to WebAssembly": …

### ISSUE THREAD

**Issue by cogiton** [mdn/content#1380] opened 2021-01-16 05:24 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/WebAssembly/Rust_to_wasm

#### What information was incorrect, unhelpful, or incomplete?

There is mention of filling in my username in the instructions, but no '@' sign in the sample code as mentioned in the following line:
"Note that you need to fill in your own username, after the @, in the dependencies section."

Another mention of username is equally ambiguous:
"Note that you need to fill in your npm username again."

I am not able to get it to work but not sure if that this is the problem. However these steps are unclear so not sure if I'm doing them incorrectly.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/webassembly/rust_to_wasm`
* MDN URL: https://developer.mozilla.org/en-US/docs/WebAssembly/Rust_to_wasm
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/webassembly/rust_to_wasm/index.html
* Report started: 2021-01-16T05:18:49.196Z

</details>

**Comment by chrisdavidmills** [comment] 2021-01-16 12:15
Closing this; duplicate of https://github.com/mdn/content/issues/505

**Closed by chrisdavidmills** 2021-01-16 12:15 UTC
