### ISSUE TITLE
After navigator.platform is abandoned ，Who can replace the function of the platform？

### ISSUE THREAD

**Issue by Sunny-117** [mdn/content#23220] opened 2022-12-27 12:43 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/platform#browser_compatibility

### What information was incorrect, unhelpful, or incomplete?

After navigator.platform is abandoned ，Who can replace the function of the platform

### What did you expect to see?

After navigator.platform is abandoned ，Who can replace the function of the platform

**Comment by Josh-Cena** [comment] 2022-12-27 19:25
Duplicate of https://github.com/mdn/content/issues/20586

**Comment by Josh-Cena** [comment] 2022-12-27 19:26
Not every API has a substitution; some are deprecated because it's entire use case is not justified.

**Closed by Josh-Cena** 2022-12-27 19:26 UTC
Labels: Content:WebAPI, needs triage

**Comment by hamishwillee** [comment] 2023-01-03 01:21
@Josh-Cena While you're absolutely right, wouldn't you say https://developer.mozilla.org/en-US/docs/Web/API/User-Agent_Client_Hints_API (and specifically https://developer.mozilla.org/en-US/docs/Web/API/NavigatorUAData/platform) is a reasonable substitution for this case?

**Comment by Josh-Cena** [comment] 2023-01-03 01:50
That's true; but even in this case https://github.com/mdn/content/issues/20586 contains more information (and also points out about `userAgentData`) and was resolved with the same reason...

**Comment by hamishwillee** [comment] 2023-01-03 04:04
Fair enough - if we add all these other options people will ignore that "use feature detection" note.
