### ISSUE TITLE
Dark mode > Primary color > Light Grey

### ISSUE THREAD

**Issue by BerndHme** [mdn/content#28709] opened 2023-08-23 07:31 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn

### What specific section or headline is this issue about?

Dark mode > Primary color > Light Grey

### What information was incorrect, unhelpful, or incomplete?

The primary text could be softer in dark mode  
... its what you stare at the most time.  

The pure white text burns into your eyes in dark mode.

### What did you expect to see?

In dark mode > A softer white primary color, instead of pure white.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/index.md
* Last commit: https://github.com/mdn/content/commit/fa93ec954ca369092902573e76ede0009d15f238
* Document last modified: 2023-06-20T02:56:54.000Z

</details>

**Comment by Josh-Cena** [comment] 2023-08-23 16:22
Duplicate of https://github.com/mdn/yari/issues/7705

**Closed by Josh-Cena** 2023-08-23 16:22 UTC
Labels: needs triage
