### ISSUE TITLE
The "Image Embed element" page supposed to contain an error

### ISSUE THREAD

**Issue by fires3as0n** [mdn/content#34026] opened 2024-06-09 21:18 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img

### What specific section or headline is this issue about?

srcset

### What information was incorrect, unhelpful, or incomplete?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#srcset
The section says that
> If the `srcset` attribute uses width descriptors, the `sizes` attribute must also be present, or the `srcset` itself will be ignored.

### What did you expect to see?

Tried this in Chrome 125 and Firefox 112 - the result is that `srcset` it not ignored but rather the `sizes` gets the default value of `100vw`

### Do you have anything more you want to share?

Can someone check this and if the behavior is confirmed - we should fix the article, I was not able to find any mention of these in the HTML standard docs unfortunately

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/img`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/img/index.md
* Last commit: https://github.com/mdn/content/commit/ba5f28ab10ef1af48a55f363c8facc04a1f94479
* Document last modified: 2024-06-02T23:20:18.000Z

</details>

**Comment by Josh-Cena** [comment] 2024-06-10 04:34
Duplicate of https://github.com/mdn/content/issues/27291

**Closed by Josh-Cena** 2024-06-10 04:34 UTC
Labels: Content:HTML, needs triage
