### ISSUE TITLE
HTMLElement: the input event requires a user to initiate changing the value of a form control

### ISSUE THREAD

**Issue by fulldecent** [mdn/content#9548] opened 2021-10-04 04:10 UTC
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event

## Specific page section or heading?

The first sentence:

> The input event fires when the value of an `<input>`, `<select>`, or `<textarea>` element has been changed.

And later:

> Note: The input event is fired every time the value of the element changes....

## What is the problem?

The germane HTML specification is at: https://html.spec.whatwg.org/multipage/indices.html#event-input-input, defining this event as:

> Fired at controls when the user changes the value (see also the change event).

But the definition on MDN is more expansive, removing the qualification that changes must be initiated by the user.

For the avoidance of doubt, we are here discussing whether some non-user-initiated change should fire the `input` event.

## What did you expect to see?

It is very possible that MDN is right and this is a mistake in the HTML spec. If so the spec should be updated. But also the MDN page should recognize and explain this difference until it is fixed upstream.

## Did you test this? If so, how?

No

**Comment by Josh-Cena** [comment] 2023-06-19 10:29
I will close it as a duplicate of https://github.com/mdn/content/issues/27044. This one is submitted earlier but that one already has a linked issue and more conversation ^^

**Closed by Josh-Cena** 2023-06-19 10:30 UTC
Labels: help wanted, Content:WebAPI
