### ISSUE TITLE
wrong fragment shader source in example

### ISSUE THREAD

**Issue by notnot** [mdn/content#33555] opened 2024-05-11 21:58 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Using_textures_in_WebGL

### What specific section or headline is this issue about?

The fragment shader

### What information was incorrect, unhelpful, or incomplete?

The given fragment shader source on the tutorial page can't be compiled by the browser. Is says WebGL 3.0 or higher is required, and a few more errors.

### What did you expect to see?

A working program.

### Do you have anything more you want to share?

The code on github contains fragment shader source that is complied just fine, and it all works.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/webgl_api/tutorial/using_textures_in_webgl`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Using_textures_in_WebGL
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/webgl_api/tutorial/using_textures_in_webgl/index.md
* Last commit: https://github.com/mdn/content/commit/005cc1fd55aadcdcbd9aabbed7d648a275f8f23a
* Document last modified: 2024-01-15T21:58:53.000Z

</details>

**Comment by Josh-Cena** [comment] 2024-06-05 09:44
Duplicate of https://github.com/mdn/content/issues/32537

**Closed by Josh-Cena** 2024-06-05 09:44 UTC
Labels: Content:WebAPI, needs triage
