### ISSUE TITLE
[Not supported][JavaScript] Provide JSON.parse with source for primitives

### ISSUE THREAD

**Issue by pepelsbey** [mdn/content#32387] opened 2024-02-22 12:20 UTC
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [ ] Add entry to Firefox release notes if feature is enabled in release
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Related Gecko bugs

- [Provide JSON.parse with source for primitives](https://bugzilla.mozilla.org/show_bug.cgi?id=1860887)

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [x] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [x] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by hamishwillee** [comment] 2024-03-15 00:38
@Josh-Cena You self-assigned this to yourself - how is it going? The release is planned for  19th (4 days). Do you need any support from me on this, and if so, what?

**Comment by Josh-Cena** [comment] 2024-03-15 04:16
Sorry, I was a bit occupied for the last few weeks. I had just meant to ask what the deadline is. I will be sending a PR tonight (CET).

**Comment by hamishwillee** [comment] 2024-03-18 00:26
@Josh-Cena Have you actually managed to get any of this to work on FF? If you inspect JSON none of the changes appear implemented. Looking at the source this seems gated on `enable-json-parse-with-source` which looks like a build time config. So this is perhaps not actually released in any build? In which case we'd need a BCD, but nothing for FF?

**Comment by Josh-Cena** [comment] 2024-03-18 00:40
I'm not entirely sure. I have had a draft doc locally for half a year because it has shipped in Chrome since at least half a year ago. Looking at the bug, I also don't see signs of it being unflagged. @pepelsbey what is the reason for `dev-doc-needed`?

**Comment by hamishwillee** [comment] 2024-03-18 01:08
I'll confirm against the bug. Cheers.

**Comment by pepelsbey** [comment] 2024-03-18 12:16
> I also don't see signs of it being unflagged. [@pepelsbey](https://github.com/pepelsbey) what is the reason for `dev-doc-needed`?

Even if it’s not enabled by default, it’s still available in Firefox and worth documenting on MDN and mentioning in the [experimental features](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/124#experimental_web_features) section and on the [Experimental features](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features) page.

**Comment by hamishwillee** [comment] 2024-03-18 23:27
@pepelsbey As confirmed in https://bugzilla.mozilla.org/show_bug.cgi?id=1860887#c21 this is behind a build and runtime flag. We don't document things that require a special build to work. Of course that wasn't at all obvious on the face of it, so perfectly reasonable to add the tag.

**Comment by Josh-Cena** [comment] 2024-09-30 16:26
https://github.com/mdn/content/issues/36113

**Comment by Josh-Cena** [comment] 2024-09-30 16:26
https://github.com/mdn/content/issues/36113

**Closed** 2024-09-30 16:26 UTC
Labels: Content:JS, on hold
