### ISSUE TITLE
"Math.log()": problem with math text

### ISSUE THREAD

**Issue by alex-ander-is** [mdn/content#9883] opened 2021-10-18 07:41 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/log

#### What information was incorrect, unhelpful, or incomplete?
Wrongly escaped text

#### Specific section or headline?
The initial description
\forall x > 0, \mathtt{\operatorname{Math.log}(x)} = \ln(x) = \text{the unique} ; y ; \text{such that} ; e^y = x

#### What did you expect to see?
A correct text with no ecapes

#### Did you test this? If so, how?
It is observable by the human being.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/math/log`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/log
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/math/log/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by himanshugarg** [comment] 2021-11-28 00:32
Possible duplicate of mdn/yari#4197

**Comment by Rumyra** [comment] 2021-12-08 15:44
Assuming this is a rendering issue and has been fixed with https://github.com/mdn/yari/pull/4222

**Closed by Rumyra** 2021-12-08 15:44 UTC
Labels: Content:JS, needs-triage
