### ISSUE TITLE
Issue with "File": SVG image overflows

### ISSUE THREAD

**Issue by edent** [mdn/content#8412] opened 2021-08-28 08:03 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/File

#### What information was incorrect, unhelpful, or incomplete?

The example image overflows - meaning the user has to scroll to see its contents.

![Screenshot 2021-08-28 at 09-00-49 File - Web APIs MDN](https://user-images.githubusercontent.com/837136/131211071-5282b20f-aaae-4f68-aca8-87f0e4e8f023.png)

#### Specific section or headline?

Top section

#### What did you expect to see?

The image displayed at full height

#### Did you test this? If so, how?

Latest version of FF for Linux. Latest version of Chromium for Linux.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/file`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/File
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/file/index.html
* Last commit: https://github.com/mdn/content/commit/ae7ab6d2dff43bb2a8f79b33b5e2e77bebb5faa1
* Document last modified: 2021-07-25T00:36:06.000Z

</details>

**Comment by edent** [comment] 2021-08-28 08:10
Source of the error is 

`<p>{{InheritanceDiagram}}</p>`
On https://github.com/mdn/content/blob/main/files/en-us/web/api/file/index.html#L22

Judging from the other samples, it should be something like:

`{{InheritanceDiagram(700, 120, 20)}}`

Where 700 is the iframe's width, 120 is the height. No idea what the 3rd digit is for.

**Comment by teoli2003** [comment] 2021-08-28 08:12
The issue is a change in Yari: this is tracked by mdn/yari#4569

**Comment by AnilSeervi** [comment] 2021-09-27 07:34
This issue can be closed, as of now the fix has been merged and is live. @sideshowbarker

**Closed** 2021-09-27 07:48 UTC
Labels: Content:WebAPI
