### ISSUE TITLE
<dialog> example broken

### ISSUE THREAD

**Issue by omentic** [mdn/content#35962] opened 2024-09-19 19:28 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog

### What specific section or headline is this issue about?

html-only_dialog

### What information was incorrect, unhelpful, or incomplete?

The embedded HTML-only dialog example seems broken. Clicking the `Ok` button does nothing, on either Firefox or Chromium.

Following the `Play` link through and interacting on the playground behaves as expected.

I am not quite sure what could be causing this issue. I've poked around in the developer console a little bit, but didn't notice anything out of the ordinary.

### What did you expect to see?

.

### Do you have anything more you want to share?

I am using uBlock Origin. Disabling it did not affect the issue, however.

**Comment by Josh-Cena** [comment] 2024-09-19 20:59
Duplicate of https://github.com/mdn/yari/issues/11460

**Closed by Josh-Cena** 2024-09-19 20:59 UTC
Labels: Content:HTML, needs triage
