### ISSUE TITLE
Images, media, and form elements: object-fit 

### ISSUE THREAD

**Issue by papiasharmin** [mdn/content#9835] opened 2021-10-15 09:09 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Images_media_form_elements

#### What information was incorrect, unhelpful, or incomplete?
For object-fit property, it is important to declare the width and height of the box and image, unless it doesn't take the object-fit property.

#### Specific section or headline?
Replaced element/ sizing image / first example

#### What did you expect to see?
Describe in detail, how object-fit works.

#### Did you test this? If so, how?
Yes, the first example is for max-width, but when I try to put object-fit, it didn't work as it work for the second example. then, I put box, image width and height to the first example. then it works.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/building_blocks/images_media_form_elements`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Images_media_form_elements
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/images_media_form_elements/index.md
* Last commit: https://github.com/mdn/content/commit/07453ac2b659a397b0fee921fa71db5488e9ca62
* Document last modified: 2021-10-08T14:43:33.000Z

</details>

**Comment by Josh-Cena** [comment] 2022-12-30 02:19
Duplicate of #14023

**Closed** 2022-12-30 02:19 UTC
Labels: duplicate, Content:Learn:CSS
