### ISSUE TITLE
Issue with "Arrays": (short summary here please)

### ISSUE THREAD

**Issue by Gitthuma** [mdn/content#4022] opened 2021-04-12 00:02 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Arrays

#### What information was incorrect, unhelpful, or incomplete?

totalBox.textContent = 'Total: $' + total.toFixed(2); 
does not print total on screen because I think it is outside the loop

#### Specific section or headline?
Arrays
Active learning: Printing those products!
Ref: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Arrays

ln github repository
Ref: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/first_steps/arrays/index.html
line 247

#### What did you expect to see?
Print the total of the active learning exercise on screen after solving the problem

#### Did you test this? If so, how?
Yes I tested this inside the text area. If I put the line inside the loop it prints the total on screen

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/first_steps/arrays`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Arrays
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/first_steps/arrays/index.html
* Last commit: https://github.com/mdn/content/commit/6dba7f1c6006efd5b984e34d7731c12da73f4a6c
* Document last modified: 2021-02-09T13:00:30.000Z

</details>

**Comment by sideshowbarker** [comment] 2021-04-12 04:09
> totalBox.textContent = 'Total: $' + total.toFixed(2);
> does not print total on screen because I think it is outside the loop

I can’t reproduce that. When I press the **Show solution** button, the total displays as expected:

> Live output
> 
>     Underpants — $6.99
>     Socks — $5.99
>     T-shirt — $14.99
>     Trousers — $31.99
>     Shoes — $23.99
> 
> Total: $83.95

I get that same result in all browsers I’ve tried it with.

> Yes I tested this inside the text area. If I put the line inside the loop it prints the total on screen

Isn’t that exactly what step 5 of the instructions says to do? —

> 5. There is a variable called <code>total</code> that is created and given a value of 0 at the top of the code. Inside the loop (below <code>// number 4</code>) we want you to add a line that adds the current item price to that total in each iteration of the loop, so that at the end of the code the correct total is printed onto the invoice. You might need an <a href="/en-US/docs/Learn/JavaScript/First_steps/Math#assignment_operators">assignment operator</a> to do this.

So when you press the **Show solution** button, for step 5, it adds this line:

> ```js
>   total += price;
> ```

In other words isn’t that doing what you described as *“If I put the line inside the loop it prints the total on screen”*?

**Comment by Gitthuma** [comment] 2021-04-12 13:19
![Arrays-outside loop](https://user-images.githubusercontent.com/31987328/114400651-d843ce00-9baa-11eb-95a0-605c0de0b063.png)
![Arrays-inside loop](https://user-images.githubusercontent.com/31987328/114400657-daa62800-9baa-11eb-8cad-91cc67928146.png)

**Comment by sideshowbarker** [comment] 2021-04-12 17:19
> I also get the total when I use the show solution button, but when I work it out on the space, I dont get the same results. The above image indicates what I am saying. Maybe there is a problem with the other part of the code?

I don’t know — and it’s hard to know how to respond on this issue, since it doesn’t seem like there’s a problem in the content of that MDN article itself

**Comment by Gitthuma** [comment] 2021-04-12 20:09
Okay.. Thanks for checking. I will leave it there for now and check it again at a later time.

**Comment by sideshowbarker** [comment] 2021-06-06 00:52
Closing, as there doesn’t seem to be a possible or expected change in the MDN content which would address this issue.

**Closed by sideshowbarker** 2021-06-06 00:52 UTC
Labels: Content:Learn, needs info, needs-triage
