### ISSUE TITLE
Fragment shader contains wrong code

### ISSUE THREAD

**Issue by BasAMols** [mdn/content#33050] opened 2024-04-12 01:02 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Using_textures_in_WebGL

### What specific section or headline is this issue about?

The fragment shader

### What information was incorrect, unhelpful, or incomplete?

The fragment shader contains the following line: 
`out vec4 fragColor;`

### What did you expect to see?

This line is not present in the github source for this article, and gives an error when running in the browser. The out parameter is deprecated in webgl

### Do you have any supporting links, references, or citations?

https://github.com/mdn/dom-examples/blob/main/webgl-examples/tutorial/sample6/webgl-demo.js

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/webgl_api/tutorial/using_textures_in_webgl`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Using_textures_in_WebGL
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/webgl_api/tutorial/using_textures_in_webgl/index.md
* Last commit: https://github.com/mdn/content/commit/005cc1fd55aadcdcbd9aabbed7d648a275f8f23a
* Document last modified: 2024-01-15T21:58:53.000Z

</details>

**Comment by Josh-Cena** [comment] 2024-06-05 09:43
Duplicate of https://github.com/mdn/content/issues/32537

**Closed by Josh-Cena** 2024-06-05 09:43 UTC
Labels: Content:WebAPI, needs triage
