### ISSUE TITLE
Inconsistency in Autonomous custom elements example

### ISSUE THREAD

**Issue by thomasmatecki** [mdn/content#24909] opened 2023-02-26 15:42 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements

### What specific section or headline is this issue about?

Autonomous custom elements

### What information was incorrect, unhelpful, or incomplete?

It seems like there's some inconsistency between the exposition and the example.

The page says:
> Inside the method connectedCallback, we define all the functionality the element will have when the element is connected to the DOM. In this case we attach a shadow root to the custom element, use some DOM manipulation to create the element's internal shadow DOM structure...

... and points to an example:
> Note: You can see the [full JavaScript source](https://github.com/mdn/web-components-examples/blob/main/popup-info-box-web-component/main.js) code here.

The description describes functionality as residing in the `connectedCallback` method, but the example implements it in the constructor. In fact, I see no `connectedCallback` in the example.

### What did you expect to see?

I expected either the example to implement `connectedCallback` or the page to describe that functionality living in the constructor. 

### Do you have any supporting links, references, or citations?

HTML spec describing this: https://html.spec.whatwg.org/#custom-elements-autonomous-example.

Based on this I think the example should implement the functionality described in `connectedCallback`.

### Do you have anything more you want to share?

I'm looking at this guide without any prior knowledge of autonomous custom elements, so I'm not sure if this is inaccurate, unclear, or I'm being dense. 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/web_components/using_custom_elements`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/web_components/using_custom_elements/index.md
* Last commit: https://github.com/mdn/content/commit/9a510e3848c4c339691a0dff08a02e2c2274bd7f
* Document last modified: 2023-01-07T19:19:54.000Z

</details>

**Comment by Josh-Cena** [comment] 2023-02-26 17:07
Duplicate of https://github.com/mdn/content/issues/22887

**Closed by Josh-Cena** 2023-02-26 17:07 UTC
Labels: needs triage
