### ISSUE TITLE
Issue with "Writing style guide": (short summary here please)

### ISSUE THREAD

**Issue by NegiAkash890** [mdn/content#2389] opened 2021-02-16 11:39 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Writing_style_guide

#### What information was incorrect, unhelpful, or incomplete?
There are some heading with black background as well as these headings are inside links   (`<a>`tags)  which  are not used .

#### Specific section or headline?
Examples like : Page title in basic section , General article content guidelines , Headings etc .

#### What did you expect to see?
Fixes in Styling .

#### Did you test this? If so, how?
I navigated the whole page and clicking on the heading with black background .

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mdn/guidelines/writing_style_guide`
* MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Writing_style_guide
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/mdn/guidelines/writing_style_guide/index.html
* Last commit: https://github.com/mdn/content/commit/83e2d2550d34ffc6eb70e4f1338c78c3f8fad8be
* Document last modified: 2021-01-28T09:35:21.000Z

</details>

**Comment by NegiAkash890** [comment] 2021-02-16 11:39
I can help fixing the same . Also please let me know some other things that can done to make tidy .

**Comment by NegiAkash890** [comment] 2021-02-16 11:40
I can help fixing the same . Also please let me know some other changes that can be done to make page  tidy and clean  .
Thank You

**Comment by chrisdavidmills** [comment] 2021-02-16 11:48
Hi @NegiAkash890 !

These headings are actually like this by design — they link to themselves, but the idea is that if you want to share a link to that heading, you click on it and then copy the resulting URL from the address bar. It's the same style as GitHub README files, and it is really useful when trying to share specific sections with friends, or ask for help with debugging problems, etc.

I'm going to close this now, but  feel free to chime in if you have any more thoughts.

**Closed by chrisdavidmills** 2021-02-16 11:48 UTC
