### ISSUE TITLE
Content bug in HTTP headers > Feature-Policy

### ISSUE THREAD

**Issue by mireille-raad** [mdn/content#8739] opened 2021-09-08 01:12 UTC
## What page(s) did you find the problem on?

**Feature-Policy** page
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy

## Specific page section or heading

The note at the start that says:
> The header has now been renamed to Permissions-Policy in the spec, and this article will eventually be updated to reflect that change.

## What is the problem?

It looks like the header name needs updating. Is it only about replacing the name? or does a serious re-write need to be done? If nothing elaborate is needed, I can submit a PR.

**Comment by teoli2003** [comment] 2021-09-08 06:13
It is mostly the name, and the links, (but all the browser-compat-data info), but we want to wait until browsers are updated to the new name. I think Chrome still uses the old name.

**Comment by mireille-raad** [comment] 2021-09-08 14:47
For Chrome, is there where I can check the status?
https://www.chromestatus.com/feature/5745992911552512

If this is the correct link, I am not sure what to make of it. I can see this:
<img width="432" alt="Screen Shot 2021-09-08 at 10 45 09 AM" src="https://user-images.githubusercontent.com/521705/132531647-fc66317e-0f5a-4096-ac7b-24fac19617bf.png">

But the **status** says:

> Status: Specification being incubated in a Community Group

Incubation sounds like something is still being thought of.

Either way, this can probably wait until you are sure that Chrome now supports it.

**Comment by teoli2003** [comment] 2021-09-08 14:52
cc/ @jpmedley that will now for sure :-)

**Comment by jpmedley** [comment] 2021-09-08 17:59
We're still trying to iron the bugs out of displaying spec status on Chrome Status. If you open [the spec itself](https://w3c.github.io/webappsec-permissions-policy/) you can see that it's published on W3C, not one of the community sites.

**Comment by jpmedley** [comment] 2021-09-08 18:00
FYI, this is a duplicate of #1831.

**Comment by teoli2003** [comment] 2021-09-09 05:13
Thanks!

Closing this per the last comment.

**Closed by teoli2003** 2021-09-09 05:13 UTC
Labels: needs-triage
