### ISSUE TITLE
all HTML code not show according to the output

### ISSUE THREAD

**Issue by aditya-1417** [mdn/content#27234] opened 2023-06-09 11:45 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/:valid

### What information was incorrect, unhelpful, or incomplete?

all HTML code not show according to the  content output

### What did you expect to see?

HTML source code

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/_colon_valid`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/:valid
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/_colon_valid/index.md
* Last commit: https://github.com/mdn/content/commit/cfcbb39cc595bd536b107f6771bfb3f8e13bacca
* Document last modified: 2023-02-24T06:27:09.000Z

</details>

**Comment by bsmth** [comment] 2023-06-16 07:49
Hello @aditya-1417 - thanks for raising the issue but I don't understand what is wrong. Could you provide some more details on what you expected to see versus what the problem is? What were the steps you took and what was the result?

**Comment by Josh-Cena** [comment] 2023-06-26 19:27
Closing until more information can be provided

**Closed by Josh-Cena** 2023-06-26 19:27 UTC
Labels: Content:CSS
