### ISSUE TITLE
this.getAttribute() doesn't work inside the constructor()

### ISSUE THREAD

**Issue by Zectbumo** [mdn/content#25028] opened 2023-03-03 03:25 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements

### What specific section or headline is this issue about?

Creating the shadow DOM structure

### What information was incorrect, unhelpful, or incomplete?

This sample code that uses `this.getAttribute("img")` is misleading. The attributes are normally inaccessible from the constructor(). The only reason this works is because the script is imported using `defer` and this is not mentioned at all in the documentation. Only when you do outside research and look at the entire code in github will you realize why this works.
You can see others having the same issue on your page but I guess nobody is reporting it.

### What did you expect to see?

I expect to see a self contained working example or at least a *CAUTION* flag mentioning that defer is required because normally attributes are inaccessible.

### Do you have any supporting links, references, or citations?

https://stackoverflow.com/questions/63564717/custom-element-not-picking-up-attributes

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/element/attachshadow`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/attachShadow
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/element/attachshadow/index.md
* Last commit: https://github.com/mdn/content/commit/9fb6c9e56c6db295967384730feeb941509ac743
* Document last modified: 2023-02-22T10:15:21.000Z

</details>

**Comment by wbamberg** [comment] 2023-03-09 05:28
The page is https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements I think?

**Comment by Zectbumo** [comment] 2023-03-10 20:04
> The page is https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements I think?

yes, thank you. I updated the url

**Comment by Josh-Cena** [comment] 2023-06-23 12:01
Duplicate of https://github.com/mdn/content/issues/22887

**Closed by Josh-Cena** 2023-06-23 12:01 UTC
Labels: help wanted, Content:WebAPI
