### ISSUE TITLE
Specifications about `javascript.operators.spread` Not Found

### ISSUE THREAD

**Issue by awxiaoxian2020** [mdn/content#19455] opened 2022-08-12 06:59 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax

### What specific section or headline is this issue about?

Specifications

### What information was incorrect, unhelpful, or incomplete?

Specifications not found

### What did you expect to see?

display correctly.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/spread_syntax`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/spread_syntax/index.md
* Last commit: https://github.com/mdn/content/commit/a6785a8e4ddad80069acf2de418235c0640688e7
* Document last modified: 2022-08-05T09:19:41.000Z

</details>

**Comment by Josh-Cena** [comment] 2022-08-12 07:44
Let's say it's a duplicate of https://github.com/mdn/browser-compat-data/issues/14392. Some work has been done to the `spread` data but it seems the spec URL isn't added yet.

**Closed by Josh-Cena** 2022-08-12 07:44 UTC
Labels: Content:JS
