### ISSUE TITLE
Issue with "aria-description": broken specification link

### ISSUE THREAD

**Issue by skwh** [mdn/content#14151] opened 2022-03-21 22:44 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-description

#### What information was incorrect, unhelpful, or incomplete?

The link in the Specification section is broken. This is because `aria-description` is not actually part of the WAI-ARIA 1.1 specification, but rather the 1.3 draft.

#### Specific section or headline?

Specification

#### What did you expect to see?

A valid link to the item's definition in the WAI-ARIA specification

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/accessibility/aria/attributes/aria-description`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-description
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/accessibility/aria/attributes/aria-description/index.md
* Last commit: https://github.com/mdn/content/commit/8ef4dbee26d302b627b6ce38e51531dc578de199
* Document last modified: 2022-03-18T16:38:43.000Z

</details>

**Comment by sideshowbarker** [comment] 2022-03-22 03:03
Thanks for reporting this — we have https://github.com/mdn/content/issues/13668 open already for tracking the problem, so I’m going ahead and closing this issue as a duplicate of that one.

**Closed** 2022-03-22 03:03 UTC
Labels: duplicate, Content:Accessibility
