### ISSUE TITLE
`AudioContext.createMediaElementSource()` demo does not work in Safari

### ISSUE THREAD

**Issue by atomiks** [mdn/content#22941] opened 2022-12-14 04:04 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/createMediaElementSource

### What specific section or headline is this issue about?

Examples

### What information was incorrect, unhelpful, or incomplete?

The code does not work in Safari (Version 16.1 (18614.2.9.1.12)), despite saying support is available since Safari 6.

### What did you expect to see?

The audio to have sound and the gain to change when the cursor moves down/up the page, like in Chrome & Firefox. There's no sound at all.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/audiocontext/createmediaelementsource`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/createMediaElementSource
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/audiocontext/createmediaelementsource/index.md
* Last commit: https://github.com/mdn/content/commit/02e1bfcad5fd0de845fb033d331c3c027afa2d6e
* Document last modified: 2022-09-14T13:55:15.000Z

</details>

**Comment by Josh-Cena** [comment] 2022-12-14 04:34
Duplicate of https://github.com/mdn/content/issues/9042

**Closed by Josh-Cena** 2022-12-14 04:34 UTC
Labels: Content:WebAPI, needs-triage
