### ISSUE TITLE
Is the event type written incorrectly?

### ISSUE THREAD

**Issue by wxuanwxwx** [mdn/content#24117] opened 2023-02-03 00:27 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Element/click_event

### What specific section or headline is this issue about?

Event type

### What information was incorrect, unhelpful, or incomplete?

Is the event type written incorrectly?

### What did you expect to see?

Should the event type be PointerEvent? This interface inherits properties from MouseEvent and Event.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/element/click_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Element/click_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/element/click_event/index.md
* Last commit: https://github.com/mdn/content/commit/5cfd1335ca537802bb064f33d22f3c58f69f6ea1
* Document last modified: 2022-09-22T08:13:42.000Z

</details>

**Comment by Josh-Cena** [comment] 2023-02-03 00:30
Duplicate of https://github.com/mdn/content/issues/21567

**Closed by Josh-Cena** 2023-02-03 00:30 UTC
Labels: Content:WebAPI, needs triage
