### ISSUE TITLE
`yarn content add-redirect` is broken

### ISSUE THREAD

**Issue by mss** [mdn/content#28782] opened 2023-08-27 14:34 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Howto/Creating_moving_deleting

### What specific section or headline is this issue about?

Deleting pages

### What information was incorrect, unhelpful, or incomplete?

I guess the content is fine but the tool was broken at some point. The documentation (similarly in `CONTRIBUTING.md`) says:

> Add a redirect. The target page can be an external URL or another page on MDN Web Docs
> `yarn content add-redirect /en-US/path/of/deleted/page /en-US/path/of/target/page`

When I try this with a relative URL I get:

```
# yarn content add-redirect /en-US/docs/foo /en-US/docs/bar
yarn run v1.22.19
warning ../package.json: No license field
$ env-cmd --silent cross-env CONTENT_ROOT=files yari-tool add-redirect /en-US/docs/foo /en-US/docs/bar
(node:32544) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:32544) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time

error: Invalid URL

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

A quick glance at the source shows that the code tries to create an `URL` from the arguments. So I can work around this issue when I add a dummy host like `yarn content add-redirect https://mdn.example/en-US/docs/foo https://mdn.example/en-US/docs/bar`.

But now I want to redirect to an external URL and I get:
```
# yarn content add-redirect https://mdn.example/en-US/docs/bar https://example.com/foo
yarn run v1.22.19
warning ../package.json: No license field
$ env-cmd --silent cross-env CONTENT_ROOT=files yari-tool add-redirect https://mdn.example/en-US/docs/bar https://example.com/foo
(node:32801) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:32801) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time

error: The URL is expected to start with /$locale/docs/: /foo

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I think the code would have dropped the host here anyway.

### What did you expect to see?

No errors and this result:

```
# git diff
diff --git a/files/en-us/_redirects.txt b/files/en-us/_redirects.txt
index 0b20cde373..4f261b5050 100644
--- a/files/en-us/_redirects.txt
+++ b/files/en-us/_redirects.txt
@@ -13434,6 +13434,8 @@
 /en-US/docs/eventPhase /en-US/docs/Web/API/Event/eventPhase
 /en-US/docs/firstChild /en-US/docs/Web/API/Node/firstChild
 /en-US/docs/focus      /en-US/docs/Web/API/HTMLElement/focus
+/en-US/docs/foo        /en-US/docs/bar
+/en-US/docs/bar        https://example.com/foo
 /en-US/docs/getAttribute       /en-US/docs/Web/API/Element/getAttribute
 /en-US/docs/getAttributeNS     /en-US/docs/Web/API/Element/getAttributeNS
 /en-US/docs/getAttributeNode   /en-US/docs/Web/API/Element/getAttributeNode
```

**Comment by Josh-Cena** [comment] 2023-08-27 14:41
Duplicate of https://github.com/mdn/yari/issues/9294

**Closed by Josh-Cena** 2023-08-27 14:41 UTC
Labels: Content:WebAPI, needs triage, Content:Meta
