### ISSUE TITLE
Issue with "Useful string methods": The 'Fixing Capitalization' task live update window is not updating correctly

### ISSUE THREAD

**Issue by Joe90Prod** [mdn/content#14728] opened 2022-04-06 02:20 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Useful_string_methods

#### What information was incorrect, unhelpful, or incomplete?

The 'Fixing Capitalization' task live update window is not updating correctly. Clicking 'show solution' updates the live preview as expected, then clicking 'hide solution' does not return the preview window it to it's previous state, and neither does altering the code in the live editor.

#### Specific section or headline?

'Fixing Capitalization' 

#### What did you expect to see?

The live preview window updating as I changed code in the editor.

#### Did you test this? If so, how?

Tested in edge and chrome. Tried refreshing the page and restarting the browser.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/javascript/first_steps/useful_string_methods`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Useful_string_methods
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/first_steps/useful_string_methods/index.md
* Last commit: https://github.com/mdn/content/commit/86857d4abe35a3529f992e0650562e0d8a62182a
* Document last modified: 2022-04-03T00:44:46.000Z

</details>

**Comment by wbamberg** [comment] 2022-04-06 05:23
This works fine for me (Firefox and Chrome):

![fix-cap](https://user-images.githubusercontent.com/432915/161901533-8aac88e8-3529-4183-bad0-07032d60371c.gif)

Or have I misunderstood what you meant?

**Comment by Joe90Prod** [comment] 2022-04-06 07:42
> This works fine for me (Firefox and Chrome):
> 
> ![fix-cap](https://user-images.githubusercontent.com/432915/161901533-8aac88e8-3529-4183-bad0-07032d60371c.gif)
> 
> Or have I misunderstood what you meant?

No, you haven't. 

Since submitting this I've noticed the issue is actually intermittent, and I haven't tracked down exactly what is triggering it. I suspect from the little bit of testing that I did, that it may be to do with either - 

a) having multiple tabs open in edge for that same page , or 
b) related to the actual code I'd written that I was copy and pasting into the editor each time I refreshed and checked again.

However, this is more of an educated hunch than anything. Not particularly helpful I know!  Obviously if you can't recreate the error and no one else is reporting it, then just ignore me.

**Comment by wbamberg** [comment] 2022-04-06 16:23
I believe the idea is that:
* `Reset` takes you back to the initial state
* `Show Solution` shows you the final state
* `Hide Solution` puts you back to where you were before - so it's different from `Reset`.

I can well believe that there is a bug in the editor but I doubt it is truly intermittent or that it is dependent on having multiple tabs open. If you can find a series of steps that will reproduce this reliably, then please add them here and reopen. In the meantime I'll close this issue since we can't try to address it without that information.

**Closed by wbamberg** 2022-04-06 16:23 UTC
Labels: Content:JS
