### ISSUE TITLE
Issue with "Book list page": (author output is giving undefined)

### ISSUE THREAD

**Issue by Norberto-Boa** [mdn/content#5661] opened 2021-06-04 06:23 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/Book_list_page

#### **bookController.js**
//Display list of all books
exports.book_list = (req, res, next) => {
    Book.find({}, 'title author')
        .populate('author')
        .exec((err, list_books) => {
            if (err) {return next (err); }
            //Sucessful, so render
            res.render('book_list', {title: 'Book list', book_list: list_books});
        });
};

**model/author.js**
//virtual for author's full names 
authorSchema
.virtual('name')
.get(()=>{
    return this.first_name + ', ' + this.family_name;
});

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/express_nodejs/displaying_data/book_list_page`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/Book_list_page
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/server-side/express_nodejs/displaying_data/book_list_page/index.html
* Last commit: https://github.com/mdn/content/commit/b3eebddc4c3a897597e3602655d596eed67851b6
* Document last modified: 2021-01-29T09:29:22.000Z

</details>

**Comment by hamishwillee** [comment] 2021-06-07 01:20
Hi @Norberto-Boa 

Last time I tested this all worked, which indicates most likely you have a copy-paste error. 
Typically authors name is undefined error might mean that you have not linked to the header where it is defined in your controller. 

Can you reproduce the problem if you try the demo project of this: https://github.com/mdn/express-locallibrary-tutorial

If that works, do a difference between your code and the working example. If that doesn't help, can you please show a screenshot of the error output and page, and perhaps upload your version of the code to github and share.

**Comment by hamishwillee** [comment] 2021-07-26 22:20
I'm closing as "not able to reproduced". Reopen if you can reproduce in https://github.com/mdn/express-locallibrary-tutorial

**Comment by gnou** [comment] 2022-11-15 06:12
For anyone who had the same issue:
```
authorSchema
.virtual('name')
.get(**()=>{**
return this.first_name + ', ' + this.family_name;
});
```
When declaring virtual, you used `=>` arrow function express, which doesn't have its own binding of `this`, `this.first_name` and `this.family_name` are all `undefined`, that's why there's no result.
Change it back to

**Comment by hamishwillee** [comment] 2022-11-18 01:12
Ah, thanks @gnou (and @Norberto-Boa ). Reopening.

FYI, I was testing the demo project which I worked through the docs to create. It does this:
```
// Virtual for author "full" name.
AuthorSchema.virtual("name").get(function () {
  return this.family_name + ", " + this.first_name;
});
```

**Comment by hamishwillee** [comment] 2022-11-18 01:25
Actually, no - the docs don't do this in current version. So there is nothing ot do.

**Comment by Josh-Cena** [comment] 2022-12-29 06:34
@hamishwillee is there anything to do here in the end? I'm quite confused.

**Comment by hamishwillee** [comment] 2023-01-03 01:01
@Josh-Cena Nothing to do - the docs and worked example don't use an arrow function so the "fix" outlined above wasn't relevant. Closing again.

**Closed by hamishwillee** 2023-01-03 01:01 UTC
Labels: Content:Learn, needs info
