### ISSUE TITLE
Issue with "Setting up a Django development environment": (short summary here please)

### ISSUE THREAD

**Issue by muthu-1812** [mdn/content#2135] opened 2021-02-06 18:20 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/development_environment

#### What information was incorrect, unhelpful, or incomplete?
for installation in windows these commands for not working for newer versions of python
mkvirtualenv my_django_environment  
and also for entering the environment
as well as the commands
#### Specific section or headline?

Creating a virtual environment 
As well as using a virtual environment
#### What did you expect to see?

Updated commands for latest version
#### Did you test this? If so, how?
https://stackoverflow.com/questions/56778211/error-message-mkvirtualenv-is-not-recognized-as-an-internal-or-external-command/56781113
this has updated commands

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/server-side/django/development_environment`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/development_environment
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/learn/server-side/django/development_environment/index.html
* Last commit: https://github.com/mdn/content/commit/edbcbfa37c7807eefc5346c734cfc55d3dcc2c8a
* Document last modified: 2021-01-25T07:12:53.000Z

</details>

**Comment by hamishwillee** [comment] 2021-02-08 01:38
Hi @muthu-1812 
This works with Python 3.8.5 which is the supported version in Ubuntu 20.04 LTS (the supported version of Ubuntu). The documentation is for Django 3.1.2 and Python 3.8 is the highest version that works with that. This might not work with higher versions of Python, but I question the need.

That said, would be good to verify.

So, can you please confirm:
1. What OS, OS version and Python version you have tried?
2. What do you see on the terminal when you enter `mkvirtualenv my_django_environment`
3. What other commands have you tried and what errors dis you get?

**Comment by hamishwillee** [comment] 2021-03-09 04:31
I am closing this as "cannot reproduce". Feel free to reopen if you can reproduce on current versions.

**Closed by hamishwillee** 2021-03-09 04:31 UTC
Labels: Content:Learn:Django
