### ISSUE TITLE
XPath translate example

### ISSUE THREAD

**Issue by miloush** [mdn/content#29767] opened 2023-10-22 08:36 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/XPath/Functions/translate

### What specific section or headline is this issue about?

2nd example

### What information was incorrect, unhelpful, or incomplete?

```xml
<xsl:value-of select="translate('The quick brown fox.', 'brown', 'red')" />
```

> The quick red fox.

The example is 1) confusing because it looks like it's a replace function 2) wrong because it does not translate the second 'o' in 'fox'.

### What did you expect to see?

A correct and insightful example. The effects of the function were already established in the first example. To illustrate the point about mismatching parameter lengths, it could be a modification of the first example, e.g.

```
<xsl:value-of select="translate('The quick brown fox.', 'abcdefghijklmnopqrstuvwxyz', 'ABCDEFGHIJKLMNOPQ')" />
```

> THE QICK BON FO.

(Moreover, the examples do not show the case where letter is not present in the match string.)

### Do you have any supporting links, references, or citations?

The current example does not match the behavior documented on the page.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/xpath/functions/translate`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/XPath/Functions/translate
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/xpath/functions/translate/index.md
* Last commit: https://github.com/mdn/content/commit/b6f343538eac4a803943b4e99b0c0545b372645a
* Document last modified: 2023-07-10T09:47:59.000Z

</details>

**Comment by Josh-Cena** [comment] 2023-10-22 19:12
Duplicate of https://github.com/mdn/content/issues/22616.

**Closed by Josh-Cena** 2023-10-22 19:12 UTC
Labels: needs triage
