### ISSUE TITLE
Issue with "Compiling from Rust to WebAssembly": …

### ISSUE THREAD

**Issue by vijaycs85** [mdn/content#835] opened 2021-01-01 19:26 UTC
MDN URL: https://developer.mozilla.org/en-US/docs/WebAssembly/Rust_to_wasm

#### What information was incorrect, unhelpful, or incomplete?

>Note that you need to fill in your own username, after the @, in the dependencies section.

There is no `@` on the dependency section. I believe the `packages.json` content has been updated, but not the explanation under it.

#### Specific section or headline?

[Using the package on the web](https://developer.mozilla.org/en-US/docs/WebAssembly/Rust_to_wasm#Using_the_package_on_the_web)

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/webassembly/rust_to_wasm`
* MDN URL: https://developer.mozilla.org/en-US/docs/WebAssembly/Rust_to_wasm
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/webassembly/rust_to_wasm/index.html
* Report started: 2021-01-01T19:08:26.949Z

</details>

**Comment by chrisdavidmills** [comment] 2021-01-16 12:15
Closing this; duplicate of https://github.com/mdn/content/issues/505

**Closed by chrisdavidmills** 2021-01-16 12:15 UTC
Labels: 30 minute task, Content:Other
