### ISSUE TITLE
Add sticky column headers for browser compatibility

### ISSUE THREAD

**Issue by garywade** [mdn/content#33075] opened 2024-04-13 16:09 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl

### What information was incorrect, unhelpful, or incomplete?

When browsing through the list of available APIs, especially for pages with long lists, the column headers scroll out of view making it difficult to reconcile a browser with a version number cell.  Changing this table so the column headers are sticky while the user scrolls the content can make this easier.  This is relatively easy for a native app although may be harder for a web app.  At the very least, adding the browser name to the alt/tooltip info per cell would be helpful: "Full support\nSafari 14.1".

### What did you expect to see?

The ability to easily reconcile a cell with a browser and version number.  Only the version number is visible after a while for longer lists of APIs.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/intl`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/intl/index.md
* Last commit: https://github.com/mdn/content/commit/37713c0c974d024ae6f695f9ae6bc7e26076ee3b
* Document last modified: 2023-10-20T14:18:14.000Z

</details>

**Comment by Josh-Cena** [comment] 2024-04-13 16:11
Duplicate of https://github.com/mdn/yari/issues/5417

**Closed by Josh-Cena** 2024-04-13 16:11 UTC
Labels: Content:JS, needs triage
