### ISSUE TITLE
Jump to header on `eval()` page doesn't work

### ISSUE THREAD

**Issue by asportnoy** [mdn/content#25521] opened 2023-03-22 00:15 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval

### What information was incorrect, unhelpful, or incomplete?

Linking to a specific header on the `eval()` page, like https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval#direct_and_indirect_eval, doesn't actually jump to the header. All other pages work as expected. And clicking a link to it within the page works as expected.

### What did you expect to see?

The page should jump to that header on load.

### Do you have anything more you want to share?

Just click this link and observe that it doesn't scroll to that heading: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval#direct_and_indirect_eval

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/eval`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/eval/index.md
* Last commit: https://github.com/mdn/content/commit/6b728699f5f38f1070a94673b5e7afdb1102a941
* Document last modified: 2023-02-21T00:38:24.000Z

</details>

**Comment by Josh-Cena** [comment] 2023-03-22 00:24
Duplicate of https://github.com/mdn/yari/issues/7168

**Closed by Josh-Cena** 2023-03-22 00:24 UTC
Labels: Content:JS, needs triage
