### ISSUE TITLE
Scrollbar isn't visible in the sidebar.

### ISSUE THREAD

**Issue by Riyan911** [mdn/content#25668] opened 2023-03-27 00:55 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects

### What specific section or headline is this issue about?

Sidebar doesn't have scrollbar.

### What information was incorrect, unhelpful, or incomplete?

The scrollbar isn't visible.

### What did you expect to see?

Expected to see the scroll in the sidebar.

### Do you have any supporting links, references, or citations?

The scrollbar isn't visible. It's probably because the css property overflow is not added. 

### Do you have anything more you want to share?

<h2>Before adding the css property overflow:auto</h2>

![Screenshot from 2023-03-27 06-17-26](https://user-images.githubusercontent.com/107925299/227816321-065844dc-1304-44a4-9c19-a54a5dce7c21.png)

<h2>After adding the css property overflow:auto</h2>

![Screenshot from 2023-03-27 06-23-59](https://user-images.githubusercontent.com/107925299/227816565-54e02801-01cc-48cf-8cb2-902cdb30eac6.png)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/javascript/objects`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/objects/index.md
* Last commit: https://github.com/mdn/content/commit/4def230f85756724b59660e3cd9de363db724ef8
* Document last modified: 2023-02-24T00:05:28.000Z

</details>

**Comment by Riyan911** [comment] 2023-03-27 01:14
One thing I noticed is that this problem is not only occuring on this page but on almost every page in the mdn docs.

**Comment by Josh-Cena** [comment] 2023-03-27 02:03
Duplicate of https://github.com/mdn/yari/issues/8494

**Closed by Josh-Cena** 2023-03-27 02:03 UTC
Labels: needs triage, Content:Learn:JavaScript
