### ISSUE TITLE
<object> for application/pdf is not supported by mobile browsers

### ISSUE THREAD

**Issue by nullpointerexceptionkek** [mdn/content#35987] opened 2024-09-21 20:16 UTC
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/object#browser_compatibility

### What specific section or headline is this issue about?

Browser compatibility

### What information was incorrect, unhelpful, or incomplete?

```html
<object type="application/pdf" data="/media/examples/In-CC0.pdf" width="250" height="200"></object>
```
Using application/pdf in <object> is not natively supported by mobile browsers such as the latest Chrome and Safari on IOS and Android devices. The browser will either use fallback or display a link asking to download the PDF instead. 

### What did you expect to see?

A warning clarifying mobile browser support regarding application/pdf

### Do you have anything more you want to share?

![image](https://github.com/user-attachments/assets/b9684e18-c53f-4292-b628-199594886347)
![image](https://github.com/user-attachments/assets/058f5ab2-a104-41ae-b1cc-2e34f4e433a5)
![image](https://github.com/user-attachments/assets/5b78c4b2-e572-46ee-b09c-f24b00e0a120)

**Comment by Josh-Cena** [comment] 2024-09-21 20:21
Duplicate of https://github.com/mdn/browser-compat-data/issues/22941

**Closed by Josh-Cena** 2024-09-21 20:21 UTC
Labels: Content:HTML, needs triage
