### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by boofPackRiderZ** [mdn/content#341] opened 2020-12-17 05:04 UTC
Good afternoon. I immediately want to apologize for my poor English. I recently began learning web development with the help of your site and are faced with the problem of the lack of some pages, although they had previously opened

https://developer.mozilla.org/ru/docs/Learn/HTML/Введение_в_HTML

Sorry, the page /ru/docs/Learn/HTML/%D0%92%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5_%D0%B2_HTML could not be found.

Thank you for providing the material, I hope the problem will be solved

**Comment by peterbe** [comment] 2020-12-17 21:05
Duplicate of https://github.com/mdn/yari/issues/2173
Unfortunately no quick workaround at the moment.

**Closed** 2020-12-17 22:14 UTC
